### ISSUE TITLE
aws emr export-cluster feature.

### ISSUE THREAD

**Issue by dgomesbr** [aws/aws-cli#1032]
Hey guys,

We constantly create new clusters via web console, would be nice to export to a actionable cluster command line version by a cluster-id which would evaluate all the apps, steps and make the reproducible aws emr cli script for later usage and experimentation.

Is this useful for anyone except my team? My current workflow is to use describe-step and describe-cluster to recreate by hand.

Thanks

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by tim-finnigan** [comment]
Checking in as this issue has received little activity in the past several years. This article was published after the issue was created and I think it addresses the use case: https://aws.amazon.com/blogs/aws/emr-4-3-0-new-updated-applications-command-line-export/

Is that approach sufficient or is this still a feature request that should be tracked for consideration?
