### ISSUE TITLE
aws kms decrypt InvalidCiphertextException error

### ISSUE THREAD

**Issue by mtougeron** [aws/aws-cli#1043]
I upgraded to version 1.6.6 of the awscli today and aws kms decrypt started failing on decryption. It works in 1.6.5.

```
$> aws --version
aws-cli/1.6.6 Python/2.7.6 Darwin/13.4.0

$> python -V
Python 2.7.6

$> aws kms encrypt --key-id REDACTED --plaintext foo 
{
    "KeyId": "arn:aws:kms:us-east-1:REDACTED:key/REDACTED", 
    "CiphertextBlob": "CiDdiD7jljnCzXlfZUp27Y4LDY+QJa2Zqcw/7+ihfBDo7hKKAQEBAgB43Yg+45Y5ws15X2VKdu2OCw2PkCWtmanMP+/ooXwQ6O4AAABhMF8GCSqGSIb3DQEHBqBSMFACAQAwSwYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwVt2CzbGDR2nUwszQCARCAHgdJ4aHQ4i7TMzBN6XlKcC73oilECgep+basamtnXQ=="
}

$> aws kms decrypt --ciphertext-blob CiDdiD7jljnCzXlfZUp27Y4LDY+QJa2Zqcw/7+ihfBDo7hKKAQEBAgB43Yg+45Y5ws15X2VKdu2OCw2PkCWtmanMP+/ooXwQ6O4AAABhMF8GCSqGSIb3DQEHBqBSMFACAQAwSwYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwVt2CzbGDR2nUwszQCARCAHgdJ4aHQ4i7TMzBN6XlKcC73oilECgep+basamtnXQ==

A client error (InvalidCiphertextException) occurred when calling the Decrypt operation: None

$> pip freeze                                       
Babel==1.3
Fabric==1.10.0
Jinja2==2.7.3
MarkupSafe==0.23
Pillow==2.6.1
PyChef==0.2.3
PyYAML==3.11
Pygments==2.0.1
Sphinx==1.2.3
argparse==1.2.1
astroid==1.2.1
awscli==1.6.6
bcdoc==0.12.2
binaryornot==0.3.0
boto==2.34.0
botocore==0.77.0
box.py==1.2.8
cffi==0.8.6
cliff==1.8.0
cmd2==0.6.7
colorama==0.2.5
cookiecutter==0.8.0
coverage==3.7.1
cryptography==0.6.1
decorator==3.4.0
docutils==0.12
dogapi==1.8.5
ecdsa==0.11
futures==2.2.0
httplib2==0.9
httpretty==0.8.3
iso8601==0.1.10
jmespath==0.5.0
jsonpatch==1.9
jsonpointer==1.5
jsonschema==2.4.0
kazoo==2.0
keyring==4.0
logilab-common==0.63.0
lxml==3.4.0
mock==1.0.1
mockito==0.5.2
netaddr==0.7.12
nose==1.3.4
numpy==1.9.1
oath==1.2
oslo.config==1.4.0
oslo.i18n==1.0.0
oslo.serialization==1.0.0
oslo.utils==1.0.0
paramiko==1.15.1
pbr==0.10.0
prettytable==0.7.2
pyOpenSSL==0.14
pyasn1==0.1.7
pycparser==2.10
pycrypto==2.6.1
pylint==1.3.1
pyparsing==2.0.3
python-ceilometerclient==1.0.12
python-cinderclient==1.1.1
python-dateutil==2.3
python-glanceclient==0.14.2
python-heatclient==0.2.12
python-keystoneclient==0.11.2
python-neutronclient==2.3.9
python-novaclient==2.20.0
python-openstackclient==0.4.1
python-swiftclient==2.3.1
python-troveclient==1.0.7
pytz==2014.9
qrcode==5.1
requests==2.4.3
rsa==3.1.2
scipy==0.14.0
simplejson==3.6.5
six==1.8.0
stevedore==1.1.0
urllib3==1.9.1
virtualenv==1.11.6
warlock==1.1.0
wsgiref==0.1.2

```

**Comment by thegranddesign** [comment]
@jamesls personally I think this is incredibly bad UI.  Not being able to pass the same ciphertext into decrypt that you got from encrypt?  If you can't change it because you don't want to break existing customers, at least give them a better error message.

```
A client error (InvalidCiphertextException) occurred when calling the Decrypt operation: None
```

Doesn't even remotely tell me what to do to fix the problem.  You could detect that the cipher is probably Base64 and output a better error and point them to a URL or something.

**Comment by thegranddesign** [comment]
Or heck why not pass an additional flag to `decrypt` to say "decode this from base64 first"?

**Comment by thegranddesign** [comment]
For those who come to this later, in order to do this _without_ saving the ciphertext to a file, you can do:

```
aws kms decrypt --ciphertext-blob fileb://<(echo 'ciphertext' | base64 -d)
```

**Comment by msabramo** [comment]
Re: @thegranddesign's [comment](https://github.com/aws/aws-cli/issues/1043#issuecomment-215633654), on OS X at least I had to use a capital 'D' for `base64`. E.g.:

```
$ echo "Decrypted: $(aws kms decrypt --ciphertext-blob fileb://<(echo $ENCRYPTED_DATA | base64 -D) --query Plaintext --output text | base64 -D)"

Decrypted: Hello world!
```

(Not sure why I get a newline before the `Decrypted` line, but not a big deal).

**Comment by ojitha** [comment]
This worked for me
`
#encrypt the password: TestReadWrite text in the test.txt file
aws kms encrypt --key-id cfc7acf7-4f20-49c3-aa11-8be4cdc3291d --plaintext fileb://test.txt --output text | base64 --decode > out.txt

#decrypt the password: TestReadWrite
aws kms decrypt  --ciphertext-blob fileb://out.txt --output text --query Plaintext | base64 --decode
`

**Comment by webjay** [comment]
I had a similar issue, but Node helped:

    'use strict';

    const KMS = require('aws-sdk').KMS;
    const fs = require('fs');

    const kms = new KMS({
      apiVersion: '2014-11-01',
      // region: 'eu-west-1'
    });

    function encrypt(params) {
      return kms.encrypt(params).promise();
    }

    const arn = 'arn:aws:kms:xxx';

    encrypt({
      KeyId: arn,
      Plaintext: fs.readFileSync('/path/to/key.pem')
    })
    .then(data => fs.writeFileSync('/path/to/key.json', JSON.stringify(data)));

**Comment by hauntingEcho** [comment]
another note on @thegranddesign 's solution - `<(cmd)` is a bashism, not POSIX compliant, so you'll need to use another solution if bash isn't an option.

**Comment by sgendler-stem** [comment]
This is a mindbogglingly dumb bug that really ought to still be open until it is actually fixed.  It is a giant anti-pattern to build a tool that performs a symmetric operation that uses one format for output and a completely different (and incompatible) format for input.  A symmetric tool that cannot consume its own output as input is BROKEN.  I don't care if it is actually working as intended, it is still broken.  The tool should either generate raw binary output by default if it is dependent on raw binary input, or else it damn well ought to be able to consume base64 encoded input THAT IT GENERATED without specifying any explicit base64 decode steps or special params that weren't also required in order to generate that output (or an anti-param if it doesn't use the same exact param).  It is beyond absurd that I can use aws kms encrypt to generate base64 encoded output of a base64 encoded encryption payload without specifying EITHER of those base64 encodings, but then I have to explicitly base64 decode both the encrypted data AND the decrypted data in order to get it back to the form I provided in the first place.  The fact that doing so also requires the use of command line params that aren't even documented at the level of the encrypt and decrypt subcommands makes it that much more difficult to figure out.  Users are all but guaranteed to waste hours trying to figure out how to do the single most obvious thing someone might want to do with an encryption/decryption client - encrypt and then decrypt a string specified in a command line param - and entirely because the tool has a broken operating mode where outputs aren't compatible with inputs despite the fact that the two sub-commands are supposed to be symmetric.  At best, closing this without fixing it states that you have absolutely no concern for usability or developer efficiency, but it mostly speaks to a dire lack of concern about developer efficiency and api usability more generally.

**Comment by hauntingEcho** [comment]
another path to resolve this (as opposed to new flags, as @thegranddesign mentioned years ago) could be that `/` is not a valid base64 character, and there is no valid way to specify binary data in json.  Therefore:
* if the ciphertext-blob parameter is valid base-64, pass it as base 64
* if the ciphertext-blob parameter contains `/`, parse as a path.  `fileb://` doing its current behavior, `file://` could be b64-encoded.

Agreed with @sgendler-stem though - this ticket is linked in every project I've worked on which uses KMS, because it's always a problem for someone trying to get on board.

**Comment by RLThomaz** [comment]
> This is a mindbogglingly dumb bug that really ought to still be open until it is actually fixed. It is a giant anti-pattern to build a tool that performs a symmetric operation that uses one format for output and a completely different (and incompatible) format for input. A symmetric tool that cannot consume its own output as input is BROKEN. I don't care if it is actually working as intended, it is still broken. The tool should either generate raw binary output by default if it is dependent on raw binary input, or else it damn well ought to be able to consume base64 encoded input THAT IT GENERATED without specifying any explicit base64 decode steps or special params that weren't also required in order to generate that output (or an anti-param if it doesn't use the same exact param). It is beyond absurd that I can use aws kms encrypt to generate base64 encoded output of a base64 encoded encryption payload without specifying EITHER of those base64 encodings, but then I have to explicitly base64 decode both the encrypted data AND the decrypted data in order to get it back to the form I provided in the first place. The fact that doing so also requires the use of command line params that aren't even documented at the level of the encrypt and decrypt subcommands makes it that much more difficult to figure out. Users are all but guaranteed to waste hours trying to figure out how to do the single most obvious thing someone might want to do with an encryption/decryption client - encrypt and then decrypt a string specified in a command line param - and entirely because the tool has a broken operating mode where outputs aren't compatible with inputs despite the fact that the two sub-commands are supposed to be symmetric. Closing this without fixing it states that you have absolutely no concern for usability or developer efficiency.

I have to completely agree with @sgendler-stem - if the code generates an output it should be, **at least**, able to take that as input.

However, there is more to that. If the ecryption is done through the SDK - adding a weird `arn` at the end of the encrypted file, the CLI won't be able to decrypt it, even after removing the **non-base64** `arn` url. This is just **broken**.

**Comment by aerovistae** [comment]
Agreed again. This has made things quite difficult for no reason.

**Comment by sunbarve** [comment]
Face the same exceptions:
botocore.errorfactory.InvalidCiphertextException: An error occurred (InvalidCiphertextException) when calling the Decrypt operation:

Used:
key = b64decode(key)
response = client.decrypt(
CiphertextBlob=key
)

**Comment by orirawlings** [comment]
I think this wouldn't be so frustrating if the output of `encrypt`, `generate-data-key`, etc didn't call the field `CiphertextBlob`. When the input to `decrypt` is called `--ciphertext-blob`, it is thoroughly unintuitive that this ciphertext blob needs to be encoded differently.

**Comment by rdkls** [comment]
There's a feature proposal for base64-encoded input to decrypt over here https://github.com/aws/aws-cli/issues/2063

**Comment by arpit728** [comment]
@ojitha 

How does kms know which encryption key to use for decryption, since we are not passing key-id as a parameter while decrypting.

**Comment by Achint08** [comment]
@arpit728 I think that CipherTextBlob returned is particular about the KeyID of a particular CMK.

**Comment by WingsLikeEagles** [comment]
Please reopen this ticket until it is resolved!

**Comment by svolotin** [comment]
played too many hours with this until found this ticket. is there any official documentation which states how exactly things should be coded and transformed between encrypt and decrypt?

**Comment by svolotin** [comment]
> Just a little background info on what's going on:
> 
> In [1.6.6](https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst#166), we fixed a [regression](https://github.com/aws/aws-cli/issues/1033) in which we were not base64 encoding "blob" types that we had previously been encoding. As a result, you now need to specify the raw binary bytes for any parameter marked as a "blob" type, and internally we will automatically base64 encode it for you. This means that to round trip key encryption you'll need to decode the base64 first:
> 
> ```
> $ aws kms encrypt --key-id <key-id> --plaintext "abcd" --query CiphertextBlob --output text | base64 -D > /tmp/encrypted-file
> $ echo "Decrypted: $(aws kms decrypt --ciphertext-blob fileb:///tmp/encrypted-file --query Plaintext --output text | base64 -D)"
> Decrypted: abcd
> ```
> 
> In this example, I'm also using the `fileb://` prefix because it's a file with binary content.

this example returns: 

An error occurred (InvalidCiphertextException) when calling the Decrypt operation: 
Decrypted:

**Comment by DestyNova** [comment]
FYI, the above link doesn't work, but the article seems pretty useful and is [available here](https://www.matchilling.com/storing-security-sensitive-data-using-aws-kms-and-openssl/).
