### ISSUE TITLE
--acl option does not work with sync

### ISSUE THREAD

**Issue by amiri** [aws/aws-cli#1060]
I was trying to batch-upload the contents of a folder to a key, and was very surprised when my --acl options had no effect. I had to re-upload each file individually, using cp instead of sync. This is a surprising non-feature!

**Comment by mitchellst** [comment]
I ran into this googling.

It appears that my problem occurred because I had already synced my files into place. 

Applying the `--acl` flag to a subsequent run didn't apply the ACL, because the files themselves had not changed. My solution was to delete the keys on that path then sync again. (`aws s3 rm s3://mybucket/myPath/ --recursive` then rerun the sync.)

**Comment by erikng** [comment]
It would be great if the --acl flag could be used for already uploaded objects. It should be the equivalent of `Make Public` in the AWS console.

**Comment by sillmnvg** [comment]
+1 to @erikng 's comment; especially when dealing with large amounts of files within a bucket.
