### ISSUE TITLE
'charmap' codec can't encode character (Windows 7)

### ISSUE THREAD

**Issue by JamesBromberger** [aws/aws-cli#1070]
Platform: Windows 7 Entreprise SP1. installed from MSI.

C:\>aws --profile lg-sec --region ap-southeast-2 cloudtrail create-trail help

'charmap' codec can't encode character u'\u2019' in position 1686: character maps to <undefined>

C:\>aws --version aws-cli/1.6.10 Python/2.7.5 Windows/7

**Comment by rayluo** [comment]
Although we don't have the `--debug` output to confirm, the symptom is most likely caused by some non-ascii character (in this case, it is the [u'\u2019', single quote](http://www.fileformat.info/info/unicode/char/2019/index.htm)) can not be displayed on the current locale. For example, if your locale is using CP437 encoding, you will see the same symptom.

    >>> u'\u2019'.encode('cp437')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/rayluo/py27/lib/python2.7/encodings/cp437.py", line 12, in encode
        return codecs.charmap_encode(input,errors,encoding_map)
    UnicodeEncodeError: 'charmap' codec can't encode character u'\u2019' in position 0: character maps to <undefined>

We haven't implemented the interim solution yet. But I believe the symptom has gone for a while, because the [problematic single quote in our service model at that time](https://github.com/boto/botocore/blob/0c09e351df871f6abfa03f0141991ca107c50165/botocore/data/aws/cloudtrail/2013-11-01.api.json#L496) has long been [changed to normal single quote already](https://github.com/boto/botocore/blob/develop/botocore/data/cloudtrail/2013-11-01/service-2.json#L1087). I think we can close this issue for now.

**Comment by gpickin** [comment]
Using s3 for backups, I am powerless to the encoding of the file names. 
This is frustrating.

**Comment by marchello2000** [comment]
Yes, what's the status on this - I can't control the files names and am running into this as well

**Comment by adamfortuno** [comment]
+status
