### ISSUE TITLE
"aws dynamodb put-item help", no examples, totally unusable docs

### ISSUE THREAD

**Issue by tat** [aws/aws-cli#1073]
I spent two hours trying to run a simple put with a conditional expression and give up.  expression-attribute-values gives an syntax error even using the example value provided in the doc.

It really needs some working examples.

**Comment by kyleknap** [comment]
Just taking note of another example that would be useful to add based on conversation with another CLI user:

This example does a conditional put on if the item exists:
```
$ aws dynamodb put-item --table-name MyJobs --item '{"jobid":{"S":"do_something"}}' --condition-expression "attribute_not_exists(jobid)"
```
If you were following along with the previous examples that I have provided, that should fail because the item already exists.

**Comment by justnance** [comment]
@tat and @viper25 - Our documentation has been updated with examples since this issue was created.  Please take a look and let us know what you think.  Thanks for your patience. 

https://docs.aws.amazon.com/cli/latest/reference/dynamodb/put-item.html
https://docs.aws.amazon.com/cli/latest/userguide/cli-services-dynamodb.html
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html

**Comment by tat** [comment]
Thanks!
