### ISSUE TITLE
attach-volume wrongly reports mount point

### ISSUE THREAD

**Issue by jeremyjjbrown** [aws/aws-cli#1089]
The aws attach-volume command demands a device mount point but does not honor the parameter. In the command below it returns JSON claiming it will mount the ebs to /dev/sdb on a t2.medium  but instead mounts it to  /dev/xvdb . This is a serious impediment to automation. The JSON should at least return the correct mount point that will be used. The  --device flag should not be required if aws may need to select it's own mount point on certain instance types.

aws ec2 attach-volume --volume-id vol-f0d14ebb --instance-id i-3534ebd8 --device /dev/sdb

{
    "AttachTime": "2015-01-12T20:57:59.294Z",
    "InstanceId": "i-3534ebd8",
    "VolumeId": "vol-f0d14ebb",
    "State": "attaching",
    "Device": "/dev/sdb"
}

[centos@ip-172-31-41-60 ~]$ ls /dev | grep db
xvdb

The management console also wrongly reports the mount point
![screenshot 2015-01-12 17 48 17](https://cloud.githubusercontent.com/assets/1660010/5713647/0f6532e0-9a84-11e4-8fb4-6b4bd766c31b.png)

**Comment by jamesls** [comment]
The AWS CLI is just returning the values from the EC2 service API.  The docs do state that it's possible that the device might be attached with a different name than what you specify depending on the block device driver in the kernel.  From http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-attaching-volume.html#device_naming:

>Depending on the block device driver of the kernel, the device might be attached with a different name than what you specify. For example, if you specify a device name of /dev/sdh, your device might be renamed /dev/xvdh or /dev/hdh by the kernel; in most cases, the trailing letter remains the same. In some versions of Red Hat Enterprise Linux (and its variants, such as CentOS), even the trailing letter might also change (where /dev/sda could become /dev/xvde). In these cases, each device name trailing letter is incremented the same number of times. For example, /dev/sdb would become /dev/xvdf and /dev/sdc would become /dev/xvdg. Amazon Linux AMIs create a symbolic link from the renamed device path to the name you specify, but other AMIs might behave differently.

There's nothing really we can do from the AWS CLI side because we don't actually know if the device has been renamed or not, as that info does not come back in the EC2 API response.
