### ISSUE TITLE
Could strip whitespace from env var credentials

### ISSUE THREAD

**Issue by smeyfroi** [aws/aws-cli#1096]
I just debugged a problem with a bash script that uses the CLI tools with env vars for the credential config. It reads the creds from text files (for legacy reasons) using cat. This fails because of a trailing '\r' that sneaks into the var:

```
export AWS_ACCESS_KEY_ID=`cat ${AWS_SECRETS}/aws_access_key`
```

The solution is to add the following, which strips the bad character:

```
export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID%$'\r'}
```

But it would be handy if the CLI tools stripped leading/trailing cruft from input strings/envvars (as the old Java based tools must have done: I'm porting these bash scripts from the Java tools to these python ones, and it used to work with the old CLI tools).

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
