### ISSUE TITLE
aws s3 sync doesn't allow file for source argument

### ISSUE THREAD

**Issue by tycho** [aws/aws-cli#1134]
I'm interested in using the 'aws s3 sync' command as a sort of conditional 'aws s3 cp'.

I have a local file which may or may not exist in the target s3 bucket, and I **only** want to do the upload if:
- the destination either doesn't exist,
- doesn't have the same length,
- or doesn't have the same MD5 hash.

The 'sync' command really seems to fit the bill. Unfortunately it seems that with the 'sync' command you can only specify a **directory** for source/destination:

```
$ aws s3 sync --dryrun somefile s3://somebucket/somedir/
warning: Skipping file /home/snoonan/somefile/. File does not exist.
Completed 0 part(s) with ... file(s) remaining
```

The following change makes it work, but introduces some new edge cases that need errors:

``` patch
diff --git a/awscli/customizations/s3/fileformat.py b/awscli/customizations/s3/fileformat.py
index fc2caca..93e475c 100644
--- a/awscli/customizations/s3/fileformat.py
+++ b/awscli/customizations/s3/fileformat.py
@@ -82,7 +82,7 @@ class FileFormat(object):
                be of the one provided.
         """
         full_path = os.path.abspath(path)
-        if (os.path.exists(full_path) and os.path.isdir(full_path)) or dir_op:
+        if os.path.exists(full_path) and os.path.isdir(full_path):
             full_path += os.sep
             return full_path, True
         else:
diff --git a/awscli/customizations/s3/filegenerator.py b/awscli/customizations/s3/filegenerator.py
index 1d587ed..d3d24e2 100644
--- a/awscli/customizations/s3/filegenerator.py
+++ b/awscli/customizations/s3/filegenerator.py
@@ -156,10 +156,7 @@ class FileGenerator(object):
         join, isdir, isfile = os.path.join, os.path.isdir, os.path.isfile
         error, listdir = os.error, os.listdir
         if not self.should_ignore_file(path):
-            if not dir_op:
-                size, last_update = get_file_stat(path)
-                yield path, size, last_update
-            else:
+            if dir_op and os.path.isdir(path):
                 # We need to list files in byte order based on the full
                 # expanded path of the key: 'test/1/2/3.txt'  However,
                 # listdir() will only give us contents a single directory
@@ -193,6 +190,9 @@ class FileGenerator(object):
                     else:
                         size, last_update = get_file_stat(file_path)
                         yield file_path, size, last_update
+            else:
+                size, last_update = get_file_stat(path)
+                yield path, size, last_update

     def normalize_sort(self, names, os_sep, character):
         """
```

It doesn't work correctly if, for example, the source is an S3 directory path and the destination is a local file (rather than local directory). Instead of erroring out, it would overwrite the destination file multiple times with each file from the source bucket.

I also notice that the function at awscli/customizations/s3/subcommands.py:918 (check_src_path) didn't throw an exception after my change. Assuming it's not dead code, I'd expect it to try to validate my arguments and realize that my source is a file, while dir_op=True, and thus the exception on 941 would be thrown. Weird.

**Comment by kyleknap** [comment]
Thanks for looking into the code to figure out how to get this to work. We would have to look into it as well to see what, if any, edge cases are missing. We will look into adding this feature.

In the meantime, I would suggest trying to use ``--include`` and ``--exclude`` filters as you could achieve roughly the same functionality. Something like this:
```
$ aws s3 sync . s3://mybucketfoo/somedir/ --exclude '*' --include 'somefile' --dryrun
(dryrun) upload: ./somefile to s3://mybucketfoo/somedir/somefile
```

However using this approach, ``ListObjects`` call(s) will be made as opposed to a single ``HeadObject`` to determine if the object exists and the size/last modified time of the object.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
