### ISSUE TITLE
Can't sync to Windows when colon in file name

### ISSUE THREAD

**Issue by cool-RR** [aws/aws-cli#1154]
I have a problem where I'm trying to sync an s3 bucket to Windows, but I'm getting an error because there's a file with a colon in the name. On one hand I understand the problem, you can't have a colon in the filename on Windows while you can on Linux; on the other hand, I need a solution. Changing the file name on s3 would be a problem because there's an existing system that saves files like that and changing it would be complex.

Is there a solution?

**Comment by danielgtaylor** [comment]
It seems like the colon character is not allowed in filenames on Windows and there is no workaround other than changing the character. This would likely break our s3 sync functionality (you could sync to Windows, but not back up to S3 without the new names). I'm not sure if there is a good solution to this.

**Comment by kenklin** [comment]
I just hit this road block on Windows today and don't have an available solution.

My S3 objects have Cognito ID prefixes, per http://docs.aws.amazon.com/cognito/latest/developerguide/iam-roles.html, so I have per-user protected folders.  The objects have been successfully generated locally on my Mac with the appropriate S3 names that contain the colons (e.g. us-east-1:abcd ...), and copied to S3 with the AWS CLI's S3 Sync command.  However today I ran into this road block when I moved the object generation environment to Windows.

So this turns out to be a naming problem.

One way to solve this is ...
1) I change my program to generate OS-acceptable filenames where I've mapped colons to an acceptable character X.  
2) When AWS CLI S3 Syncs, it maps X to colon.  This could be done be allowing me to perhaps specify the mapping via a pair of regular expressions, one for each direction.

Thoughts?

**Comment by JordonPhillips** [comment]
I don't think there's anything we can do here. Various operating systems and filesystems have different rules for what is and isn't a vaild filename. Only the end users have the context to know what they should name their objects, so I am not in favor of making those calls on their behalf.

**Comment by mciureanu** [comment]
Downloading a file containing ":" character from the console changes the ":" to "_" so this is the expected behavior from the CLI as well.

**Comment by aleemerichxpi** [comment]
Hello. Does anyone know if this has evolved? I have the same problem (I use Windows 10 and files with the same problem on S3).

**Comment by PoLaKoSz** [comment]
I am not a Powershell wizard but this works for me:
```powershell
$bucketName = 'test'
$prefix = 'b638c827-8251-434d-8379-98e3a6e5845c/timeline'

$s3Response = Get-S3ObjectV2 -BucketName $bucketName -Prefix $prefix

foreach ($s3File in $s3Response) {
    $localFileName = $s3File.Key.Substring($prefix.Length).Replace(":", "_")
    $localPath = "$(Get-Location)\$($localFileName)"
    Read-S3Object -BucketName $bucketName -File $localPath -Key $s3File.Key -Region eu-central-1
}
```

- [Read-S3Object](https://docs.aws.amazon.com/powershell/latest/reference/items/Read-S3Object.html)
- [Get-S3ObjectV2](https://docs.aws.amazon.com/powershell/latest/reference/items/Get-S3ObjectV2.html)
