### ISSUE TITLE
Invalid loadbalancer names not blocked

### ISSUE THREAD

**Issue by vacri** [aws/aws-cli#1165]
I had some trouble getting an autoscaling group running, and the issue was that load balancers were a comma-delimited list and not a space delimited list. The web console reported the error as 'invalid character in load balancer name'.

As other items are comma-delimited (eg --vpc-zone-identifier), comma delimitation should be allowed for load balancers. Or at least, give a syntax error since non-allowed characters were in the name - "elb1,elb2" is read as a single name, but with a non-allowed character.

**Comment by danielgtaylor** [comment]
@vacri these arguments and errors come directly from the service itself. From the documentation (via `aws autoscaling create-auto-scaling-group help`:

```
 --load-balancer-names (list)
          One or more load balancers.

          For  more  information,  see Load Balance Your Auto Scaling Group in
          the Auto Scaling Developer Guide .

       Syntax:

          "string" "string" ...

 --vpc-zone-identifier (string)
          A  comma-separated  list of subnet identifiers for your virtual pri-
          vate cloud (VPC).

          If you specify subnets and Availability Zones with this call, ensure
          that  the  subnets'  Availability Zones match the Availability Zones
          specified.

          For more information, see Auto Scaling and Amazon VPC  in  the  Auto
          Scaling Developer Guide .
```

You can see that `--vpc-zone-identifier` is actually a string that the service treats as a list. Since we see it as a plain string there isn't much that we can do on the CLI side. When in doubt, always check out the documentation and make sure to look at the argument type and syntax examples!
