### ISSUE TITLE
Extremely slow download performance when outputting to a stream

### ISSUE THREAD

**Issue by nbrownus** [aws/aws-cli#1187]
When I download a file using `s3 cp s3://somebucket/file ./localfile` I achieve around 48MiB/s down.

When I download a file using `s3 cp s3://somebucket/file -` I only get about 5MiB/s down. It appears that only one connection is transferring data at any given point in time. While outputting to a local file has many connections working together.

I haven't had the chance to study the code very much but this seems like an effort to reduce memory usage? In any case it would be awesome if outputting to a pipe could achieve the same rates as outputting to a file.

**Comment by kyleknap** [comment]
Your observation that the streaming downloads is noticeably slower than the regular downloads is correct. It is due to a combination of trying to reduce memory usage by using less threads and there being a bottleneck in the code where even though the threads have made a connection to s3 in parallel, only one connection is being read and written to standard output at a time. We need to be reading from all of the connections at the same time, but then write it out one at a time (as is required due to the nature of non-seekable streams).

Making the streaming downloads faster by refactoring the code is something that we want to do in the near future as it will fix a couple of bug reports that we have received. However, it will take a fair amount of work.

**Comment by kyleknap** [comment]
With the release of 1.10.57, we updated the underlying architecture of streaming functionality such that there is no longer the read bottleneck from when downloading a stream. Sreaming downloads are much more comparable to the speed of a regular download in our testing of it. Therefore, resolving issue.
