### ISSUE TITLE
use libmagic (filemagic) to guess content type if mimetypes.guess_type() fails

### ISSUE THREAD

**Issue by rhelmer** [aws/aws-cli#1204]
Right now commands such as `aws s3 cp` attempt to guess the file type using  `mimetypes.guess_type()`, which will fail for files that aren't registered mime types on the system.

`filemagic` could be tried if this fails, it uses libmagic (just like the unix `file` command) and will try reading the first few bytes of the file to see if it can be identified.

It would be nice to be able to invoke this as a fallback for when `mimetypes.guess_type()` returns `None`, perhaps as an option (disabled by default) because it incurs some overhead on each of the source files.

**Comment by phrawzty** [comment]
:+1:

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by tim-finnigan** [comment]
Checking in as this issue hasn't received any community activity since 2015. There have since been other issues related to mimetypes created, for example: https://github.com/aws/aws-cli/issues/1249. That specific issue involves incorrect mimetypes for `.woff` files. Would libmagic address that? Or which other incorrectly guessed mimetypes are an issue? There are also workarounds mentioned in that issue where users can set their own mimetypes.
