### ISSUE TITLE
s3 sync not syncing timesstamps properly

### ISSUE THREAD

**Issue by DrStrangepork** [aws/aws-cli#1222]
The default behavior of --exact-timestamps is not working properly. According to the documentation:
```--exact-timestamps (boolean) When syncing from S3 to local, same-sized items will be ignored only when the timestamps match exactly. The default behavior is to ignore same-sized items unless the local version is newer than the S3 version.```

However:
```
$ aws s3 sync s3://bucket/ansible/ ~/ansible
$ ll ~/ansible/branches/cassandra/inventory/dse/host_vars/dse00
-rw-rw-r--. 1 platform platform 37 Mar 14 22:24 /home/platform/ansible/branches/cassandra/inventory/dse/host_vars/dse00
$ aws s3 ls s3://bucket/ansible/branches/cassandra/inventory/dse/host_vars/dse00
2015-03-16 17:05:33         37 dse00
```
The local version is NOT newer than the S3 version, but it is not getting synced. Using --exact-timestamps works properly.

**Comment by kyleknap** [comment]
This behavior seems correct to me. Given that ``--exact-timestamps`` is not being used, the sync is ignoring the S3 object ``s3://bucket/ansible/branches/cassandra/inventory/dse/host_vars/dse00`` (i.e not downloading it) because its last modified time is newer than the last modified time of the local file ``/home/platform/ansible/branches/cassandra/inventory``.

If you use ``--exact-timestamps``, the S3 object should be downloaded because the last modified times differ. Can you go into further detail on how you expect the ``--exact-timestamps`` parameter to work based on the documentation?

**Comment by DrStrangepork** [comment]
Ok, yeah, I misread this. Although I'm not why this behavior would pertain to S3 to local. Why wouldn't it be "*the default behavior is to ignore same-sized items unless the* **target** *version is newer than the* **source** *version*"?

**Comment by kyleknap** [comment]
It is the purpose of roundtripping syncs and how s3 is treated as a backup system. If we were to make the general rule that if source is newer than the target, you would not be able to roundtrip. So if you upload a file to s3 (the source object in s3 will be newer than the destination local file) and if you immediately try resyncing the object result the CLI will download the object back down because s3, which is the source, is newer than the local file object. Let me know if you have any more questions

**Comment by kyleknap** [comment]
Closing. Please reopen if you have anymore questions.
