### ISSUE TITLE
Unknown encoding on Mac OS X

### ISSUE THREAD

**Issue by freimer** [aws/aws-cli#1238]
receiving unknown encoding message on Mac OS X even with PYTHONIOENCODING=utf-8 env var.  Will fix and do PR.

**Comment by braddr** [comment]
This fixed the issue for me on osx 10.11 as well.  @freimer, how about submitting the fix as a pull request?

**Comment by kjenney** [comment]
This fixed the issue for me on OSX 10.11.4. This needs to be merged, though.

**Comment by blochberger** [comment]
Can be worked around when setting `LC_CTYPE=en_US.UTF-8` (was `UTF-8`).
I think that is a bug rather than a feature request.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
