### ISSUE TITLE
aws elb create-load-balancer --listeners parameter should not be required 

### ISSUE THREAD

**Issue by stuz5000** [aws/aws-cli#1253]
aws elb create-load-balancer --listeners parameter should not be required when creating a load balancer as I may not have created instances when creating the loadbalancer.
The CLI  rejects a create-load-balancer call if  --listeners is not specified or empty.

Clearly, this parameter is not required under the hood  - I can create a load balancer though the web dashboard without having to specify any instances.

Seen in: aws-cli/1.5.4 Python/2.7.6 Linux/3.13.0-30-generic

**Comment by quiver** [comment]
You're misunderstanding APIs.
`create-load-balancer`'s `--listers` parameter  specifies front-end/back-end protocol/ports  just like ` --listeners Protocol=HTTP,LoadBalancerPort=80,InstanceProtocol=HTTP,InstancePort=80`.
http://docs.aws.amazon.com/cli/latest/reference/elb/create-load-balancer.html

Attaching instances to ELB is done thru `register-instances-with-load-balancers`.
http://docs.aws.amazon.com/cli/latest/reference/elb/register-instances-with-load-balancer.html

**Comment by stuz5000** [comment]
Yes, but these port forwarding properties are a function of the services
that will be  running on instances behind the loadbalancer.
I may not know up front what service's I'll start, but I can delegate the
configuration of the port forwarding in the load balancer to each service
-- as each service is ready and tested, it registers itself with the load
balancer and also ensures the load balancer is listening on the necessary
port.

Thus, I don't want to make assumptions about what the right configuration
is when creating the load balancer ... it will always be wrong. In my case,
the only correct initial configuration is a listening to no ports.

**Comment by danielgtaylor** [comment]
@stuz5000 unfortunately the service does not support what you are trying to do. Even the console requires at least one listener to be defined:

![screen shot 2015-03-31 at 1 42 45 pm](https://cloud.githubusercontent.com/assets/106826/6928933/2780514c-d7ac-11e4-8d4a-dac91a8ecc00.png)

You can always start with a dummy configuration and modify the port forwarding later:

http://docs.aws.amazon.com/cli/latest/reference/elb/create-load-balancer-listeners.html

Hopefully that helps, otherwise please reopen this issue.
