### ISSUE TITLE
aws s3api put metadata parsing error?

### ISSUE THREAD

**Issue by 2jinglei** [aws/aws-cli#1254]
using aws cli version 1.6.10, trying to set s3 object metadata with incorrect format, 
"key=name key2=name2", and it worked with no error msg.
Put command,
$aws s3api get-object --bucket mybucketname --key bucket-policy.json \
--metadata "key=value key2=value2"
Returns,
{
    "VersionId": "YqEWM69I8irSrfBpMyKV1LG1Nkk5Xl9F", 
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\""
}

Do a get,
$aws s3api get-object --bucket  mybuckename --key bucket-policy.json testfile
Returns,
{
    "AcceptRanges": "bytes", 
    "ContentType": "binary/octet-stream", 
    "LastModified": "Tue, 31 Mar 2015 03:11:31 GMT", 
    "ContentLength": 0, 
    "VersionId": "YqEWM69I8irSrfBpMyKV1LG1Nkk5Xl9F", 
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"", 
    "Metadata": {
        "key": "value key2=value2"
    }
}

I would have expected an error message on put, something like "Error parsing parameter '--metadata': should be: --metadata key_name=string,key_name2=string".

**Comment by danielgtaylor** [comment]
@2jinglei I think this is expected behavior. You are quoting the entire metadata parameter, and the format that you are using is incorrect, therefore the value is parsed as shown above. No error is raised because `value key2=value2` is a valid value for a metadata entry.

One thing you could do to help is to quote individual pairs, something like this:

```bash
$ aws s3api put-object --bucket mybucketname --key bucket-policy.json --metadata "key=value and some spaces","key2=value2"
```

Please let me know if you have any other questions.
