### ISSUE TITLE
aws ecs register-task-definition should not revision new registrations without change

### ISSUE THREAD

**Issue by jlchereau** [aws/aws-cli#1332]
running repeatedly

```
aws ecs register-task-definition --family "task-definition" --cli-input-json "file://../definitions/task-definition.json"
```

keeps adding revisions although the file does not change.

IMO, AWS should detect changes and only revision diffs because it is very complex to manage in a bash script. In other words, only commit changes like GIT.

Any suggestions/best practices in the meantime?

**Comment by kyleknap** [comment]
This just looks like the ``RegisterTaskDefinition`` is just not idempotent with respect to revision numbers. More specifically look at the CLI documentation for the ``revision`` output element: http://docs.aws.amazon.com/cli/latest/reference/ecs/register-task-definition.html. Looks like the revision number will get bumped up no matter if there is no changes.

I have not tried this yet, but if I were to write something I would probably make the call to ``describe-task-definition`` and compare it with what is currently in your ``task-definition.json``.

It would also be good to ask how to do it on the AWS Forums: https://forums.aws.amazon.com/forum.jspa?forumID=187 to see if they have any suggestions. You could also probably submit a feature request for the ECS there since for the CLI to pick up such a feature it would first need to be exposed by ECS's API.

**Comment by kyleknap** [comment]
Let me know if you have any more questions.

**Comment by kyleknap** [comment]
Closing. Please reopen if any updates come in or if you have any further questions.

**Comment by geoffreywiseman** [comment]
Yeah, I'm hitting this via boto instead of the CLI -- comparing the two is possible, of course, but troublesome, because you have to do it with a very content-aware comparison. Env keys can come  back in a different order than you sent them, values that you left blank might come back as empty lists ... etc. I wish the service tier would simply return the existing revision if there was no change. ;)

**Comment by laliconfigcat** [comment]
I run into the same problem and I started to go with the json compare solution, but it didn't feel right to me - feels a bit fragile. I went with a slightly different approach.
I calculate a checksum for my task-definition.json file after all environment variables, image tags, etc. are updated in my template task-definition.json. 
I store this checksum as a tag when registering the task definition at AWS.
But before I register the new task definition, I check the currently active task definition's checksum tag and compare it with my local checksum. If they are the same, i don't register the task definition and don't update the service.
