### ISSUE TITLE
InvalidEncryptionAlgorithmError

### ISSUE THREAD

**Issue by ssoto2** [aws/aws-cli#1349]
Issue:
s3api get object not supporting kms encryption 

Version Information:
╰─$ aws --version
aws-cli/1.7.30 Python/2.7.6 Linux/3.13.0-52-generic

Additional Details: 
Signature v4 turned on with aws configure set default.s3.signature_version s3v4
and does show in config file

Command being issued:
aws s3api get-object --bucket file-node --if-modified-since 2015-05-27T05:00:00Z --key latest/file.ova /tmp/file.ova --sse-customer-algorithm aws:kms --sse-customer-key (Key Redacted)

Error:
A client error (InvalidEncryptionAlgorithmError) occurred when calling the GetObject operation: The Encryption request you specified is not valid. Supported value: AES256.

Per the documentation at: http://docs.aws.amazon.com/cli/latest/reference/s3api/get-object.html

--sse-customer-algorithm (string) Specifies the algorithm to use to when encrypting the object (e.g., AES256, aws:kms).

--sse-customer-key (string) Specifies the customer-provided encryption key for Amazon S3 to use in encrypting data. This value is used to store the object and then it is discarded; Amazon does not store the encryption key. The key must be appropriate for use with the algorithm specified in the x-amz-server-side-encryption-customer-algorithm header.

**Comment by kyleknap** [comment]
@ssoto2 

How did you encrypt the object when you uploaded it? Was it server-side encryption or server-side with customer-provided encryption keys (SSEC).

I think our docs may be off here because according to S3's API docs, you cannot use kms for SSEC: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html. You can only use AES256. This is important because the parameters you are using to retrieve the object are SSEC parameters. I believe if you uploaded the object via server-side encryption (not SSEC), you should be able to retrieve the object without using any special parameters (i.e. only --bucket --key is needed).

**Comment by ssoto2** [comment]
@kyleknap you are completely correct. I had complete derp moment! Thanks for clearing it up... It works and all is good now! :)
