### ISSUE TITLE
route53domains only has one region

### ISSUE THREAD

**Issue by atward** [aws/aws-cli#1354]
route53domains is a global service and calls should be mapped through to the correct endpoint. 
```
$ aws route53domains list-domains

Could not connect to the endpoint URL: "https://route53domains.ap-southeast-2.amazonaws.com/"
$ python -c 'import boto.route53.domains;print boto.route53.domains.regions()'
[RegionInfo:us-east-1]
$ aws --region us-east-1 route53domains list-domains
{
    "Domains": []
}
$ aws --version
aws-cli/1.7.31 Python/2.7.6 Darwin/14.3.0
```
Should config.default.region be used when there's only one endpoint?

**Comment by kyleknap** [comment]
According to the [docs](http://docs.aws.amazon.com/general/latest/gr/rande.html#r53_region), the route53domains api does not have a global endpoint. It is just one regional endpoint, as you noted. The issue with defaulting to this single regional endpoint is that if route53domains ever expands into a new region, this logic will be broken because the new endpoint will never be used.

I do see that the error message is not too helpful, and that is something that we are looking to improve.

Let me know if you have any more questions.

**Comment by kyleknap** [comment]
Closing issue. Please reopen if you have any more questions or comments.

**Comment by FBosler** [comment]
So how does one connect to the service via the cli?

**Comment by Pluies** [comment]
Thanks @FBosler ! I use `eu-west-1` as default, and was running into the same issue in the AWS Go SDK, which showed up as:

```
RequestError: send request failed
caused by: Post "https://route53domains.eu-west-1.amazonaws.com/": dial tcp: lookup route53domains.eu-west-1.amazonaws.com: no such host
```

Setting the region to `us-east-1` for this session fixed this. 👍

**Comment by carlin-q-scott** [comment]
Well, over 5 years later, and r53 domains API still hasn't expanded to other regions. Seems like a lot of time would have been saved to have had the logic default to us-east-1. It can still be done, and simply revert the change if AWS ever expands r53 domains API to other regions.

**Comment by shearn89** [comment]
Yep - just bumped into this, when using the regular `aws route53 change-resource-record-sets` command, and sure enough setting the region to us-east-1 solved the problem. Would be nice if that was the default for the subcommand.

**Comment by scottebetts** [comment]
Hitting this today, March 27 in the year 2023. Probably ought to get around to fixing this.

**Comment by shearn89** [comment]
Bumping this to prevent auto-close. 8 years is long enough, please!
