### ISSUE TITLE
aws s3 sync --delete, removed some new local files

### ISSUE THREAD

**Issue by keithbmcd** [aws/aws-cli#1361]
Hi, 

There are some files in s3 bucket

s3 - 
s3://my-bucket/test/1.jpg
s3://my-bucket/test/2.jpg

my local - 

/test/1.jpg
/test/2.jpg

Then I removed a file s3://my-bucket/test/2.jpg in the bucket and created a file /test/3.jpg in local.

Then run aws s3 sync s3//my-bucket/ ./ --delete

it will return - 

delete ./2.jpg
delete ./3.jpg

I expect the 3.jpg will stay in local and 2.jpg will be removed
How can we fix it?

cheers.

keith

**Comment by kyleknap** [comment]
That behavior is as expected. The ``--delete`` flag will delete any files that exist in the destination that do not exist at the source. Based on the the steps that you did prior to the ``sync`` command, to my understanding your setup is the following:

s3 -
s3://my-bucket/test/1.jpg

my local -

/test/1.jpg
/test/2.jpg
/test/3.jpg

Since test/2.jpg and test/3.jpg are not in the s3 bucket, they should be deleted, as you observed.

Let me know if you have any more questions.

**Comment by keithbmcd** [comment]
Thanks for your reply,

we have no idea how to keep the new content and remove old content at the same time. We do not want to sync some old content back to s3 bucket..

Any suggestions to do that?

Thanks
