### ISSUE TITLE
aws deploy push Command = Add Support for "--query" and "--output"

### ISSUE THREAD

**Issue by colinbjohnson** [aws/aws-cli#1369]
## Current Behavior:

when running aws deploy push the command returns output as follows:
`To deploy with this revision, run:`
`aws deploy create-deployment --application-name codedeploy --s3-location bucket=codedeploy-codedeploybucket-1ajnq59aekkfj,key=codedeploy_1.0,bundleType=zip,eTag="77021852995a5e7be590c7dc8a2227fd" --deployment-group-name <deployment-group-name> --deployment-config-name <deployment-config-name> --description <description>`
## Desired Behavior:

For use in writing command line scripts, I'd like to be able to control the output using the `--query` option and "--output" command that is supported by other `awscli` commands. An example, I would run command:
`aws deploy push --application-name codedeploy --s3-location s3://$codedeploy_s3_bucket/codedeploy_${revision} --source ./ --region $region --query s3-location.key[eTag]`
And I would get returned:
`77021852995a5e7be590c7dc8a2227fd`
## Summary:

My feeling is that output from the command should be able to be controlled by the `--query` argument so that subsequent execution of the program allows us to use output in subsequent commands.

**Comment by jamesls** [comment]
Thanks for sharing the feedback.  What's going on here is that this "push" command is a custom command and it doesn't support the structured output and query options used by the "built in" commands.  We should be able to update this command to support this though.

Marking as a feature request.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
