### ISSUE TITLE
[BUG] [aws kinesis] Unexpected output values by table & text format on describe-streams

### ISSUE THREAD

**Issue by tcsh** [aws/aws-cli#1404]
* aws --version aws-cli/1.7.35 Python/2.7.5 Darwin/13.4.0

# normality

It expects "ACTIVE".

command (no output option):
```bash
$ aws kinesis describe-stream --stream-name ${STREAM_NAME} --query 'StreamDescription.StreamStatus'
```

result:
```text
"ACTIVE"
```

command (output json):
```bash
$ aws kinesis describe-stream --stream-name ${STREAM_NAME} --query 'StreamDescription.StreamStatus' --output json
```

result:
```text
"ACTIVE"
```

# BUG

It expects "ACTIVE".

command (output table):
```bash
$ aws kinesis describe-stream --stream-name ${STREAM_NAME} --query 'StreamDescription.StreamStatus' --output table
```

result:
```text
----------------
|DescribeStream|
+--------------+
```

command (output text):
```bash
$ aws kinesis describe-stream --stream-name ${STREAM_NAME} --query 'StreamDescription.StreamStatus' --output text
```

result:
```text
None
```

It happened not only "StreamStatus" but also "StreamName".

Thank you.

**Comment by kyleknap** [comment]
The output for the table is as expected because the end value is just a single string. Thus you cannot represent it as a table. It needs to be a list or structure. So something like this:
```
$ aws kinesis describe-stream --stream-name foo --query 'StreamDescription.[StreamStatus]' --output table
----------------
|DescribeStream|
+--------------+
|  ACTIVE      |
+--------------+
```

The output for text I can confirm and looks like a bug. That should not output ``None`` when all it needs to do is remove the quotes around a string.

**Comment by mtdowling** [comment]
After taking a deeper look, the root cause of this issue is that when using `--output text` on a paginated response, the resulting data is streamed as pages of results are retrieved from the service. The keys that we extract and stream are based on which keys change for each page of results. When applying the `--query` parameter to a paginated response using text output, the `--query` is applied to the filtered paginated keys rather than the entire response body. What this means is that you need to modify your `--query` to be relative to the paginated keys of an operation or you need to disable pagination using the `--no-paginate` argument.

As of right now, it's not obvious when an operation is paginated or what keys are streamed when paginating through responses using `--output text`. I'll work on a PR that injects this type of information in help output.
