### ISSUE TITLE
Unable to retrieve a job output if job ID starts with a dash

### ISSUE THREAD

**Issue by amaltsev** [aws/aws-cli#1409]
If, as a result of a "initiate-job" the job ID starts with a dash it seems to be impossible to retrieve that job results:

```
aws glacier get-job-output --vault-name vaultname --account-id - --job-id -job-id-with-a-leading-dash
usage: aws [options] <command> <subcommand> [parameters]
aws: error: argument --job-id: expected one argument
```

For "describe-job" there is a reasonable workaround (described in issue 1319):

```
aws glacier describe-job --vault-name vaultname --account-id - --cli-input-json '{"jobId":"-job-id-with-a-leading-dash"}'
```

But no such workaround exists for "get-job-output". If it is hard to properly fix this, then maybe at least a cli-input-json support can be added for "get-job-output"?

**Comment by mtdowling** [comment]
You can pass the `--job-id` argument in using `--job-id='-job-id-with...'`. You can use this type of argument syntax for a single argument or any argument:

```
aws glacier describe-job --vault-name='vaultname' --account-id='-' --job-id='-job-id-with-a-leading-dash'
```

**Comment by Levino** [comment]
Great engineering. I am overwhelmed by this beauty and genius. Thank you, whoever thought it was a good idea to allow hyphens in the ids to begin with.

And no Amazon. Do not change this. It might break... ahem... nothing? This is something that you can change and nobody will ever have an issue.

Thanks to @mtdowling and @amaltsev for running through this stupidity before me.

Further more: The python aws-cli tool is so beautifully parsing the strings from the bash in its own peculiar way, that escaping the hyphen with the usual hacks is impossible. Well done!

**Comment by bobilibop** [comment]
This Issue is not solved and should be reopened I think. I still have the same problem and no way to get the job output. I used the jobID from attached [joblist.json.txt](https://github.com/aws/aws-cli/files/948997/joblist.json.txt) and double checked the JobId, but the workaround with '-' syntax doesn't work with get-job-output command:
`aws glacier get-job-output --account-id - --vault-name test-sylvain-couhault --job-id '-MSbDtRA0yvqadVEoAN462dXuoorq7Ms8xo1rUfqD-QM9pnqgNO07yEwquxVf9iimmpnTv3ecIbiSp9OBxtx_FtyIc5O' output.json`

`An error occurred (ResourceNotFoundException) when calling the GetJobOutput operation: The job ID was not found: '-MSbDtRA0yvqadVEoAN462dXuoorq7Ms8xo1rUfqD-QM9pnqgNO07yEwquxVf9iimmpnTv3ecIbiSp9OBxtx_FtyIc5O'`

**Comment by stilts22** [comment]
this pattern worked for me, equal sign with no single/double quotes:
 --job-id=-FDRuiJXslObrKP
