### ISSUE TITLE
Include CHANGELOG in awscli bundle

### ISSUE THREAD

**Issue by jcmcken** [aws/aws-cli#1430]
I think it would be useful if the change log for `awscli` were included with the `awscli-bundle` (even if it's not deployed via the installer) so that users don't have to hunt for the updates here or other places.

**Comment by nkadel** [comment]
Please, yes. It would make packaging the awscli as an RPM or other package managed component much more useful.

**Comment by jamesls** [comment]
I'll take a look, should be pretty straightforward.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
