### ISSUE TITLE
$ ec2 copy-snapshot --no-encrypted raises InvalidParameterValue error.

### ISSUE THREAD

**Issue by quiver** [aws/aws-cli#1440]
I think this is a server side bug.
# Problem

`ec2 copy-snapshot` has an option(`--encrypted`) to encrypt non-encrypted EBS snapshots. (http://docs.aws.amazon.com/cli/latest/reference/ec2/copy-snapshot.html)

```
$ aws ec2 copy-snapshot --source-region ap-northeast-1 --source-snapshot-id <SNAPSHOTID> --description XXX --encrypted
```

According to the API doc(http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CopySnapshot.html), this flag(`Encrypted`) is boolean and AWS-CLI supports `--encrypted` _and_ `--no-encrypted` flags.

But if you pass `--no-encrypted` option, `InvalidParameterValue` error is raised.

```
$ aws ec2 copy-snapshot --source-region ap-northeast-1 --source-snapshot-id <SNAPSHOTID> --description XXX --no-encrypted --debug
...
GET
/
Action=CopySnapshot&Description=encrypted%20snapshot&DestinationRegion=ap-northeast-1&Encrypted=false&...
...
A client error (InvalidParameterValue) occurred when calling the CopySnapshot operation: -10022: The parameter encrypted=false is invalid
```

This error occurs against both encrypted and unencrypted snapshots.
# Expected result
- [ok]`--encrypted` => copied snapshots are encrypted.
- [gray zone]`--no-encrypted` => copied snapshots are unencrypted.But decrypting encrypted EBS snapshots are not supported(http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-copy-snapshot.html), so this flag is meaningless against encrypted snapshots. For such case, server side should raise errors, I think. What do you think?
- [ok]no Encrypted flag provided => as-is. Keep encrypted state

**Comment by quiver** [comment]
`--no-encrypted` has no use cases at the moment.

**Comment by mtdowling** [comment]
Yeah, this appears to be a parameter in which the only use case for the parameter is setting the value in the affirmative. We will double check to make sure that is the case and if so, see if we can customize this parameter such that `--no-encrypted` is not listed as an option.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
