### ISSUE TITLE
Can't seem to run ./install after pulling in s3 codedeploy 

### ISSUE THREAD

**Issue by joshbedo** [aws/aws-cli#1441]
I'm trying to setup codedeploy on a amazon linux AMI and have everything working to the point where i need to run `./install auto` to start the agent. I ran the following command `aws s3 cp s3://aws-codedeploy-us-east-1/latest/install . --region us-east-1` to download the latest and now when i run `./install auto` after `chmod -x ./install` i get `permission denied`. I also tried running it with `sudo` and it  throws an error saying `sudo: unrecognized command ./install`. Any ideas on how i can get `./install` to execute?

![](https://camo.githubusercontent.com/3058038c762de12b294c9d2ce035c6ad3594efdb/687474703a2f2f692e696d6775722e636f6d2f51506d774957702e706e67)

**Comment by jamesls** [comment]
Looks like this is for the installer for the codedeploy agent, which is a separate project from the AWS CLI.    I'm not familiar with this installer, but it appears to be a ruby file, so maybe "ruby ./install" might work.  Otherwise, the codedeploy should be able to help you out if you ask on [their forums](https://forums.aws.amazon.com/forum.jspa?forumID=179).

**Comment by joshbedo** [comment]
Got it working, it worked after running `chmod -R 777 ./install`. I guess i didn't have execute privileges.
