### ISSUE TITLE
large files no failure message

### ISSUE THREAD

**Issue by alexfrieden** [aws/aws-cli#1446]
Running on large files (around 30 GBs)
```
aws s3 cp s3://mybucket/myfile .
Completed 1890 part(s) with ... file(s) remaining
```
The file doesn't complete and doesn't alert that it has failed.  Is this a known bug?

**Comment by jamesls** [comment]
This shouldn't be happening.  What actually happens when you say it doesn't complete?  Do you mean that the CLI just exits?  Does it hang?
  
Can you share more information about what's happening, or steps to repro?  If possible, you can rerun the command with `--debug` so you can see the last thing it did.  This will give us any insight into what went wrong.

**Comment by alexfrieden** [comment]
It does not hang, just exits, I have noticed the file size is less than what it should be as if it only writes part of it.

**Comment by jamesls** [comment]
Are you getting a non zero rc?

**Comment by alexfrieden** [comment]
Haven't checked rc, will check
