### ISSUE TITLE
using sse-kms when uploading objects

### ISSUE THREAD

**Issue by kbiton** [aws/aws-cli#1466]
I use the aws s3 cli command to upload multiple object to s3 , I am utilising the parallel multipart build-in features. I noticed thar sse-kms is not a supported option when using aws s3 it looks like only sse-s3 is supported is there any particular reason for that ? I can use the high level API , aws s3api that being said this API (IMHO) does not support parallel & multipart uploads.
can you recommend on a workaround will support to SSE-KMS added to the cp options?

**Comment by kyleknap** [comment]
It just has not been added it. Mainly because there may be some edge cases that we will have to take into account. For example, in order to use kms with s3, the requests must be signed using signature version 4.

I do not think that there is a good workaround, other than using ``s3api``, but like you said that does upload in parallel or automatically handle multipart. Marking this as feature request.

**Comment by kbiton** [comment]
thank you
