### ISSUE TITLE
Add support for cognito cred provider

### ISSUE THREAD

**Issue by quiver** [aws/aws-cli#1518]
This is a feature request.

I would be great if AWS-CLI handles tedious cognito unauth user flow behind the scene, just like sts `assume-role`.
## implicit cognito-identity API calls

Currently, if you want to access AWS resources via cognito unauth users, you have to call two `cognito-identity` APIs.
1. `cognito-identity`  to get ids
2. `get-credentials-for-identity`  to get temporary credentials.

After that, set credentials for the next API calls.

If AWS-CLI handles these auth flow, shell scripts become much simpler.
## file-caching cognito credentials

cognito unauth users really fit with IoT devices since you don't need to distribute credentials,
and I don't want these devices to incur extra communication costs.
Just like sts assume-role, local-caching cognito credentials reduces cognito-wise API calls.
## new style

```
$ cat ~/.aws/credentials
[profile foo]
identity-pool-id = ... <- new attributes for unauth cognito user
$ aws s3 cp foo s3://bucket/foo --profile foo # If there's no cognito credentials, get cred via cognito-identity APIs before calling S3 command.
$ aws s3 cp bar s3://bucket/bar --profile foo # use local-cached cognito credential
```
## old style

```
$ aws cognito-identity get-id --identity-pool-id XXX --region eu-west-1
{
    "IdentityId": "YYY"
}
$ aws cognito-identity get-credentials-for-identity --identity-id XXX --region eu-west-1
{
    "Credentials": {
        "SecretKey": "AAA",
        "SessionToken": "BBB",
        "Expiration": 1442811006.0,
        "AccessKeyId": "CCC"
    },
    "IdentityId": "YYY"
}
$ export AWS_SECRET_KEY=AAA ...
$ aws s3 cp foo s3://bucket/foo
```

**Comment by kyleknap** [comment]
Marked as feature request.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (152/150 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 6170 characters long; only the first
------ 5000 or so are included here.
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:44276 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1ej0Oz-001aUO-Vh
	for hello@salmanwaheed.info; Tue, 06 Feb 2018 03:23:03 -0700
Date: Tue, 06 Feb 2018 02:22:35 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1517912555;
	bh=SMtOi1Rc7PSr1hpHbiWXgtEGIsjv+WdUvY8xEpHZLwg=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=OT9z80f+CJEFqgKT4V3anPAmeD8EzUUFd65xhh7FHvs7PVOI0r5L2PIEx9+yLEuRp
	 lNgYKx4orm2U/P7keavpDJJHBhjx/gS2MkpnAJ6U1PWspxU7/o/A4bw0ISaWeWNamF
	 SLs7GCATR2f2lZCLohG4YsYpAYnLHqEdMoRLDs0w=

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by tim-finnigan** [comment]
It looks like this issue hasn’t had any community engagement in the past few years. @quiver is this request still something you would like to see added?

**Comment by quiver** [comment]
>  @quiver is this request still something you would like to see added?

Not anymore.
Close this issue.
