### ISSUE TITLE
Error parsing parameter if it contains ]

### ISSUE THREAD

**Issue by patanachai** [aws/aws-cli#1528]
I try to submit s3dist following this tutorial
http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/UsingEMR_s3distcp.html

When I run this command
`aws emr add-steps --cluster-id j-3GYXXXXXX9IOK --steps Type=CUSTOM_JAR,Name="S3DistCp step",Jar=/home/hadoop/lib/emr-s3distcp-1.0.jar,\
Args=["--s3Endpoint,s3-eu-west-1.amazonaws.com","--src,s3://mybucket/logs/j-3GYXXXXXX9IOJ/node/","--dest,hdfs:///output","--srcPattern,.*[a-zA-Z,]+"]`

it returns
Error parsing parameter '--steps': Expected: ',', received: '+' for input:

If I remove `[a-zA-Z]`, for example
`aws emr add-steps --cluster-id j-3GYXXXXXX9IOK --steps Type=CUSTOM_JAR,Name="S3DistCp step",Jar=/home/hadoop/lib/emr-s3distcp-1.0.jar,\
Args=["--s3Endpoint,s3-eu-west-1.amazonaws.com","--src,s3://mybucket/logs/j-3GYXXXXXX9IOJ/node/","--dest,hdfs:///output","--srcPattern,.*z+"]`

It works fine.
This problem doesn't exist in aws-cli 1.7

**Comment by kyleknap** [comment]
Can confirm. This looks like another issue from when we updated the shorthand parser.

**Comment by jamesls** [comment]
I spent some time looking into this.  This command just happened to work before, but the latest bug fixes to the shorthand parser now no longer make this work.

The issue isn't with the actual shorthand syntax, that's backwards compatible.  The issue is how bash is interpreting those sequences *before* handing it off to the AWS CLI.  If I prefix this command with `echo`, you can see that the double quotes are being removed:

```
$ echo aws emr add-steps --cluster-id j-3GYXXXXXX9IOK --steps Type=CUSTOM_JAR,Name="S3DistCp step",Jar=/home/hadoop/lib/emr-s3distcp-1.0.jar,\ Args=["--s3Endpoint,s3-eu-west-1.amazonaws.com","--src,s3://mybucket/logs/j-3GYXXXXXX9IOJ/node/","--dest,hdfs:///output","--srcPattern,.*[a-zA-Z,]+"]

aws emr add-steps --cluster-id j-3GYXXXXXX9IOK --steps Type=CUSTOM_JAR,Name=S3DistCp step,Jar=/home/hadoop/lib/emr-s3distcp-1.0.jar, Args=[--s3Endpoint,s3-eu-west-1.amazonaws.com,--src,s3://mybucket/logs/j-3GYXXXXXX9IOJ/node/,--dest,hdfs:///output,--srcPattern,.*[a-zA-Z,]+]
```

Notice the end of the output: `--srcPattern,.*[a-zA-Z,]+]`.  The double quotes have been removed.

What needs to happen is that the double quotes surrounding the values needs to be passed through to the CLI.  The easiest way to do this is to surround the value with single quotes:

```
$ echo aws emr add-steps --cluster-id j-3GYXXXXXX9IOK --steps 'Type=CUSTOM_JAR,Name="S3DistCp step",Jar=/home/hadoop/lib/emr-s3distcp-1.0.jar,Args=["--s3Endpoint,s3-eu-west-1.amazonaws.com","--src,s3://mybucket/logs/j-3GYXXXXXX9IOJ/node/","--dest,hdfs:///output","--srcPattern,.*[a-zA-Z,]+"]'
aws emr add-steps --cluster-id j-3GYXXXXXX9IOK --steps Type=CUSTOM_JAR,Name="S3DistCp step",Jar=/home/hadoop/lib/emr-s3distcp-1.0.jar,Args=["--s3Endpoint,s3-eu-west-1.amazonaws.com","--src,s3://mybucket/logs/j-3GYXXXXXX9IOJ/node/","--dest,hdfs:///output","--srcPattern,.*[a-zA-Z,]+"]
```

That example should now work.  I'll follow up with getting the doc page you've linked updated.

**Comment by JordonPhillips** [comment]
This issue is being closed due to inactivity

**Comment by Ozgurian** [comment]
jamelsls, thanks for the wonderful explanation, you are giant carrying us on shoulder.
