### ISSUE TITLE
s3 sync has an error when bucket contains "directory" name that matches file

### ISSUE THREAD

**Issue by cmawhorter** [aws/aws-cli#1538]
In s3 a "directory" can share the same name as a "file" because in s3 there are only objects.    But of course on most file systems, file and directory names cannot be the same.

I couldn't find any existing issue, but it's probably not surprising that s3 sync has an issue here.

When doing a sync of a bucket -> local with objects named that way, s3 sync dies.

**Comment by rayluo** [comment]
I thought S3 stores "objects", which are more like "files" than "directories". Do you mean you already encounter some issue, or you are imagining there would be an issue? If there is an issue, feel free to write down the steps to reproduce that and we are happy to help.

**Comment by cmawhorter** [comment]
> Do you mean you already encounter some issue

There's an issue.

Repro:

1. Create a file named "something"; put in bucket
2. Create directory named "something" with a single file "page.html" inside; put in same bucket
3. There will now be two keys in the bucket: /something, and /something/page.html
4. Try to `aws s3 sync` the bucket locally.  aws cli tries to write to the file as if it were a directory and dies

I'm not sure what the correct behavior should be.

**Comment by rayluo** [comment]
@cmawhorter  Thanks for pointing out this issue. You are so clever to find it.

While this issue does exist, IMHO I don't think there will be a solution for it. The root cause of such issue is that, as you already pointed out, the [flat S3 key naming space](https://docs.aws.amazon.com/AmazonS3/latest/dev/IndexDocumentSupport.html#IndexDocumentsandFolders) is subtly yet fundamentally different to the typical hierarchical file system structure. There is no way to fully overcome the gap.

In practice, even the `www.example.com/products` and `www.example.com/products/mug` case can be mitigated by using `www.example.com/products/index.html` to represent the folder summary, so that you will have 2 files in same folder, as usual.

**Comment by cmawhorter** [comment]
I know it may seem small, but it's really annoying that there is no good way to do  "example.com/products" instead of "example.com/products/" on an s3 website.  

The problem isn't with s3, it's with how the discrepancy is (isn't) handled by the client.

The tl;dr; of my workaround is: all filenames get a prefix while on disk.  It'd be nice to have this or something else baked into sync.

I'll probably put this in a gist or post, but using an intermediary bucket is the only thing I could come up with:

1. `aws s3 rm s3://website-intermediary --recursive` 
2. `aws s3 sync . s3://website-intermediary --acl public-read` 
3. `node workaround-s3-rename.js website-intermediary` 
4. `aws s3 sync s3://website-intermediary s3://website --acl public-read`

The [workaround-s3-rename.js](https://gist.github.com/cmawhorter/b706e45ba88e43bc379c) script loads all keys and copies them to the unprefixed name location, then deletes the prefixed version.

The end result is a bucket that contains a clean s3 website sans trailing slashes.

Of course, the downside to not having this in sync is that the entirety of the contents gets uploaded each and every time.  If this were baked in, we could do all this in one `aws s3 sync` operation both ways.

**Comment by JordonPhillips** [comment]
I really don't think there is anything we can do to support this. Your workaround works because you are moving the issue out of a file system and into an object store, which does not have the issue. Another way to work around the issue would be to have `example.com/products/index` and copy (or move) that to `example.com/products` after your sync. This will get you the benefit of sync while still allowing you to have the url without needing to use `/index` at the end. That will be some extra commands you may not want to have to do if you have a large site. In that case you could have s3 trigger a lambda function to do it for you (say, on any object with the suffix `/index`).

**Comment by cmawhorter** [comment]
> s3 trigger a lambda function

I like this idea to make the workaround better.  Changing it to be /index though assumes there isn't a second, different page already at that location.

And there is still the problem of one-way sync and needing to reupload everything every time.

If there was just some way to hook into the actual `aws s3 sync` put/get...  plan on supporting scripting any time soon? :))

I fully admit this is an edge case, but it's an edge case without a solid workaround. :(

Another random idea.  If sync could work off a flat list of files and grab keys from an index.json, that would work too.

/path/to/local-site:
  - abe174...f1
  - ...
  - index.json => { "products/mugs": "abe174...f1", ... }

In fact.  If aws cli worked this way and I could store params with the file, it'd solve some other issues I'm having like per-object content-types, caching, etc.

**Comment by JordonPhillips** [comment]
The whatever you alias the file as isn't that important since you're going to be changing it anyway. You could ping on the suffix `-set-as-directory-index` or some such. You might incur a small expense due to an elevated number of requests, but it wouldn't be significant ($0.005 per 1000 requests). The lambda processing would probably be free, as the first million requests per month are without cost and it's like $0.20 per million after that. With your use case, I doubt you'd ever hit cost on lambda.

Direct support for hooks in the cli aren't supported, though botocore (the underlying library) has a robust events system that can be hooked into. You could wrap the cli and add in the hooks, but that could become a pain.

**Comment by JordonPhillips** [comment]
You would be able to sync just fine, only with the exception of the file copy. Your lambda function would take care of updating the copy for you though, so it would become a non-issue.

Also, I think it is pretty well standard to have `/index` and `/` be the same thing. I would be very confused if a website had `/products` and `/products/index` and they weren't the same page.

**Comment by JordonPhillips** [comment]
Your lambda function would look something like this:

```python
import json
import boto3


s3 = boto3.resource('s3')


def lambda_handler(event, context):
    bucket = event['Records'][0]['s3']['bucket']['name']
    key = event['Records'][0]['s3']['object']['key']
    index = s3.Object(bucket, key)
    # You could also do a string replace. We're getting rid of '/index'
    # from the key.
    new_key = key[:-6]
    print("New Key: " + new_key)
    copy = s3.Object(bucket, new_key)
    print(bucket+key)
    response = copy.copy_from(CopySource=bucket+'/'+key)
    return response
```

(Yay, python is supported in Lambda now!)

You would also want something in there to clean up if you delete the thing.

**Comment by JordonPhillips** [comment]
I'm going to go ahead and close this issue since there's nothing more we can do here. Feel free to open a feature request regarding your translation idea, but I don't think it is something we would want to pursue.
