### ISSUE TITLE
Feature Request: Ability to print all known CLI options

### ISSUE THREAD

**Issue by lorengordon** [aws/aws-cli#1571]
Please consider a flag such as `aws configure list --all` to print all known CLI options. See https://github.com/aws/aws-cli/pull/1379#discussion_r42416824 for context.

**Comment by mtdowling** [comment]
Thanks. We'll add supporting something like this to our backlog.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (156/150 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 6170 characters long; only the first
------ 5000 or so are included here.
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:56916 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1ej0PP-001aej-HB
	for hello@salmanwaheed.info; Tue, 06 Feb 2018 03:23:28 -0700
Date: Tue, 06 Feb 2018 02:23:11 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1517912591;
	bh=OQSa+mCtxaLsRDS38XLDMS64zYJdjWZcB6CrMg9nbaE=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ClyxGblZ6K7uiq+hYPep2Mxh0ZpXJBzb6n2ZsmkzUSi9DsksEsf7qYqALFeIqbQol
	 2Mp2sEuEzWDmeY+1pFkZ/cYbLCqHsthd1jNYgtCJ4lEYR9+5VRLpyKAFZdhpi+uaur
	 noTP+iQV0iIdVLMKBCJLc2DehMp/1yeY7XyVqmEU=

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (157/150 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:39211 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1ej0PR-001ael-E5
	for hello@salmanwaheed.info; Tue, 06 Feb 2018 03:23:30 -0700
Date: Tue, 06 Feb 2018 02:23:12 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1517912592;
	bh=MosmXual6caIhj8FubGmWxpQzP1AIqUBoI4+jsi8BNI=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=tCLMLljxl3oAZrF+l0pNDo6x3FOBJf2aFCx+lFSUmTuTBM2Jxxx/O8396Z5l/otAq
	 BQ1+YkKzJZiTKmmMp7SvMuJEJGT5nH9smQZVybdwG5u+pkLAwIIaZrdwNHVNLqGIsP
	 I0dlnMToKx5RAxGHQi65DjWeIyEHfSsVm6TfQQJM=

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
