### ISSUE TITLE
s3: sync/cp: regular filesystem ACL are not preserved

### ISSUE THREAD

**Issue by drzraf** [aws/aws-cli#1585]
POSIX ACL (Access Control Lists) are not preserved during cp/sync operation.
I guess other filesystem extended attributes are not either.

$ getfacl file.txt

```
user::rw-
user:www-data:rw-
group::r--
mask::rw-
other::r--
```

$ aws s3 cp file.txt s3://bucket/
$ aws s3 cp s3://bucket/file.txt file.2.txt
$ getfacl file.2.txt

```
user::rw-
group::r--
mask::rw-
other::r--
```

The ACL about `www-data` was not preserved.

**Comment by mtdowling** [comment]
I'll mark this as a feature request, but this might be something that we decide not to add support for.

**Comment by kyleknap** [comment]
Adding on the request of having a general purpose "additional file metadata/attributes" feature from this issue https://github.com/aws/aws-cli/issues/1833

**Comment by frekele** [comment]
+1

**Comment by frekele** [comment]
+1
example in s3cmd Config.py and FileList.py:

```
    preserve_attrs = True
    preserve_attrs_list = [
        'uname',    # Verbose owner Name (e.g. 'root')
        'uid',      # Numeric user ID (e.g. 0)
        'gname',    # Group name (e.g. 'users')
        'gid',      # Numeric group ID (e.g. 100)
        'atime',    # Last access timestamp
        'mtime',    # Modification timestamp
        'ctime',    # Creation timestamp
        'mode',     # File mode (e.g. rwxr-xr-x = 755)
        'md5',      # File MD5 (if known)
        #'acl',     # Full ACL (not yet supported)
    ]
```

**Comment by mike503** [comment]
+1 please add in at least basic mode support. if going through the effort, probably makes sense to just do all extended attributes. but I just had to evaluate and wound up using s3cmd instead of aws s3 sync (which is way faster!) because it supports the basic attributes I want (mainly executability / modes, but everything would be good to have...)

s3cmd is a lot slower, possibly because of extra work due to this? or maybe it just isn't as well done from the multithreading. either way, please consider.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (161/150 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:58479 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1ej0PV-001aiW-Pk
	for hello@salmanwaheed.info; Tue, 06 Feb 2018 03:23:34 -0700
Date: Tue, 06 Feb 2018 02:23:17 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1517912597;
	bh=zcaF8QIZW1q4tq+rzk4t4iP883cWHsQy2HULPOAHfTM=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=FarKqqwK0mQ4xoYhd3ncznVSI8s/yhZJhdJoa6XyF0c5cClOUgiqBn5kBjfO9bJMR
	 9WRLVOeQFnh9Ns9oEt3KfA95Oj8p0AD5fa2X5GO8vVpENQrFai3xf9eBNdZToTl4eM
	 M7+XV7hKBYKmda+1qveRev84vVnhLSFsjjYgOsf0=

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (158/150 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 6170 characters long; only the first
------ 5000 or so are included here.
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:58769 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1ej0PT-001akU-JT
	for hello@salmanwaheed.info; Tue, 06 Feb 2018 03:23:32 -0700
Date: Tue, 06 Feb 2018 02:23:17 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1517912597;
	bh=UBM9uOjVajlXdwjT0MXNeYbAMPFmR/T5dpKhLYQA8Zs=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=aua3cufUjbYTeiGifuBX/Nz9S3ZrGYkUc/Juuta3a26KqGR6V7GanF5gWhRbufcqt
	 /pCrWq8sl3SbgwnlXdjMoEnK8XIJHUdtY8oCv1BwS7Y+BAxvxaa0y/gJYljOfqmSn5
	 QfBOnHaxAwt8Lxp1Qwfutsg91A2+CKbQl5QSxazM=

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by aaronjensen** [comment]
For anyone else coming here, I was able to use this to copy one bucket to another and keep ACLs: https://github.com/cobbzilla/s3s3mirror/tree/2.1-stable

It's also significantly faster.
