### ISSUE TITLE
aws s3 rb --recursive doesn't recursively delete files in pseudo folders.

### ISSUE THREAD

**Issue by ovjh** [aws/aws-cli#1587]
This issue we are noticing for our proprietary s3 compatible storage. We are seeing one issue with the way aws cli handles "rb" command with --recursive flag.

we have one bucket bucket1 with following object structure.
s3://bucket1/object1
s3://bucket1/folder1/object2
s3://bucket1/folder1/folder2/object1

now if we issue "aws s3 rb s3://bucket1/ --recursive" then I observed that aws cli issues below commands 

1) It does  GET s3://bucket1/
2) and then deletes all the objects listed above.

Now the response for the command 1) can be.
PRE folder1/
        object1

What we see is that aws cli deletes "object1" but doesn't recursively traverse and delete objects in "folder1/". It will be great if aws cli can recursively traverse and delete files in the pseudo folders.

**Comment by mtdowling** [comment]
I wasn't able to reproduce this issue. I also see that you're using `--recursive`, but I think you want to use `--force`. Can you confirm that you're using the latest version of the CLI?

**Comment by ovjh** [comment]
I tried using both the options.. its fails with both of them when you have pseudo folders. I think amazon's s3 interface returns all the objects inside pseudo folders if delimiter is not specified.  The way to reproduce this issue with cli will be to modify cli code to send GET request with delimiter option = "/". That way in the reply you will get pseudo folders.

**Comment by mtdowling** [comment]
I was able to successfully delete an entire bucket that has nested pseudo folders using `aws s3 rb`. I didn't run into any issues with nested pseudo folders being left behind.

Maybe I'm misunderstanding what the issue is. Can you make the problem statement more clear? Are you saying the CLI is not deleting pseudo folders from your bucket?

**Comment by ovjh** [comment]
So if aws cli is used to delete bucket recursively like this "aws s3 rb s3://bucket_name --recursive" then it is able to delete objects inside pseudo folders for amazon s3 service. But it fails to delete them for a s3 api compatible service. The reason why this doesn't work is that the cli doesn't recursively try to list objects inside pseudo folders and delete them.

The easiest way you can reproduce this for amazon s3 will be to issue "GET /bucket_name" with delimiter option set to "/". So it won't list you all the files inside folders and thereby cli will not delete it.

If I understand correctly then when you issue "aws s3 rb --recursive" command below steps are executed.
1) it issues GET /bucket_name/ without delimiter option set to "/"
2) it deletes all the entries(files) returned by previous api. However if there is any pseudo folder there then it won't try to read files inside it. (This is the root cause of the problem).

**Comment by mtdowling** [comment]
> So if aws cli is used to delete bucket recursively like this "aws s3 rb s3://bucket_name --recursive" then it is able to delete objects inside pseudo folders for amazon s3 service. But it fails to delete them for a s3 api compatible service.

Because the CLI is working for Amazon S3 buckets, the root cause of this issue seems to be an incompatibility with the proprietary S3 compatible storage service you are using and the actual S3 service.

> The easiest way you can reproduce this for amazon s3 will be to issue "GET /bucket_name" with delimiter option set to "/". So it won't list you all the files inside folders and thereby cli will not delete it.

The CLI actually issues a GET request to the bucket to list keys with no delimiter option. This means that we will list the keys contiguously with no CommonPrefix traversal necessary. Here's an excerpt request start-line taken from a `--debug` log where I observed this: `GET /?prefix=&encoding-type=url HTTP/1.1`. You can observe the same behavior by running `aws s3 rb $my_bucket --force --debug` (where `$my_bucket` is your bucket name).

**Comment by ovjh** [comment]
@mtdowling Yes you are right. But is it hard to add that change? If CommonPrefix is returned in response then do the traversal? I think by adding this it will add an additional feature to it and that way help other s3 compatible vendors too if they default to delimiter="/" if not specified.? what do you think?

**Comment by mtdowling** [comment]
I don't think making this change is in the best interest of the CLI as what we are doing right now is the most performant thing possible for *real* S3. Adding a delimiter would force the CLI to issue many more requests -- one for each level of pseudo folder nesting. By omitting delimiter, we are retrieving as many keys per operation as possible, limiting the number of required HTTP requests, and giving a better user experience.

The root cause here is that the S3 compatible storage system you're using needs to provide a more compatible S3 API so that it is consistent with how S3 works.

**Comment by ovjh** [comment]
@mtdowling  I complete understand this. But what I am asking is not for CLI to issue request with delimiter (that is just for testing the code) but if say s3 server sends "CommonPrefix" in the response then it should be able to handle that? If you want I can work on that add send pull request. Can you point me to the code where to look at? what do you think? By doing this S3 will be able to handle CommonPrefix too if in the response (if it comes).

**Comment by mtdowling** [comment]
Getting S3 to include CommonPrefixes for responses that did not include a Delimiter would need to be a change made by the S3 team. S3 is not open source so it's not something that you could contribute. I also don't think it makes sense to send back CommonPrefixes as part of a response when no delimiter was used because you can infer the common prefixes from the keys returned in the response client-side (everything is in a flat list when no delimiter is used).

**Comment by ovjh** [comment]
What I am saying is that we don't need to make any change in S3 service. Just add a feature in AWS -S3-CLI to process "CommonPrefixes" in the response if there are any. Client side parsing is fine but the problem comes when we are using "--recursive" or "--force" option in bucket delete. Here client won't get the control. That is the problem we are facing.

In case of --recursive or --force option with bucket delete, what happens is explained below. (By the way this is happening for S3 compatible our service and not for Amazon S3 service).
1) client issues s3 bucket delete command. "aws s3 rb s3://bucket1 --recursive"
2) server responds with below response
  PRE folder1/
  PRE folder2/
  file1.txt
  file2.txt
3) aws cli then just deletes file1.txt and file2.txt
4) aws cli now tries to delete bucket but gets an exception as the bucket is not empty.
5) Client gets an exception and gets control back. (But here client can not do anything).

So what I was suggesting was that at step 3). if step 2) returned anything in "CommonPrefixes" then try to explore those folders and delete files in them recursively. This do it only when you are deleting files recursively in case of 
1) rb command with "--recursive" and/ or "--force" option.
2) rm command with "--recursive" option.

**Comment by ovjh** [comment]
@mtdowling does the above explanation for the feature request makes sense? I would be happy to contribute if necessary.

**Comment by mtdowling** [comment]
I don't think we'll be able to make that change in the CLI. The CLI targets the Amazon S3 service. Using the CLI with an "S3 like" service is not something that we directly support, but rather it's up to the "S3 like" services to behave like S3 in order to be fully supported by the CLI. Adding workarounds for inconsistent "S3 like" implementations into the CLI will complicate the CLI, and has a maintenance cost associated with it. I suggest you raise an issue with your "S3 like" service to let them know of the issue.

**Comment by ovjh** [comment]
@mtdowling no problem. I understand the maintenance problem. Can you let me know the code to look at? file/function? That would be really helpful and thank you for all the help.
