### ISSUE TITLE
aws cli dynamodb query documentation needs clarifying and examples

### ISSUE THREAD

**Issue by keithdotpower** [aws/aws-cli#1601]
The current documentation for using dynamodb via cli (at http://docs.aws.amazon.com/cli/latest/reference/dynamodb/query.html) is not very helpful. I've got some queries going by trial and error but I just can't work out how to use --starting-token.

What would be particularly helpful would be some examples. The single example there is very simple and uses a parameter which is documented as legacy (--key-conditions).

The particular problem I still can't solve after a day of hair-pulling is how to use the NextToken value returned from one query to pass into another. E.g. at the end of my results for one query I get:

```
    "NextToken": "{u'license': {u'S': u'a5fef9b2-a8b7-4213-8d63-e9cb6f8ca7e7'}, u'ts': {u'S': u'1445257263181'}, u'key': {u'S': u'c7c420b2-c95b-42c0-92ba-15a9eaab3aa2'}}",
    "ScannedCount": 50,
    "ConsumedCapacity": null
}
```
How do I pass that via --starting-token to my next query to get the rest of the results? If I try:

```
--starting-token '{"license": {"S": "a5fef9b2-a8b7-4213-8d63-e9cb6f8ca7e7"}, "ts": {"S": "1445257263181"}, "key": {"S": "c7c420b2-c95b-42c0-92ba-15a9eaab3aa2"}}'
```

I get: 

```
Parameter validation failed:
Invalid type for parameter ExclusiveStartKey, value: {"license": {"S": "a5fef9b2-a8b7-4213-8d63-e9cb6f8ca7e7"}, "ts": {"S": "1445257263181"}, "key": {"S": "c7c420b2-c95b-42c0-92ba-15a9eaab3aa2"}}, type: <type 'unicode'>, valid types: <type 'dict'>
```

I'm giving up on this now and will try again with the Java API tomorrow, just adding this issue to help the next guy.

**Comment by JordonPhillips** [comment]
This looks like a bug with how we handle pagination tokens. Thanks for reporting!

**Comment by krishnan-mani** [comment]
@JordonPhillips: when you assigned this to yourself, does this indicate you are investigating this bug and hope to contribute a fix. Also, is it fair to assume this is likely to be an issue on the API end rather than with aws-cli itself?

I was about to try and add more documentation for use of the aws-cli with dynamodb (as in the original text of the issue) and send in a pull request. Let me know if you think this is still worth doing. 

I am going over issues and looking for something to get my feet wet with and start contributing. Any pointers are appreciated. Thanks!

**Comment by philmcmahon** [comment]
@krishnan-mani re adding more documentation, that would be extremely useful. I've been battling trying to get a simple get-item query working but without success, now planning to try with the legacy key-condition query as that's at least documented.
