### ISSUE TITLE
aws emr create-cluster --configurations and web console settings are inconsistent

### ISSUE THREAD

**Issue by fs111** [aws/aws-cli#1678]
When creating a new EMR cluster on the cli, the emr commandline insists that the protocol for the configurations either being `file://` of `http(s)://`. Using `s3://` will not work. The web-console on the other hand demands that the protocol has to be `s3://`. That is inconsistent and confusing.

**Comment by rayluo** [comment]
Thanks for bringing this to our attention.

The underlying API expects a raw json as input. Web console and CLI each provides a convenience on top of it to give customer a chance to load json content directly from a file. It turns out they implement different input format. [Web console accepts `s3://...` only](http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/EMR_CreateJobFlow.html#CreateJobFlowConsole), while CLI traditionally accepts either `file(b)://` or `http(s)://` for almost any parameter. Current CLI implementation specifically [documents this requirement already](http://docs.aws.amazon.com/cli/latest/reference/emr/create-cluster.html).

That being said, it is still possible in future we add a `s3://...` as an input method in CLI. So I am now marking this as a feature request, although it may not be in a super high spot in our to-do list.

**Comment by fs111** [comment]
I can see that it isn't a priority, I just stumbled upon it while writing a howto for users of our product and saw the differences. These little paper-cuts tend to confuse users and can be a source of much wasted time. That's why I submitted the issue here.

**Comment by sporkthrower** [comment]
While having the console and the cli be consistent and both support http and s3 protocols, the real issue in my mind is that users can't currently host a public configuration file in an s3 bucket and make it available for others to use in the console.  Since the console requires s3 protocol, people in different regions or accounts will get errors when trying to specify the configuration URI.  Using the http protocol is preferred in this case.  Related to the following forums post : https://forums.aws.amazon.com/message.jspa?messageID=696248#696248

**Comment by fs111** [comment]
If http is not an option, it should at least behave the same way that EMR bootstrap-actions behave. They can be used from any public bucket, which makes sharing them very easy.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (164/150 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 6164 characters long; only the first
------ 5000 or so are included here.
Received: from o7.sgmail.github.com ([167.89.101.198]:54583)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-a7b0-hello=salmanwaheed.info@sgmail.github.com>)
	id 1ej0Pr-001asR-AT
	for hello@salmanwaheed.info; Tue, 06 Feb 2018 03:23:55 -0700
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=Mj0NcYqJIK6dQwIiDdi8eAtn488=; b=m4Z47nDNUrd6gdlR
	a1uUD9XZw164fdWOkgp7bnetdi/24UoV39BDuLv3GnFkEFXoEctkjx6c66QelxN4
	283dlAMl57H+IrdI3BZ4T3Y6TFPRDhQUkEy599lxb2iQxRQ2LD3pAMsnOMBqSpAK
	NK4ZqsfS12GXmbtY5/PHmYXwCnM=
Received: by filter0602p1mdw1.sendgrid.net with SMTP id filter0602p1mdw1-17352-5A79822E-18
        2018-02-06 10:23:42.854042013 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0006p1iad2.sendgrid.net (SG) with ESMTP id s3NgQBkVSdaAu6SXtjRwSw
	for <hello@salmanwaheed.info>; Tue, 06 Feb 2018 10:23:42.798 +0000 (UTC)
Date: Tue, 06 Feb 2018 10:23:42 +0000 (UTC)

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (165/150 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:3453)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-a7b0-hello=salmanwaheed.info@sgmail.github.com>)
	id 1ej0Pr-001asE-4n
	for hello@salmanwaheed.info; Tue, 06 Feb 2018 03:23:56 -0700
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=+79mOvxe4t9wKQZm1rRoR4rwjOI=; b=SMP2UH2+1UxjNpol
	9wPdkc5bYY0r3+2YDyllyR1c2a+V+ryNvRRIB2zfMybruoAoHw07ze57dTWLLEwR
	6EY9w2VHFRolvlWFKS81eDmJyVFDhcZbGZNKUnw+JEjm88aeL2S+bUk6h5GAH+sO
	NGPdhRnH2e2xqvKDirsR930LBgE=
Received: by filter0095p1las1.sendgrid.net with SMTP id filter0095p1las1-19416-5A79822D-20
        2018-02-06 10:23:41.94005158 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0021p1iad2.sendgrid.net (SG) with ESMTP id dnB2IJG1TwC8ALFYamZEuA
	for <hello@salmanwaheed.info>; Tue, 06 Feb 2018 10:23:41.892 +0000 (UTC)
Date: Tue, 06 Feb 2018 10:23:41 +0000 (UTC)

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by tim-finnigan** [comment]
Checking in as this issue hasn't been active in a while. According to [this page](https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-configure-apps-create-cluster.html#emr-configure-apps-create-cluster-cli) in the EMR documentation it is now possible to set a `s3://` path for the configuration file. Does that address the original feature request? Please let us know if there's anything you wanted to expand on or clarify here. Thanks!

**Comment by fs111** [comment]
I have not used EMR in many years. Feel free to close this bug.
