### ISSUE TITLE
AWS CLI query option Doesn't "Ordering" Return as Requested

### ISSUE THREAD

**Issue by colinbjohnson** [aws/aws-cli#1717]
## Example Request
`aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names $group_name --region $region --query '*[0].{AutoScalingGroupName:AutoScalingGroupName,MaxSize:MaxSize,DesiredCapacity:DesiredCapacity}' --output text`

## Expected Result
`aws-ha-release-test-webServerAutoScalingGroup-DWA54M2EAJNJ	2	1`
Where `Max-Size` is listed first and `DesiredCapacity` is listed second.

## Actual Result
`aws-ha-release-test-webServerAutoScalingGroup-DWA54M2EAJNJ	1	2`
The `DesiredCapacity` is actually listed first and `Max-Size` is listed second.

## Example Request, JSON Return
THIS 
`cjohnson04:~ cjohnson$ aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names $group_name --region $region --query '*[0].{AutoScalingGroupName:AutoScalingGroupName,MaxSize:MaxSize,DesiredCapacity:DesiredCapacity}'`
## Example Return
Notice the return order is MaxSize, AutoScalingGroupName, DesiredCapacity.
`[
    {
        "MaxSize": 2, 
        "AutoScalingGroupName": "aws-ha-release-test-webServerAutoScalingGroup-DWA54M2EAJNJ", 
        "DesiredCapacity": 1
    }
]
`

**Comment by JordonPhillips** [comment]
This appears to be a [jmespath](https://github.com/jmespath/jmespath.py) issue related to the fact that [Objects](http://jmespath.org/specification.html#data-types) have no imposed ordering. Since it looks like you don't care about the keys themselves, using a list instead will get you the order you want:

`*[0].[AutoScalingGroupName,MaxSize,DesiredCapacity]`

So:
`aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names test --region us-west-2 --query '*[0].[AutoScalingGroupName,MaxSize,DesiredCapacity]' --output text`
Returns:
`test    2    1`

**Comment by colinbjohnson** [comment]
@JordonPhillips - thank you! Understand completely.

**Comment by JordonPhillips** [comment]
Glad it worked out!
