### ISSUE TITLE
add --all-dependencies option to ec2 delete-vpc

### ISSUE THREAD

**Issue by meonkeys** [aws/aws-cli#1721]
## Feature request

support `aws ec2 delete-vpc --all-dependencies --vpc-id vpc-deadbeef`
## Details

The AWS web console will delete a VPC along with all its dependencies. The `aws` cli tool says (when trying to delete a VPC with any dependencies): `A client error (DependencyViolation) occurred when calling the DeleteVpc operation: The vpc 'vpc-deadbeef' has dependencies and cannot be deleted.`
1. Subnets
2. Security Groups
3. Network ACLs
4. VPN Attachments
5. Internet Gateways
6. Route Tables
7. Network Interfaces
8. VPC Peering Connections

Maybe also add `--vpn-connection`.

**Comment by JordonPhillips** [comment]
Something like this might be handy, but it requires more magic smoke than I'm really comfortable with. I would suggest making this request on the [EC2 forums](https://forums.aws.amazon.com/forum.jspa?forumID=30). If they add it to their API, we'll be able to pick it up immediately.

**Comment by meonkeys** [comment]
Good call. Done: https://forums.aws.amazon.com/thread.jspa?threadID=223412

**Comment by jrozansk** [comment]
I am in need for this feature, also.
:+1:  from me

**Comment by bzz** [comment]
@JordonPhillips is not it all about just listing dependencies and removing them one by one, or is it something more then that?

**Comment by voyalab** [comment]
+1 Is there any progress with this feature?

**Comment by lianghong** [comment]
+1 frome me

**Comment by samfrances** [comment]
A definite +1

**Comment by erickfaustino** [comment]
+1

**Comment by stormyk** [comment]
+1  I have bunches of vpc's to be deleted.

**Comment by setevoy2** [comment]
+1

**Comment by nicksuckling** [comment]
+1

**Comment by ale93p** [comment]
+1

**Comment by joejulian** [comment]
:+1:

**Comment by ZhongtianWang** [comment]
+1

**Comment by apsferreira** [comment]
+1

**Comment by seancurran157** [comment]
+1

**Comment by chankongching** [comment]
+1000

**Comment by snowsky** [comment]
+1

**Comment by cwitte4191** [comment]
+1

**Comment by taylorsmithgg** [comment]
+1

**Comment by scollier** [comment]
+1

**Comment by freshyogurt** [comment]
+10000000

**Comment by lerkasan** [comment]
+1

**Comment by serant** [comment]
+1

**Comment by rpaquito** [comment]
+1

**Comment by iasinDev** [comment]
+1

**Comment by shdobxr** [comment]
+1

**Comment by TryTryAgain** [comment]
For anyone else looking for this feature, in the meantime, I've been using this: https://github.com/toddm92/vpc-delete to get almost all the way there...still looking to extend it to include VPNs, defaultDHCP options and anything else but have not attempted as it does basically everything I was looking for.

**Comment by PAgrawal16** [comment]
+1

**Comment by bernadinm** [comment]
+1

**Comment by anshulshah96** [comment]
+1

**Comment by ricott1** [comment]
+1

**Comment by guineveresaenger** [comment]
+1

**Comment by masterzion** [comment]
+1

**Comment by trevorrowe** [comment]
I understand there is significant desire for this feature to be added to the CLI. Currently we have no plans to implement this functionality in the CLI. The feature is a moving target, requiring frequent updates as EC2 adds functionality. There is also the issue with the ambiguity of what resources should be deleted, especially ones tangentially related to the VPC, such as snapshots. In the end, it makes more sense to do this server-side, especially so that all of the SDKs and Tools can benefit from this feature.

Please continue to share feedback and input on the linked EC2 forum thread.

**Comment by jasonmcintosh** [comment]
https://abhishekis.wordpress.com/2017/04/26/python-script-to-remove-the-default-vpc-of-all-the-regions-in-an-aws-account/

FYI for those who hit this...

**Comment by stormyk** [comment]
Trevorrowe..  This might be a moving target, but there is no ambiguity.  The --all-dependencies should handle removing every dependency that would otherwise prevent the vpc from being deleted.  If something is tangentially linked, the --all-dependencies should unlink it from the VPC.

Clicking hundreds of VPCs one by one on the GUI is a garbage way of getting VPC's closed en-masse.  I'd much rather feed my shell script, and work on something less tedious.

If the GUI interface gets a mass vpc-close option, I'd be down for that too.

**Comment by wandergeek** [comment]
+1

**Comment by ericraymond** [comment]
Do cusotmers care if the VPC (and it's dependencies) get deleted via the client or server side code?  

What customers do care about is a way to fully delete the VPC (and deps) via an action from the AWS CLI or when there is a Cloudformation delete.   The current situation where we can build a stack automatically but cannot not tear it down automatically is getting tired.  There are many asymmetries and exceptions all across AWS that reveal a trail of teams not working together on more complex issues.

Why can't we expose an API to the (AWS Console) server side function to delete a VPC and use that API in the CLI and CloudFormation?  If organizational boundaries are getting in the way of providing users with fixes to critical bugs and gaps,  why push that burden of changing cross org priorities onto the customers (to post in another project's forum thread)?  Clearly this approach is not working.

The current situation where we can build a stack automatically but cannot not reliably tear it down automatically is getting tired. How many wasted hours of time do customers spend to manually work work around this?  How many aws resources are underutilized because they are bound to half torn down VPC's?

**Comment by munishase** [comment]
Did anyone write script to delete all VPC in aws including the related resources?

**Comment by zukeru** [comment]
+99999999999999999

If anyone wants I can provide a nodejs script I utilize for doing just this when I delete a eks cluster with eksctl since it can't clean the vpc for some reason because of dependencies. :)

**Comment by munishase** [comment]
> for doing just this when I delete a eks cluster with eksctl since it can't clean the vpc for some reason because of dependencies. :)

can yo share it?

**Comment by AkiraKane** [comment]
> +99999999999999999
> 
> If anyone wants I can provide a nodejs script I utilize for doing just this when I delete a eks cluster with eksctl since it can't clean the vpc for some reason because of dependencies. :)

HAHAHA boss, I am trying the same thing !!

**Comment by scottstensland** [comment]
Of course Amazon drags their feed in giving a cleanup tool 
why should they since its a revenue generator to leave all these dangling unwanted resources running ... so sad

**Comment by gregohardy** [comment]
This might help. It's in ruby, but it shows the ordering you need to delete VPC's. You will have to have tagged your resources to use this out of the box, but the order seem's to be key for a few of you. Resource order is a pain across the major Cloud's. We suffer daily. Hope this helps. If you have VPN gateways and peering you will just have to delete those before the rest of the resources in the script.

*Opens the musty tome*

https://gist.github.com/gregohardy/ef026eef3beddae49eb05ea0fe5993e0

**Comment by mjbright** [comment]
> Of course Amazon drags their feed in giving a cleanup tool
> why should they since its a revenue generator to leave all these dangling unwanted resources running ... this has been an issue for MANY years

So true unfortunately

**Comment by anjneeksharma** [comment]
is there any way i can get what are the dependency attached to particular resource so before deleting main resource i will delete dependency first.
for example i want to delete network interface but i am getting operation not allowd error.
can any one suggest me what the things i need to delete before deleting network interface.

**Comment by anjneeksharma** [comment]
i stuck in my task i want to delete all unused resource from my aws endvironment

**Comment by creslinux** [comment]
Seriously need this - can spend an entire day easily running around in circles trying to remove a VPC - its the most annoying nonsense.

**Comment by alexandrejuma** [comment]
This is a basic feature everyone needs. It took me days to implement a VPC resource crawler to remove everything.

+100000000000

**Comment by thscheer** [comment]
+1

**Comment by masterzion** [comment]
I did it some time ago.. it can be useful..
Feel free to improve. 

https://github.com/masterzion/aws-amicleaner

**Comment by lianghong** [comment]
It's my script to delete a VPC with all  dependencies
https://github.com/lianghong/delete_vpc

**Comment by TryTryAgain** [comment]
Similarly, I've used https://github.com/toddm92/vpc-delete in the past.

**Comment by paschalidi** [comment]
@lianghong thanks that worked like a charm!!

**Comment by kennyworkman** [comment]
@lianghong u charming devil

**Comment by cjobeili** [comment]
@lianghong THANK YOU !

**Comment by memark** [comment]
Any update on this? Still really needed.

**Comment by roeera** [comment]
+1

**Comment by wanghui17** [comment]
+1

**Comment by mayk0gan** [comment]
+1

**Comment by sebastianserrano** [comment]
+1

**Comment by matiassilverocfa** [comment]
+1

**Comment by twpayne** [comment]
I wrote a tool to delete a VPC and all of its dependencies: https://github.com/isovalent/aws-delete-vpc

**Comment by paololazzari** [comment]
The AWS cli functionality should reflect that which is available in the AWS console. This issue should be reopened

**Comment by voycey** [comment]
Awful that this doesnt exist still

**Comment by tobiasparaiso** [comment]
We need this functionality to handle IaC!

**Comment by hyperfraise** [comment]
+1

**Comment by benbenben-be** [comment]
bump

**Comment by electronym** [comment]
+1

**Comment by hebelsan** [comment]
+1

**Comment by merusso** [comment]
@twpayne , thanks for sharing your tool! We've been using it for a while, but I see now that the repo no longer exists. Was it moved?

**Comment by twpayne** [comment]
> [@twpayne](https://github.com/twpayne) , thanks for sharing your tool! We've been using it for a while, but I see now that the repo no longer exists. Was it moved?

I don't know. I did the work when I was working for @isovalent, who have since been acquired by @cisco. I left Isovalent several years ago. I agree, it would indeed be a shame if they've since deleted it. The polite thing to do would have been to archive the repository if they were no longer willing or able to maintain it.
