### ISSUE TITLE
Does 'cp' perform data integrity checks and return non-zero exit code if md5 is incorrect?

### ISSUE THREAD

**Issue by bpourriahi** [aws/aws-cli#1750]
Can't find this in the documentation.

**Comment by kyleknap** [comment]
The CLI will auto-populate the Content-MD5 header for PutObject and UploadPart. So if there is an issue with checksum, S3 will send an error backs and we will retry the request. We will retry up to 5 times.

For downloads, if it is a non-ranged download we will do md5 checksum checks as long as the file is not encrypted server side and we will retry if it does not match. For ranged downloads however we do not do md5 checks because we cannot reliably use the ETag to check MD5's.

Let me know if this helps or if you have more questions. Otherwise, getting this documented somewhere would be a good idea.

**Comment by bpourriahi** [comment]
Thanks, Kyle. That is helpful and would be good to have in the docs.

Another question along the same lines, perhaps not in the scope of this project: 

If I upload a file to an previously non-existant s3 object, and the download fails for whatever reason using the aws-cli, is there a chance that s3 will show that the object exists?

**Comment by JordonPhillips** [comment]
@bpourriahi Do you mean if the upload fails? If the upload fails, the object should not exist in S3.

**Comment by bpourriahi** [comment]
Yes, I meant upload, sorry.

Ok great. Just wanted to confirm. Thank you.

**Comment by kyleknap** [comment]
Cool glad that helped. Keeping issue open to make sure we add information on how md5's get handled in s3 commands. This question is asked from time to time.  Thinking of adding a topic in the topic guide for s3 command FAQs or deep dive into s3 commands to put answers to questions like this.

**Comment by marchelbling** [comment]
@kyleknap @jamesls sorry to revive this thread but integrity checks for multi-part uploads is still unclear to me.
In the case of a MP upload, the [Knowledge Center](https://aws.amazon.com/fr/premiumsupport/knowledge-center/s3-multipart-upload-cli/) says to send both the 'whole' object MD5 and each part MD5. 
From the aws-cli FAQ, it's not clear to me wether both 'levels' of MD5 are handled by aws-cli or if just parts MD5 are sent (thus only asserting that no network occurred but and that re-assembling the parts went well).
Could you clarify this please?
