### ISSUE TITLE
describe-route-tables does not honour --filters?

### ISSUE THREAD

**Issue by amosshapira** [aws/aws-cli#1762]
I'm trying to extract the default route from a route table using the following (based on the docs from http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-route-tables.html):

    aws ec2 describe-route-tables --route-table-ids rtb-deadbeef \
      --query 'RouteTables[*].Routes' \
      --filters 'Name=route.destination-cidr-block,Values="0.0.0.0/0"'

But I keep getting all routes in that table, including ones which do not have `DestinationCidrBlock=0.0.0.0/0`.

The `Name=route.destination-cidr-block` is recognised (the command complains, for instance, if I add an 's' to the end of the name), but seem to be ignored.

What am I doing wrong?

**Comment by ctarwater** [comment]
I'm running into the same problem.
I'm trying to get the RouteTableAssociationId for a specific Subnet using the following command:
`aws ec2 describe-route-tables --query 'RouteTables[*].Associations[*].RouteTableAssociationId[]' --filters "Name=association.subnet-id,Values=subnet-6b90221d"  --output text`

Which gives me the following results:
`rtbassoc-b07aebd7       rtbassoc-6560f102`

Here's all of my route tables:
```
[
    {
        "SubnetId": "subnet-289e4a70",
        "Main": false,
        "RouteTableId": "rtb-7a8b801e",
        "RouteTableAssociationId": "rtbassoc-b07aebd7"
    },
    {
        "SubnetId": "subnet-6b90221d",
        "Main": false,
        "RouteTableId": "rtb-7a8b801e",
        "RouteTableAssociationId": "rtbassoc-6560f102"
    }
]
```
They both have different subnetIds, but filtering by that doesn't work.

**Comment by kyleknap** [comment]
@amosshapira @ctarwater

I think that is just how EC2's API behaves. I was seeing the same thing as well. My guess is that since the operation is named DescribeRouteTables, the filters are applied directly to the route tables and not any of its sub data (like subnets or cidr blocks). The purpose of the operation is to describe the entirety of route table. So from EC2's side, it may be confusing if it filtered out some of this sub data as it would be an incomplete description of the route table.

This is me just guessing on why EC2 behaves the way it does. If you have further questions or more insight, I would recommend posting the question in the EC2 forums: https://forums.aws.amazon.com/forum.jspa?forumID=30. Closing issue.

**Comment by amosshapira** [comment]
Thanks. I posted a question here: https://forums.aws.amazon.com/thread.jspa?threadID=226440
