### ISSUE TITLE
--filter vs --filters

### ISSUE THREAD

**Issue by rowanu** [aws/aws-cli#1772]
I just noticed that [`describe-nat-gateways`](http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-nat-gateways.html) takes a `--filter` parameter, whereas most of the other commands I know of (e.g. [`describe-route-tables`](http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-route-tables.html)) take `--filters` (note the "**s**").

Is the difference intentional? I'll submit a PR if not.

**Comment by jamesls** [comment]
Looks like `describe-hosts`, `describe-nat-gateways` and `describe-flow-logs` are the only operations that accept `--filter`.  All the other EC2 operations supporting server side filtering use `--filters`.  This was not intentional.

We can fix this to be consistent, but the issue here is that we need to still silently support `--filter` for backwards compatibility.

We've had similar requests from boto3, so we'd probably support aliasing arguments in botocore to address this.  What will probably happen:

* Create a new arg `--filters` that is an alias to `--filter`.  We'd support both arguments
* Update our docs so we don't document the deprecated argument `--filter`.

Related: 

* https://github.com/boto/boto3/issues/463
* https://github.com/boto/botocore/issues/772

Let's track this work over in boto/botocore#772.
