### ISSUE TITLE
allow ability to pass optional custom parameters to aws emr ssh/socks

### ISSUE THREAD

**Issue by kirkhansen** [aws/aws-cli#1799]
I would like to be able to run a proxy command via command line options when running aws emr ssh or emr socks.

An example request could look something like:

`aws emr ssh --cluster-id j-3SD91U2E1L2QX --key-pair-file ~/.ssh/mykey.pem -o ProxyCommand='ssh firewall_jump -W %h:%p'`

where you could have as many `-o'`s as you please.

It would also be beneficial to allow custom ports for the -D option.

**Comment by jamesls** [comment]
It also we worth seeing if we could also just print out the ssh command to stdout so a user could modify it as they need to.  Something like:  `$(aws emr ssh-command --cluster-id ...) -o ProxyCommand='ssh'`

**Comment by JordonPhillips** [comment]
The issue with the above is that we create a file if putty is being used. Otherwise it would be a trivial change.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (170/150 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 6167 characters long; only the first
------ 5000 or so are included here.
Received: from o1.sgmail.github.com ([192.254.114.176]:13952)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-a7b0-hello=salmanwaheed.info@sgmail.github.com>)
	id 1ej0Q6-001av6-4P
	for hello@salmanwaheed.info; Tue, 06 Feb 2018 03:24:10 -0700
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=zi7VU8UrBDFT521Oe/PIlXFaCik=; b=crySspXAsj5u27QM
	4NyZfHX5Vepc/d7zHxhbTQshbQ5rFkQrFZ6g6rHfmz9aM7w0g8nb1MiO1lZUzcd/
	WcXB8nFc5rnP39mee7Ex5ycBjntYTVgUdzkf3cKRznydOfUR+UlrwirxZeTNMzUn
	KIf7Su/vSdhxDXf+RCvE2RApOwU=
Received: by filter0916p1mdw1.sendgrid.net with SMTP id filter0916p1mdw1-3545-5A79823E-1
        2018-02-06 10:23:58.04066921 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0006p1iad2.sendgrid.net (SG) with ESMTP id 9PN6AXnCT5yQ1GPOrOB-IQ
	for <hello@salmanwaheed.info>; Tue, 06 Feb 2018 10:23:58.005 +0000 (UTC)
Date: Tue, 06 Feb 2018 10:23:58 +0000 (UTC)

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (171/150 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o8.sgmail.github.com ([167.89.101.199]:24750)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-a7b0-hello=salmanwaheed.info@sgmail.github.com>)
	id 1ej0Q8-001b3Y-Op
	for hello@salmanwaheed.info; Tue, 06 Feb 2018 03:24:13 -0700
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=KcYnzAO9MF1e/Vr7K4WkMg4rx+c=; b=uUrgXnXd+oo3cil6
	M9bzfdnqsSWWg8Wm6+eicGMuWkHkEFy0Hprboqg9OTVwmARcq+ZxOMWG98lCFKhK
	JpNXY7KgNyv7zO4F3zye7QQmtqfRod1h17wn6wLaWDmBVi0q9nvAASeVONYj/Kt3
	pEkZGz56FBp4ukreM8RJaMVr+t8=
Received: by filter0469p1las1.sendgrid.net with SMTP id filter0469p1las1-11231-5A798241-1D
        2018-02-06 10:24:01.735464735 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id PEJqAQSzR7a7K_IbsfQs1g
	for <hello@salmanwaheed.info>; Tue, 06 Feb 2018 10:24:01.650 +0000 (UTC)
Date: Tue, 06 Feb 2018 10:24:01 +0000 (UTC)

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
