### ISSUE TITLE
 aws dms create-replication-task  "TargetSchema" under --task-settings is ignored when source DB is SQLServer

### ISSUE THREAD

**Issue by jeremywwalker** [aws/aws-cli#1871]
aws dms create-replication-task 
...
 --task-settings '{"TargetMetadata":{"TargetSchema":"****Target Schema****" ,"SupportLobs":true,"
...

When the source DB is a MS SQLServer, the TargetSchema value is being ignored or not applied when target DB is Aurora.

**Comment by kyleknap** [comment]
I am not too sure what could be causing the issue. I would recommend opening up an issue in the developer forums: https://forums.aws.amazon.com/forum.jspa?forumID=216 to get a hold of the service team to see if there is an issue server side. I do not think we can do much from the CLI side because the tool just formats request and sends them over the wire and parses the response back. It has no control of server side behavior.
