### ISSUE TITLE
aws route53 list-resource-record-sets help is broken

### ISSUE THREAD

**Issue by nderzhak** [aws/aws-cli#1887]
```
ubuntu@docker-vpc:~/docker-elasticsearch$ aws --version
aws-cli/1.10.17 Python/2.7.6 Linux/3.13.0-83-generic botocore/1.4.8
ubuntu@docker-vpc:~/docker-elasticsearch$ aws route53 list-resource-record-sets help

'ascii' codec can't decode byte 0xe2 in position 86: ordinal not in range(128)
```

**Comment by jamesls** [comment]
This was due to the fact that we included a few bad CLI examples in the latest CLI release that contains non ascii chars.  This has been fixed (https://github.com/aws/aws-cli/pull/1882) and will be available in the next CLI release.  FWIW, the linked pull request also adds a test case to ensure this doesn't happen again.
