### ISSUE TITLE
Multipart uploads data integrity and metadata

### ISSUE THREAD

**Issue by marchelbling** [aws/aws-cli#1892]
In the case of a MP upload, the [Knowledge Center](https://aws.amazon.com/fr/premiumsupport/knowledge-center/s3-multipart-upload-cli/) says to send both the 'whole' object md5 and each part md5.
My understanding is that parts md5 are used to check for network errors and the object md5 is used to check that the multiparts reassembling went well.

Reading https://github.com/aws/aws-cli/issues/1750 comments and the [aws cli s3 faq](http://docs.aws.amazon.com/cli/latest/topic/s3-faq.html), it is not clear to me that both parts and object md5 are checked by the cli and what the behavior is if all parts md5 checks are good but the object check fails?

Also, related to https://github.com/aws/aws-cli/issues/1561, I think it would be nice to have an option to automatically add the `aws-amz-meta-md5` header with the s3 cli "upload" commands.

**Comment by JordonPhillips** [comment]
For uploads, the CLI sends all the necessary metadata for S3 to validate chunks and objects. If all the chunks pass, but the whole object fails, it's a fail. For downloads, we generally don't check because we can't calculate ETag on multipart-uploaded objects. For us to check, it has to meet the following conditions:

* MD5 is available on the system openssl
* The object is not multipart
* It is not kms encrypted

There is no multipart to worry about, so it's a simple pass fail at that point.

Regarding metadata, there is a `--metadata` argument you can use to pass in arbitrary metadata. ([docs](http://docs.aws.amazon.com/cli/latest/reference/s3/cp.html))
