### ISSUE TITLE
Add ec2 fingerprint-key command

### ISSUE THREAD

**Issue by garnaat** [aws/aws-cli#191]
This command mimics the one in the legacy EC2 CLI tool and computes the fingerprint of a locally stored SSH private key file.

**Comment by kmcquade** [comment]
@sbillig - confirmed that works. just in case anyone else stumbles upon this. Thanks

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by tim-finnigan** [comment]
I believe this is now possible via the AWS CLI per this documentation: https://docs.aws.amazon.com/cli/latest/userguide/cli-services-ec2-keypairs.html

If the request is for something beyond what is documented there then we can reopen this or create a new issue to clarify the distinctions.
