### ISSUE TITLE
Provide versioned download links (Windows)

### ISSUE THREAD

**Issue by gregmac** [aws/aws-cli#1921]
Currently the download link (https://s3.amazonaws.com/aws-cli/AWSCLI64.msi) only goes to the latest version. This leads to problems for the [Chocolately package](https://chocolatey.org/packages/awscli) as described at https://github.com/dtgm/chocolatey-packages/issues/175:

* When a new version is released, the Chocolatey-based install fails until it gets updated with the new hash
* It's impossible to install a specific or old version (which should only be necessary in case of regression)

If the aws-cli team provided permanent links such as `/aws-cli/AWSCLI64_1.10.16.msi` it would alleviate these problem entirely.

**Comment by JordonPhillips** [comment]
We do keep packages for previous versions as far back as 1.6.9. The format for these URLs is
`https://s3.amazonaws.com/aws-cli/AWSCLI{64/32}-{version}.msi` For example:

https://s3.amazonaws.com/aws-cli/AWSCLI64-1.6.9.msi

https://s3.amazonaws.com/aws-cli/AWSCLI32-1.7.34.msi

You can of course install older versions via `pip` as well. They have as far back as 0.4.1, but they aren't msi installers. I believe the homebrew formula grabs the tars from [pypi's site](https://pypi.python.org/simple/awscli/). That may not be the best solution for Windows, however, since you aren't guaranteed to have python installed.

**Comment by gregmac** [comment]
Ah perfect, that's exactly what is needed, thanks. I will take this back to Chocolatey.

**Comment by vivek-billore** [comment]
So when i edit the link for example to download version 2.0.31 https://s3.amazonaws.com/aws-cli/AWSCLI{64/32}-{version}.msi

https://s3.amazonaws.com/aws-cli/AWSCLI32-2.0.31.msi

It fails saying access denied
