### ISSUE TITLE
No way to wait for an s3 key to be updated

### ISSUE THREAD

**Issue by davidblewett** [aws/aws-cli#1933]
I have a process that writes updated versions of a file to the same S3 key on a regular basis. The [FAQ](https://aws.amazon.com/s3/faqs#What_data_consistency_model_does_Amazon_S3_employ) states that in this scenario, S3 only guarantees eventual consistency (i.e., an immediate read after the PUT command succeeds is not guaranteed to return the updated version). I would like to use the `s3api wait object-exists` command to wait for the key to be updated, so that I know that the change has propagated.

However, it seems that the the `--if*` conditions ( --if-match, --if-modified-since, --if-none-match, --if-unmodified-since) were not designed for this use case. If the condition isn't met, they return immediately. I would expect `s3api wait` to imply that the process would honor its contract ( "Wait until 200 response is received when polling with head-object. It will poll every 5 seconds until a successful state has been reached. This will exit with a return code of 255 after 20 failed checks."), and only then exit with the failed HTTP status code (304 or 412).

Ideally, what I would like to do is this, where the previous contents of the key's `LastModified` was `2016-04-20T12:34:09.000Z`:

```
aws s3api wait object-exists --bucket my-bucket --key path/to/my/key --if-modified-since $(date '+%Y-%m-%dT%H:%M:%SZ')
```

This command would not return until it had exhausted the 20 checks for the incremented `LastModified` value. If the value has been updated (either before the wait command started or during execution), then exit with status 0. If it hasn't changed after 20 checks, then exit status 255. Currently, the process returns immediately:

```
aws s3api wait object-exists --bucket my-bucket --key path/to/my/key --if-modified-since "2016-04-21T12:34:09Z" 

Waiter ObjectExists failed: Not Modified
```

**Comment by JordonPhillips** [comment]
This definitely seems like a useful thing to have. What would you think about `object-updated` as a separate waiter?

**Comment by cristim** [comment]
I'm not sure I completely understand your use case, but to me this kind of polling for object changes can be better solved with the native events generated by S3 when objects are changed in your bucket. You can then invoke a Lambda function and take action immediately after the object is uploaded.

**Comment by volodymyrrudyi** [comment]
> You can then invoke a Lambda function and take action immediately after the object is uploaded.

Unfortunately, events can come to Lambda before the object is actually available and the same issue will appear again

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (178/150 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 6170 characters long; only the first
------ 5000 or so are included here.
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:51496 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1ej0R0-001bmn-JF
	for hello@salmanwaheed.info; Tue, 06 Feb 2018 03:25:07 -0700
Date: Tue, 06 Feb 2018 02:24:55 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1517912695;
	bh=Bo/joZ7+HYcAJ8vFmfZpYpVKBPTU7K1eqn5W8eX0dQY=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=nnDf3HUKTXnLDeZprkg9K5z2gxhtgkvsTCtZAu0M3HUOcTmLlqR6BztsJR6eY7FYr
	 A3WHRs+rIW6+eu16pxRQoRtL3UO7VQlZVUsEm1gkemu36CU/JGQTcC28paAf64wrz5
	 sRTCgLKVKbAS9xZ5knMdBvhlewR7BC/Z3OqQ3kKI=

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (179/150 (119%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:36696 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1ej0R2-001bmt-M6
	for hello@salmanwaheed.info; Tue, 06 Feb 2018 03:25:09 -0700
Date: Tue, 06 Feb 2018 02:24:57 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1517912697;
	bh=6mooeda5B9cMiteT9UuxWrVAiWcNadltcMfWhF4b+ak=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=iL4sXavQ2Fti5Lb0WtTQp8jgb2An4yGuUmsSEBT3PnxwxIuPHmsztVXJWlAUxm+Q5
	 gZz8URseuOIO5oq0Xng9w+tp6jkks6C+5cqVTZXSS/LRsifAA+Qz8Q9duL4gF4jJ8H
	 Kzje8AkPofHvyAdxLIwcUhbB5h/UeetScOTfm51E=

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by fantapop** [comment]
Documentation for the waiter is difficult to track down, My assumption is that this behavior was how the --if-modified-since flag would interact with ```object-exists```.  It seems to go against the very nature of the waiter to not wait until the conditions could be true!  In my case the ```object-updated``` would not be useful here because it may be that the object doesn't exist yet.  What I really want to do is wait for a case where the object exists and was last modified within the timeframe.  I realize it would be difficult to make this backwards incompatible change this late in the game.  Maybe a new flag is in order.  Instead of a new unique flag for the new ```if-modified``` behavior, it could be something like ```--wait-for-all-conditions``` which would modify the behavior of any of the params to wait the full timeout until they could be possibly true.

**Comment by mingrammer** [comment]
Any progress?
