### ISSUE TITLE
Confusion using the new UserPool commands

### ISSUE THREAD

**Issue by SteveALee** [aws/aws-cli#1962]
Please see aws/amazon-cognito-identity-js#23 for problems I had trying to use AWS cognito-identity create-identity-pool

thanks

**Comment by kyleknap** [comment]
Based on the issue, looks like an example on how to use the [create-identity-pool](http://docs.aws.amazon.com/cli/latest/reference/cognito-identity/create-identity-pool.html) command is needed. We have examples for a lot of commands. Would not be hard to add one here. Any thoughts on this idea?

**Comment by SteveALee** [comment]
@kyleknap that would have helped a lot :)
Where are the examples? I only found the tutorial style docs so far.

FYI, Here's [my effort that worked](https://github.com/OpenDirective/brian/blob/master/aws.sh)

**Comment by kyleknap** [comment]
The examples are located [here](https://github.com/aws/aws-cli/tree/develop/awscli/examples) in the codebase. The CLI will take examples from this directory and embed them into the help documentation. Here is a [blog post](https://blogs.aws.amazon.com/cli/post/Tx35HKB9G84XZ7D/Contributing-Topics-and-Examples-to-the-AWS-CLI) that I wrote describing the process if you are interested in contributing.

**Comment by SteveALee** [comment]
I've be using the source but missed those examples.

Definitely interested in contributing back after this double panic is over. AKA Mvp

**Comment by justnance** [comment]
@SteveALee - Thank you again for reporting this issue.  Since your last update, our online documentation has changed.  It would be great if you could take a minute to review and let us know what you think.  Are there any other improvements or examples you'd like to see here? 

https://docs.aws.amazon.com/cli/latest/reference/cognito-identity/create-identity-pool.html
https://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_CreateIdentityPool.html#API_CreateIdentityPool_Examples
