### ISSUE TITLE
Uncessary pool id prefix for cognito-identity create-identity-pool for user pools?

### ISSUE THREAD

**Issue by SteveALee** [aws/aws-cli#1966]
When creating an identity pool with ```cognito-identity create-identity-pool``` and using a user pool a prefix is required for the user pool id.

```
cognito-idp.us-east-1.amazonaws.com/
```

This caught me out as it is never seen in the Web UI and although it is documented it is in a hard to find footnote. 

Why is this needed? Is it temporary and due to the region limitation of user pools. the User Pool's region is specified in the pool id.

If it is constant or dependent on the User Pool region can it not be generated by AWS?

thanks

**Comment by kyleknap** [comment]
I would recommend reaching out on the [Cognito forums](https://forums.aws.amazon.com/forum.jspa?forumID=173) for the rationale behind this.

In terms of autopopulating the prefix client side, I would be hesitant to do this because there is no guarantee that cognito does not update what are valid provider names in the future to their API and that could restrict future CLI users. I would much rather add an example as we talked about in a [previous issue](https://github.com/aws/aws-cli/issues/1962) that you opened.
