### ISSUE TITLE
completer doesn't work with file redirection in bash

### ISSUE THREAD

**Issue by qfissler** [aws/aws-cli#1967]
`aws ec2 describe-instances > <TAB><TAB>` 

doesn't let me choose a file.

**Comment by jamesls** [comment]
Related issue: https://github.com/aws/aws-cli/issues/77

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (184/150 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 6167 characters long; only the first
------ 5000 or so are included here.
Received: from o6.sgmail.github.com ([192.254.113.101]:43619)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-a7b0-hello=salmanwaheed.info@sgmail.github.com>)
	id 1ej0RI-001bvT-2U
	for hello@salmanwaheed.info; Tue, 06 Feb 2018 03:25:24 -0700
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=YgaF88guTvSehIde3JY1BvGfLXg=; b=AAQ2cn2h3AGktAPr
	JOBOphWRVrNewTD2P9gM1I2t1USRhWi3q0SDfi7Po/ZvO956JZnFRusAEjmla4wH
	QM5/6m6FTp5lOUBQgvn6sTGGbExWdtz2/dI2EAVKrh9Bk63KXfoDAuRbnUbGm6PL
	QyzbLvWPfyB0TkT1bpyGlIBtPRE=
Received: by filter0025p1las1.sendgrid.net with SMTP id filter0025p1las1-4219-5A798287-10
        2018-02-06 10:25:11.584690712 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0002p1iad2.sendgrid.net (SG) with ESMTP id En-VknORTciocnH1O64OnQ
	for <hello@salmanwaheed.info>; Tue, 06 Feb 2018 10:25:11.543 +0000 (UTC)
Date: Tue, 06 Feb 2018 10:25:11 +0000 (UTC)

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (185/150 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:34696)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-a7b0-hello=salmanwaheed.info@sgmail.github.com>)
	id 1ej0RH-001bvd-Qm
	for hello@salmanwaheed.info; Tue, 06 Feb 2018 03:25:24 -0700
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=7PQn7L+kEa3E/GE+TvoS3gjgunQ=; b=Jr9iOUT/LKJKxugD
	mKygjbzOGUlpi7Ku7I1Kkw6gHm51ZdFonTVbN70SSAhV5y10dRSUs/sStfKHXOlg
	k/AARtreAERFaEJaPG/t7Ad2ebwU4g8F2FiMeoinON+WiaUya2vRp+cDwO5ASK2B
	bEpO3nINfq1xWgPOKBJKHFdN2M0=
Received: by filter0476p1las1.sendgrid.net with SMTP id filter0476p1las1-11263-5A798288-30
        2018-02-06 10:25:12.951946226 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0020p1iad2.sendgrid.net (SG) with ESMTP id TAngOu9BQ1WXllCv6p7zJQ
	for <hello@salmanwaheed.info>; Tue, 06 Feb 2018 10:25:12.888 +0000 (UTC)
Date: Tue, 06 Feb 2018 10:25:12 +0000 (UTC)

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by stobrien89** [comment]
Appears this has been fixed in more recent versions of v1 and v2.  Please let us know if you're still having an issue!
