### ISSUE TITLE
Updating CoreOS cloud config via user-data fails when trying to update with file

### ISSUE THREAD

**Issue by austenLacy** [aws/aws-cli#1995]
Running the following command:

```
$ aws ec2 --profile myprof modify-instance-attribute --instance-id=i-XXXXXX --user-data file://some-cloud-config.yaml
```

throws the following error:

```
Error parsing parameter '--user-data': Expected: '=', received: '#' for input:
#cloud-config
^
```

The cloud config works perfectly when doing `aws ec2 run-instances --user-data file://some-cloud-config.yaml ...`

**Comment by kyleknap** [comment]
This is a unfortunate but the API for modify-instance-attribute is different than run-instances, but for --user-data for modify-instance-attribute as shown in the [docs](http://docs.aws.amazon.com/cli/latest/reference/ec2/modify-instance-attribute.html) requires a ``Value`` key. So something like:
```
--user-data Value='my yaml contents'
```
Probably, the larger issue is that for nested parameters like this you cannot use ``file://``. Instead you will have to ``cat`` the contents of the file into the command. So something like this:
```
$ aws ec2 modify-instance-attribute --instance-id=i-XXXXXX --user-data Value="$(cat some-cloud-config.yaml)"
```
There is not really much we can do to make this consistent because this was just how the EC2 API was modeled and the CLI more or less directly reflects it, but I hopes this helps.

**Comment by austenLacy** [comment]
I think that's a valid solution. I'll try it out soon. I think it could be worthwhile to add that use case/example in the docs since the use of --user-data would imply it works similarly to other commands (i.e. run-instances)

**Comment by kyleknap** [comment]
Sounds good. We can get an example added for this.

**Comment by danvaida** [comment]
@kyleknap yes, please! and thanks for offering the hint.
