### ISSUE TITLE
Support setting signature versions through an environment variable

### ISSUE THREAD

**Issue by jalaziz** [aws/aws-cli#2003]
You can already use `AWS_DEFAULT_PROFILE` to set the default profile, but it does not seem like you can set the default signature version through an environment variable.

This is particularly problematic when using the aws cli as a docker container. For most applications, it doesn't make sense to make SigV4 the default in a docker container. However, when working with S3 and SSE with KMS, you must use SigV4. It would be great to set something along the lines of `AWS_DEFAULT_S3_SIGNATURE_VERSION` to temporarily override the signature version.

Another options would be to allow the signature version to be set as a CLI option.

**Comment by JordonPhillips** [comment]
I don't think setting signature versions via environment variables would be user-friendly. Since every service supports a different subset of the signature versions, we would need a new variable for each service. With 70+ services and counting, that would become pretty messy.

I'm not super familiar with docker usage, is it not feasible to set up a profile that sets the relevant config variable?

**Comment by jalaziz** [comment]
So I actually tried creating a docker container with a built-in profile that uses sigv4 for S3 and EC2. It works well if you're using IAM roles. However, it fails to use credentials from environment variables if specifying a profile. This makes it quite difficult to make a generic docker image that can be used by multiple users.

The thing about the environment variable is you really don't need a new variable for each service. Since the docker container would only run one command at a time, it could be universal. I do agree that it may not be the best approach given that it would likely apply to the non-docker case as well.

Setting the signature version as a CLI option may be a better option. The profile option would also be a reasonable compromise if you could still use credentials from the environment variables.

**Comment by JordonPhillips** [comment]
Let me see if I understand this correctly:

* Your container has a configuration profile in `~/.aws/config`
* That profile does not have credentials
* You are attempting to provide the credentials via environment variables

Now here's where I think the error is. I think what's happening is you are using `--profile` to select your configuration profile. In the CLI's credential provider chain, hard coded credentials come before environment variables. Since this constitutes hard-coded credentials, it preempts the environment variables in the credential provider chain. If this is the case, you should be setting the profile with `AWS_DEFAULT_PROFILE`. That will pull the configuration from the profile, and the credentials from your environment variables.

**Comment by jalaziz** [comment]
Ahh yes, using `AWS_DEFAULT_PROFILE` instead of `--profile` does the trick. That solves the problem for now. Although it would still be nice to not have to include a special SigV4 profile in the docker image. However, it's a reasonable compromise given the current state of things.

Feel free to close if there's no value in trying to make signatures configurable outside of profiles.

**Comment by JordonPhillips** [comment]
I'll discuss it with the team, but I'm not sure there's a way to do it that wouldn't be either confusing or difficult to maintain.

**Comment by JordonPhillips** [comment]
I talked about it with the team, and the result of that discussion was that we would not be able to make a good experience setting signature versions through environment variables. For your particular case, we are working on being able to set sigv4 as the default signature version for S3, so hopefully soon there will be no issue.
