### ISSUE TITLE
Feature Request: set `--debug` via .aws/config

### ISSUE THREAD

**Issue by stephenchu** [aws/aws-cli#2007]
I would like to be able to set the command line switch `--debug` in a profile inside of a `.aws/config` file. After a few tries it does not appear to support it. Does awe-cli have a way to do this?

```
[profile foo]
debug=true
```

**Comment by JordonPhillips** [comment]
That is not currently supported, no. Can I ask what your use case is?

**Comment by stephenchu** [comment]
I am creating bash script wrappers on top of the aws-cli command line. The wrappers calls the `aws` command line with `--profile wrapper` so that all command line executions are using the same auth credentials and what not.

My scripts wrappers are chainable via unix pipes: e.g. `describe-vpcs.sh | describe-instances.sh` (heavily simplified).

However, I would like to "flip a switch" to know what API calls req/resp I am getting when I run into problems. The nice way to do that on all `aws-cli` calls would be to do that within my `[profile wrapper]`.

**Comment by JordonPhillips** [comment]
I can see how it would be difficult if you want to flip ALL of them to debug, unless you had some argument that could add it in. Marking this as a feature request.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
