### ISSUE TITLE
Unhelpful Error Message on creating ELB policy

### ISSUE THREAD

**Issue by tommyp1ckles** [aws/aws-cli#2021]
When running

 `aws elb set-load-balancer-policies-for-backend-server --load-balancer-name my-elb --instance-port 80 --policy-names AWSConsole-SSLNegotiationPolicy-my-elb-0000000000000 ELBSecurityPolicy-2015-05 proxy-protocol` 

I get this non ambiguous error:

`An error occurred (InvalidConfigurationRequest) when calling the SetLoadBalancerPoliciesForBackendServer operation: AWSConsole-SSLNegotiationPolicy-my-elb-2-0000000000000 cannot be enabled`

It'd be nice if there was some sort of explanation of what went wrong here.

**Comment by jamesls** [comment]
I agree it would be nice if the error messages had more information.  However, the error message the CLI is displaying comes directly from the service API.  In order to get more information, the ELB would need to return that information back to the CLI so we can display it to you.  I'd suggest reaching out to the ELB team on their [forums](https://forums.aws.amazon.com/tags/elb) and share this feedback to them.

I'm going to go ahead and close this issue out, as there's nothing we can do on the CLI side for now.  Let me know if I've missed anything and we can discuss further.  Also, feel free to chat with us [gitter](https://gitter.im/aws/aws-cli) if you have additional questions/concerns.
