### ISSUE TITLE
Configure profile on a folder basis

### ISSUE THREAD

**Issue by deiga** [aws/aws-cli#2084]
I'd love to use a certain AWS profile for specific projects. The best way would be to set a `.awsrc` file into the folder which has somekind of profile settings.

**Comment by jamesls** [comment]
What all would you say should go into the the `.awsrc` file?

**Comment by deiga** [comment]
I don't personally see the need for anything else than `AWS_PROFILE`, but of course someone could argue that any of the environment variables could be set there

**Comment by jamesls** [comment]
I'll mark this as feature-request/others-chime-in.  While I think the functionality is useful, I'm hesitant to introduce another config file that differs from `~/.aws/config`.  I would be interested to hear a proposal that somehow keeps some form of consistency with existing config files.

**Comment by omar** [comment]
I came looking for a request for this feature because I was working on two projects for two different AWS accounts on the same computer.

A few proposals:

1. Use a new file format
   The simplest solution for my problem would be a `.awsprofile` file with the name of the profile to use. This file could then be added to `.gitignore` so that others can manage that on their own.

2. Use ./.aws/config with a higher precedence
   Make the [AWS CLI configuration precedence](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#config-settings-and-precedence) look for a `./.aws/config` file AFTER looking at the command line arguments but before looking at environment variables. 

   This file would behave exactly as the file located at `~/.aws/config`. To change the default profile, I would set the value for the `[default]` profile in `./aws/config`.

I think option 2 might be the cleanest route since it provides future extensibility for the same config file. Folks can also start modifying any variables they need for that directory not just the default profile.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by deiga** [comment]
@diehlaws Can I somehow help the discussion move forward? I encounter this quite often as different projects require different AWS profiles and I have to triple-check to remember to set it in ENV.

Of course, I can just start using something like https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/dotenv in the meantime to alleviate my problem

**Comment by bersace** [comment]
I too would like to have local configuration. I see two solutions, that are complementary:

- Load `.env` file like docker-compose and other softwares do. This solve the profile per folder feature request. Having a feature-flag for this like `AWS_LOAD_DOTENV` may mitigate issue with project suddenly having .env file loaded by `aws`.
- Search for `./.aws_config` file, *including parent folder*, before falling back to `$HOME`. This solve per-folder profile.

What do you think of this ?

**Comment by cbcoutinho** [comment]
For anyone that wants this functionality in the shell _now_ you can use `direnv`, which is a program that (among many other things) handles this exact use case - automatic loading of environmental variables based on a directory. The variables are maintained throughout the subdirectory tree.

https://direnv.net

It supports export environmental variables as well, as unsetting them when you leave the directory so there is no dangling state.

It's as easy as the following:

```shell
$ mkdir /tmp/aws && pushd /tmp/aws
$ pushd /tmp/aws
$ env | rg AWS
AWS_DEFAULT_REGION=eu-west-1
AWS_PAGER=
$ echo 'export AWS_PROFILE=profile-name' > .envrc
direnv: error /tmp/aws/.envrc is blocked. Run `direnv allow` to approve its content
$ direnv allow
direnv: loading /tmp/aws/.envrc
direnv: export +AWS_PROFILE
$ env | rg AWS
AWS_DEFAULT_REGION=eu-west-1
AWS_PAGER=
AWS_PROFILE=profile-name
$ popd
direnv: unloading
$ env | rg AWS
AWS_DEFAULT_REGION=eu-west-1
AWS_PAGER=
```

**Comment by amason13** [comment]
my solution was to add .awsprofile file in each project directory. 

inside each file you save the name of the profile you'd like to activate. 

then add the following script to your .zshrc file

```
### script to alias CD with activate aws profile
hasAwsProfile () {
  if [ -f .awsprofile ]; then
    export AWS_PROFILE="`cat .awsprofile`"
  fi
}
awsProfileCd () {
cd "$@" && hasAwsProfile
}

alias cd="awsProfileCd"
```
