### ISSUE TITLE
Storing files in the wrong region now doesn't throw an error anymore

### ISSUE THREAD

**Issue by tim-kos** [aws/aws-cli#2099]
Hey there,

We have recently upgraded from `1.7.4` to `1.10.54` and have noticed that when we try to store a file in a bucket with `aws s3api put-object --bucket someBucketInEuWest1 --region us-east-1` it does not crap out on us anymore. We used this error throwing to then issue a `aws s3api get-bucket-location` request to fetch the proper region and then retry the put-object request.

We need to know the region that the file got stored in so that we can build the https URL to the file properly, which must be `https://someBucketInEuWest1.s3-eu-west-1.amazonaws.com/path/to/file` versus `https://someBucketInEuWest1.s3.amazonaws.com/path/to/file`, otherwise it throws a 301 when requesting the file.

Now after the upgrade it seems that `put-object` stores the file in the correct region right away. Is there any way for us to digest from the response, which region the file eventually got stored in? It seems the response only contains the ETAG and the EXPIRY. Or is there some other better way to build the http and https URLs to a just stored file?

For now we would issue a `get-bucket-location` request in parallel, but we would like to avoid that, as most of the time, our customers store files in `us-east-1`, which is the default region.

**Comment by kyleknap** [comment]
Yep so in botocore, we recently made a change such that if you have sigv4 enabled then we will redirect to the proper region now if you did not specify the correct one.

Currently, there is not a great way for figuring this out in the CLI with out requesting the bucket location. 

One option would be to expose response metadata on what region the bucket is located since s3 for some operations returns the region of the bucket in the response headers.

Another option would be to have a flag or config option to turn off automatically redirecting of requests.

What are your thoughts on these ideas?

**Comment by tim-kos** [comment]
> One option would be to expose response metadata on what region the bucket is located since s3 for some operations returns the region of the bucket in the response headers.

Another option would be to have a flag or config option to turn off automatically redirecting of requests.


The first solution would be nice for the end-game, because it essentially puts the logic that we have implemented into the awscli SDK so that everybody can enjoy it. However, that only works for sigv4 regions.

Until all regions/buckets support sigv4 and thus the automatic redirect (then exposing the used region in the response would be great) I am afraid we need a config option to turn off the automatic redirect for now.

**Comment by JordonPhillips** [comment]
@tim-kos All regions / buckets do support sigv4, in fact new regions ONLY support it. Are you having issues using it in certain regions?

**Comment by tim-kos** [comment]
Please see my example in the first post.

I tried storing a file in a eu-west-1 bucket supplying `--region us-east-1`. That would have thrown an error with version `1.7.4`, but it does not anymore.

**Comment by jamesls** [comment]
Ok, so what I would propose for now is a new config file option that disables this behavior.  I'll try to draft up a proposal for this shortly.

**Comment by tim-kos** [comment]
Okay thank you.

Our main motivation behind this is to upgrade to get rid of the problem in #2089 , which now got closed due to inactivity.

**Comment by tim-kos** [comment]
Do you have an idea of when this would be committed to master and released?

**Comment by tim-kos** [comment]
This is not really a feature request by the way ... it's really a bug fix, because the new version of the client had a BC breaking change.

**Comment by tim-kos** [comment]
What is the status on this? We really need to upgrade, but can't and it's been almost two months since my last reply and over two months since your last action. :/

**Comment by tim-kos** [comment]
Is there any new status on this? :(

**Comment by tim-kos** [comment]
Gentlemen?

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by kvz** [comment]
Hi there, thanks for the update. Just wanted to let you know that we've (that includes @tim-kos) successfully worked around this issue so even while it still exists, if we're the only ones that hit it, your efforts are likely best spent elsewhere :) Closing this 👌
