### ISSUE TITLE
Allow configuration of aws_session_token through aws configure

### ISSUE THREAD

**Issue by BPScott** [aws/aws-cli#2116]
I work a lot with temporary credentials, as such I have to reconfigure the AWS CLI pretty often. 

Currently `AWS configure` lets you set  `aws_access_key_id`, `aws_secret_access_key`, `region` and `output`. `aws_session_token` is missing from that list of options.

**Comment by jamesls** [comment]
It's something worth considering.

Out of curiosity, how are you working with temporary credentials?  I wonder if there's a more direct way we can make working with temporary credentials easier in the CLI instead of requiring users to copy/paste temp creds into `aws configure`.

**Comment by BPScott** [comment]
Whoops, that fell down the back of the sofa.

I discovered that I can set `aws_session_token` from the command line using `aws configure set aws_session_token <SESSIONTOKENHERE>`.

---

As for how I work with the temp credentials - my company provides access to AWS through roles. I visit an endpoint with an x.509 certificate and it spits back a suite of credentials that are good for $timelimit. I can't think of any joined up mechanism to help automate that which would suit the general case unfortunately.

**Comment by JordonPhillips** [comment]
`aws configure set` isn't limited on what you can set. For instance you could say `aws configure set foobar baz` and that would work as expected. It is also worth noting that you can set the environment variable `AWS_SESSION_TOKEN` if that is easier.

Closing out since the feature requested is supported.

**Comment by rmharrison** [comment]
Using `aws configure set` is NOT the same as support of `aws_session_token` from within the `aws configure` prompts. Yes, it accomplishes the same end, but it's two steps instead of one.

As of now, you'll have to take two steps...
```
> aws configure --profile mfa
> aws configure set aws_session_token <SESSIONTOKENHERE>
```

Instead of one...
```
> aws configure --profile mfa --aws_session_token
```

Indeed, better yet...
```
> aws sts get-session-token --serial-number arn-of-the-mfa-device --token-code code-from-token | aws configure --profile mfa
```
Much more convenient than [xargs](https://stackoverflow.com/questions/38148397/is-there-a-way-to-pipe-the-output-of-one-aws-cli-command-as-the-input-to-another).
