### ISSUE TITLE
No error while trying to copy non-existent path recursively from S3

### ISSUE THREAD

**Issue by felipelb** [aws/aws-cli#2121]
When trying to copy recursively from a non-existent S3 path, there is no error thrown, compared to when trying to copy from a local one.

```
felipelb@linux:~$ aws --version
aws-cli/1.10.40 Python/2.7.12 Linux/4.4.0-31-generic botocore/1.4.30
felipelb@linux:~$ aws s3 cp bar s3://foo1234/bar --recursive
upload: bar/1.txt to s3://foo1234/bar/1.txt
felipelb@linux:~$ aws s3 cp s3://foo1234/bar s3://foo1234/bar_copy --recursive
copy: s3://foo1234/bar/1.txt to s3://foo1234/bar_copy/1.txt
felipelb@linux:~$ aws s3 cp baz s3://foo1234/baz --recursive

The user-provided path baz does not exist.
felipelb@linux:~$ aws s3 cp s3://foo1234/baz s3://foo1234/baz_copy --recursive
felipelb@linux:~$ aws s3 cp s3://foo1234/baz . --recursive
felipelb@linux:~$
```

**Comment by jamesls** [comment]
I do agree that it would be nice to be consistent.  However, it can get tricky to implement given this is the response we're getting back from S3.  We're essentially calling `s3api list-objects --bucket bucket --prefix baz/` and S3 is returning us an empty list instead of a 404 which makes sense for that specific API call with a prefix arg.

I think if we wanted to address this we'd then maybe do a HEAD object for `baz/` to see if there's at least a single object `'baz/'` there to indicate that the path does exist, but just has no files.

What do others think?  cc @kyleknap

**Comment by beanaroo** [comment]
We store build artifacts on s3 and pull them down right before a deploy. A trivial thing to catch but it would be useful if the command could throw an error status if nothing was copied.

**Comment by JordonPhillips** [comment]
I don't think heading the `baz/` would be a great idea since there could be no filler object there. However, it would be reasonable to fail on a copy that copies nothing. That would be a little tricky though since technically that's a breaking change. Marking as a feature request.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
