### ISSUE TITLE
fresh install using pip failed

### ISSUE THREAD

**Issue by vadimkim** [aws/aws-cli#2160]
Hi, 
       I have a strange installation problem:

```
<root@xxxx>/root # pip install awscli
Collecting awscli
  Could not find a version that satisfies the requirement awscli (from versions: )
No matching distribution found for awscli

```
Pip itself seems to pass dependency requirements
```
<root@xxxx>/root # pip -V
pip 7.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)

```

**Comment by JordonPhillips** [comment]
This appears to be an issue with pip, not the CLI. I would recommend asking the pip maintainers. That said, I was able to find a very similar issue on the homebrew repo that might be of assistance: https://github.com/Homebrew/legacy-homebrew/issues/41253

**Comment by vadimkim** [comment]
Thank you Jordon, it was indeed pip issue.
I have fixed it by manually running python setup.py install for each dependent module. Not the optimal way (in compare to SSL update) but fast enough.

**Comment by sapeish** [comment]
In my case turned out to be a SSL version error which I was able to see when running the command using verbose:
`sudo pip install -vvv awscli`

The fix was to upgrade pip as this thread explains https://stackoverflow.com/questions/49768770/not-able-to-install-python-packages-ssl-tlsv1-alert-protocol-version
