### ISSUE TITLE
Adding --recursive to an s3 cp when downloading a .zip does nothing

### ISSUE THREAD

**Issue by pmartindev** [aws/aws-cli#2194]
When I run the command _aws s3 cp s3://mybucket/files/test.zip  C:\files\text.zip --recursive_, the command outputs nothing to stdout/stderr, and it does not download anything.  If used on an empty directory, _no such file or directory_ is output to stderr. Should this error be thrown when downloading a file as well?

**Comment by JordonPhillips** [comment]
This is an issue that arises from the fact that S3 is not a file system, but an object store. When you do `aws s3 cp s3://bucket/some/prefix --recursive` the underlying call to S3 asks for all the objects with the prefix `some/prefix/` in the bucket `bucket`. If there are no objects with that prefix, the call returns an empty list much like `ls` on an empty directory would. But S3 doesn't have the concept of directories. A prefix doesn't require a `directory` object to exist at every delimiter (though it is not uncommon for people to place empty objects there). So when there is no object at `s3://bucket/some/prefix/` it isn't an error case.

**Comment by pmartindev** [comment]
Thank you for the clarification! If an empty list is returned though, shouldn't the call output to stdout that an empty list is returned and/or that there are no objects with that prefix? It seems misleading to output nothing for that case especially when a non-recursive copy on an empty folder outputs a 404 error.

**Comment by JordonPhillips** [comment]
Generally speaking we don't print to stdout unless we've actually done something. In this case the lack of output signifies that we've done nothing and the 0 rc indicates that it wasn't because of a problem. If you are interested in finer details of what happened, you can look at the `--debug` log which, amongst other things, will show you the empty response from s3 like so:

```
2016-09-26 14:34:54,184 - MainThread - botocore.parsers - DEBUG - Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>bucket</Name><Prefix></Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><EncodingType>url</EncodingType><IsTruncated>false</IsTruncated></ListBucketResult>'
```

The difference between this and specifying a particular object is that if I want to copy `foo.zip` down from my bucket and it isn't there, then that's a problem. If I want to copy a directory and it happens to empty, then it's just an empty directory that I'm copying which is perfectly valid.
