### ISSUE TITLE
aws autoscaling wait for autoscaling operation completion

### ISSUE THREAD

**Issue by eldondevcg** [aws/aws-cli#2226]
I have recently run across an issue like the following when trying to update the desired capacity on an autoscaling instance.

```
An error occurred (ScalingActivityInProgress) when calling the SetDesiredCapacity operation: Scaling activity b065594a-1c39-4c9a-8e5a-562c6b103df2 is in progress and blocks this action.
```

It would be nice if something like the aws ec2 wait .... functionality that was recently introduced could be applied, so that I would know when it was safe to attempt this type of change.

**Comment by kyleknap** [comment]
Looks like you need functionality from this closed PR: https://github.com/boto/botocore/pull/818.

Unfortunately, based on the discussion in the PR we are unable to pull the waiter in because of a limitation of our waiter implementation. We will have to revamp our waiter specification to be able to support it. Marking as blocked feature request.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by d-grendach** [comment]
Faced with the same issue.
An error occurred (ScalingActivityInProgress) when calling the SetDesiredCapacity operation: Scaling activity 16724625-6ee7-42c7-a6e0-96c3da3e7590 is in progress and blocks this action

Is there any workaround for this error ? Or any updates regarding this feature request?

**Comment by issacg** [comment]
This would also be helpful with the new-ish `start-instance-refresh` commands

Any update?

**Comment by tim-finnigan** [comment]
I just reached out to the Auto Scaling team for a response on this feature request. I will update this issue when we hear back.

**Comment by tim-finnigan** [comment]
Thanks all for your patience. After reaching out to that team, their recommendation was to try configuring retries because the API calls could also fail due to throttling. (Here is the CLI documentation for doing that: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-retries.html)

They also created a backlog item to consider adding this wait command. But I can’t provide any timeline for if or when that would be implemented. I'm going to close the issue but we can revisit this in the future.
