### ISSUE TITLE
aws.cmd on Linux

### ISSUE THREAD

**Issue by szepeviktor** [aws/aws-cli#2240]
Would it be possible not to install `aws.cmd` on non-Windows platforms?

_aws-cli/1.10.63 Python/3.4.2 Linux/3.16.0-4-amd64 botocore/1.4.53_

**Comment by JordonPhillips** [comment]
I don't think pip allows you to conditionally include / exclude files based on the os. We could potentially exclude it from the bundled installer, but now that bash on windows s a thing we can't guarantee that bundled installer users can't use cmd. Given that, and that it's a very small file, I don't think there's any way for us to conditionally remove it.

**Comment by szepeviktor** [comment]
@JordonPhillips Would entry points solve this?
http://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation
https://github.com/redacted/XKCD-password-generator/blob/master/setup.py#L16-L20

**Comment by JordonPhillips** [comment]
Possibly, thanks for pointing that out!

**Comment by szepeviktor** [comment]
Try running pylint and later integrate it into Travis.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by kdaily** [comment]
This has been fixed in AWS CLI V2, thanks!
