### ISSUE TITLE
s3 cp does not copy metadata within s3

### ISSUE THREAD

**Issue by huangting1** [aws/aws-cli#2253]
My command:
aws s3 cp 's3://bucket/a' 's3://bucket/archive/b'  --profile myprofile --metadata-directive COPY

I have some metadata on a that's not copied over to b after issuing the above command. Any idea?

**Comment by JordonPhillips** [comment]
To clarify: is *some* of the metadata being transferred?

**Comment by huangting1** [comment]
Content-Type is there, but none of x-amz-meta-* is transferred.

**Comment by JordonPhillips** [comment]
In that case, is the object large? There is a caveat in the docs:

> Note that if the object is copied over in parts, the source object's metadata will not be copied over,  no  matter  the  value  for --metadata-directive,  and  instead the desired metadata values must be specified as parameters on the command line.

**Comment by huangting1** [comment]
The object is ~58MB. The copy of metadata worked on the same file with native http PUT request (via x-amz-copy-source header). What does the s3 command work inconsistently?

**Comment by JordonPhillips** [comment]
At that size, a multipart transfer would occur. Unfortunately, the multipart transfer api does not support copying metadata. If S3 added support then we could then support it. You can request that feature on the [service forum](https://forums.aws.amazon.com/forum.jspa?forumID=24).

**Comment by tiferrei** [comment]
Hi I'm having the exact same issue, with the exact same command, however my files are not big, in fact, they're empty. They only have metadata, yet it's not being copied.

**Comment by 2WheelCoder** [comment]
I'm having the same issue @tiferrei. My files are also empty and can't seem to get the metadata to copy over. Did you ever figure out a workaround?

**Comment by tiferrei** [comment]
@2WheelCoder honstely I ended up just using a super simple [python script](https://gist.github.com/tiferrei/32f6641f9df4860ca9d1f0b25b911b5d). Left it running for some minutes and it got the job done, but be sure to check your transfer and copy fees.

**Comment by kislyuk** [comment]
@JordonPhillips I think this is a serious issue in the S3 API, and I understand that the AWS CLI team believes it's in the S3 team's court to address this. However, what this amounts to is silent loss of data while copying objects, since the metadata just gets dropped on the floor without warning above a certain opaque file size. I think that behavior is a bug and it is very unfortunate that neither team will own it while customers suffer from it. If metadata cannot be copied despite specifying `--metadata-directive COPY`, then at least the high level command (which `aws s3 cp` is) should error out.
