### ISSUE TITLE
Add progress bar UI for s3 copying

### ISSUE THREAD

**Issue by davidrabinowitz** [aws/aws-cli#2269]
If you're in higher latency parts of the world where connectivity isn't great (e.g. Australia, India, Israel), not having the progress output appear until after the first 5 MB is insufficient. I regularly upload 100 MB files from Sydney to an S3 bucket in the East US and it's beyond frustrating to have no output from the CLI.

**Expected behaviors:**
1. Upload a file from the CLI with aws s3 cp s3://bucket/file.ext 
2. View file progress/output as soon as the command executes

**Current behaviour:**
1. Upload a file from the CLI with aws s3 s3://bucket/file.ext 
2. Sit at an empty terminal for extended periods of time

The current behaviour leads to a poor interaction and negatively impacts the experience of the aws s3 cp command. 

This is taken from the comments of issue #312 , as it seems there is still a large demand for this feature.

**Comment by ciphertxt** [comment]
+1

**Comment by venkatd** [comment]
+1

**Comment by betesh** [comment]
Just my 2 cents: We've all plus-one'd #312 already, and Amazon can follow the links from here to there to see how much of a demand there is for this.  There's no need for all of us to plus-one here again.

@davidrabinowitz Agreed?

**Comment by davidrabinowitz** [comment]
@betesh I agree that all the +1's on #312 are relevant, but I don't know how AWS make their preferences...

**Comment by andyfowler** [comment]
This appears to be mostly [addressed in 1.11.0](https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst#1110), (with improvements in subsequent versions). I see this in v1.11.12 during an `aws s3 cp . s3://REMOTE_BUCKET`:

![image](https://cloud.githubusercontent.com/assets/107073/20022485/3404db78-a2b1-11e6-8178-7177dae6b64c.png)

**Comment by pehcha** [comment]
+1

**Comment by JordonPhillips** [comment]
As @andyfowler mentioned, we do have a more specific progress report now. It isn't perfect as it only shows estimates for the files in the upload / download queue (default 1000), but it does give a much more useful response. When running benchmarks on the new code I found it to be a *huge* improvement.

**Comment by davidrabinowitz** [comment]
I've also noticed the progress bar of 1.11 and it suits my needs. I think we can close this issue unless there are other comments.

**Comment by erikhakansson** [comment]
I'm running aws-cli from a Jenkins instance. I think there are issues with buffering or something, because after the command has started there is no output until at the end (after about 1 hour) when ALL rows are printed simultaneously:

`6:29:32 Completed 256.0 KiB/1.4 GiB (18.3 KiB/s) with 1 file(s) remaining
Completed 512.0 KiB/1.4 GiB (34.9 KiB/s) with 1 file(s) remaining
Completed 768.0 KiB/1.4 GiB (46.9 KiB/s) with 1 file(s) remaining
Completed 1.0 MiB/1.4 GiB (56.9 KiB/s) with 1 file(s) remaining  
Completed 1.2 MiB/1.4 GiB (69.2 KiB/s) with 1 file(s) remaining  
Completed 1.5 MiB/1.4 GiB (83.1 KiB/s) with 1 file(s) remaining  
Completed 1.8 MiB/1.4 GiB (91.2 KiB/s) with 1 file(s) remaining  
Completed 2.0 MiB/1.4 GiB (95.3 KiB/s) with 1 file(s) remaining  `

I know that wget gets the same issue if using --progress=bar (which modifies the last line of the tty) but works fine with --progress=dot (which prints a new line for each progress update)

I figure this is a Jenkins issue, rather than aws-cli but perhaps there is some easy workaround for it?

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by justnance** [comment]
This is partially related to #2598, #4190, and #3618

**Comment by tim-finnigan** [comment]
Regarding [this comment](https://github.com/aws/aws-cli/issues/2269#issuecomment-260574499), I see the original author of this issue said: 
> I've also noticed the progress bar of 1.11 and it suits my needs. I think we can close this issue unless there are other comments.

Since the addition of a progress bar addresses the original request, I'm going to close this issue. If anyone would like to see any functionality beyond what is currently available then please consider opening a new issue.
