### ISSUE TITLE
s3 cp --source-region parameter not being used?

### ISSUE THREAD

**Issue by jrotenstein** [aws/aws-cli#2274]
The `--source-region` parameter doesn't seem to have an impact on command success.

As a test, I copied from an object from a bucket in Sydney to a bucket in Singapore with different `--region` parameters:

    aws s3 cp s3://sydnet-bucket/x.txt s3://singapore-bucket/xx.txt --region ap-southeast-2
    aws s3 cp s3://sydnet-bucket/x.txt s3://singapore-bucket/xx.txt --region ap-southeast-1
    aws s3 cp s3://sydnet-bucket/x.txt s3://singapore-bucket/xx.txt --region us-west-2

All of them worked successfully.

Thus, it doesn't seem to matter "where" the command was sent to, the objects will magically copy.

Therefore, what does the `--source-region` parameter actually do?

**Comment by JordonPhillips** [comment]
Do you have your signature version for s3 set to `s3v4`? If so, the cli and boto3 will redirect you to the correct region if we get a service error that indicates an incorrect region. With that in mind, setting region or source region isn't strictly necessary, but setting them to the correct regions will prevent unnecessary requests. It is also worth noting that you do not use `--source-region` in any of your supplied commands.

**Comment by jrotenstein** [comment]
Ah! So what you're saying is that the `--source-region` parameter is not actually required, but if supplied it will be enforced? That's fine, except the documentation also says:

> If `--source-region` is not specified the region of the source will be the same as the region of the destination bucket.

My tests suggest that this is not the case? Or is it just semantics?

Feel free to close this issue if you think everything is as-expected, but perhaps some clarification in the documentation would be worthwhile -- especially your comment about `s3v4` and redirection.

**Comment by JordonPhillips** [comment]
No, not quite. Setting those parameters tell us how to construct our clients under the hood. Example:

```
aws s3 cp s3://sydney-bucket/x.txt s3://singapore-bucket/xx.txt --source-region ap-southeast-2 --region us-east-1
```

Under the hood we have constructed two clients: one for `sydney-bucket` with the region `ap-southeast-2` (correct) and one for `singapore-bucket` with the region `us-east-1` (incorrect). Previously, this would cause the request to fail since the client for `singapore-bucket` is incorrectly configured. Now that we will redirect for you, we catch that failure and retry with the correct region.

So setting those parameters used to prevent errors, but now prevents unnecessary requests.

**Comment by jrotenstein** [comment]
Okay. I'll close because there doesn't seem to be an issue, but feel free to share some of this knowledge in the documentation if you have time. Thank you for your fast response!
