### ISSUE TITLE
Local caching for read-only ops

### ISSUE THREAD

**Issue by lwoodson** [aws/aws-cli#2300]
I couldn't find any issues/feature-requests describing this.  The aws cli tools would be much easier to use in an iterative style if read-only data retrieved from the API could be cached locally for a time.  This would have transitive benefits of limiting the number of calls made and lowering network traffic for AWS and the end-user.  I think this would be most useful as a CLI flag that could be used on an adhoc basis, as in this example:

```
aws cloudformation describe-stacks --cache 60s
```

* first execution of above would make remote call, cache data locally, then spit out results
* subsequent executions of above within 60 seconds would return the locally cached data with no API call
* an execution after 60 seconds would refresh the stale local data.

Purging/cleanup of stale data so that it doesn't clutter the local file system would be an issue.  Some ideas:

* Document where the cache is located and let people know they may want to clean it periodically using standard tools (`rm`, etc...)
* Have it located within `tmp` so that it gets cleaned up periodically by the OS
* Have a cleanup command that can be run periodically and leave it up to the user as to when/if its run
* Purge any stale data every time an `aws` command is invoked.

**Comment by JordonPhillips** [comment]
Having a cache could be useful in some scenarios, but the problem is we would then be feeding potentially invalid data to customers. That's not something I think we should be doing. If you're fine with stale data, it can always be stored somewhere else and referenced.

That said, it would be great for services to support http caching via `if-modified-since` and similar, with that we could maintain a cache without having to worry about stale data. Right now it looks like S3 supports that for a few operations, but only for `get_object` and `copy_object`.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by tim-finnigan** [comment]
This issue has been open for several years with very little activity in that time. I think based on [this earlier comment](https://github.com/aws/aws-cli/issues/2300#issuecomment-263982486) it doesn't sound like something that would be implemented as requested. If anyone is still tracking this feature request please let us know here, and if you can expand on your use cases that would be helpful as well.
