### ISSUE TITLE
iot commands require output filename

### ISSUE THREAD

**Issue by aztecrex** [aws/aws-cli#2352]
The **iot-data** commands such as **get-thing-shadow** and **update-thing-shadow** require a filename parameter. Output from the commands is directed to that file rather than to stdout.  The filename is required and even the common *nix designation for stdout, "-", does not work. 

This behavior is inconsistent with most other CLI commands and works against the normal composition of *nix commands.  The output is JSON so a user should reasonably expect the output to go to stdout. As it stands, there is no way to pipe the output and a user is forced to contend with cleaning up temporary files.

These commands should be consistent with the *nix conventions (and the bulk of other AWS CLI commands) by writing semantic output to stdout and letting the caller decide whether to redirect to a file.

This should be fixed before the use of intermediate files for what should be simple piping becomes widespread.

**Comment by stealthycoin** [comment]
Seems like a reasonable idea to me. I'll mark this as a feature request.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by tim-finnigan** [comment]
Checking in as this issue hasn't received any community activity since it was opened in 2016. @aztecrex is this still an issue for you? I haven't seen many IoT-related issues in general, I think several users may have pivoted to use one of the [IoT SDKs](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sdks.html) for their use cases.
