### ISSUE TITLE
Wrong error message when s3 bucket name not available

### ISSUE THREAD

**Issue by helinwang** [aws/aws-cli#2364]
When I run `aws s3api --region=us-west-1 create-bucket --bucket test-kube`, I get:
> An error occurred (InvalidRequest) when calling the CreateBucket operation: You are attempting to operate on a bucket in a region that requires Signature Version 4.  You can fix this issue by explicitly providing the correct region location using the --region argument, the AWS_DEFAULT_REGION environment variable, or the region variable in the AWS CLI configuration file.  You can get the bucket's location by running "aws s3api get-bucket-location --bucket BUCKET".

But if I try to create the s3 bucket from web console, it shows
> The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.

And when creating a unique name from aws cli, it works. So the problem should be in the error message. I think error message should print something reasonable indicating bucket name is not available.

```
aws --version
aws-cli/1.11.36 Python/2.7.10 Darwin/15.6.0 botocore/1.4.93
```

**Comment by dstufft** [comment]
I can confirm that this bug is reproducible.

Digging into this, it appears that awscli makes a ``PUT`` to ``test-kube.s3.amazonaws.com`` which then fails with a 400, presumably because the bucket that already exists under a different user is not in the default region. While the console makes a ``PUT`` to ``https://s3-$REGION.amazonaws.com/test-kube`` which returns a 409.

If I run ``aws configure set default.s3.signature_version s3v4`` then the error changes, but it changes to the same error as in https://github.com/aws/aws-cli/issues/589, and doing the fix mention there works for me.

So I'm going to say you need to ensure that you've enabled s3v4 signatures and since you're using the low level API you have to use the ``--create-bucket-configuration`` [option](http://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html#options).
