### ISSUE TITLE
awscli requires python-six but does not declare it

### ISSUE THREAD

**Issue by Fale** [aws/aws-cli#2369]
Also, it would be nice to know which minimum version of six is required

**Comment by dstufft** [comment]
``awscli`` does not itself depend on ``six``, but instead it uses the version of six that comes with ``botocore``. However, instead of depending on ``six``, ``botocore`` bundles a copy internally to use so that it does not need to declare a dependency. Inspecting ``botocore/vendored/six.py`` indicates that it is currently using v1.8.0.

Are you getting an error where it's failing to import six?

**Comment by Fale** [comment]
yes, on machines with python-six 1.3 installed (see https://bugzilla.redhat.com/show_bug.cgi?id=1409681)

**Comment by dstufft** [comment]
Yes, this does appear to be a bug, it looks like we actually *sometimes* use the bundled version of six and *sometimes* don't. It generally works because we pick up a transitive dependency on six via ``python-dateutil`` . This also appears to affect ``botocore`` as well.

I'm not 100% sure if we should fix this by rewriting all uses of ``six`` to use the one bundled in botocore or if we should just depend on ``six`` and stop bundling it. In either case we should probably be consistent.

**Comment by Fale** [comment]
Uhm, why not removing the bundled version and depend on the "external" six? I mean, the huge majority of packages depend on six, so I guess 99% (if not all) the users already have it

**Comment by dstufft** [comment]
That decision predates me, so I'm not sure!

**Comment by Fale** [comment]
I'm sure that when it was done had reasons, but I wonder if today it still makes sense or not, and since that code needs to be touch either way, probably is a good moment to think about it

**Comment by kyleknap** [comment]
Looks like it is a bad import in the ``cloudformation package/deploy`` commands. In general in the CLI codebase, if we need to use six, we should be importing from the [compat.py](https://github.com/aws/aws-cli/blob/develop/awscli/compat.py#L17). The problem is it is easy to forget that as ``python-dateutil`` has that dependency so if you import it from the wrong location, it still may work.

Here is the issue on why we vendored six: https://github.com/aws/aws-cli/issues/1051. It is related to how OS X pre-installs pip and sets its precedence before the six installed by pip.

I will look into updating the code so that import is correct.

**Comment by dstufft** [comment]
@kyleknap Perhaps a linter should be added?

**Comment by Fale** [comment]
@kyleknap that seems to be a 2014 problem. I wonder if it's still current or if it has been fixed in the meantime

**Comment by kyleknap** [comment]
@dstufft 
Yes, I think a linter would be good to add. We really do not have any linters in any of the boto/CLI codebases currently, but I think it is a good idea. It also probably won't be hard to add just need to setup the framework to fail the build when it fails the linter. I would be willing to add one if everyone is fine with it? @jamesls @JordonPhillips @stealthycoin 

@Fale 
I am not sure if it is still is a problem. Even if it is still not a problem, I am pretty hesitant to start depending on ``six`` again because there is no guarantee that OS X will not break us again. Furthermore, the issue affected a lot of users and broke the entire CLI (due to import errors). So it would be a high risk/low reward in my opinion.

**Comment by dstufft** [comment]
It is still an issue. Changes in macOS Sierra make it possible for pip to fix it, but thus far it has not been fixed. It will remain an issue on older macOS versions forever though.

**Comment by stealthycoin** [comment]
@kyleknap A linter for this sort of thing sounds like a good idea to me.

**Comment by jamesls** [comment]
@kyleknap Sounds good, go for it.

**Comment by JordonPhillips** [comment]
+1 to linter. It'll be great to have linting set up.
