### ISSUE TITLE
aws s3 cp for urls with spaces results in fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden

### ISSUE THREAD

**Issue by iteratelance** [aws/aws-cli#2379]
This error occurs when trying to execute the command on urls with the following format:

` aws s3 cp s3://mybucket/with+space.zip my.zip`
` aws s3 cp s3://mybucket/with%20space.zip my.zip`

However this works as expected:

` aws s3 cp "s3://mybucket/with space.zip" my.zip`

My best guess is that it's the security token being generated incorrectly because in the debug logs I see the following generated 

```
x-amz-security-token:XXXXXXX
/mybucket/with%2Bspace/my.zip
```

This bug is hard to track down because if you're using automation you'll pull your hair out as to why you're getting a forbidden response on folders that have spaces.  At the very least I'd expect a 404 error.

Perhaps worth noting that I first discovered this error via AWS CodeDeploy.  I'm assuming that it might use this library on EC2 instances when pulling S3 builds.

**Comment by dstufft** [comment]
I can reproduce this, but I think this is an unsolvable issue. The problem is we have no way of knowing whether ``s3://mybucket/with%20space.zip`` is an URL that has already been quoted and thus needs no further processing, or if it is an url that includes a literal ``%20`` that needs to be quoted to ``%2520``. The only way I could think of adding this is as a flag to the CLI that allows you to say that the URL has already been quoted, but that feels like it'd be better handled by just having whatever is pushing urls into it unquote the URL first.

Tagging this as needs discussion to see what others think. Thanks!

**Comment by iteratelance** [comment]
I understand the complexity of this issue but at the very least I'd expect this to work.

`aws s3 cp s3://mybucket/with+space.zip my.zip`

I discovered this when trying to use the AWS console to copy and past a S3 object into CodeDeploy.  Copying URL's from S3, via properties url encodes spaces as "+".  I'm not 100% certain that AWS is using this under the hood but I suspect that it is because the errors are similar. 

I know we should not have spaces in URL's but sometimes these things are out of my control.

**Comment by dstufft** [comment]
Hmm, the Python ``urllib.parse.quote`` function will urlencode a ``+`` to ``%2B``, though we could mark ``+`` as a "safe" character that doesn't need quoting, I can see if I add a ``--debug`` to the awscli command though that we're sending ``test%20space`` and I'm not sure if a ``test+space`` is valid or not on the server side of S3. I suspect not, but I'll need to dig into that to be sure.

**Comment by JordonPhillips** [comment]
I'm -1 on supporting something like this. As Donald mentioned we have no way of knowing how you've encoded that string. The standard way of accepting strings with spaces in a command line tool is to use quotes, so I would prefer we stick to that.

**Comment by JordonPhillips** [comment]
So a reasonable way to do this might be to have something like a `--url-encoded-input` flag, which would also allow for the use of control characters.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by majlisg** [comment]
Hi All,
I used \ and added the space to the string path and it works.
aws s3 cp s3://mybucket/with\ space.zip my.zip
Also with folders
aws s3 cp s3://mybucket/with\ space/ ./ --recursive
