### ISSUE TITLE
s3api multi events per bucket

### ISSUE THREAD

**Issue by arukaen** [aws/aws-cli#2387]
### aws cli version
``` sh
aws-cli/1.11.36 Python/2.7.10 Darwin/15.6.0 botocore/1.4.93
```

I have this json document which I am attempting to use to create two events for an S3 bucket.

``` json
{
  "QueueConfigurations": [
    {
      "Id": "imagesapi",
      "QueueArn": "arn:aws:sqs:us-east-1:123456789:dev-genjishamada-screenupload",
      "Events": [
        "s3:ObjectCreated:Put"
      ],
      "Filter": {
        "Key": {
          "FilterRules": [
            {
              "Name": "prefix",
              "Value": "images-api/"
            }
          ]
        }
      }
    },
    {
      "Id": "upload",
      "QueueArn": "arn:aws:sqs:us-east-1:123456789:dev-genjishamada",
      "Events": [
        "s3:ObjectCreated:*"
      ]
    }
  ]
}
```

However when I run `aws s3api put-bucket-notification-configuration --bucket dev-genjishamada --notification-configuration file://bucket-events.json`, I get the following error:
```
An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type.
```

I first attempted to add the two by using two different json documents and two `s3api` commands but this was overwriting the other(which from another issue in GH, it is intended this way). I know on the GUI I can go in and add two events with no issues but that would be a pain on 200+ buckets.

**Comment by kyleknap** [comment]
I am not too sure what the console may be doing to get this to work. The CLI is pretty much a direct mapping to the API and the console often has extra logic on top of the API, and so the error you are getting back is coming from the service.  While I am not too sure how you would do this through the API. One thing that I would suggest doing is to figure out how the console logic translates to the API, I will run a ``get`` command on the resource that I just created. Then from there, I can figure out all of the properties that got added for me.

So I would recommend try running the ``s3api bucket-notification-configuration`` on the console configured bucket to get insight on what a put configuration would look like.

Otherwise, I am not too sure how to accomplish this through S3's API. It might be worth asking on Stack Overflow using the [aws-cli](http://stackoverflow.com/questions/tagged/aws-cli) or [aws-s3](http://stackoverflow.com/questions/tagged/amazon-s3) tags to see if someone has ran into this as well.

**Comment by arukaen** [comment]
@kyleknap thanks for the idea. I was able to solve it. 

```json
{
  "QueueConfigurations": [
    {
      "Filter": {
        "Key": {
          "FilterRules": [
            {
              "Name": "Prefix",
              "Value": "images-api/"
            }
          ]
        }
      },
      "Id": "imagesapi",
      "QueueArn": "arn:aws:sqs:us-east-1:123456789:dev-genjishamada-screenupload",
      "Events": [
        "s3:ObjectCreated:Put"
      ]
    },
    {
      "Id": "upload",
      "QueueArn": "arn:aws:sqs:us-east-1:123456789:dev-genjishamada",
      "Events": [
        "s3:ObjectCreated:Copy"
      ]
    }
  ]
}```
