### ISSUE TITLE
Unable to download RDS log files that contain binary data

### ISSUE THREAD

**Issue by andybeak** [aws/aws-cli#2400]
When using aws rds download-db-log-file-portion if the log file contains binary data you get the error message "An error occurred (InvalidParameterValue) when calling the DownloadDBLogFilePortion operation: This file contains binary data and should be downloaded instead of viewed."

**Comment by kyleknap** [comment]
This looks like an error coming from the service. The CLI is just a wrapper over the API. So it is just creating an HTTP request based on parameters provided and parsing/displaying the resulting HTTP response. The CLI in this case is just propagating the error from the service.

So unfortunately, there is not much that can be done from the CLI codebase. I did a quick search of other people who ran into this issue and found this thread: https://forums.aws.amazon.com/thread.jspa?threadID=144248. So that may be of some use. If it is not, I would recommend reaching out on the AWS Developer Forums to see if there are any workarounds.

**Comment by andybeak** [comment]
Hi,

Yeah I also came to that conclusion.  I decided on using mysqlbinlog to download them (here's a [gist](https://gist.github.com/andybeak/24dbc28f0f2d2c31515197e693335da9) I made).

The problem with this workaround is that the user/pass is in the script.  Even having them in an environment variable is not great.

**Comment by andybeak** [comment]
Although I can use mysqlbinlog to download the binary logs I cannot download the general log for auditing purposes.

This means that RDS instances are not suitable for PCI compliance since requirement 10.2.4 insists that there is an audit trail of authentication attempts.

I really need a better answer regarding how to do this.

**Comment by bdobberteen** [comment]
+1

**Comment by JordonPhillips** [comment]
[Support](https://console.aws.amazon.com/support/home#/) is probably the best avenue for getting help here, but since there's nothing we can do about the issue I'm closing it out.
