### ISSUE TITLE
Create linter for ensuring proper import of six is being used

### ISSUE THREAD

**Issue by kyleknap** [aws/aws-cli#2487]
The CLI does not have a direct dependency on ``six``. It only gets pulled in because of the dependency on ``python-dateutil``. However because of this, some of the imports directly import ``six`` instead of import ``six`` from ``awscli.compat`` which points to the vendored version of ``six``. Ideally we would have a linter for this that fails the build on  direct ``six`` imports as discussed in these issues:
https://github.com/aws/aws-cli/pull/2393
https://github.com/aws/aws-cli/issues/2369

**Comment by dstufft** [comment]
+1

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by nateprewitt** [comment]
With the removal of six for the CLI code base, this FR is no longer needed. Resolving.
