### ISSUE TITLE
Creating dynamodb json in shell is just too painful

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-cli#2488]
<a href="https://twitter.com/kaihendry/status/841139347881582592"><img src=https://s.natalian.org/2017-03-13/1489378157_2548x1380.png></a>

A similar problem IIUC occurs with the JS SDK, but they have solved it with the [Doc client](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html), which allows just the JSON to be updated, without the 'dynamodb JSON' marshalling.

**Comment by stealthycoin** [comment]
Marking as a feature request. Maybe something similar to how 
[boto3 handles it](https://boto3.readthedocs.io/en/latest/guide/dynamodb.html#updating-item)?

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by tim-finnigan** [comment]
This issue hasn't received any 👍 reactions or community comments since it was opened in 2017. Is it still an issue? As mentioned earlier you can use boto3 as an alternative, although there is another open feature request related to this: https://github.com/boto/boto3/issues/1630
