### ISSUE TITLE
Bash redirection malforms output with single instance EC2 regions

### ISSUE THREAD

**Issue by ivankisic** [aws/aws-cli#2493]
I'm using a loop to list some information from all the instances across all zones:

```
#/bin/bash

for region in $(aws ec2 describe-regions --output text | cut -f3)
do
	echo "##### $region ######"; aws ec2 describe-instances --query 'Reservations[*].Instances[*].[{Name:[Tags[?Key==`Name`].Value][0][0],Service:[Tags[?Key==`service`].Value][0][0],LocalIP:PrivateIpAddress,PublicIP:PublicIpAddress,Owner:[Tags[?Key==`owner`].Value][0][0],PrivateDNS:PrivateDnsName,RunningState:State.Name,AvailabilityZone:Placement.AvailabilityZone}]' --output table --region $region

done
```

The output is expected for all zones, but when I use bash redirect (either > or &> or 2&1> or even tee) it is malformed for zones that have single instances. I've created a few EC2 instances to test it and it really does seem to be connected to the number of servers in a region. More than one and the table is looking wrong, but again, only when using redirects.

JSON and text works fine.

aws-cli/1.10.49 Python/2.7.10 Linux/4.2.0-16-generic botocore/1.4.39
Ubuntu 15.10
GNU Bash 4.3.42

**Comment by ivankisic** [comment]
Here's how my output looks when piping to a file:

![example](https://cloud.githubusercontent.com/assets/14118888/24039382/3dd82d82-0b05-11e7-9cd2-53c572261a93.jpg)

As you can see, both single instance regions (ap) are structured differently.

**Comment by ivankisic** [comment]
Any ideas? This is still happening with single instance zones.

**Comment by joguSD** [comment]
This is by design as can be seen here: [table.py](https://github.com/aws/aws-cli/blob/develop/awscli/table.py#L105).

As of writing this there are two conditions for having the table be reformatted to the vertical style:
1) There has to be a single row
2) The width of the table is greater than the width of the terminal

In your case, the IO redirection is causing the width of the terminal to be unknown and thus the aforementioned function is causing the table to become vertical. This behavior is also by design.
It's worth noting that the `table` and `text` output formats are designed to be human readable and we currently don't guarantee that they will be consistent enough for programmatic use.

Hopefully that clears things up!
