### ISSUE TITLE
Sorting with query returns empty response

### ISSUE THREAD

**Issue by mkriaf** [aws/aws-cli#2512]
Im trying to get a list of RDS snapshots that have a start time is < or = to a certain date.
by running the following command and query:

```
aws rds describe-db-snapshots --snapshot-type manual  --query 'DBSnapshots[?SnapshotCreateTime<=`2017-03-20`].[DBSnapshotIdentifier]'   --output text
```

on a AWS CLI version 1.10.1
```
~$ aws --version
aws-cli/1.10.1 Python/3.5.2 Linux/4.7.5-040705-generic botocore/1.3.23
```

I am getting a list of DB snapshot names as expected:
```
$ aws rds describe-db-snapshots --snapshot-type manual --query 'DBSnapshots[?SnapshotCreateTime<=`2017-03-20`].[DBSnapshotIdentifier]' --output text
someDBname-2017-03-15-15-10-40
someDBname-2017-03-15-15-51-36
someDBname-2017-03-15-18-02-00
.......
```

When running the same exact command on a newer version, 
```
$ aws --version
aws-cli/1.11.44 Python/2.7.6 Linux/4.4.0-31-generic botocore/1.5.7
```
im getting an empty list, (i removed  "--output text" since it returned nothing).
```
$ aws rds describe-db-snapshots --snapshot-type manual  --query 'DBSnapshots[?SnapshotCreateTime<=`2017-03-20`].[DBSnapshotIdentifier]'  
$ []
```

Is this kind of query a functionality that was removed in newer versions?

**Comment by kyleknap** [comment]
It looks like there was a regression in the dependency that ``--query`` relies on: https://github.com/jmespath/jmespath.py/issues/124. How did you install the CLI? If you are using ``pip``, I would recommend upgrading to 0.9.2 of ``jmespath`` if you can.  Otherwise upgrading to the latest version of the CLI should fix this as well as it should be pulling in that version of ``jmespath``.

**Comment by mkriaf** [comment]
Confirming that upgrading to `jmespath 0.9.2` from `0.9.1`solved the problem.
