### ISSUE TITLE
AWS CLI Windows Installer should use Python 3 for better performance

### ISSUE THREAD

**Issue by ffeldhaus** [aws/aws-cli#2514]
I have done extensive testing with the latest version of AWS CLI on Windows Server 2012R2 with 8 cores against a custom S3 endoint and I discovered that the Windows Installer version which uses Python 2.7 is approx 30% slower than AWS CLI if installed via Python 3.6 (120MByte/s vs 160MByte/s read and 50MByte/s write vs 70MByte/s write). This seems to be due to much better multithreading in Python 3 where all 8 cores are used and in Python 2 only 4 cores are used. In both cases I'm using a 16GB file with `multipart_chunksize = 512MB` and `max_concurrent_requests = 8`.

Why does the AWS CLI Installer uses Python 2.7? Can the AWS CLI Installer be changed to use Python 3?

**Comment by kyleknap** [comment]
The CLI Installer uses Python 2.7 for legacy reasons. It was the version chosen when the MSI installer was first introduced. And yes. We would like to upgrade the MSI installer to use Python 3. Python 3 has a lot of improvements over Python 2 that users of the CLI will then be able to take advantage of. Marking as feature request.

**Comment by nkadel-skyhook** [comment]
You can test it under CygWin with python-3.4 pretty easily. Be quite cautions about *which* python-3.x release you use for testing, they are not entirely cross-compatible.

I've actually tried to RPM bundle it for CentOS 6 or 7, and got bogged down very fast in getting all the python modules into RPM's to match.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by joguSD** [comment]
The MSI installers have been migrated to use Python 3 instead of Python 2 and are now the default installers linked to in the documentation:

https://docs.aws.amazon.com/cli/latest/userguide/install-windows.html#install-msi-on-windows

The Python 2 based MSI installers are still being created and uploaded at the same URIs as they have been.
