### ISSUE TITLE
CloudTrail 2 SNS (topic policy) not possible with CLI / SDKs

### ISSUE THREAD

**Issue by pgollucci** [aws/aws-cli#2515]
aws sns add-permission --topic-arn arn:aws:sns:us-east-1:ACCOUNT_ID:NAME --label StmtLabel --aws-account-id NOTHINGWORKSHERFORCLOUDTRAIL  --action-name Publish

http://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-permissions-for-sns-notifications.html

See also https://github.com/aws/aws-sdk-ruby/issues/1454

**Comment by kyleknap** [comment]
Based on the issue opened in the Ruby SDK, it sounds like a service issue. The CLI, along with the Ruby SDK, just send requests to the service based on parameters parameters and collect the response from the service. If the service behavior changed, there is not really anything the client-side tooling can do about it. I would recommend following the issue opened up on the Ruby SDK as it seems that @awood45 is following up with them. Otherwise, you can open up a thread on the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=72) or get in contact with AWS Support.
