### ISSUE TITLE
Switch to generate aws cli command from aws component?

### ISSUE THREAD

**Issue by nitrocode** [aws/aws-cli#2523]
Hi. This is a question / feature request.

I've created a few components within AWS Console (web browser UI) and I'd like to simplify my preconfigured processes into AWS commands so in case something happened like an accidental deletion, I could easily run a command to bring it back.

Is there a way to generate AWS CLI commands from pre existing components? I'm doing this by hand right now and for all the components (ec2, redshift, kinesis firehose, etc), it's painful.

**Comment by stealthycoin** [comment]
There is no way to do this right now with the CLI, have you considered looking into cloudformation and maintaining your stacks? Those can be deleted/updated easily.

**Comment by nitrocode** [comment]
Interesting. We have not considered cloudwatch. However, our manual testers could also benefit from a feature like this since they will manually create the AWS components, run functions, and have to recreate them in testing. It would be a lot easier if we could convert the component into its command line equivalent.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by tim-finnigan** [comment]
Checking in as this issue hasn't received any 👍 reactions or community comments since it was opened in 2017. As mentioned here earlier, using CloudFormation stacks may be more aligned with your use case. Alternatively I suggest looking into the [AWS CDK](https://aws.amazon.com/cdk/) to see if that would help with what you're trying to do. Is this still an issue for you or have you found any alternatives to be sufficient?
