### ISSUE TITLE
aws s3 sync command publishes absolute directories as relative directories

### ISSUE THREAD

**Issue by nkadel-skyhook** [aws/aws-cli#2530]
If I use the command:

     aws s3 sync /tmp/dirname/ s3://bucket/foldername/

The output of the sync command prepends the source directory with a set of "../../../" prefixes depending on the $PWD when I ran the command, designed to match a relative directory to the "/tmp/dirname/". This is confusing and undesirable information. And it's quite unlikely to be accurate for someone reviewing the file transfers later, since "../../../" from their $PWD is unlikely to match that of the working environment when the original command was run.

Please, publish absolute filenames or directory locations as absolute names in the output of "aws s3 sync".

**Comment by stealthycoin** [comment]
Marking as a feature request.

**Comment by Subzidion** [comment]
The function relative_path is [called when formatting the results](https://github.com/aws/aws-cli/blob/develop/awscli/customizations/s3/results.py#L150) and that is what is giving you the '../../..' prefixes. This can be changed to `return os.path.abspath(fileobj)` and that will give you the absolute path. 
Should it always give the absolute path, or should it be an option of the sync command? Perhaps it could give the absolute path output if an absolute path is passed and then give the relative path otherwise?

**Comment by nkadel-skyhook** [comment]
Perhaps the pathname used by the user should be published without post-processing interpretation instead? What python deduces a path to be may bear little resemblance to what the user actually typed, and can be extremely broken in auto-mounting environments or environments with complex symlink arrangements.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by jbauers** [comment]
Hi! We just stumbled upon this and were a bit surprised by this behaviour.

> Perhaps the pathname used by the user should be published without post-processing interpretation instead

That would be amazing - is there any possibility to change this?

**Comment by smacdonald-ppo** [comment]
Came here for the same reason: AWS is publishing relative paths when it shouldn't. This clutters up the logging and can cause confusion in later traceability situations.

`aws-cli/2.7.33 Python/3.9.11 Linux/4.19.0-5-amd64 exe/x86_64.debian.10 prompt/off`  

Issue is not listed as fixed in the https://raw.githubusercontent.com/aws/aws-cli/v2/CHANGELOG.rst so isn't fixed in newer versions than mine.
