### ISSUE TITLE
`get-rest-api` not returning "NotFoundException" for empty RestApi Id

### ISSUE THREAD

**Issue by markymark** [aws/aws-cli#2534]
I discovered this with one of the SDKs so it's not necessarily a CLI issue and likely more of an API one, but I was able to reproduce the potential issue with the client as well.

Calling `get-rest-api` with a valid RestApi Id returns RestApi output as expected, and an invalid one like `aws apigateway get-rest-api --rest-api-id blah` generates an exception:

> An error occurred (NotFoundException) when calling the GetRestApi operation: Invalid REST API identifier specified

However `aws apigateway get-rest-api --rest-api-id ""` returns nothing--neither an error nor an exception. With both the CLI and SDKs the output is empty. (Less of a concern at the command line than when checking programmatically and expecting either api info or an error/exception.)

Reporting here with the idea that the right parties can be advised.

**Comment by stealthycoin** [comment]
So the reason this is happening is that API Gateway is a restful service which means the urls look like this:
`aws apigateway get-rest-apis`
`https://apigateway.{region}.amazonaws.com/restapis`

`aws apigateway get-rest-api --rest-api-id ""`
`https://apigateway.{region}.amazonaws.com/restapis/`

`aws apigateway get-rest-api --rest-api-id "123"`
`https://apigateway.{region}.amazonaws.com/restapis/123`

Technically from a ReST point of view there is nothing semantically different between the first two urls. So they are both interpreted by the service as calls to `GetRestApis` and it returns the list of APIs. Since the response format wasn't what the CLI was expecting, it fails to transcribe the response from the wire into a response object, and hence prints nothing since the response  object is empty, which in the CLI happens to mean nothing gets printed.


May I ask what your use case was for sending up "" as the rest api id?
