### ISSUE TITLE
Reading/writing EMR key_pair_file configuration options behaves oddly

### ISSUE THREAD

**Issue by muz** [aws/aws-cli#2536]
Version:

```
$ aws --version
aws-cli/1.11.75 Python/2.7.10 Darwin/15.6.0 botocore/1.5.38
```

[It's suggested that one can set a default key_pair_file argument here](https://github.com/aws/aws-cli/blob/master/awscli/customizations/emr/ssh.py#L25) by running `aws configure set emr.key_pair_file <value>`

By that token, I would expect `aws configure get emr.key_pair_file` to retrieve this item and to exit with a exit code of 0.

```
$ aws configure set emr.key_pair_file /tmp/foo

$ cat config
[default]
emr =
    key_pair_file = /tmp/foo

$ aws configure get emr.key_pair_file

$ echo $?
1
```

As you can see, setting this and trying to retrieve it exits with a non-zero exit code which makes it a pain to check for this config item being set as part of shell scripts prior to do other EMR-based commands (such as create-cluster).

As an aside, trying to get the top level `emr` config item fails too;

```
$ aws configure get emr

expected a character buffer object
```

Additionally this item doesn't show up when `aws configure list` is run either;

```
$ aws configure list
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
access_key     REDACTED                    shared-credentials-file
secret_key      REDACTED                    shared-credentials-file
    region                <not set>             None    None

```

**Comment by stealthycoin** [comment]
Interesting. I get exit code 0 under both python 2 and 3. Can you try upgrading the cli `pip install -U awscli`? List specifically only prints out `profile`/`access_key`/`secret_key`/`region` so it won't appear there, but that doesn't mean it isn't loaded.

When using get with dot syntax (`aws configure get emr.key_pair_file`) the first component separated by they dots is interpreted as the profile. So in this case it finds nothing since there is no `key_pair_profile` in a profile named `emr`.

This will work however: 
```
$ aws configure get default.emr.key_pair_file
tmp/foo
```
