### ISSUE TITLE
feature request: Add aws s3 sync --update

### ISSUE THREAD

**Issue by danielmotaleite** [aws/aws-cli#2563]
Hi

`rsync` have a feature that is very useful:

```
  -u, --update                skip files that are newer on the receiver
```

aws-cli is missing this feature, without it, any change made to the S3 files will be lost.

Without this, it is hard to migrate LIVE services from local to s3, as it will force to have some downtime to move data without losing any change. We are required to stop writes locally, copy all changed files and start writes to S3... with many files this can be a LONG downtime just to compare and copy the files.

With the `--update` flag, we could enable writes on both sides, then stop the local ones, and then `sync --update` any changed or new files to the S3, without breaking any already updated files on the S3. Now this sync can take a long time, but it will not force any downtime, the only problems might be some missing or outdated files in S3, that are still being copied. This is usually acceptable for most people and can be minimized by migrating writes to s3 just after a successful s3 sync and then start a new s3 sync --update

**Comment by dstufft** [comment]
Marking this as a feature request, thanks!

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
