### ISSUE TITLE
AWS CLI - Update existing or allow multiple policies

### ISSUE THREAD

**Issue by vikas027** [aws/aws-cli#2576]
I am following the below command as listed out [here](http://docs.aws.amazon.com/cli/latest/reference/ecr/set-repository-policy.html)  to create ECR policy.

```
aws ecr set-repository-policy --repository-name <my_repo_name> --policy-text <my_policy_text>
```

This does the job, but it overwrites any existing permissions. Is there a way to update an existing policy or add multiple (independent) policies? If not, can you please take this as a feature request.

**Comment by kyleknap** [comment]
Unfortunately, there is no single CLI command to do this. This is because the CLI is just a wrapper over the ECR's API so the commands are essentially a 1:1 mapping of command to API operation. If ECR exposed this functionality in their API, the CLI would pick it up automatically. I would recommend opening a thread on the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=187) on this.

However given the current API, the best option to get the functionality that you want will probably be to describe the policy with the ``get-repository-policy``, update the policy with what you want to add, and then run the ``set-repository-policy`` with your updated policy.

Let us know if you have anymore questions.

**Comment by vikas027** [comment]
Thanks @kyleknap , yes for now I have written a ruby script to update the existing policy. As suggested, I will raise a thread on [Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=187)
