### ISSUE TITLE
upload-ssh-public-key returns before succeeding

### ISSUE THREAD

**Issue by doom777** [aws/aws-cli#2615]
after `upload-ssh-public-key`, the new key is not immediately usable. In my experience, it takes about 10 seconds for it to activate.

The solution it to add new command `iam wait ssh-public-key-exist` Currently, my workaround is putting `/bin/sleep 10` before using code commit

version:
aws-cli/1.11.84 Python/3.4.3 Linux/4.4.0-43-Microsoft botocore/1.5.47

**Comment by stealthycoin** [comment]
Marking this as a feature request for a GetSSHPublicKey waiter.

**Comment by doom777** [comment]
@stealthycoin tentatively, and without commitment, how long do you think it will take until this feature is implemented?

**Comment by stealthycoin** [comment]
@doom777 Actually looking at this again I'm not sure there is any waiter here that makes sense. You are waiting on [eventual consistency](http://docs.aws.amazon.com/IAM/latest/UserGuide/troubleshoot_general.html#troubleshoot_general_eventual-consistency) between codecommit and iam, not on iam to return the key when you try to `GetSSHPublicKey`. I tested waiting on `GetSSHPublicKey` and it always returns the key on the first call in `<1` second, so that isn't a useful metric.


I think the best you can do is just try to interact with codecommit and if your key is rejected, wait and try again.
