### ISSUE TITLE
Using GIT SHELL i am creating amazon aws ec2 instance  

### ISSUE THREAD

**Issue by kattomdevops** [aws/aws-cli#2629]
Hello there,

I  am using git shell on windows to create an Amazon aws instance ec2. after  aws configure    i got this error to create security group  
command:  aws ec2 create-security-group --group-name aws1-sg --description "My Security Group"                                                                                                                                                                                ('Connection aborted.', error(10013, 'An attempt was made to access a socket in a way forbidden by its access permissions'))                                                                    ~\Documents\GitHub\aws-cli

**Comment by stealthycoin** [comment]
Hmm I don't know anything about git shell, or windows in particular. Sounds like a permission issue on your system or something. I don't believe it to be an issue with the cli. You would probably have better luck asking this on stack overflow and tagging it based on the environment you are in since I think that is where the issue lies.
