### ISSUE TITLE
Query and text output not filtering correctly (with aws deploy list-deployments)

### ISSUE THREAD

**Issue by sgarner** [aws/aws-cli#2650]
I have a deployment script for bootstrapping new instances which relies on looking up the ID of the last successful deployment. It runs a command like this:

```sh
aws deploy list-deployments --application-name "foo" --deployment-group-name "bar" --include-only-statuses Succeeded --query "deployments[0]" --output text
```

This should return a single deployment ID in text format. I have some older instances with 1.10 versions of `aws-cli` where this command runs correctly:

Command output with `aws-cli/1.10.11 Python/2.7.6 Linux/3.13.0-79-generic botocore/1.4.2`:

```
d-YVXZIAJFM
```

However instances with newer 1.11 versions of `aws-cli` are returning a list of deployment IDs from the same command.

Command output with `aws-cli/1.11.100 Python/2.7.6 Linux/3.13.0-119-generic botocore/1.5.63`:

```
d-YVXZIAJFM
d-WY1VX89VL
d-3IH0XGJFL
# ... etc, a total of 24 IDs are displayed
```

Note that this output is not the complete list of deployments. If the query is removed entirely, many more deployments are returned.

If the output format is changed to JSON, then the query works correctly regardless of the `aws-cli` version used. The output is a single ID in JSON format, as expected:

```
"d-YVXZIAJFM"
```

So it appears something has been broken with queries applied in `text` output mode, at some point between versions 1.10.11 and 1.11.100.

I have only seen this problem occur with `aws deploy list-deployments`, though it might well be affecting other commands too.

**Comment by JordonPhillips** [comment]
Could you show a `--debug` output for the failing command?

**Comment by sgarner** [comment]
Hi @JordonPhillips 

I've pasted debug output into https://gist.github.com/sgarner/6c6cb6a6eff202870b8eb90904c2b603

**Comment by jamesls** [comment]
Hi, the difference in behavior is due to the `list-deployments` command being auto-paginated in newer version of the CLI.  There's  a tradeoff involved where in order to stream results and not buffer them in memory with `--output text`, the `--query` expression is applied to each page of results.  This means if you have N pages, you'll get N deployment ids.  You have a few options:

1. If you want the old behavior back, you can specify `--no-paginate`.  This might lead to undesired behavior because it won't paginate results.
2. You can use `--output json`, which will buffer the entire set of results in memory but will only run the `--query` expression once.
3. Use other CLI tools to filter results.  Something like `aws deploy list-deployments --query deployments[] | head -n 1`.

Let me know if you have any more questions.

**Comment by sgarner** [comment]
OK, that would explain it.

> Use other CLI tools to filter results. Something like `aws deploy list-deployments --query deployments[] | head -n 1`.

This is precisely what I've been doing to work around the problem...

> If you want the old behavior back, you can specify `--no-paginate`. This might lead to undesired behavior because it won't paginate results.

... but it sounds like this would also be (more?) appropriate for me.

Can I suggest this pagination behaviour and how it conflicts with some queries should be described in [the user guide](http://docs.aws.amazon.com/cli/latest/userguide/controlling-output.html#controlling-output-filter) for the benefit of anyone else trying to query a limited number of results and encountering this issue.

**Comment by faultylee** [comment]
I'm having the same issue with `aws-cli/1.16.122 Python/3.7.2 Linux/5.0.2-arch1-1-ARCH botocore/1.12.112` 
```
$ aws codepipeline list-pipeline-executions --pipeline-name pipeline --query "pipelineExecutionSummaries][].{\"startTime\": startTime, \"status\": status} | [0]" --output json
...
{
    "startTime": 1552890158.533,
    "status": "InProgress"
}

$ aws codepipeline list-pipeline-executions --pipeline-name pipeline --query "pipelineExecutionSummaries][].{\"startTime\": startTime, \"status\": status} | [0]" --output table
...
----------------------------------
|     ListPipelineExecutions     |
+-----------------+--------------+
|    startTime    |   status     |
+-----------------+--------------+
|  1552890158.533 |  InProgress  |
+-----------------+--------------+

$ aws codepipeline list-pipeline-executions --pipeline-name pipeline --query "pipelineExecutionSummaries][].{\"startTime\": startTime, \"status\": status} | [0]" --output text
...
1552890158.533  InProgress
1550816105.024  Succeeded

```
The 2 results from the `text` output comes from first and 101th row. This doesn't happen to `json` nor `table`

**Comment by justnance** [comment]
Our [documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-output.html#controlling-output-filter) has been updated with notes related to `--query` section which include warning about how `--output` text can have an unexpected result set due to the pagination before querying.  The following is an excerpt for quick reference:

> Important
> 
> The output type you specify (json, text, or table) impacts how the --query option operates.
> 
> If you specify --output text, the output is paginated before the --query filter is applied and the AWS CLI runs the query once on each page of the output. This can result in unexpected extra output, especially if your filter specifies an array element using something like [0], because the output then includes the first matching element on each page.
> 
> If you specify --output json, the output is completely processed and converted into a JSON structure before the --query filter is applied. The AWS CLI runs the query only once against the entire output.
> 

@faultylee - Please let us know if this answers your question too.  Thanks.
