### ISSUE TITLE
Error installing with pip : [Errno 13] Permission denied

### ISSUE THREAD

**Issue by EmilioMN92** [aws/aws-cli#2654]
Hello,
I'm trying to install aws-cli through both pip command and installer, but they are failing with this error:

```
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\NSS_AD~1\\AppData\\Local\\Temp\\pip-build-f83og7_h\\awscli\\awscli/examples/s3api/get-object-torrent.rst'
```

I'm using the admin profile in a Windows environment. 

Can anybody help me ? I'm freaking out!

Thanks in advance.

**Comment by JordonPhillips** [comment]
Looks like you haven't got permission to do that. Try running in a shell with administrator access. If that doesn't work I would recommend asking on one of our [community resources](https://github.com/aws/aws-cli#getting-help).

**Comment by kokkondaabhilash** [comment]
I'm also facing the same issue. The error appears even while running the command prompt as administrator.@JordonPhillips

**Comment by lisandrolan** [comment]
I have the same issue

**Comment by jansonjc** [comment]
I get the same error while trying to install awscli. I tried the following options without luck.

1. Using admin rights - `pip install awscli`
2. Using --user option - `pip install --user awscli`
3. Using virtual environment. Created a new virtual environment, activated it and used the pip install command `pip install --user awscli`

All of these options give the same error

_Could not install packages due to an EnvironmentError: [Errno 13] Permission denied_

**Comment by jansonjc** [comment]
For me the issue was with Enterprise Virus Protection (McAfee in my case). System Admins couldn't find a way other than to uninstall McAfee, install AWS CLI and then again install McAfee back. Hope this information helps people who are getting this error in Windows 10 environment.

**Comment by choyrim** [comment]
(cross posting from https://github.com/pypa/pip/issues/7033 since this one talks about awscli and virus protection)

Like @jansonjc I was able to reproduce the problem by installing recent versions of awscli on windows with virus protection. as it turns out, just `pip download awscli` will fail with a similar error most of the time. If I lower the priority of CylanceSvc.exe I can reproduce close to a 100% of the time.

```
> set TEMP=c:\tmp\pip
> pip download awscli
Collecting awscli
  Using cached https://files.pythonhosted.org/packages/f2/f5/d682aa32100edc6908a784630aa2903ef7d2735130e6df98a05af6c33096/awscli-1.16.271-py2.py3-none-any.whl
  Saved c:\users\rich9002\tmp\awscli-1.16.271-py2.py3-none-any.whl
ERROR: Exception:
Traceback (most recent call last):
  File "c:\sw\python37\lib\shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'c:\\tmp\\pip\\pip-unpack-4gdrskd3\\awscli-1.16.271-py2.py3-none-any.whl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\sw\python37\lib\site-packages\pip\_internal\cli\base_command.py", line 188, in main
    status = self.run(options, args)
  File "c:\sw\python37\lib\site-packages\pip\_internal\commands\download.py", line 156, in run
    resolver.resolve(requirement_set)
  File "c:\sw\python37\lib\site-packages\pip\_internal\legacy_resolve.py", line 196, in resolve
    self._resolve_one(requirement_set, req)
  File "c:\sw\python37\lib\site-packages\pip\_internal\legacy_resolve.py", line 359, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\sw\python37\lib\site-packages\pip\_internal\legacy_resolve.py", line 307, in _get_abstract_dist_for
    self.require_hashes
  File "c:\sw\python37\lib\site-packages\pip\_internal\operations\prepare.py", line 199, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "c:\sw\python37\lib\site-packages\pip\_internal\download.py", line 1064, in unpack_url
    progress_bar=progress_bar
  File "c:\sw\python37\lib\site-packages\pip\_internal\download.py", line 935, in unpack_http_url
    os.unlink(from_path)
  File "c:\sw\python37\lib\site-packages\pip\_internal\utils\temp_dir.py", line 60, in __exit__
    self.cleanup()
  File "c:\sw\python37\lib\site-packages\pip\_internal\utils\temp_dir.py", line 83, in cleanup
    rmtree(self.path)
  File "c:\sw\python37\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "c:\sw\python37\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "c:\sw\python37\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "c:\sw\python37\lib\site-packages\pip\_vendor\six.py", line 693, in reraise
    raise value
  File "c:\sw\python37\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "c:\sw\python37\lib\site-packages\pip\_internal\utils\misc.py", line 166, in rmtree
    onerror=rmtree_errorhandler)
  File "c:\sw\python37\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\sw\python37\lib\shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\sw\python37\lib\site-packages\pip\_internal\utils\misc.py", line 176, in rmtree_errorhandler
    os.chmod(path, stat.S_IWRITE)
PermissionError: [WinError 5] Access is denied: 'c:\\tmp\\pip\\pip-unpack-4gdrskd3\\awscli-1.16.271-py2.py3-none-any.whl'
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```
using Process Monitor (procmon), I confirmed that `CylanceSvc.exe` (virus protection) was still reading the file as python kept trying to delete the files.

Two workarounds (1) hack the code, or (2) install the big whl file directly. The first work around is to download the .whl file (with curl or a failed pip download) and install the .whl file directly. The second workaround is the change the retry time in the `pip\_internal\utils\misc.py` file.

```python
# Retry every half second for up to 3 seconds
#@retry(stop_max_delay=3000, wait_fixed=500) # original
@retry(stop_max_delay=60000, wait_fixed=500) # wait up to a minute
def rmtree(dir, ignore_errors=False):
    # type: (str, bool) -> None
    shutil.rmtree(dir, ignore_errors=ignore_errors,
                  onerror=rmtree_errorhandler)
```

**Comment by danizen** [comment]
@choyrim, we do still see this problem in our environment, and we do run CylanceProtect.  Good catch on involvement of CylaneProtect.   This reminds me of a fundamental difference between Windows filesystems and *nix filesystems such as CIFS and NFS.   Windows has hard-locks and Linux has advisory file locks (such as fntl) lock.   So, maybe this has to do with OpLocks?   Maybe Python does not distinguish between PermissionError due to ACL/mask and permission error due to an OpLock?

I will try to prove this in a kernel, and then add some code to do locking of the file in a platform independent way before reading.

**Comment by danizen** [comment]
@choyrim, I am working on duplicating this on a Windows system that does not necessarily have Cylance Protect on it, and to make the problem worse and affect any package, rather than just Django.

The technique I plan to use is mentioned here:
http://timgolden.me.uk/python/win32_how_do_i/watch_directory_for_changes.html

See https://github.com/danizen/watchandlock for further developments until I can prove and re-open my issue.

**Comment by rekhahariram** [comment]
I have the same issue as @EmilioMN92 while using msi to install either V1 or V2. @denizen or any of you able to find a way to get it installed in Windows once you had that problem?
