### ISSUE TITLE
s3 sync calls open() even if no files need to be uploaded

### ISSUE THREAD

**Issue by steffenweber** [aws/aws-cli#2661]
I'm using `aws s3 sync /local/dir/ s3://mybucket --region eu-central-1 --delete` to sync a local directory hierarchy (totalling 580 GB distributed among 3.4 million files) to an S3 bucket. This currently takes about 35 minutes and I'm wondering whether this could be optimized.

I've attached `strace` to aws-cli to monitor syscalls. Aside from multiple `stat`calls per file I've noticed that `open` is called on files even if they don't have to be transferred (the local directory and S3 are in sync). For each file I'm seeing the following `strace` output:

```
stat("file.jpg", {st_mode=S_IFREG|0664, st_size=21646, ...}) = 0
lstat("file.jpg", {st_mode=S_IFREG|0664, st_size=21646, ...}) = 0
stat("file.jpg", {st_mode=S_IFREG|0664, st_size=21646, ...}) = 0
stat("file.jpg", {st_mode=S_IFREG|0664, st_size=21646, ...}) = 0
stat("file.jpg", {st_mode=S_IFREG|0664, st_size=21646, ...}) = 0
open("file.jpg", O_RDONLY|O_CLOEXEC) = 5
fstat(5, {st_mode=S_IFREG|0664, st_size=21646, ...}) = 0
ioctl(5, TCGETS, 0x7ffc971b2330)        = -1 ENOTTY (Inappropriate ioctl for device)
fstat(5, {st_mode=S_IFREG|0664, st_size=21646, ...}) = 0
lseek(5, 0, SEEK_CUR)                   = 0
ioctl(5, TCGETS, 0x7ffc971b2290)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(5, 0, SEEK_CUR)                   = 0
close(5)                                = 0
stat("file.jpg", {st_mode=S_IFREG|0664, st_size=21646, ...}) = 0
```

I'm not sure whether this `open` call could have a big impact. From what I'm reading, `open` is more expensive than `stat`. Is the `open` call expected behaviour? It only seems to be used for `fstat` calls, no data is read.

I've taken a look at the aws-cli source code but the only `open` call I've found is in an error-handling code path in `filegenerator.py` which should not be the issue here. The `open` syscall is probably caused indirectly by Python. But I don't know where to look.

(I'm looking at I/O syscalls because the sync is not CPU bound, it uses about 70% of a single CPU core according to `top`.)

```
$ aws --version
aws-cli/1.11.81 Python/3.4.5 Linux/4.9.28 botocore/1.5.52
```

**Comment by steffenweber** [comment]
If I'm interpreting the `time` output correctly then at most 14 minutes are spent waiting for I/O.

```
real	35m20.771s
user	20m37.250s
sys	1m26.327s
```

So probably the `open` call is not such a huge issue.

**Comment by jamesls** [comment]
I believe that comes from the `is_readable` function (https://github.com/aws/aws-cli/blob/develop/awscli/customizations/s3/filegenerator.py#L52) which checks if a file is readable by actually opening the file with `'r'`.  IIRC that was done because it was the most reliable cross platform way to verify read access (i.e windows).

It's been a while since I've dug into this code, but I think If we don't check readability up-front, it fails deeper in the code base when it actually tries sending data to s3.  It gets harder to propagate a better error message /warning when that happens.

The filtering for sync happens after we generate the list of candidate files, which would be why you're seeing this happen if we decide to skip the file.

As you mention, unless this is causing a perf issue, I'd prefer to keep it as is.  Let me know if you have any more questions.

**Comment by steffenweber** [comment]
Thank you for the detailed response.

My feeling is that it should be possible to improve the `aws s3 sync` performance a lot although it is written in Python: if the source and destination are already synced then `aws s3 sync` should be completely I/O-bound and not CPU-bound. But the `open` call does not seem to be the low-hanging fruit that I had hoped for and I'm not familliar with Python. So this issue is not very useful and I'm closing it.
