### ISSUE TITLE
add awsebcli to https://github.com/aws/

### ISSUE THREAD

**Issue by graingert** [aws/aws-cli#2696]
Currently https://pypi.python.org/pypi/awsebcli exists only on PyPI and there is no public repo.

The owners are  @nhumrich, @aws, @awsebcli

I've created a mirror here https://github.com/awsebcli/awsebcli

(Yeah I know this is the aws/aws-cli repo, and so not really the right place for an issue, but there's no github issues for awsebcli so it's a catch 22.)

**Comment by graingert** [comment]
Also it looks like @nhumrich (currently at @canopytax) is not at AWS anymore so having him as an owner is a bit of a security hole

**Comment by dstufft** [comment]
I believe the elastic beanstalk developer forum would be the best place to ask this question: https://forums.aws.amazon.com/forum.jspa?forumID=86.

**Comment by graingert** [comment]
It's already been brought up on the forums: https://forums.aws.amazon.com/thread.jspa?threadID=232432

**Comment by dstufft** [comment]
Ok, well we wouldn't be able to do anything more than that. That is owned by a different team than aws-cli.

**Comment by graingert** [comment]
@dstufft and @nhumrich

**Comment by nhumrich** [comment]
The elastic beanstalk team had no desire to make this repo open source while I was there, and I assume, still has no desire. I am sure if you get enough people interested and open support tickets, this could happen.

**Comment by graingert** [comment]
@nhumrich it's already open source (Apache 2)

**Comment by nhumrich** [comment]
Sorry, let me clarify. no desire to put the source on github.

**Comment by graingert** [comment]
@dstufft @nhumrich awsebcli is now broken with Python 3.7

**Comment by mronoffon** [comment]
so, who is currently maintaining the project?

I just installed a fix for the "requests 2.18.4 has requirement urllib3<1.23,>=1.21.1, but you'll have urllib3 1.23 which is incompatible.", but now can't run awsebcli because of outdated 'botocore<1.12" dependency. Downgrade, at this point, is not an option.

root@dev:/usr/local/lib/python3.7/site-packages# eb
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
ws.require(__requires__)
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 892, in require
needed = self.resolve(parse_requirements(requirements))
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (botocore 1.12.1 (/usr/local/lib/python3.7/site-packages), Requirement.parse('botocore<1.12'), {'awsebcli'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/bin/eb", line 6, in <module>
from pkg_resources import load_entry_point
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3088, in <module>
@_call_aside
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
f(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 576, in _build_master
return cls._build_from_requirements(__requires__)
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
dists = ws.resolve(reqs, Environment())
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 778, in resolve
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'botocore<1.12' distribution was not found and is required by awsebcli

specs --

FreeBSD 11.2-RELEASE-p2
Python 3.7.0

Thanks in advance

**Comment by electricBonfire** [comment]
I agree, there should be a github repo for awsebcli. I would like to submit an issue and possible a PR fix but it does not appear to be a way through pypi!
