### ISSUE TITLE
Support for encrypted private SSH key for ec2 get-password-data

### ISSUE THREAD

**Issue by cjeanneret** [aws/aws-cli#2713]
Hello,

It would be good to support encrypted SSH keys when we call the ``ec2 get-password-data --priv-launch-key ~/.ssh/id_rsa``.

For now, if our ssh key is encrypted, we get an error: ``Unable to decrypt password data using provided private key file.``

For security reason, we want to avoid clear SSH private keys. Guess we're probably not the only one.

Tool version:
```
aws --version
aws-cli/1.11.13 Python/2.7.9 Linux/4.9.0-0.bpo.1-amd64 botocore/1.4.70
```

Thank you!

Cheers,

C.

**Comment by stealthycoin** [comment]
Marking this as a feature request.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by tim-finnigan** [comment]
Checking in as this issue hasn't received any community activity since 2017. In the [ec2 get-password-data documentation](https://docs.aws.amazon.com/cli/latest/reference/ec2/get-password-data.html) it looks like there is now a `--priv-launch-key` option that you can pass. Does this address the original feature request? Please let us know if there's any thing you want to clarify or expand on related to this.
