### ISSUE TITLE
aws s3 cp stdout issue

### ISSUE THREAD

**Issue by taraslayshchuk** [aws/aws-cli#2731]
Hello, I have been using aws s3 cp command like this:
```bash
$ aws s3 cp pingdom-check.html "s3://bucket/pingdom-check.html" | awk '{print "datetime " $0}'
datetime upload: ./pingdom-check.html to s3://bucket/pingdom-check.html
$ aws --version  aws-cli/1.10.25 Python/2.7.11 Darwin/16.6.0 botocore/1.4.16
```
But after updating to latest version of awscli a stdout become broken:
```bash
$ aws --version
aws-cli/1.11.125 Python/2.7.11 Darwin/16.6.0 botocore/1.5.88
$ aws s3 cp pingdom-check.html "s3://bucket/pingdom-check.html" --acl public-read  | awk '{print "datetime " $0 }'
upload: ./pingdom-check.html to s3://bucket/pingdom-check.html
$ aws s3 cp pingdom-check.html "s3://bucket/pingdom-check.html" --acl public-read  | awk '{print "datetime " $1 }'
datetime Completed
```

**Comment by kyleknap** [comment]
I believe this is happening because there may be progress being shown in newer version of the CLI that was not shown before for a single file. So for a single small file, the output may look something like this:
```
Completed 2.0 KiB/2.0 KiB (4.8 KiB/s) with 1 file(s) remaining
upload: ./pingdom-check.html to s3://mybucketfoo/pingdom-check.html     
```
And in-between the completed line and the upload their is a carriage return followed by a new line. So when you do `awk` with `$0` the carriage return is causing the upload portion to clobber the datetime portion you have in your command.

Could you describe why you are relying on using `awk` on the output like you described?

**Comment by taraslayshchuk** [comment]
I would like to add timestamp to every output line in log file.

**Comment by kyleknap** [comment]
Marking as feature request then for logging timestamps to the output.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
