### ISSUE TITLE
Error Creating EC2 Instance in Custom Layer of OpsWorks Stack

### ISSUE THREAD

**Issue by shinroo** [aws/aws-cli#2734]
I am trying to create a t2.micro instance in my OpsWorks stack in the us-west-1 region.

I followed the following:

The contents of my .aws/config:
```
[default]
output = json
region = us-west-1
```
Creating the stack:
```
aws opsworks create-stack --name $name --stack-region "us-west-1" --service-role-arn $service_role_arn --default-instance-profile-arn $default_instance_profile_arn --default-ssh-key-name $default_ssh_key_name --configuration-manager '{"Name":"Chef","Version":"11.10"}' --chef-configuration '{"ManageBerkshelf":false}' --no-use-custom-cookbooks
```
this returns the stack id, which you then use as $stack_id
```
aws opsworks create-layer --region "us-west-1" --stack-id $stack_id --type "custom" --name $name --shortname $shortname
```
this returns the id of the layer which is used as $layer_id in
```
aws opsworks create-instance --stack-id $stack_id --layer-ids $layer_id --instance-type "t2.micro" --os "Ubuntu 14.04 LTS" --root-device-type "ebs"
```

No matter what combination of input parameters (tried specifying the region, availability zone and provisioning a VPC/subnet and trying with different instance types) I user the following error is returned

> An error occurred (ValidationException) when calling the CreateInstance operation: Instance Type: is not supported for EC2 classic stacks

I created a [thread on reddit](https://www.reddit.com/r/aws/comments/6pz4fp/aws_cli_instance_type_problem_on_createinstance/) to discuss the issue and user /u/Himekat was able to reproduce the error in the eu-west-1 region.

I've consulted the documentation which suggests to check if the type of instance is available via the console. I was able to create multiple different types of instances in the same stack/layer I used over the CLI via the management console, so the error does seem to be in the actual CLI or perhaps in my approach.

Any help would be appreciated!

**Comment by kyleknap** [comment]
From the reddit thread, it sounds like you opened a support ticket. That will probably be your best option to get the issue resolved.

Most of the commands in the CLI just take the parameters you provide, send them as an HTTP request to the AWS service, and display the response back from the service. For this command, it is not doing anything more than that, and the error you are getting back comes straight from the service. Given there is not really any more information provided, it cannot be really determined from the CLI-side as to why specifically the error is getting returned to you, which is why I recommend continuing conversations with support.

Let us know if you have any further questions.

**Comment by shinroo** [comment]
Thanks, I'll take it up with the AWS support. I appreciate all the responses, have a great weekend.
