### ISSUE TITLE
aws lambda update-function-configuration: Partially update environment variables

### ISSUE THREAD

**Issue by jinjor** [aws/aws-cli#2796]
Is there any way to partially update Lambda's environment variables?

This is easy script to reproduce the situation. The second command successfully creates `BAR` but it overrides the first variable `FOO` at the same time.
```sh
aws lambda update-function-configuration --function-name env-test --environment Variables={FOO=foo} &&
aws lambda update-function-configuration --function-name env-test --environment Variables={BAR=bar}
```
In my case, I use a secret token to access some API with it. The problem is that the token changes over time.

**Comment by cwgem** [comment]
Honestly, instead of this setup you might want to consider using [EC2 Parameter Store](http://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-paramstore.html) instead. For your particular case:

```
aws ssm put-parameter --name "FOO" --type "String" --value "foo" && aws ssm put-parameter --name "BAR" --type "String" --value "bar"
```

Then simply use the GetParameter call in the appropriate SDK (you will of course need to adjust your Lambda IAM role permissions accordingly):

* NodeJS [ssm.getParameter](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SSM.html#getParameter-property)
* Python [SSM.Client.get_parameter](http://boto3.readthedocs.io/en/latest/reference/services/ssm.html#SSM.Client.get_parameter)
* Java [AWSSimpleSystemsManagement.getParameter](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/simplesystemsmanagement/AWSSimpleSystemsManagement.html#getParameter-com.amazonaws.services.simplesystemsmanagement.model.GetParameterRequest-)
* C#
  * [AmazonSimpleSystemsManagementClient.GetParameters](http://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SSM/MSSMSSMGetParametersGetParametersRequest.html)
  * [AmazonSimpleSystemsManagementClient.GetParametersAsync](http://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SSM/MSSMSSMGetParametersAsyncGetParametersRequestCancellationToken.html)
  * [GetParametersRequest](http://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SSM/TSSMGetParametersRequest.html) (this is for the options to the call)

As with Lambda environment variables you can also utilize encrypted strings to store your API secrets in. For example:

```
aws ssm put-parameter --name "FOO" --type "SecureString" --value "foo" && aws ssm put-parameter --name "BAR" --type "SecureString" --value "bar"
```

Then when you go to pull the parameter store value pass in the `WithDecryption` option accordingly. Note your Lambda will need KMS access via IAM to whatever key is used to encrypt the data (generally the default key). That said, note that each time you decrypt the key you make a call against the KMS API allocation and will be charged accordingly.

**Comment by jamesls** [comment]
Thanks @cwgem!  SSM is a good option here, especially if you're storing a secret token.

If you did want to update the lambda environment variables, you'd have to query for all of them, update/inject what you want, and then do the `update-function-configuration`.

```
env_vars=$(aws lambda get-function-configuration --function-name MyFunction --query Environment.Variables)
# Modify/add vars
aws lambda update-function-configuration --function-name MyFunction --environment ...
```

Let me know if you have any more questions.

**Comment by jinjor** [comment]
Thank you both! I didn't even know EC2 Parameter Store. Nice to know.
