### ISSUE TITLE
"aws elb describe-load-balancer-policies" gives older policies which are not currently attached to ELB

### ISSUE THREAD

**Issue by singhjayesh** [aws/aws-cli#2797]
Hi,

Upon following the below command to check which policy is currently used by my respective "redacted" ELB, the console output gives me all the past policies as well.
This makes it difficult for a user to identify the current policy on the ELB and due to this issue, I cannot have an automated check for policies on all my ELBs.
The console UI shows the current policy only.

$ aws elb describe-load-balancer-policies --region us-east-1 --load-balancer-name redacted  --query PolicyDescriptions[].PolicyName
[
    "AWSConsolePolicy-1", 
    "AWSConsolePolicy-2", 
    "AWSConsole-SSLNegotiationPolicy-redacted", 
    "AWSConsole-LBCookieStickinessPolicy-redacted-1401270498291", 
    "AWSConsole-LBCookieStickinessPolicy-redacted-1401196917496", 
    "MySSLNegotiationPolicy", 
    "AWSConsole-SSLNegotiationPolicy-redacted-1411148658282", 
    "AWSConsole-SSLNegotiationPolicy-redacted-1412757992003", 
    "AWSConsole-SSLNegotiationPolicy-redacted-1411730992859", 
    "AWSConsole-SSLNegotiationPolicy-redacted-1467114332291", 
    "AWSConsole-SSLNegotiationPolicy-redacted-1467114213256", 
    "AWSConsole-SSLNegotiationPolicy-redacted-1493053165429", 
    "AWSConsole-SSLNegotiationPolicy-redacted-1493053148373", 
    "AWSConsole-SSLNegotiationPolicy-redacted-1493061556472", 
    "AWSConsole-SSLNegotiationPolicy-redacted-1493052351939", 
    "AWSConsole-SSLNegotiationPolicy-redacted-1431933112864", 
    "ELBSecurityPolicy-2015-05", 
    "AWSConsole-LBCookieStickinessPolicy-redacted-1464274060336", 
    "AWSConsole-SSLNegotiationPolicy-redacted-1478767492133", 
    "AWSConsole-SSLNegotiationPolicy-redacted-1413529248618", 
    "AWSConsole-SSLNegotiationPolicy-redacted-1461316447754", 
    "AWSConsole-SSLNegotiationPolicy-redacted-1464104514209", 
    "AWSConsole-SSLNegotiationPolicy-redacted-1464105591959", 
    "AWSConsole-SSLNegotiationPolicy-redacted-1501662184303", 
    "AWSConsole-SSLNegotiationPolicy-redacted-1457467760655", 
    "AWSConsole-SSLNegotiationPolicy-redacted-1460448526370"
]

**Comment by jamesls** [comment]
The CLI is forwarding the DescribeLoadBalancerPolicies command to the ELB service.  It doesn't have any special client side logic for filtering out results.  The response you're seeing is just what the ELB service is returning back to us.

Is it possible to get this information from `describe-load-balancers` instead of `describe-load-balancer-policies`?

Otherwise, I'd suggest moving this to stackoverflow, as suggested in our ["Getting Help" section](https://github.com/aws/aws-cli#getting-help) of our README.  It will reach a wider audience of people that may be able to answer your question.
