### ISSUE TITLE
describe-db-clusters doesn't show version of aurora 

### ISSUE THREAD

**Issue by sivarohithm** [aws/aws-cli#2810]
## aws rds describe-db-clusters --db-cluster-identifier

           
```
            "Status": "available", 
            "MultiAZ": true, 
            "LatestRestorableTime": "2017-09-03T21:50:05.421Z", 
            "PreferredBackupWindow": "08:05-08:35", 
            "AllocatedStorage": 1, 
            "BackupRetentionPeriod": 7, 
            "PreferredMaintenanceWindow": "fri:12:43-fri:13:13", 
            "Engine": "aurora",
            "AssociatedRoles": [], 
            "EarliestRestorableTime": "2017-08-27T08:14:05.625Z", 
            "IAMDatabaseAuthenticationEnabled": false, 
            "ClusterCreateTime": "2017-05-16T
            "EngineVersion": "5.6.10a", 
```

**Comment by cwgem** [comment]
Is this the entire output out of curiosity? I ask because I notice in the [REST documentation](http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBClusters.html) that one entry has aurora and one has aurora5.6.

That said there is an `EngineVersion` property you can pull from so I'm wondering what the specific use case would be to get it off of `Engine` instead.

**Comment by JordonPhillips** [comment]
Looks like the version is right there under `EngineVersion`. If you have any other questions on usage I would recommend asking on StackOverflow or making use of one of our other [community resources](https://github.com/aws/aws-cli#getting-help).

**Comment by sivarohithm** [comment]
My question was, in describe api call i couldn't see cluster version of Amazon Aurora 1.14 or Amazon Aurora 1.13. Please check below link
https://forums.aws.amazon.com/ann.jspa?annID=4864
