### ISSUE TITLE
docker push fails on Docker for Mac with an error "no basic auth credentials"

### ISSUE THREAD

**Issue by yohei1126** [aws/aws-cli#2842]
Hi, I tried to push a docker image to ECR using Docker for Mac. Then I got an error "no basic auth credentials".

## docker info

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 36
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.41-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: moby
ID: SR2O:ICK2:6GBS:LBCT:FMEP:BZPA:Z7OG:6XAP:DMHZ:55KX:FHDN:UJHF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 29
 System Time: 2017-09-14T23:22:42.225546039Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

## what I did

* Created a repository on ECR web console.
* Logged in using `aws ecr get-login --no-include-email --region ap-northeast-1`. It succeeded.
* Tried to push a docker images built locally to the repository but it failed.

## console log

```
$ docker push xx.dkr.ecr.ap-northeast-1.amazonaws.com/kafka:latest
The push refers to a repository [xx.dkr.ecr.ap-northeast-1.amazonaws.com/kafka]
d3a49746dc78: Preparing 
86732a3c9fa2: Preparing 
8eff05291997: Preparing 
4a4be3bbe7b8: Preparing 
1d63b624ee12: Preparing 
64a72f460067: Preparing 
65f2d0254776: Preparing 
e315e40a6a4f: Preparing 
no basic auth credentials
```

## FYI: AWS CLI commands succeeded

```
$ aws ecr describe-repositories 
{
    "repositories": [
        {
            "registryId": "xxx", 
            "repositoryName": "yyyy", 
            "repositoryArn": "arn:aws:ecr:ap-northeast-1:zzzzz:repository/yyy", 
            "createdAt": 1501738101.0, 
            "repositoryUri": "zzzz.dkr.ecr.ap-northeast-1.amazonaws.com/test"
        }, 
        {
            "registryId": "zzzz", 
            "repositoryName": "fr/airflow", 
            "repositoryArn": "arn:aws:ecr:ap-northeast-1:zzzz:repository/fr/airflow", 
            "createdAt": 1485987417.0, 
            "repositoryUri": "zzzz.dkr.ecr.ap-northeast-1.amazonaws.com/fr/airflow"
        }
    ]
}
```

**Comment by dstufft** [comment]
Did you run the command that ``aws ecr get-login`` printed to the console? It doesn't actually log you in, it jus gives you a command that you can use to login.

**Comment by yohei1126** [comment]
Yes, I do it always.

**Comment by joguSD** [comment]
What if you add `https://` to the beginning of the url  you're pushing to?

**Comment by yohei1126** [comment]
How can I do that?

The URI in docker login command starts with `https://`.

```
docker login -u AWS -p xxx https://834215269232.dkr.ecr.ap-northeast-1.amazonaws.com
```

**Comment by yohei1126** [comment]
```
$ docker push https://976801230820.dkr.ecr.ap-northeast-1.amazonaws.com/training/confluent:3.2.0
invalid reference format
```

**Comment by joguSD** [comment]
In your `$HOME/.docker/config.json` file do you have a `credsStore` entry key?

**Comment by yohei1126** [comment]
My config.json is as follows.

```
{
        "auths": {
                "xx.dkr.ecr.ap-northeast-1.amazonaws.com": {},
                "https://xx.dkr.ecr.ap-northeast-1.amazonaws.com": {}
        },
        "credsStore": "osxkeychain"
}
```

**Comment by yohei1126** [comment]
I edited like following, but it still failed.

```
{
        "auths": {
                "https://xxx.dkr.ecr.ap-northeast-1.amazonaws.com": {}
        },
        "credsStore": "osxkeychain"
}
```

**Comment by joguSD** [comment]
What is the output of `docker-credential-osxkeychain version`?
I was able to build and push to an ECR repo using v0.5.2.
https://github.com/docker/docker-credential-helpers/releases/tag/v0.5.2 states that some issues with the OSX keychain were fixed. So you may need to update your docker version and login to your repo again.

**Comment by yohei1126** [comment]
```
$ docker-credential-osxkeychain version
0.5.2
```

**Comment by joguSD** [comment]
Were you able to get this working?
It might be worthwhile to try asking in the related issue on the docker repo: https://github.com/docker/for-mac/issues/1439

**Comment by jamesls** [comment]
Closing due to in activity.

**Comment by yohei1126** [comment]
hi, this issue is not fixed.

**Comment by joguSD** [comment]
Unfortunately, I don't think there's much we can do from this side. As far as I can tell this is a bug with docker. 

Try:
Deleting any `Docker Credential` entries related to AWS in the OS X keychain
Delete any entires related to AWS in the `config.json`.
Re-run the command from `aws ecr get-login`
Try to push again

**Comment by sandakith** [comment]
Having the same issue with newSierra osx and
docker-credential-osxkeychain version 0.6.0

**Comment by stefanverhoeff** [comment]
Had the same error with a `docker pull`. Turns out the ECR was in a different region than where I was logged in. (DOH!)

**Comment by buckmaxwell** [comment]
Had this issue after initially running config w no secret key.  Try deleting the aws line from config.json and re-run aws ecr get-login command.

**Comment by scott2b** [comment]
This is still an issue. Can we get an update?

**Comment by scott2b** [comment]
It turns out this problem can rear itself due to authentication mismatches in various places in your AWS account and your aws cli configs. You will want to be sure the ID part of the ARN for the repository matches the ID of the profile of the user you are using to issue a get-login. If this is not the case and you successfully get a docker login string for the wrong user, you will get this error when Docker uses the wrong credentials to try to push the repository to an endpoint associated with a different ID. If the https endpoint at the end of a `get-login` result does not start with the same ID as your repo arn, then you are not going to be able to push.

Note that, depending on how you are using IAM, it may also be necessary set your ECR IAM policies for the appropriate user or group. If there is an IAM user or group with an ID that matches the ID portion of the repository ARN, then this seems likely to be the case. Note also that the ECR policies do not have "ECR" in their names. Rather, they are variously referred to as "EC2ContainerRegistry" so use "registry" or some such to filter when looking for the policies, not "ECR". And, I don't know if it's needed for the issue at hand, but while I was at it, I also ended up attaching ECS policies.

Things to look at in general when debugging this problem:
~/.aws/credentials
~/.aws/config
~/.docker/config.json (there should be an auth entry with ID that matches the ID portion of the repo arn)
Your Mac keychain: search for "docker". The relevant entry should have an https endpoint that also matches said ID
`aws sts get-caller-identity` can be useful for identifying the current aws cli identity

Besides what the ECR console show you, when issuing a get-login, you may need to include any of the following: `--profile`, `--no-include-email`, `--region`. You may also need to change the resulting http endpoint to an https endpoint according to others.

Finally, to clarify how this all works (to the best of my very limited understanding):
1. In the ECR console, all of your repositories have a shared root arn that has an ID portion that matches either your AWS account ID or possible an IAM ID. If it is an IAM ID then you will need to add appropriate "EC2ContainerRegistry" policies to that user and/or group

2. When you issue the `get-login` it needs to be with the matching profile ID. Use the `--profile` flag if this is not your [default] profile. The resulting docker login command will also have a matching endpoint (the https part of the end of the command string)

3. Furthermore, Docker should be using your keychain for authentication matching, and executing the docker login command that you receive should result in matching entries in ~/.docker/config.json and in your Mac keychain

4. The `docker push` command should work if you got this far

**Comment by eddroid** [comment]
The docker image-uri was was prefixed with my group's `aws_account_id`. I replaced it with my user `aws_account_id` everywhere and `docker pull ...` worked.

**Comment by on0n** [comment]
This tripped me up a bit too. Make sure the **region** you use to log in is the same as the one in your docker image URI.

What fixed for me:

- Delete Mac keychain for "Docker Credentials" and remove any existing aws URLs under `auths` in `~/.docker/config.json`

- If not already tagged, copy the repository URI from AWS ECR console and tag your docker image
e.g. `1234567.dkr.ecr.us-east-1.amazonaws.com/hello-repository:latest`

- Run the aws login command **with the same region specified in your image URI above**
e.g. `aws ecr get-login --no-include-email --region us-east-1` <-- make sure that region matches the one from the previous step! (in your image name)

Then, try pushing the image.

**Comment by abhilashak** [comment]
Before using the push command did you do docker login to AWS from your terminal?
If you are wondering how you can get the login cmd, did you notice that AWS itself generates this command by `aws ecr get-login` this command?

Do `docker login -u AWS -p <hashpassword-from-aws-ecr-cmd>`

and do

`docker push <ecr-repo-url>`

Cheers!

**Comment by mal-mamun** [comment]
As @on0n mentioned in the solution, it was something I missed as well, the region argument:
`aws ecr get-login --no-include-email --region us-east-1` as the default region configured with AWS CLI may be different than the *ECR URL region* that you are trying to push. It saved me an hour of troubleshoot.

**Comment by Voldiemert** [comment]
> Did you run the command that `aws ecr get-login` printed to the console? It doesn't actually log you in, it jus gives you a command that you can use to login.

Wow, considering how many issues I looked at regarding this, you are the only one that mentioned the get-login command doesn't actually login. I was confused on why mine never said "Login Succeded". Not even some AWS I looked at mentioned that.
