### ISSUE TITLE
s3 cp --reqeust-payer

### ISSUE THREAD

**Issue by non7top** [aws/aws-cli#2845]
This option is already supported by 's3 ls' but not for cp which is the most useful command. Please add the support.

works:
$ aws s3 ls --request-payer requester  s3://bucket/

doesn't work:
$ aws s3 cp --request-payer requester  s3://bucket/ /target/

Unknown options: --request-payer,/target/

**Comment by gtseres** [comment]
A similar request has been made [here](https://github.com/aws/aws-cli/issues/797). Try using the `s3api` command and let us know if it fits your needs.

**Comment by dstufft** [comment]
Thanks! As @gtseres mentioned The s3api command might work for you here, but I'm going to go ahead and mark this as a feature request as well.

**Comment by rroscoe17** [comment]
I just ran into another customer that would like the aws -s3 cp --request-payer feature added. so +1 for the request.  They could use s3api but it would involve a lot more work for them to do.

**Comment by aquanyc** [comment]
We really need the --request-payer option to work with S3 instead of just s3api for our clients.  How do we get this moved up the priority list ?

**Comment by jjfarrell** [comment]
This would be a useful feature. It is confusing when you can **aws ls** the bucket file but get an error about the --request-payer argument when copying.

**Comment by nicbor** [comment]
+1

**Comment by aquanyc** [comment]
The AWS "S3" commands like cp, sync should work with "--request-payer" option.

**Comment by finnessyj** [comment]
+1

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by aquanyc** [comment]
UserVoice is for FEATURE REQUESTS.  This is a BUG whereby a command that should work DOES NOT.  It is not a feature.  It was supposed to have been fixed over a year ago and is still NOT FIXED.

What is the point of moving a BUG to a feature request platform ?

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by snavely** [comment]
Any news on this bug fix? According to the AWS documentation (see below), adding --request-payer to "aws s3 cp" should work, but aws-cli does not actually recognize --request-payer as a valid option.

https://docs.aws.amazon.com/cli/latest/reference/s3/ls.html

**Comment by aquanyc** [comment]
It is working but you need the latest version of AWS CLI...upgrade your CLI.

**Comment by snavely** [comment]
You are right -- I was using an old version. Works great!

**Comment by justnance** [comment]
@snavely - Thank you for your feedback.  Closing issue.
