### ISSUE TITLE
Question: aws ec2 wait instance-status-ok and termination

### ISSUE THREAD

**Issue by muhqu** [aws/aws-cli#2849]
Given I launch a new EC2 instance and want to wait for its status to become _ok_. Now, before that happens, the instance terminates. There is no way for the waiter to ever satisfy in that situation. However, it waits until it times out after 10 minutes.
```
aws ec2 wait instance-status-ok --instance-ids i-0123456789abcdef
# waits 10 min… during that time the EC2 instance gets terminated…
Waiter InstanceStatusOk failed: Max attempts exceeded
```

Wouldn't it be possible for a waiter to fail more quickly when it can detect that a condition can no longer be met? e.g. fail with a specific error code, indicating that the condition can not be met.

**Comment by dstufft** [comment]
Hi there! I'm going to go ahead and mark this as a feature request.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by tim-finnigan** [comment]
Hi @muhqu thanks for sharing more info here: https://github.com/aws/aws-cli/issues/1295#issuecomment-955169339. 

I’m trying to think of scenarios where your EC2 instances are getting terminated. Could you expand a bit more on your use case here?

Do you think using the `instance-terminated` wait command would help with what you’re trying to do? https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/wait/instance-terminated.html

**Comment by muhqu** [comment]
I faced the issue when I was launching newly created AMIs that needed to be tested with different instance types. So, basically if there is an issue in the startup scripts of the AMI the instance might fail to start and go straight from launching to terminating while never reaching the running state. So my client code that needed to wait for the instance to become available always reached the timeout (10min) while the instance was terminated within the first minute after launch.

But this issue is not only applicable to EC2. Any finite state (terminated, deleted, etc.) should indicate a waiter that a condition can no longer be met. And it makes sense to fail early in that case instead of waiting for the timeout.

**Comment by tim-finnigan** [comment]
Hi @muhqu, thanks for sharing that information. I see the point that you’re making. Is this issue of quickly terminating instances something that you often encounter? This troubleshooting guide on the topic might be helpful:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/troubleshooting-launch.html#troubleshooting-launch-internal

**Comment by muhqu** [comment]
No, I actually don’t remember when I last started an EC2 instance… it’s been 4years since I filed this feature request. 😄

**Comment by tim-finnigan** [comment]
Hi @muhqu ok I understand! Thanks again for your patience and sorry it has taken so long for us to follow up here. 

I think we can leave this feature request open for now and see if anyone else has anything to add to this topic.
