### ISSUE TITLE
"aws deploy push" suggest wrong command for create-deployment

### ISSUE THREAD

**Issue by ylmrx** [aws/aws-cli#2871]
in the file : ```lib/python2.7/site-packages/awscli/customizations/codedeploy/push.py:161``` : 
```python
s3location_string = (
  '--s3-location bucket={0},key={1},'    
  'bundleType=zip,eTag={2}{3}'.format(
    params.bucket,
    params.key,
    params.eTag,
    version_string
  )
)
```
the ```bundleType``` value should be generated according to ```params.key``` or be ```"[tgz,zip]"```, this was very confusing to my co-worker.
version : ```aws-cli/1.11.56 Python/2.7.12 Linux/4.10.0-35-generic botocore/1.5.19```

**Comment by kyleknap** [comment]
The `deploy push` command only supports zip files for now when it bundles an artifact and sends it to s3. So switching the bundleType will result in the artifact stored in s3 to be processed incorrectly when the deployment is created. I am going to mark this a feature request though to support these alternative bundle types.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
