### ISSUE TITLE
Not possible to set client-request-token to CloudFormation deploy

### ISSUE THREAD

**Issue by ghost** [aws/aws-cli#2907]
When using SAM to create and deploy serverless functions functions cloudformation package and deploy are used.

To be able to create a release history we today use stack notifications and use the ClientRequestToken to distinguish who triggered the release.
There is today no support for client-request-token in cloudformation deploy, as there is in other functions e.g. cloudformation execute-change-set.

Suggest to add support for client-request-token in the deploy function.

**Comment by JordonPhillips** [comment]
@sanathkr 

Seems reasonable!

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
