### ISSUE TITLE
Cannot use double-quote in --metadata

### ISSUE THREAD

**Issue by tim-kos** [aws/aws-cli#2912]
Version:

```
$ aws --version
aws-cli/1.11.165 Python/2.7.10 Linux/3.13.0-61-generic botocore/1.7.23
```

Command:

```
aws s3api put-object --debug --bucket **** --region eu-west-1 --output json --body /srv/current/api2/test/fixture/file/test.png --key foo.jpg --acl public-read --content-type image\/jpeg --metadata 'first=foo\"bar'
```

Fails with:

```
Error parsing parameter '--metadata': Expected: ',', received: '"' for input:
first=foo\"bar
```

Same is true with any combination of quotes, double quotes and escape characters. This is the argument passed to the CLI as per `--debug`:

```
2017-10-19 13:30:07,214 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3api', 'put-object', '--debug', '--bucket', 'testireland.transloadit.com', '--region', 'eu-west-1', '--output', 'json', '--body', '/srv/current/api2/test/fixture/file/test.png', '--key', '756b8efaed084669b02cb99d4540d81f/photos/1/9/d88e4520b4cc11e781776b509b21195e.jpg', '--acl', 'public-read', '--content-type', 'image/jpeg', '--metadata', 'first=foo\\"bar']
```

It looks like it does some escaping itself, but not getting it quite right.

This happen when I do not escape the double quote:

```
2017-10-19 13:34:49,175 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3api', 'put-object', '--debug', '--bucket', 'testireland.transloadit.com', '--region', 'eu-west-1', '--output', 'json', '--body', '/srv/current/api2/test/fixture/file/test.png', '--key', '756b8efaed084669b02cb99d4540d81f/photos/1/9/d88e4520b4cc11e781776b509b21195e.jpg', '--acl', 'public-read', '--content-type', 'image/jpeg', '--metadata', 'first=foo"bar']
```

But the same error happens.

**Comment by tim-kos** [comment]
Also, a different bug:

Equal signs get an extra escaping backslash, whereas commas don't.

```
aws s3api put-object --bucket **** --region eu-west-1 --output json --body foo.jpg --key foo.jpg --acl public-read --content-type image\/jpeg --metadata "caption=Some_ characters / that - might get \= \= \, \\, \\=  rejected to test . \, dfgdfg | dfg"
```

But this is what I get on the S3 web ui:

<img width="553" alt="screen shot 2017-10-19 at 16 51 15" src="https://user-images.githubusercontent.com/15005/31777204-c7677a8e-b4ed-11e7-8375-fc5b99d91f67.png">

**Comment by tim-kos** [comment]
Notice how the commas are dealt with fine, but the equal signs keep their escaping backslash.

**Comment by JordonPhillips** [comment]
The shorthand parser only seems to support escaping commas. You can work around that by providing raw json, like so:

```
aws s3api put-object --bucket foo --key bar --metadata '{"first": "foo\"bar"}'
```

That said, we should really support escaping other characters.

**Comment by DataWanderer** [comment]
Also a different bug.
docker run --env-file=**** --env AWS_DEFAULT_REGION=us-east-1 garland/aws-cli-docker aws emr add-steps --cluster-id j-xxxxxxx --steps Type=CUSTOM_JAR,Name=CustomJAR,ActionOnFailure=CONTINUE,Jar=s3://command-runner.jar,Args=spark-submit,--deploy-mode,cluster,--class,DataMigrationFramework,s3://ha-stage-data-ephemeraldatabasesetup-us-east-1/jars/DataMigrationFramework-1.0-SNAPSHOT-jar-with-dependencies.jar ''\'''\'''

Error parsing parameter '--steps': Expected: '=', received: ''' for input:

**Comment by tim-kos** [comment]
> The shorthand parser only seems to support escaping commas. You can work around that by providing raw json, like so:

Thank you, that worked really well!

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
