### ISSUE TITLE
sizes of downloaded files do not match what is in s3 bucket

### ISSUE THREAD

**Issue by ruddhardesty** [aws/aws-cli#2913]
I have an s3 bucket with 165 files, each one 100 MB in size. They were created from 7-zip, zipping up a large folder structure (the complete Cygwin download) specifying to split it into 100 MB pieces.  I can view the s3 bucket via a browser and it shows all the files, and the sizes are listed at 100 MB.

When I use "aws s3 sync" to download them locally, they all appear on my windows 10 machine as 196 MB files (specifically, 200,704 KB as shown in Windows Explorer).

If i download just a single file from S3 using chrome, it downloads as 100 MB.

Any idea what might be going on?  Is sync adding some extra data to each file?  I have not tried this with "cp" yet.  I might start that on another system to see what happens.

Edit:  "cp" did the same thing for a single file downloaded

aws-cli/1.11.28 Python/2.7.9 Windows/8 botocore/1.4.85

**Comment by JordonPhillips** [comment]
Does this happen with any other size file? Are you modifying the files while you're downloading them? If you use `aws s3api get-object --bucket mybucket --key mykey` do you still experience the issue?

**Comment by ruddhardesty** [comment]
Hi - I have not tried with other files.  I updated my version of the aws-cli to the latest, as of today, hoping that would fix it,  But now I am stuck with error:

fatal error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

or if i pass in the "--no-verify-ssl" option, I get:

An error occurred (SignatureDoesNotMatch) when calling the GetObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.

So i've been spinning my wheels trying to get those resolved (no luck) before I can get back to trying to download again.

did try the "aws s3api" command above, but i am not sure i have the right format for the "bucket".  Is this the "s3://bucketname/path/filename" format?

**Comment by JordonPhillips** [comment]
The s3api commands don't take the s3 paths in the same way. Instead of `s3://bucketname/path` you have `--bucket bucketname --key path`. I'm not sure what the SSL issue is. Could you post some `--debug` logs so I can get an idea of what's going on?

**Comment by ruddhardesty** [comment]
Hi - i went back to version 1.11.28, so i could get back to a point of getting the double-size download.  The debug log is quite lengthy - i've zipped it up and attached it to this issue.  This is from running the command:

aws s3 cp s3://bucketname/username/cygwin-2.9.0-win32-full-download.7z.001 cygwin-2.9.0-win32-full-download.7z.001 --debug --no-verify-ssl > debug.log 2>&1

Screen shots showing size of files from S3 via the chrome browser (top), and after download (bottom).  
![from-browser](https://user-images.githubusercontent.com/8784147/31963390-52ba6734-b8b5-11e7-994b-0530bf4c2cb2.PNG)
![after-copy](https://user-images.githubusercontent.com/8784147/31963395-56747c7a-b8b5-11e7-96c9-28640f1e3961.PNG)

[debug.zip](https://github.com/aws/aws-cli/files/1412343/debug.zip)

**Comment by joguSD** [comment]
Thanks for the debug logs. Just from a quick once over there are definitely some odd things going on in the debug logs. It's gonna take some more digging to see what the actual issue is.

How did you go about installing the CLI? If you haven't, could you try using a version of the CLI installed via an MSI? http://docs.aws.amazon.com/cli/latest/userguide/awscli-install-windows.html#install-msi-on-windows

**Comment by joguSD** [comment]
After looking through the debug logs the only thing I can really discern is that we continue submitting `IOWriteTasks` well after the actual size of the file. The other odd thing is that it claims to have done 1.3GiB/100MB. 

Were you ever able to try this using the `s3api` command? Also were you able to successfully update your CLI version?

**Comment by ruddhardesty** [comment]
Hi - the CLI was installed using the MSI files.  1.11.28 originally, then the upgrade to the latest, both with the MSI file installation.  When I down-graded to 1.11.28, I used the zip file re-downloaded from the site, as I couldn't find the MSI file any more.

I was not able to s3api command to work, although I didn't try all that hard.  I've since downloaded all 165 files using the browser.

**Comment by jamesls** [comment]
Hi, just wanted to circle back on this issue and give more info on the behavior
you're seeing.

The debug logs you've provided were helpful and we were able to see what's
going on.  In summary, it appears that there is some intermediary process
(likely a proxy of some sort) that appears to be removing the `Range` header in
our `GetObject` requests.  This is generating the odd behavior you're seeing.

This also explains the behavior you're seeing in your comment
[here](https://github.com/aws/aws-cli/issues/2913#issuecomment-338215437).
Specifically:

1. You're getting an SSL error because you're not getting the
   actual SSL cert for S3.  This is likely a proxy that's intercepting the
   request.
2. When you turn off SSL cert validation, you get a signature error.  The
   signature type being used in later versions of the CLI use sigv4, and
   part of that signature includes signing all the headers.  This means
   that if something were to remove a header, the signature wouldn't
   validate.  This is the second behavior your were seeing.

Downgrading to an earlier version of the CLI changed the behavior for you
(the double size download).  This is because in older versions of the CLI,
the default signature version for S3 was `s3`, or `HmacV1Auth`.  When requests
are signed using this signature version, headers are *not* signed.  This means
this signature cannot detect if something removes headers from the request.
So essentially you're seeing the weird behavior and corrupted files because
the requests are being altered.  We can also confirm this by looking at the
HTTP responses in your debug logs.  Normally, when you send the `Range` header
as part of the `GetObject` request you should see these HTTP response headers:

```
Making request for OperationModel(name=GetObject) (verify_ssl=True) with params: {
  'body': '',
  'url': u'https://s3.us-west-2.amazonaws.com/bucket/key',
  'headers': {u'Range': 'bytes=0-1000', ...}
  ...

Response:

Response headers: {
  'content-length': '1001',
  'content-range': 'bytes 0-1000/227997',
  ...
}
```

Note that:

1. The `content-length` matches the length of the `Range` we requested, `1001`
   bytes.
2. We also get a `content-range` header returned.

However, here's one of the responses from your attached debug logs:

```
Making request for OperationModel(name=GetObject) (verify_ssl=False) with params: {
  'body': '',
  'url': u'https://s3-us-west-1.amazonaws.com/bucketname/username/cygwin-2.9.0-win32-full-download.7z.001',
  'headers': {u'Range': 'bytes=8388608-16777215', ...}


Response headers: {
  'content-length': '104857600',
  'x-amz-id-2': '...',
  'accept-ranges': 'bytes',
  'server': 'AmazonS3',
  'last-modified': 'Wed, 18 Oct 2017 19:49:04 GMT',
  'connection': 'Keep-Alive',
  'etag': '"4346036bede1ccff815446928c33002b-7"',
  'x-amz-request-id': '607D2BAF7EED136B',
  'date': 'Tue, 24 Oct 2017 16:44:59 GMT',
  'content-type': 'application/x-www-form-urlencoded; charset=utf-8'
}
```

Notice here how the `content-length` does not match up to the `Range` size we
requested (`(16777215 + 1) - 8388608 == 8 MB`), and there's no `content-range`
header.  This also suggests that this is a response to a `GetObject` request
with no `Range` header provided.

Let me know if you have any more questions.
