### ISSUE TITLE
emr create-default-roles adds entries to config (and shouldn't)

### ISSUE THREAD

**Issue by eikenb** [aws/aws-cli#2915]
Every time I setup a new account with the default emr roles using `aws emr create-default-roles` it adds an emr entry to my .aws/config file for that profile. I don't like things automatically messing with my config in general and I don't want those entries in this specific case and have to go in and remove them each time.

Please either remove this feature or provide an option to disable it.

Thanks.

**Comment by JordonPhillips** [comment]
I think having a `--no-create-profile` flag would be a good thing, marking as a feature request.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
