### ISSUE TITLE
`aws cloudformation deploy` "strict" parameters mode

### ISSUE THREAD

**Issue by btisdall** [aws/aws-cli#2940]
I don't whether I'm alone in this, but IMO silent use of current stack state to provide missing parameter values during updates is an infrastructure as code anti-pattern. Infrastructure updates should be declarative in nature, using either defaults from the infrastructure code or values explicitly provided on the command line/in a parameters file.

I therefore propose a mode called something like `--strict-parameters` which would provide `aws cloudformation update`-like semantics, failing unless every parameter lacking a template default is provided or `UsePreviousValue` is explicitly requested.

**Comment by dstufft** [comment]
Flagging this as a feature request for the cloudformation/deploy code. Thanks!

**Comment by btisdall** [comment]
This looks like it would be reasonably easy to do, I shall have a go...

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
