### ISSUE TITLE
envsubst for ssm?

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-cli#2950]
Is there an `envsubst` utility for filling in secret variables from AWS parameter store aka ssm aka where I'm storing my organisation's secrets? https://s.natalian.org/2017-11-10/1510284612_2558x1406.png

For example:
`aws ssm get-parameters --names MYSQL_PASSWORD --with-decryption --query Parameters[0].Value` is a little cumbersome to say the least!

**Comment by joguSD** [comment]
This sounds useful, marking as a feature request.

**Comment by mithun** [comment]
@kaihendry checkout [ssm-env](https://github.com/remind101/ssm-env)

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
