### ISSUE TITLE
Support for querying what region a service support or what services a region support

### ISSUE THREAD

**Issue by etsangsplk** [aws/aws-cli#2957]
We have this table:
https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/

It is highly useful to add query to do this on the cli level.

e.g I want to see what regions support EFS ...

**Comment by kyleknap** [comment]
Makes sense to me. We have this functionality exposed in `botocore` so all we would need to do is plumb it through to the CLI.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
