### ISSUE TITLE
Cannot get all version of lambda function using lambda list-versions-by-function

### ISSUE THREAD

**Issue by KrzysztofWilczek** [aws/aws-cli#2965]
It appears that when I run 
`aws lambda list-versions-by-function --function-name xyz`
I cannot get more than 50 version of my lambda (while I have right now over 60) 
I found parameter for this method like --max-items and I've set it to 100. And still only 50 version are in response. So I'm unable to get all version of my lambda function.
What's more, this limitation for 50 elements isn't described on http://docs.aws.amazon.com/cli/latest/reference/lambda/list-versions-by-function.html

Can you please assist on this issue?

**Comment by kyleknap** [comment]
My guess is 50 is the hard limit for the max items returned right now by the API. So what you will have to do to get the remaining versions is to use the `NextMarker` value from the output and feed that into the `--marker` parameter to get the remaining 10 versions.

It looks like we need to add a paginator for this in this [model](https://github.com/boto/botocore/blob/develop/botocore/data/lambda/2015-03-31/paginators-1.json) to automatically paginate over the responses from the `ListVersionsByFunction` API. Feel free to submit a pull request to add the paginator. Otherwise, we will get around to adding it.

Let us know if that helps.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by mputilin** [comment]
+1 to feature request

**Comment by tim-finnigan** [comment]
It looks like a paginator was added [here](https://github.com/boto/botocore/blob/develop/botocore/data/lambda/2015-03-31/paginators-1.json) for `ListVersionsByFunction`. In the [documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/list-versions-by-function.html) it also now says:


> Returns a list of versions , with the version-specific configuration of each. Lambda returns up to 50 versions per call.


So 50 is the limit but you can use pagination to access more versions. 

Here is the documentation for using pagination with the CLI: https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html
