### ISSUE TITLE
Support `help` command conventions (`-h/--help` or `aws help <command/service>`

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-cli#303]
Most developers are familiar with `git help commit`.

Not `aws s3 help` which is jarring.

**Comment by mfowlewebs** [comment]
Most developers are familiar with `-h` and `--help`. Help subcommands is kind of a new thing, seen in subcommand centric software. I'd go for `-h`/`--help` not saying `aws: error: too few arguments` before this.

**Comment by mtdowling** [comment]
I'm :+1: on adding `-h/--help`. We will discuss this on the CLI team.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by adamchainz** [comment]
What if it's not the morning in my timezone? That's rather presumptuous :)

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by tim-finnigan** [comment]
For future reference, some ideas related to this were also mentioned in https://github.com/aws/aws-cli/issues/7629. Thanks @calebstewart for the suggestions [here](https://github.com/aws/aws-cli/issues/7629#issuecomment-1414234380) and [here](https://github.com/aws/aws-cli/issues/7629#issuecomment-1414236669). If the help convention doesn't change I think at least the default message when using `-h/--help` should point users to the existing `help` command (https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-help.html#cli-usage-help-command).

**Comment by tim-finnigan** [comment]
Now that https://github.com/aws/aws-cli/pull/7765 has merged, the output when running `aws --help` is:

```
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: the following arguments are required: command
```
This error message is more helpful, as it corresponds to the [documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-help.html#cli-usage-help-command) referenced above. (The previous behavior is described here: https://github.com/aws/aws-cli/issues/7754). Although the original issue here was to support `--help` rather than `help`, I don't think that can be considered until the next major version of the CLI, which would not be for some time. So I think it's something to revisit down the line, and for now the `help` command can be used to get more information at those three levels (`aws help`, `aws <command> help`, `aws <command> <subcommand> help`).
