### ISSUE TITLE
progress bar UI for s3 copying

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-cli#312]
So I can have an idea how my transfer is doing please

**Comment by ciphertxt** [comment]
If you're in higher latency parts of the world where connectivity isn't great (e.g. Australia), not having the progress output appear until after the first 5 MB is insufficient. I regularly upload 100 MB files from Sydney to an S3 bucket in the East US and it's beyond frustrating to have no output from the CLI. 

__Expected behavior:__
1. Upload a file from the CLI with *aws s3 cp s3://bucket/file.ext* 
2. View file progress/output as soon as the command executes

__Current behavior:__
1. Upload a file from the CLI with *aws s3 s3://bucket/file.ext* 
2. Sit at an empty terminal for extended periods of time

The current behavior leads to a poor interaction and negatively impacts the experience of the *aws s3* sp command. Would it be possible to reopen and address this?

**Comment by pastafari** [comment]
:+1: from India - uploads are really slow. Some indication of progress - not necessarily a bar, just the fact that an upload is taking place - would be great!

**Comment by ArashJalalian** [comment]
Can you reopen this please? From Australia and having the same problem.

**Comment by betesh** [comment]
+1

**Comment by mcasto** [comment]
I just found a solution for myself for this problem. I changed the AWS CLI S3 configuration. Details for doing so can be found here: http://docs.aws.amazon.com/cli/latest/topic/s3-config.html

I set:
max_concurrent_requests = 5 (this prevents timeouts due to hogging bandwidth, probably not necessary for most people)
multipart_threshold = 1MB
multipart_chunksize = 1MB

By setting the threshold & chunksize to 1 MB, it starts chunking pretty quickly. Of course, you could set it for something even smaller. Then, by piping the output to a file, you can easily determine the progress.

The chunked output looks like "Completed 473 of 477 part(s) with 1 file(s) remaining"

For my purposes, wanting a graphical progress bar, I wrote a script to read the output file, find the last line, and parse the (in my example above) 473 & 477. From there, it's a simple matter to find percent complete and send that to my graphical progress bar.

**Comment by mcasto** [comment]
Well ... nuts. As I wrote the previous post, I was running a test, and everything seemed to be humming. Shortly after I finished the previous post, I got an error (EntityTooSmall) because the final chunk was smaller than the minimum allowed size. Now I'm looking into either changing minimum allowed size or, if it can't be changed, finding out what it is and setting my multipart_chunksize accordingly.

**Comment by mcasto** [comment]
Ah. Well. It appears 5MB is the minimum allowable size for multipart upload. So this is a dead end for providing any sort of feedback in a timely manner over a slow connection. Sorry if I got anyone's hopes up.

**Comment by fredericofs** [comment]
Can we use pv (pipe viwer) command line tool for this?

**Comment by andybergon** [comment]
The total parts number displayed even on slow connections would be very useful!

+1

**Comment by enissay14** [comment]
+1

**Comment by fro** [comment]
Agree, It could be helpful.

**Comment by psihodelik** [comment]
+1

**Comment by aussiDavid** [comment]
+1

**Comment by attaboy** [comment]
+1

**Comment by adamatan** [comment]
+1
Uploading from Israel. Waiting for the first 5Mb can take a long time.

**Comment by sebastianvera** [comment]
+1

**Comment by adamatan** [comment]
We can use the rsync progress bar format - both the CLI parameter `--progress` and the nicely-built percentage and size preview.

<img width="634" alt="screen shot 2016-07-18 at 4 05 52 pm" src="https://cloud.githubusercontent.com/assets/1014189/16915687/941ffeee-4d01-11e6-9fbf-9353f8fd63f7.png">

**Comment by daniel-ro** [comment]
+1

**Comment by shamank** [comment]
+1 This is really necessary. I'm uploading 5 GB to S3 and I don't know what's comming on since I'm stuck at package X of N with a poor internet connection... and don't blame the connection!

**Comment by jrmiller82** [comment]
+1 This is necessary. Don't know why the issue is closed.

**Comment by avinash** [comment]
+1 I agree. A progress bar is essential when syncing or copying data from different parts of the world. I routinely transfer data from Singapore to the East Coast and sometimes it's difficult to understand what is happening...

**Comment by adamatan** [comment]
This can easily be done using boto3 (I have written my own 'aws s3 cp' clone just for the sake of having a progress bar).

**Comment by pehcha** [comment]
+1 I agree this is absolutely necessary for such a common tool.

**Comment by shockey** [comment]
+1.

**Comment by jrmiller82** [comment]
+1 again. :)

**Comment by toshke** [comment]
+1

**Comment by davidrabinowitz** [comment]
+1, amazing a progress bar is missing from such action which may be lengthy

**Comment by venkatd** [comment]
+1 here too. Not sure why this isn't implemented yet.

**Comment by davidrabinowitz** [comment]
I have open a new issue (#2269) for raising this, as it seems this issue will remain close. I would appreciate it if everyone who had +1'ed this issue will do the same for the new one so we can get this going.

**Comment by andyfowler** [comment]
This appears to be mostly [addressed in 1.11.0](https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst#1110), (with improvements in subsequent versions). 
![image](https://cloud.githubusercontent.com/assets/107073/20022485/3404db78-a2b1-11e6-8178-7177dae6b64c.png)

**Comment by adamatan** [comment]
Yup. About time.
