### ISSUE TITLE
run-instance from launch template failed as launch template had network type as Classic

### ISSUE THREAD

**Issue by DuyNguyen152** [aws/aws-cli#3120]
An existing instance was running in VPC. Run following commands to get its data for creating a new launch template with same parameters

iid=`echo $(aws ec2 describe-instances --filter Name=tag:Name,Values=xxx-xxx --query 'Reservations[].Instances[].[InstanceId]' --output text)`

aws ec2 get-launch-template-data --instance-id $iid --query 'LaunchTemplateData' --output json > instance-data.json

Create a new launch template successfully
aws ec2 create-launch-template --launch-template-name TemplateName --version-description Version1 --launch-template-data file://instance-data.json

But when launch a new instance from the template, it was failed
ltid=$(aws ec2 describe-launch-templates --query "LaunchTemplates[*].{ID:LaunchTemplateId}" --filters Name=launch-template-name,Values="TemplateName" --output text)

aws ec2 run-instances --launch-template LaunchTemplateId=$ltid

The error is reproduced on GUI with same error description: "Value (1) for parameter QueryStringParameter is invalid. Invalid or illegal XML character specified"

The root cause is Network Type was set as Classic in the template instead of VPC as expected. 

How can I switch from Classic to VPC? Either creating a new launch template version or re-getting launch template data with correct network type?

Appreciate for any help!
Thanks.

**Comment by kyleknap** [comment]
I am not too familiar with the in's and out's of launch templates, but you would probably want to do both so:

1) Find an instance that is not launched in Classic and is instead in a Vpc and determine what the template data is
2) Determine what the differences are between the launch template that used classic and the one that used vpc
3) Change the template running in classic accordingly so it matches what the Vpc configuration has and create a new template and launch the instance with that template.

Let us know if you have any questions. Otherwise, I would recommend reaching out to StackOverflow or the AWS Developer forums as there will probably be individuals that can provide further help.
