### ISSUE TITLE
Granting s3 permissions to aws groups

### ISSUE THREAD

**Issue by dopey** [aws/aws-cli#3128]
According to the documentation for `aws s3 cp`:

    ...
    --grants (string)
        Grant specific permissions to individual users or groups. 
    ...

The documentation goes on to say that I can use ID's to specify the grantee.

So, I get my group id using `aws iam get-group --group-name <my-group>`, and then i try to use the cp command like `aws s3 cp <my-object> s3://<my-bucket> --grants full=id=<my-group-id>` and i get: 
    An error occurred (InvalidArgument) when calling the PutObject operation: Invalid id

I try using `aws s3api put-object-acl` and i get the same result. Not sure what i'm doing wrong.

**Comment by kyleknap** [comment]
I would recommend checking this previous GitHub issue out: https://github.com/aws/aws-cli/issues/2651

So the ID that you are getting back from `iam get-group` is not the ID that you want to use when setting grant ID's for S3. There is a link to figure out how to get the user ID in the issue. However, I am not sure if it is possible to set a grant using a specific group that you own. The reason the description says groups is because you can set permission for predefined groups: https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html such as authenticated users or all users (even anonymous ones). I think if you want to set permissions to a specific IAM group you will most likely need to set up a bucket policy.

Let us know if you have any more comments/questions.

**Comment by joguSD** [comment]
Closing out due to inactivity.

**Comment by dopey** [comment]
got it. appreciate the help :)
