### ISSUE TITLE
S3 CP Failing to convert invalid characters when creating windows folders

### ISSUE THREAD

**Issue by Ray-B** [aws/aws-cli#3130]
**Version Info**
`aws-cli/1.14.33 Python/3.6.2 Windows/10 botocore/1.8.37`

**Command Run**
`aws s3 cp s3://super-great-bucket/logs/ . --recursive --exclude "*" --include "*\bootstrap.log"`

**Expected Result**
Copy N number of logs to the local filesystem nested inside of timestamped folders (prefix).

**Actual Result** 
Command fails silently with no output. 
Run-run command with _--debug_.

> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\s3transfer\tasks.py", line 248, in _main
>     on_queued_callback()
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\awscli\customizations\s3\utils.py", line 697, in on_queued
>     "Could not create directory %s: %s" % (d, e))
> awscli.customizations.s3.utils.CreateDirectoryError: Could not create directory C:\Development\Temp\consul\**2017-11-22T23:46:21.2160728+00:00**: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Development\\Temp\\consul\\2017-11-22T23:46:21.2160728+00:00'

**Comments / Workaround**
It looks like the underlying code isn't correctly converting characters in the prefix to be windows-safe. I re-ran this command on my ubuntu box, zipped up the results, and extracted them to windows as a work-around.

**Comment by kyleknap** [comment]
Hmm. So I can see how this problem could arise. Unfortunately, I do not think there would be a great story to have this be solved automatically. Specifically, take the scenario when you want to download a directory and then reupload the same directory. If we were to convert the underlying characters automatically, it would be ambiguous when the CLI reuploads it to S3 as the CLI would unable to determine if the character was automatically converted or was not and therefore would not be able to roundtrip correctly one hundred percent of the time. I think in order to support something like this we would need to add a flag to do the character conversions.

The other problem though is that the CLI is not raising a warning for this issue and is not returning a nonzero rc. I want to do some investigation on this to see what our options are, but at least we should warn and return a nonzero rc if this is the case.

**Comment by repl-raymond-bolander** [comment]
Agreed on your first point, in so far as it is assumed that the CLI has a duty to prevent that, as opposed to a just a duty to warn about it. I'm not sure what the general convention is, but when a tool's only job is to "take this one thing, and put it there", it makes sense to do it implicitly, otherwise what good is the tool.

Middle ground would be to have the _option_ to convert, through a flag, with or without warnings, but implicitly _not convert_, to avoid any compatibility issues.

**Comment by Ray-B** [comment]
Agreed on your first point, in so far as it is assumed that the CLI has a duty to prevent that, as opposed to a just a duty to warn about it. I'm not sure what the general convention is, but when a tool's only job is to "take this one thing, and put it there", it makes sense, in theory to do it implicitly, otherwise what good is the tool, right?

Practically speaking though, it would probably be better to have the _option_ to convert, through a flag, with or without warnings, but implicitly _not convert_, to avoid any compatibility issues.
