### ISSUE TITLE
Cannot run the command with eval if character space in a arguement

### ISSUE THREAD

**Issue by git5135** [aws/aws-cli#3142]
If run following command, everything is fine:
  **aws ec2 authorize-security-group-ingress --group-name 'Test - Huizhou' --protocol tcp --port 81 --cidr 199.106.64.0/24 --region us-west-2**

But if run the above command within eval, issue happens:
  **eval aws ec2 authorize-security-group-ingress --group-name 'Test - Huizhou' --protocol tcp --port 81 --cidr 199.106.64.0/24 --region us-west-2**

The error message is:

**usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
  To see help text, you can run:

    aws help
    aws <command> help
    aws <command> <subcommand> help

  Unknown options: Huizhou', -**

The aws version is:
 **aws-cli/1.11.29 Python/2.7.12 Linux/4.4.35-33.55.amzn1.x86_64 botocore/1.4.86**

Thanks,
Huizhou

**Comment by jamesls** [comment]
This isn't an AWS CLI specific bug, this is just something you have to account for in your shell.  The quotes are used to denote arguments, but are subsequently stripped when passed to the underlying program.  You can see the same effect if you use `echo` instead of `eval`.  Note:

```
$ echo aws ec2 authorize-security-group-ingress --group-name 'Test - Huizhou' --protocol tcp --port 81 --cidr 199.106.64.0/24 --region us-west-2
aws ec2 authorize-security-group-ingress --group-name Test - Huizhou --protocol tcp --port 81 --cidr 199.106.64.0/24 --region us-west-2
```

Notice how the quotes are gone.  To fix this, you'll want to escape the quotes so they're preserved for the `eval` command:

```
$ eval aws ec2 authorize-security-group-ingress --group-name \'Test - Huizhou\' --protocol tcp --port 81 --cidr 199.106.64.0/24 --region us-west-2
```
