### ISSUE TITLE
Listing S3 bucket takes over 30 seconds with CLI but under 1 second with python/boto

### ISSUE THREAD

**Issue by brentstrong** [aws/aws-cli#3203]
I spent some time today working with a support rep to troubleshoot this and he escalated to the CLI team as well as recommending I post here. 

When attempting to list one of our buckets we see very poor performance using 

aws s3 ls s3://<bucketname> - this takes approximately 30 seconds to return
aws s3api list-objects-v2 --bucket <bucketname> - this never returns

When doing the same thing using boto3 and python we get instant results.
import boto3
session = boto3.Session(profile_name="<removed>")
client = session.client('s3')
print client.list_objects_v2(Bucket="<bucketname>")

We do, however, see poor performance in the browser when viewing the root level of the bucket using the AWS console. 

Version info: aws-cli/1.14.50 Python/3.6.4 Darwin/16.7.0 botocore/1.9.3

**Comment by kyleknap** [comment]
@brentstrong This is because the CLI automatically paginates this for you. However, `boto3` does not, but if you use the [pagination interface](https://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Paginator.ListObjectsV2) from Boto3 you should be able to see the same performance as both are trying to retrieve all of the objects in your bucket. Hope this helps!
