### ISSUE TITLE
aws elbv2 describe-listener-certificates

### ISSUE THREAD

**Issue by prensoni0143** [aws/aws-cli#3260]
as said here:https://docs.aws.amazon.com/cli/latest/reference/elbv2/describe-listener-certificates.html

$ aws elbv2 describe-listener-certificates --listener-arn arn:aws:elasticloadbalancing:ap-southeast-1:415204155249:loadbalancer/app/SGE1PRDGDMWEB-W-ELB/71c13eb61264c03e

An error occurred (ValidationError) when calling the DescribeListenerCertificates operation: 'arn:aws:elasticloadbalancing:ap-southeast-1:415204155249:loadbalancer/app/SGE1PRDGDMWEB-W-ELB/71c13eb61264c03e' is not a valid listener ARN

However I can find ARN is correct and also in console I can see certificate, so what could be the issue?

**Comment by stealthycoin** [comment]
Hi, I would suggest contacting [AWS Support](https://console.aws.amazon.com/support/home#/) with this question since that is an error coming from the service and they would be able to provide you with more assistance. The CLI just calls the API and reports back the answer, we don't have any more visibility into this than you do. Let us know if you have an issue with the CLI itself. I would also suggest when you contact support to give them debug logs that you can get by adding `--debug` to the CLI command.

**Comment by prensoni0143** [comment]
Thanks a lot
