### ISSUE TITLE
Improve error reporting of cloudformation validate-template

### ISSUE THREAD

**Issue by sgronblo** [aws/aws-cli#3361]
When running CF validate-template I might get an almost useless error message like:

`An error occurred (ValidationError) when calling the ValidateTemplate operation: Invalid template resource property 'Name'`.

At this point my template is pretty small so I can probably find it eventually by manually reviewing the template. However, with a larger template, this is going to hurt productivity.

This should at least show a line and column number or resource name to speed up debugging.

**Comment by kyleknap** [comment]
So the error that is getting reported is being generated by CloudFormation. The CLI is only displaying the error returned by the service. So unfortunately the CLI does not have really any context in terms of where in the template the issue is occurring. Really the only option would be if CloudFormation returned this information in the error it returns back. So I would recommend posting in the [forums](https://forums.aws.amazon.com/forum.jspa?forumID=92) or contacting AWS Support to request this feature from CloudFormation. Once this information is exposed from the API then it should be automatically picked up and displayed by the CLI.

**Comment by sgronblo** [comment]
I see. After starting to dig in to the source a bit I started realizing that it might be that it's the CloudFormation API that returns the error. Thanks for your input.
