### ISSUE TITLE
Request: aws rds copy-db-snapshot --target-region

### ISSUE THREAD

**Issue by daytonpa** [aws/aws-cli#3362]
So far the `aws rds copy-db-snapshot` command supports a `--source-region` flag for identifying the region the snapshot is stored, and you can add the snapshots ARN if you're in a different region, but there isn't a `--target-region` feature if you want to copy a snapshot from us-east-1 to us-west-1 if your default region is also us-east-1.  I know this can all be performed through the console, but automating snapshot copies via the CLI would be a sweet addition.  

It would be nice to have a command be something similar to:
```
aws rds copy-db-snapshot \
  --source-db-snapshot-identifier <full_arn_of_rds_snapshot> \
  --target-db-snapshot-identifier my_snapshot \
  --target-region us-west-1
```
OR send a copy to multiple regions
```
aws rds copy-db-snapshot \
  --source-db-snaphot-identifier source_snapshot \
  --target-db-snapshot-identifier new_snapshot \
  --source-region us-east-1 \
  --target-region us-west-1,ap-northeast-1
```

AWS CLI version:
aws-cli/1.15.34 Python/2.7.12 Linux/4.13.0-43-generic botocore/1.10.34

**Comment by kyleknap** [comment]
@daytonpa the region that you have configured will be the region that the DB snapshot gets created in according to the [documentation](https://docs.aws.amazon.com/cli/latest/reference/rds/copy-db-snapshot.html). So essentially the `--region` parameter is a `--target-region` parameter. For example:
```
aws rds copy-db-snapshot \
  --source-db-snapshot-identifier <full_arn_of_rds_snapshot> \
  --target-db-snapshot-identifier my_snapshot \
  --region us-west-1
```
should ensure that the DB snapshot is created in `us-west-1`.

 As to copying to multiple regions, this should be capable by calling the `copy-db-snapshot` command multiple times and changing the value to `--region`. Furthermore, the RDS API does not really expose a mechanism to copy to multiple regions in a single API call and since CLI commands are a strict 1:1 mapping of the AWS service's API, RDS would need to expose that functionality through its API.

Let us know if that helps or if you have anymore questions.

**Comment by daytonpa** [comment]
I have tried that command, but I am beginning to wonder if it is due to the snapshot being encrypted.  This is the most recent command I have been running:
```
aws rds copy-db-snapshot \
    --source-db-snapshot-identifier <full_arn_of_rds_snapshot_in_east> \
    --target-db-snapshot-identifier my_snapshot_west \
    --kms-key-id <key_id_in_east> \
    --region us-west-1
```
and it returns:
```
An error occurred (InvalidParameterValue) when calling the CopyDBSnapshot operation: PreSignedUrl could not be authenticated.
```
I've read the docs, but maybe I am missing something?

**Comment by justnance** [comment]
@daytonpa - Thank you for your feedback.  Yes, the snapshot being encrypted is a factor.  Based on the snippet it appears the `kms-key-id` is located in one of the "east" regions while the target region is `us-west-1`.   As per our [documentation](https://docs.aws.amazon.com/cli/latest/reference/rds/copy-db-snapshot.html), "_if you copy an encrypted snapshot to a different AWS Region, then you must specify a KMS key for the destination AWS Region. KMS encryption keys are specific to the AWS Region that they are created in, and you can't use encryption keys from one AWS Region in another AWS Region._".  There is more information on how to [copy an encrypted RDS DB snapshot ](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CopyDBSnapshot.html)posted online.
