### ISSUE TITLE
aws s3 sync on Windows wrongly sets Content-Type to text/plain for js files

### ISSUE THREAD

**Issue by niwsa** [aws/aws-cli#3367]
I have a linux build server where the s3 sync works as expected setting the Content-Type to application/javascript.But coming to windows server 2012 it does not work.

**Comment by Kralizek** [comment]
I got the same issue again.

I created a simple Angular application, built in production mode, used the cli to sync the artifacts with a bucket. All the JS files had conte-type set to text/plain.

**Comment by ggallotti** [comment]
Same problem here.
Created an Angular Ap.p. Used aws cli s3 sync and all files have text mimetype.

**Comment by arpanmkjee** [comment]
same issue here

**Comment by moznuy** [comment]
Same issue here.
On Windows mime types are all text/plain.
On Linux it works as expected.

**Comment by moznuy** [comment]
Ok, so the problem probably lies even deeper.

So based on this:
[Python mimetypes](https://docs.python.org/3.9/library/mimetypes.html#mimetypes.init)
> on Windows, the current registry settings are loaded

And this [implementation](https://github.com/python/cpython/blob/faff81c05f838b0b7a64bbc8c53c02a9b04bb79d/Lib/mimetypes.py#L232)

It looks at `HKEY_CLASSES_ROOT\.js` in case of JS file. (Cached version of it).
So the problem in my case is that in `HKEY_CLASSES_ROOT\.js` Key `Content Type` Value is equal to `text/plain`. I don't know if it is the default value, or this value is set by any of the installed programs.

**Comment by Rastamas** [comment]
Quick and easy workaround if you don't want to (or can't) change the registry value is just to upload js files separately.
```
aws s3 sync <LocalPath> <S3Uri> --exclude `"*.js`" --delete
```
then
```
aws s3 sync <LocalPath> <S3Uri> --exclude `"*`" --include `"*.js`" --content-type application/javascript
```

**Comment by xsalazar** [comment]
Wow @moznuy you're spot on. I was struggling with this exact issue with Terraform running some local-exec blocks to copy files between S3 buckets. The files would be transferred over, but suddenly every `.js` file had its Content-Type rewritten from the original value in the original file. I tried every combination of `--metadata`, `--metadata-directive`, `--no-guess-mime-type` and I could not figure out why this was failing. Cutting out Terraform and running the AWS CLI directly changed nothing. I tried a similar approach to @Rastamas, but we were using the additional `--metadata-directive REPLACE` tag that forces AWS to only apply the metadata values passed in through the CLI.

Ended up being the incorrect Registry value. I can only guess that installing some editor or changing the default editor for `.js` files in Windows somehow corrupted this key. The commands worked in almost all other scenarios since we spin up fresh images, but my local machine was totally wrong.

**Comment by odyth** [comment]
It seems aws cli pulls the content type from HKEY_LOCAL_MACHINE\Software\Classes\.js and for me on windows server 2016 this was set to text/plain. Interestingly though HKEY_CLASSES_ROOT\.js was set to application/javascript. Changing HKEY_LOCAL_MACHINE\Software\Classes\.js to have a content type of application/javascript resolved the issue for me.

**Comment by bradisbell** [comment]
Seems like the current issue can be found here:  https://github.com/aws/aws-cli/issues/1249

**Comment by jarrodlilkendey** [comment]
I'm running into this issue today using aws s3 sync to upload a built vite app to an s3 bucket.

It sets the MIME type for javascript files to "text/plain" resulting in the following error in the web console, preventing the website from loading.

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by AmineC95** [comment]
I have the same issue as @jarrodlilkendey have you found any solution ?

**Comment by jarrodlilkendey** [comment]
Hi @AmineC95 , I had to use this workaround because this still hasn't been fixed.

aws s3 sync ./dist s3://vite-household-management-swa --exclude "*.js" --delete
aws s3 sync ./dist s3://vite-household-management-swa --exclude "*" --include "*.js" --content-type application/javascript
