### ISSUE TITLE
AWS Cli doesn't show implicitly associated subnets when using describe-route-tables

### ISSUE THREAD

**Issue by rh-dluong** [aws/aws-cli#3380]
When using `describe-route-tables`, if it's an environment where the subnets are not explicitly associated, defaulting to the main route table, the subnets are not shown as associated with the main route table.

**Comment by jamesls** [comment]
In general, the CLI commands are just exposing whatever API the service offers.  If the subnets are not being shown in this command it's because the service isn't returning that data to us.  I'd suggest reaching out on the AWS EC2 forums and someone can comment on why that's the case.  However, from the CLI there's not much we can do if the service isn't give us this data.
