### ISSUE TITLE
aws cloudformation package support ProvisioningArtifactProperties of AWS::ServiceCatalog::CloudFormationProduct

### ISSUE THREAD

**Issue by georgealton** [aws/aws-cli#3388]
It would be very useful to be able to package and upload local Cloud Formation Templates to S3 when creating a Service Catalog Product within Cloud Formation, the same as the process for creating ApiGateway and Lambda functions.

**Comment by joguSD** [comment]
Marking as a feature request. @sanathkr

**Comment by caylorme** [comment]
+1
Is there a current best practice for automating the uploading of product templates to s3 and referencing them in a cfn template through a pipeline?

**Comment by georgealton** [comment]
similar to 
https://github.com/aws/aws-cli/issues/3570#issuecomment-444323097

The key for this artifact isn't at the top level

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-servicecatalog-cloudformationproduct-provisioningartifactproperties.html

The other issue is that it's expecting a https:// url, where the current uploader returns a s3 url

**Comment by Ni-k0** [comment]
+1
Anyone found a workaround for this?

**Comment by farrantch** [comment]
+1

**Comment by apachler** [comment]
+1

**Comment by tim-finnigan** [comment]
Checking in as this issue hasn't had any activity in a while. We have been advised to refer uses to the [SAM CLI](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html) and the [sam package](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-package.html) command going forward. It looks like there are a couple PRs linked above where this issue was mentioned, most recently https://github.com/aws/aws-sam-cli/pull/2422. That PR was closed as the feedback wasn't addressed but I'd recommend reaching out on the repository to address this feature request if it is still needed.

**Comment by andyfase** [comment]
+1 sam-cli is not a replacement for aws-cli. Support for packaging of this resource looks to have a PR for this already but it requires more upvotes for it to be considered: https://github.com/aws/aws-cli/pull/5220

Suggest anyone interested upvote this issue so that the PR can be considered.
