### ISSUE TITLE
Issue with updating access logs, log format

### ISSUE THREAD

**Issue by ppvo** [aws/aws-cli#3392]
Can't seem to find any resolution on this, on the cli I have` aws apigateway update-stage --cli-input-json '{\"restApiId\":\"apiId\",\"stageName\":\"beta\",\"patchOperations\":[{\"op\":\"replace\",\"path\":\"/accessLogSettings/format\",\"value\":{\"requestId\":\"$context.requestId\"}}]}'` and I get the error  _Invalid_ type for parameter patchOperations[0].value, value: {u'requestId': u'$context.requestId'}, type: <type 'dict'>, valid types: <type 'basestring'> __

Please can you guys help me out with this issue.

**Comment by jamesls** [comment]
You might have better luck asking on the AWS forums for API gateway, but that error message is saying that the service expects the value as a string, so perhaps instead of `{"requestId": "$context.requestId"}`  it should be a string: `"{\"requestId\": \"$context.requestId\"}"`.

Otherwise for service usage questions, the forums are the best place for help
