### ISSUE TITLE
upgrade 1.15.65 => 66 for ssm changes in order of outputs, when --output text flag is used

### ISSUE THREAD

**Issue by etorkos** [aws/aws-cli#3476]
The ssm upgrade in 1.15.66 caused breaking changes for us, with the order of the outputs when the --output text flag is passed. 

1.15.65
PARAMETERS - Name - Type - Value - Version

1.15.66
Actual Behavior
PARAMETERS - ARN - LastModifiedDate - Name - Type - Value - Version

Expected Behavior
PARAMETERS - Name - Type - Value - Version - ARN - LastModifiedDate

Is it expected that --output text does not lock order for minor subversion releases? if so, could you update the documentation to reflect this?

**Comment by lyoungblood** [comment]
OMG!  This is going to break a ton of my production systems the next time CodeBuild rebuilds their Docker containers which have awscli in them.  My staging environment already broke because the actual parameter is now in field 6 of the `--output text` instead of field 4.

Please think about the downstream impacts of breaking changes like this.  Here is my code that broke:

```
echo "Loading password from SSM..."
export PASSWORD=`aws --region=$region ssm get-parameters \
	--name /path/password \
	--with-decryption \
	--output text | cut -f 4`
```

Now it is in field 6, so I have to modify it to be:

```
echo "Loading password from SSM..."
export PASSWORD=`aws --region=$region ssm get-parameters \
	--name /path/password \
	--with-decryption \
	--output text | cut -f 6`
```

**Comment by etorkos** [comment]
Simple solution perhaps should be to query specifically for the value `--query Parameters[*].Value`

```
export PASSWORD=`aws --region=$region ssm get-parameters \
	--name /path/password \
	--with-decryption \
	--output text \
        --query Parameters[*].Value`
```

**Comment by lyoungblood** [comment]
@etorkos I like that solution better that using cut.  Thanks!

**Comment by justnance** [comment]
@lyoungblood - Thanks for reaching out.  @etorkos - Thanks for responding.  I just want to confirm ` --query Parameters[*].Value` is the better/best practice for this type of expected results.
