### ISSUE TITLE
route53domains only supports ASCII domains

### ISSUE THREAD

**Issue by bogdanr** [aws/aws-cli#3482]
`aws --region us-east-1 route53domains check-domain-availability --domain-name 'rădulescu.cc'`

    'ascii' codec can't encode character u'\u0103' in position 49: ordinal not in range(128)

**Comment by justnance** [comment]
@bogdanr  - thank you for reaching out.  Without knowing the CLI version or seeing a —debug log, it's hard to tell why that's happening. I would say try first upgrading to the latest version of the CLI and test. If there is still an issue, please use the —debug option and please post a sanitized debug log so we can look into this issue further.  Thanks.

**Comment by jamesls** [comment]
The error you're seeing is caused by your locale being configured for ascii instead of something like utf-8.  When I configure the `LANG` to be ascii I get the same error message:

```
$ LANG=ascii aws --region us-east-1 route53domains check-domain-availability --domain-name 'rădulescu.cc'

'ascii' codec can't decode byte 0xc4 in position 1: ordinal not in range(128)
```

If I set my local to `en_US.UTF-8` (or something besides ascii):

```
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

I get this error message:


```
$ aws --region us-east-1 route53domains check-domain-availability --domain-name 'rădulescu.cc'

An error occurred (InvalidInput) when calling the CheckDomainAvailability operation: Invalid domain.Errors: [Unsupported character : [ă] in domain [rădulescu.cc]]
```

That error message comes directly from route53, so it appears the service does not support non-ascii domain names.  Not sure there's nothing we can do on the CLI side.

Let me know if you have any other questions.
