### ISSUE TITLE
aws cloudformation package idea

### ISSUE THREAD

**Issue by michaelwittig** [aws/aws-cli#3487]
`aws cloudformation package` is a great way to turn relative files and folders into s3 references. 

They work great for a limited set of resource properties.

`aws cloudformation package` could be even better if we could use it everywhere.

Imagine we had something like this

```
!!S3Url ./file.txt
!!S3Url ./folder 
```

That would be replaced to `s3://bucket-name/hash`

But sometimes, we need the s3 reference as an object. We could use something like this:

```
!!S3 ./file.txt
```

would be replaced to an object
```
{
  BucketName: 'bucket-name'
  Key: 'hash'
}
```

To make it more flexible:

```
!!S3 ['./file.txt', 'BucketKey', 'ObjectKey]
```

would be turned into:

```
{
  '$BucketKey': 'bucket-name'
  '$ObjectKey': 'hash'
}
```

### solve #2513

```
Transform :
     Name : 'AWS::Include'
     Parameters :
         Location : !!S3 ./file.txt
```

Also #3464 and #3388

### Use it for UserData scripts

```
UserData:
  'Fn::Base64': !Sub
    - |
      #!/bin/bash
      aws cp ${S3Url} - | bash -e
    - S3Url: !!S3 ./userdata.sh
```

**Comment by kyleknap** [comment]
@michaelwittig Trying to generalize S3 references seems like it would be very helpful. We will need to get a specification more fleshed out for this, but this looks like a good start. @sanathkr what are your thoughts on this idea?

**Comment by andyRokit** [comment]
Duplicate of #2862?

**Comment by andyRokit** [comment]
Q: Could a quick fix for this be to add a new pseudo param to CF which gives it a reference to its own bucket?  E.g. `AWS::S3DeploymentBucket`

This way your CICD tool (or whatever mechanism you're using) could push resources up to the same bucket as the CF script and the script could get a handle on them without having to pass its own bucket as a parameter (redundant!).

I understand that this would involve a change to CloudFormation itself rather than the CLI.  I just wanted to float the idea here first as we're on the topic.

Note: I prefer the mechanism @michaelwittig suggested as CLI `package` command has already assumed the responsibility for uploading *some* of your resources.  So uploading the rest seems like a reasonable next step.  I'm just suggesting this as an alternative that may solve the same problem.

**Comment by tim-finnigan** [comment]
Checking in as there hasn't been any activity on this issue in a while. Is this a duplicate of https://github.com/aws/aws-cli/issues/2862 as suggested above? 

Also we were advised to refer users of `aws cloudformation package` to the [SAM CLI](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html), as the [sam package](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-package.html) command may have some of the extended functionality you are looking for.
