### ISSUE TITLE
Can not override aws-cli logging output

### ISSUE THREAD

**Issue by wimnat** [aws/aws-cli#3511]
I want to use the aws cli s3 sync command as part of a python script that I have.  I have a custom logging implementation to log as json.  Looking through the aws-cli implementation i can see standard logging all over the place... e.g. `LOG.info("bla")`

Unfortunately, my override doesn't seem to have any effect.  My script just prints out the aws cli log as a plain text stdout line.

Here's an example:

```
import logging
from pythonjsonlogger import jsonlogger
from awscli.clidriver import create_clidriver

logger = logging.getLogger(__name__)
logHandler = logging.StreamHandler()
formatter = jsonlogger.JsonFormatter()
logHandler.setFormatter(formatter)
logger.addHandler(logHandler)
logger.setLevel(logging.INFO)

logger.info("Start")
create_clidriver().main(['ec2', 'describe-instances'])
logger.info("End")
```

The output looks like this:

```
{"message": "Start"}
Unable to locate credentials. You can configure credentials by running "aws configure".
{"message": "End"}
```

Whereas I would expect:

```
{"message": "Start"}
{"message": "Unable to locate credentials. You can configure credentials by running \"aws configure\"."
{"message": "End"}
```

Am I doing something wrong here?

**Comment by kyleknap** [comment]
It is not being handled by the logger because the `Unable to locate credentials. You can configure credentials by running "aws configure".` message is being written directly to stderr and not to a logger. I also want to note that we do not recommend the use the internal of the CLI directly in a script as we provide no guarantee of backwards compatibility guarantees for any of those modules/classes. Instead, I'd recommend just using `subprocess.Popen` with the CLI command you want to run.
