### ISSUE TITLE
S3api list-object-versions weird implementation

### ISSUE THREAD

**Issue by Diliz** [aws/aws-cli#3515]
Hello there!

Juste a simple issue to say that the list-object-versions is actually not listing all versions of one object, since you can't target a specific key.

Let me explain, let's say you have multiple files with names like this:

toto
toto-1
toto-2
toto-3
toto-10

If I want to list the versions of toto-2, i can use the --prefix toto-2 to have versions of only toto-2.

For having the toto-1 versions I can use the --prefix toto-1 --delimiter 0 to have only this object versions.

But how to do it now for only toto simply?

I think the --key option here should be available, the --prefix and --delimiter are not really obvious to use when you want to target one specific object, since the fonction name is list-object-versions...

Thanks for you hard work, and thanks for reading :)

**Comment by diehlaws** [comment]
@Diliz Thanks for reaching out to us about this. What you are describing is expected behavior for the underlying API call for `list-object-versions` ([GET Bucket Object versions](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETVersion.html)) - there is no request parameter to specify a single key on this operation that we could implement from the CLI side without requiring an update to this API call. 

Implementing this change would certainly improve usability of the AWS CLI in use cases such as your own, however since this would be an API-level change rather than a customization of the AWS CLI it is more likely to gain traction if a feature request is submitted for it in the [AWS Forums for S3](https://forums.aws.amazon.com/forum.jspa?forumID=24) or as a [Premium Support case](https://console.aws.amazon.com/support/v1?#/case/create) under the S3 Service.
