### ISSUE TITLE
configservice subscribe 

### ISSUE THREAD

**Issue by moulya-somasundara** [aws/aws-cli#3516]
An error occurred (InsufficientDeliveryPolicyException) when calling the PutDeliveryChannel operation: Insufficient delivery policy to s3 bucket: my-aws-config-bucket-test, unable to assume role: arn:aws:iam::248409795601:user/aws-config-test-user.

**Comment by justnance** [comment]
@moulya-somasundara - thanks for reaching out.  This appears to be expected behavior from the API and a  [common API error](https://docs.aws.amazon.com/config/latest/APIReference/CommonErrors.html).  I suggest reviewing the [Managing AWS Config](https://docs.aws.amazon.com/config/latest/developerguide/manage-config.html) and Configuration Recording settings.  If it is still an issue, I would suggest contacting [AWS Support](https://console.aws.amazon.com/support/home#/) for additional follow up.  As stated in our [README](https://github.com/aws/aws-cli#getting-help), We try to reserve GitHub issues to CLI bugs and feature requests.  As such, this GitHub issue will be marked as closed.
