### ISSUE TITLE
regression in elb register-instances-with-load-balancer with botocore==1.12.0

### ISSUE THREAD

**Issue by caboteria** [aws/aws-cli#3554]
We've been using "aws elb register-instances-with-load-balancer" successfully for several years but recently the behavior of the command seems to have changed.

It works fine with botocore==1.10.19:
```
$ aws elb --version
aws-cli/1.15.19 Python/2.7.5 Linux/3.10.0-862.2.3.el7.x86_64 botocore/1.10.19
$ aws elb register-instances-with-load-balancer --instances i-0f530a0249108584b --load-balancer-name kitchen-qual
{
    "Instances": [
        {
            "InstanceId": "i-0f530a0249108584b"
        }
    ]
}
```
If fails with botocore==1.12.0:
```
$ aws elb --version
aws-cli/1.15.19 Python/2.7.5 Linux/3.10.0-862.2.3.el7.x86_64 botocore/1.12.0
$ aws elb register-instances-with-load-balancer --instances i-0f530a0249108584b --load-balancer-name kitchen-qual

Error parsing parameter '--instances': Expected: '=', received: 'EOF' for input:
i-0f530a0249108584b
                   ^
```

**Comment by caboteria** [comment]
It works with botocore==1.11.9 so it looks like the regression was introduced with botocore==1.12.0.

**Comment by jamesls** [comment]
How are you installing the AWS CLI?  The CLI version locks to a specific version of botocore because sometimes we need to make coordinated changes across both repos (such as this issue).

Version 1.15.19 of the CLI that you're using should require 1.10.19 of botocore, as shown here: https://github.com/aws/aws-cli/blob/1.15.19/setup.py#L26

The latest version of the CLI (1.16.10) is the only version that calls out version 1.12.0 of botocore (https://github.com/aws/aws-cli/blob/develop/setup.py#L26), so pip wouldn't have allowed those two versions to be installed together.

**Comment by caboteria** [comment]
Thanks for your help!  We'll upgrade to awscli 1.16.10.
