### ISSUE TITLE
aws emr create-cluster steps missing type="spark"

### ISSUE THREAD

**Issue by awhillas** [aws/aws-cli#3562]
The documentation for the `create-cluster` --steps options seems to be missing `Type=SPARK`? Also any useful examples of how to do this with a JAR in an S3 bucket.

**Comment by justnance** [comment]
@awhillas - Thanks for reaching out.  It appears the missing `Type=SPARK` might be a limitation of the API.  The CLI does not have any control over this behavior because the CLI only picks up and displays information exposed by the API.  It also appears the issue might be related to an EMR version or maybe the upper case syntax.  As per our online documentation, [Amazon EMR releases 4.0 and later... support a list of the following valid values are: "Hadoop", "Hive", "Mahout", "Pig", and "Spark."  They are case insensitive](https://docs.aws.amazon.com/emr/latest/APIReference/API_RunJobFlow.html).  

It is recommended to reach out on the [AWS EC2 forums](https://forums.aws.amazon.com/forum.jspa?forumID=30) or contact [AWS Support](https://console.aws.amazon.com/support/home#/) as we try to reserve this GitHub repo for CLI bugs and feature requests.
