### ISSUE TITLE
aws cloudformation delete-stack returns nothing

### ISSUE THREAD

**Issue by adamchainz** [aws/aws-cli#3569]
The output and exit code of `delete-stack` are 0 and empty, respectively, no matter whether the named stack exists, is deletable, etc. Thus any mistake is silently passed over.

**Comment by justnance** [comment]
@ adamchainz - Thanks for reaching out.  This is expected behavior by CloudFormation. The CLI is only displaying the error returned by the service and does not have any control over this behavior.   Modifying the output to display the results would be a good feature request for the Cloudformation service team.  It is recommended to reach out on the [CloudFormation forums](https://forums.aws.amazon.com/forum.jspa?forumID=92) or contact [AWS Support](https://console.aws.amazon.com/support/home#/).  Once this information is exposed from the API then it should be automatically picked up and displayed by the CLI.

**Comment by adamchainz** [comment]
The CLI could poll though to check. Or do you never add extra API calls to commands over the underlying API? I'll write a support ticket later today.

**Comment by adamchainz** [comment]
Reported to support

**Comment by justnance** [comment]
@adamchainz - Thanks for your feedback and reaching out to Support.  We do not add extra API call to commands over the underlying API.

**Comment by adamchainz** [comment]
Mokay
