### ISSUE TITLE
[v2] Move to a single binary for the cli comand

### ISSUE THREAD

**Issue by rnhurt** [aws/aws-cli#3605]
I think it would be great to have a single binary to install and maintain.  There are several languages that provide this capability today and would be suitable for something like the AWS CLI.  Rust would be at the top of my list of languages with Go being a close 2nd.

**Comment by justnance** [comment]
@rnhurt - Thank you for reaching out.  This seems like a reasonable feature request and has been labeled as such being further review.

**Comment by oliwer** [comment]
I think pyinstaller would be the easiest way to do this. That's what docker-compose is using, with great success!

**Comment by marczis** [comment]
I think it would be really huge effort to rewrite, instead of single binary, just drop it into a docker build, that will work for everyone, who has docker. Otherwise @oliwer has a really good "workaround". 
There would be other effects if you rewrite in go or rust, just randomly checked some "programming language popularity charts, python usually in the first 3, meanwhile go and rust still far down on the lists. I'm afraid it would attract less contributors, and would make more spin offs from the original python code... ofc this is only my humble point of view.

**Comment by lorengordon** [comment]
I'll second pyinstaller, and sticking with python! ;)

**Comment by justnance** [comment]
@rnhurt, @oliwer, and @marczis - Thank you for your feedback.  This feature request is being considered for CLI v2.  The tracking issue for V2 is #3587.

**Comment by kyleknap** [comment]
Closing issue. We are currently using pyinstaller to build the binary and we currently have binaries for Mac, Linux, and Windows.

**Comment by HarryCaveMan** [comment]
Do your linux binaries include both gnu and musl?
