### ISSUE TITLE
allow source_profile entries to make use of the credential_process function

### ISSUE THREAD

**Issue by shmick** [aws/aws-cli#3624]
Currently a profile using a _role_arn_ and _source_profile_ cannot use a _source_profile_ entry that uses the _credential_process_, requiring the user to either have the keys stored in the config file with the profile or use environment variables for the Access and Secret keys.

**Comment by ngrilly** [comment]
It works for me if `credential_process` is specified in the `default` profile:

```
[default]
credential_process = /usr/local/bin/aws-credentials.sh
 
[profile admin]
source_profile = default
role_arn = arn:aws:iam::123456:role/admin
```

**Comment by benkehoe** [comment]
Does it only work with the credential provider in the default profile, or can it be any profile?

**Comment by iliana** [comment]
ref https://github.com/boto/botocore/pull/1790

**Comment by ngrilly** [comment]
> Does it only work with the credential provider in the default profile, or can it be any profile?

@benkehoe Any profile.

**Comment by ngrilly** [comment]
@shmick Can you retry and tell us if it works for you now, and close the issue if it works?

**Comment by pcChristopher** [comment]
Not working for me.

I use source_profile very heavily with my IAM accounts.  It saves a lot of duplication in the config file.  I'd really like to be able to do this with SSO.

Here's an example of what I'd like to see work:

> [default]
> region=us-east-1
> output=text
> 
> [profile master]
> sso_start_url = https://company.awsapps.com/start
> sso_region = us-east-1
> sso_role_name = AdministratorAccess
> region = us-east-1
> output = text
> 
> [profile test-account]
> sso_account_id = 111111111111
> source_profile = master

I have an empty/broken [default] because I don't want anything to work by default.  I always have to force the --profile.  This prevents me from running commands on the wrong account by accident.  So I source a profile that I call master, which contains my IAM User.  The IAM user can stsassumerole to all other accounts.  It works today with IAM keys.  I'd really like to replace the IAM user with an SSO user but still have very minor configurations in the profiles and keep the majority up in the source profile.  The sole reason is to make it easier to work with the config file.

**Comment by thomasgreensmith** [comment]
Not sure where the issue lies with this, I am using [aws-adfs](https://github.com/venth/aws-adfs) along with vscode toolkit
It seems that even if the credentials in default profile have expired, inheriting profiles will just attempt to use them and error out.

`[ERROR]: Error trying to connect to AWS with Credentials Provider profile:DEMO. Toolkit will now disconnect from AWS. ExpiredToken: The security token included in the request is expired`

The only way that works for me is to first connect to the default profile (generating new credentials) then reconnect back to the other profile

**Comment by kdaily** [comment]
I think this issue is resolved via https://github.com/boto/botocore/pull/1790. 

@pcChristopher your question seems to be slightly different. If you're still having an issue, check for a duplicate from [these SSO related issues](https://github.com/aws/aws-cli/labels/sso) or open a new issue, please!

@thomasgreensmith - if you're still having an issue, let us know in a new issue. This might be similar to this issue with MFA? https://github.com/aws/aws-cli/issues/5880#issuecomment-769243927
