### ISSUE TITLE
Ability to detect if cloudformation update error is due to no change

### ISSUE THREAD

**Issue by aztecrex** [aws/aws-cli#3625]
The CLI should provide a way to determine if there are any effective changes in a template. This could be by either returning a distinct status on no-op update or by providing an additional sub-command.

If a stack update results in no change, the remote API reports an error instead of it being a NO OP. This behavior is carried down through the CLI in an undetectable way.  i.e. the error code is 255, same as the response for a material error in the invocation.

The CLI should provide a way to determine if there are any effective changes in a template. This could be by either returning a distinct status on update or by providing an additional sub-command.

The rational is that since the user is required to know whether an operation represents no change, the user should have a way of detecting that fact.

**Comment by aztecrex** [comment]
cloudformation update-stack

**Comment by justnance** [comment]
@aztecrex - Thanks for posting this request.  I've labeled it as feature request + confusing error pending further review and discussion.  @sanathkr, What are your thoughts?

**Comment by jessedye** [comment]
I would like to second this. We ran into this problem today also. It returns an error code 255 instead of an error code 0. It shouldn't be doing that if there's no updates. E.g. what I was running:

aws cloudformation update-stack

Error Response:

An error occurred (ValidationError) when calling the UpdateStack operation: No updates are to be performed.

**Comment by RhysC** [comment]
Any updates on this?

**Comment by kartik-moolya** [comment]
Any progress on this ?

**Comment by ionty** [comment]
I am waiting for this too!

**Comment by hackersky109** [comment]
Any updates on this?

**Comment by Josh-a-e** [comment]
I agree this would be a nice feature. If it helps anyone else, my solution was to use `aws cloudformation deploy` instead which has a `--no-fail-on-empty-changeset` option. There are a few other differences (`--template-file` rather than `template-body` and it gave a weird error when I was supplying `--parameters` rather than the `--parameter-overrides` that apparently it requires - see this issue: https://github.com/aws/aws-cli/issues/3601)

Final solution for CI purposes looked something like this:
```
aws cloudformation deploy --stack-name my-stack-name --no-fail-on-empty-changeset --template-file ./my-resources.cf.yml --parameter-overrides 'Foo=bar' && aws cloudformation wait stack-update-complete --stack-name my-stack-name
```

**Comment by zmajstor** [comment]
as a temporary fix for the `aws cloudformation update-stack`, I use something like this:

```
#!/bin/bash

output=$(aws cloudformation update-stack --stack-name foo 2>&1)

RESULT=$?

if [ $RESULT -eq 0 ]; then
  echo "$output"
else
  if [[ "$output" == *"No updates are to be performed"* ]]; then
    echo "No cloudformation updates are to be performed."
    exit 0
  else
    echo "$output"
    exit $RESULT
  fi
fi
```

**Comment by dlegr250** [comment]
Just ran into this today as well with a specific implementation where we are passing an image tag as a param and the image already exists so it throws the error about not updating.

The above solutions should work, but an alternative for my specific situation was to check if the image tag exists to avoid calling the `update-stack` method.

Some pseudocode, may be some minor issues since I'm typing from memory:

```
result=$(aws ecr describe-images \
  --repository-name "repo_name",
  --image-ids imageTag="a4528ec" \
  --profile "PROFIILE" \
  --query "imageDetails[0].imageTags[0]" || echo "false")

if [ $result = "false" ]; then
  # image tag does not exist...
fi
```

I'm using the git commit hash as the image tag and my ECR repos are set up with immutable tags.

This may help someone else in a similar specific situation.

**Comment by tim-finnigan** [comment]
Checking in as this issue hasn't has any activity in a while. This issue relates to the underlying CloudFormation [UpdateStack](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_UpdateStack.html) API rather than the AWS CLI directly. For cases involving service API issues we recommend reaching out directly to [AWS Support](https://aws.amazon.com/contact-us/) for further escalation. 

We can also forward requests like this to the service team internally but it looks like several workarounds have already been noted above so please let us know if anyone is still encountering this issue.

**Comment by ihsan-96** [comment]
I understand that this issue stems from the [UpdateStack](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_UpdateStack.html) API.

But the CLI should have an option to ignore the error `No updates are to be performed.` as requested in the issue #3989 

This is affecting CI/CDs. I can see there are some workarounds, But I prefer a clean solution.

Can this be picked up?

**Comment by krugermil** [comment]
I second that, this is still an issue, and surprisingly it was not solved by postponing it, and then close it.. ;)
