### ISSUE TITLE
CVE-2018-15869: --owners flag isn't mandatory

### ISSUE THREAD

**Issue by jbicha** [aws/aws-cli#3629]
I noticed that Debian and Fedora are tracking a security issue they are calling CVE-2018-15869

Here's the description from the Red Hat bug:
> The Amazon Web Services (AWS) CLI version 1.15.85 (and possibly earlier versions) does not require the --owners flag when describing images, which makes it easier for remote attackers to trigger the loading of an undesired AMI by setting similar image properties (i.e., name), as exploited in the wild during August 2018 with a Monero miner AMI instead of the expected Ubuntu AMI.

References
--------------
- https://security-tracker.debian.org/tracker/CVE-2018-15869
- https://bugzilla.redhat.com/1623095
- https://github.com/hashicorp/packer/issues/6584

**Comment by justnance** [comment]
@jbicha - Thank you for reaching out with the details of the CVE-2018-15869. As you have already pointed out, ["Omitting the --owners flag from the describe-images command will return all images for which you have launch permissions, regardless of ownership."](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/finding-an-ami.html ). As per our EC2 service team, the owners field is optional by design. We provide customers with the options and flexibility they need, and encourage that they follow AWS recommended best practices when incorporating features in 3rd party tools. Also note, the referenced forums closed the issue and confirmed that it is not an AWS CLI bug.

For more information, please reach out and open a case to [AWS Premium Support](https://console.aws.amazon.com/support/home#/ ).
