### ISSUE TITLE
Ambiguous error message: An error occurred (InvalidInstanceId) when calling the SendCommand operation:

### ISSUE THREAD

**Issue by minfrin** [aws/aws-cli#3646]
We recently saw the following error message when running "aws ssm send-command":

An error occurred (InvalidInstanceId) when calling the SendCommand operation:

In our case, the error was triggered by the ssm-agent not running on the target machine, however AWS tech support has confirmed this same error appears in other scenarios, including the aws client not having been logged in with the same account as the instance.

To fix this:

- Replace the "InvalidInstanceId" error response with unique and unambiguous error responses for each case, including "SSM agent not accessible" and "instance ID not found".
- Leave "InvalidInstanceId" for instance IDs that are actually invalid.

**Comment by justnance** [comment]
@minfrin - Thank you for reaching out.  I understand the use-case here and the recommended fix.  The CLI is only returning results by the service and does not have any control over this behavior.  If the service team approves and adds this feature, it will automatically be exposed from the API to the CLI.  

Since you already reached out to AWS Premium Support but your case is closed, you can reply and it will automatically reopen the case.  Let them know you want to submit a new feature request.
