### ISSUE TITLE
--output text doesn't respect JMESPath sort_by

### ISSUE THREAD

**Issue by chizou** [aws/aws-cli#3652]
Running the following command prints the JSON in sorted order, as expected:
``aws organizations list-accounts --query 'Accounts[?starts_with(Name, `RS-aws-student`)].{Id: Id, Name: Name} | sort_by(@, &Name)'``

However, adding `--output text` clobbers the sort and output is unsorted. Interestingly, `--output table` respects the sort order.

**Comment by justnance** [comment]
@chizou - Thanks for reaching out.  This is expected behavior of [Text Output Format](https://docs.aws.amazon.com/cli/latest/userguide/controlling-output.html#text-output) when [the command return a large list of items.  A service may not return items in the same order each time.](https://docs.aws.amazon.com/cli/latest/userguide/pagination.html)

**Comment by chizou** [comment]
Sorry, I don't understand why that would be expected behavior? I'm not receiving enough output that I'm getting a NextToken. Also, my understanding is that the `sort_by` function in the JMESPath `--query` is applied after the response is received. Why would pagination affect the JMESPath if that's the case?

**Comment by jamesls** [comment]
The difference here is that the `table` and `json` output before multiple pages into a single, final document, and then apply the JMESPath expression to the whole thing.  The `text` output is "streaming" in the sense that every page is printed as soon as we receive it and the JMESPath expression is applied to each page:

```
json/table:

sort_by([page1 + page2 + page3 + page4])

text:

sort_by(page1) + sort_by(page2) + sort_by(page3)
```

Let me know if you still have questions.
