### ISSUE TITLE
Release 1.16.39 Boto3 install error

### ISSUE THREAD

**Issue by TheJedinator** [aws/aws-cli#3674]
installing boto3 after installing awscli is failing
ImportError: No module named ordered_dict

Specifying awscli == 1.16.38 and then installing boto3 works fine.

**Comment by justnance** [comment]
Thanks for reaching out @TheJedinator.  What installation method are you using?  PIP, MSI, bundled installer?

**Comment by davideagle** [comment]
Same issue here, installing via pip

FROM node:8
RUN apt-get update && apt-get install python-pip libpython-dev -y
RUN pip install pySocks
RUN pip install urllib3
RUN pip install awscli --upgrade --user
RUN pip install boto3
RUN pip install botocore

Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 22, in <module>
    import requests, six
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 80, in <module>
    from . import utils
  File "/usr/lib/python2.7/dist-packages/requests/utils.py", line 25, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/usr/lib/python2.7/dist-packages/requests/compat.py", line 94, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict

how ever like @TheJedinator suggested setting the version to 1.16.38 of awscli works like a charm

**Comment by TheJedinator** [comment]
Using pip

**Comment by TheJedinator** [comment]
I haven't tried reverting our pipeline. has this been resolved? @davideagle

**Comment by davideagle** [comment]
No it has not, checked by creating a Docker file with the contents of:

FROM node:8
RUN apt-get update && apt-get install python-pip libpython-dev -y
RUN pip install pySocks
RUN pip install urllib3
RUN pip install awscli --upgrade --user
RUN pip install boto3
RUN pip install botocore

and run "docker build --tag testing-boto3-install ." from the directory where Dockerfile resides

**Comment by JordonPhillips** [comment]
There's a couple of issues at play here. pip, to ensure it is compatible with other python packages you have installed, vendors all its dependencies. debian (and some other linux distros) *unbundle* those dependencies to manage them with their package managers. BUT packages you install via pip can be taken over packages you install via your system package manager. Final piece of the puzzle: both pip and the CLI rely on urllib3.

So here's what happens:

1. `FROM node:8` - Base image with node is installed. After this you have the following python packages installed via your system package manager:

```
libpython-stdlib/now 2.7.9-1 amd64 [installed,local]
libpython2.7-minimal/now 2.7.9-2+deb8u2 amd64 [installed,local]
libpython2.7-stdlib/now 2.7.9-2+deb8u2 amd64 [installed,local]
python/now 2.7.9-1 amd64 [installed,local]
python-bzrlib/now 2.6.0+bzr6595-6+deb8u1 amd64 [installed,local]
python-configobj/now 5.0.6-1 all [installed,local]
python-minimal/now 2.7.9-1 amd64 [installed,local]
python-six/now 1.8.0-1 all [installed,local]
python2.7/now 2.7.9-2+deb8u2 amd64 [installed,local]
python2.7-minimal/now 2.7.9-2+deb8u2 amd64 [installed,local]
```

2. `RUN apt-get update && apt-get install python-pip libpython-dev -y` - Several more python packages are installed via the system package manager. You now have the following:

```
libpython-dev/oldstable,now 2.7.9-1 amd64 [installed]
libpython-stdlib/oldstable,now 2.7.9-1 amd64 [installed,automatic]
libpython2.7/oldstable,now 2.7.9-2+deb8u2 amd64 [installed,automatic]
libpython2.7-dev/oldstable,now 2.7.9-2+deb8u2 amd64 [installed,automatic]
libpython2.7-minimal/oldstable,now 2.7.9-2+deb8u2 amd64 [installed,automatic]
libpython2.7-stdlib/oldstable,now 2.7.9-2+deb8u2 amd64 [installed,automatic]
python/oldstable,now 2.7.9-1 amd64 [installed,automatic]
python-bzrlib/oldstable,oldstable,now 2.6.0+bzr6595-6+deb8u1 amd64 [installed,automatic]
python-cffi/oldstable,now 0.8.6-1 amd64 [installed,automatic]
python-chardet/oldstable,now 2.3.0-1 all [installed,automatic]
python-colorama/oldstable,now 0.3.2-1 all [installed,automatic]
python-configobj/oldstable,now 5.0.6-1 all [installed,automatic]
python-cryptography/oldstable,now 0.6.1-1+deb8u1 amd64 [installed,automatic]
python-distlib/oldstable,now 0.1.9-1 all [installed,automatic]
python-html5lib/oldstable,now 0.999-3 all [installed,automatic]
python-minimal/oldstable,now 2.7.9-1 amd64 [installed,automatic]
python-ndg-httpsclient/oldstable,now 0.3.2-1 all [installed,automatic]
python-openssl/oldstable,now 0.14-1 all [installed,automatic]
python-pip/oldstable,now 1.5.6-5 all [installed]
python-pkg-resources/oldstable,now 5.5.1-1 all [installed,automatic]
python-ply/oldstable,now 3.4-5 all [installed,automatic]
python-pyasn1/oldstable,now 0.1.7-1 all [installed,automatic]
python-pycparser/oldstable,now 2.10+dfsg-3 all [installed,automatic]
python-requests/oldstable,now 2.4.3-6 all [installed,automatic]
python-setuptools/oldstable,now 5.5.1-1 all [installed,automatic]
python-six/oldstable,now 1.8.0-1 all [installed,automatic]
python-support/oldstable,now 1.0.15 all [installed,automatic]
python-urllib3/oldstable,now 1.9.1-3 all [installed,automatic]
python-wheel/oldstable,now 0.24.0-1 all [installed,automatic]
python2.7/oldstable,now 2.7.9-2+deb8u2 amd64 [installed,automatic]
python2.7-minimal/oldstable,now 2.7.9-2+deb8u2 amd64 [installed,automatic]
```

In particular, note that you have some variant of urllib3 version 1.9.1

3. `RUN pip install pySocks` - installs pySocks, which has no python dependencies on unix
4. `RUN pip install urllib3` - does nothing because urllib3 is already installed
5. `RUN pip install awscli --upgrade --user` - Installs the CLI and all its dependencies, including `urllib3>=1.20,<1.25`. Note that the minimum version of urllib3 is higher than the version you have installed, which is why pip will now install a new version. pip is now broken.
6. `RUN pip install boto3` - pip fails because it is depending on a specific version of urllib3 that is not compatible with the version it is finding.

To resolve this issue you will need to do one or more of the following:

* Upgrade pip in place with `pip install --upgrade pip` - probably safe, but I can't really say for sure
* Upgrade pip using an alternative package source (I don't know one off the top of my head)
* Upgrade your OS. That dockerfile is using debian jessie as it's base, but the current stable 'stretch' is also available and has workarounds to prevent your system pip from breaking when pip installs packages: `FROM node:8-stretch`
* Use a virtual environment
* Install via the [bundled installer](https://docs.aws.amazon.com/cli/latest/userguide/awscli-install-bundle.html)

**Comment by TheJedinator** [comment]
After reading your suggestions I ran the following:

`- apt-get -y install python-dev python-pip libpython-dev zip
            - pip install --upgrade pip
            - pip install pySocks
            - pip install awscli --upgrade
            - pip install boto3 boto`
In place of:
`- apt-get -y install python-dev python-pip zip
- pip install awscli
- pip install boto3==1.3.0 boto `

It now works and builds successfully. Thanks for your help!
