### ISSUE TITLE
Support different S3 ls output formats

### ISSUE THREAD

**Issue by zasran** [aws/aws-cli#371]
aws s3 ls does not support the usual formats (json, text, table) and the default format is not very good for scripting, it prints out some extra irregular data in addition to names of buckets, keys and objects.

It also does not differentiate between keys and objects, if asked to list an object it treats it as a key and essentially lists it as empty directory. In comparison I find s3cmd output more useful, it lists the object itself (plus last modified time and size).

**Comment by isaacegglestone** [comment]
This issue is closed but realistically here the best thing to do would be to put this information in the s3 ls command output.  (This tool does not support output formats use s3api instead if you need this.
Here I am some four years later still encountering this problem and finding the solution here when it could easily be added to the help for the tool.

**Comment by jarruda** [comment]
@jamesls In my opinion this issue should not have been closed just because a workaround exists. The customer request is for the ls command to support it, and the workaround is cumbersome at best.

**Comment by zasran** [comment]
@jamesls thanks for providing information about workaround but I don't think this issue should have been closed without the fix. Either providing support for different formats (good fix) or at least error message mentioning s3api (IMO bad fix but sort of acceptable) would be ok.
