### ISSUE TITLE
awscli not working properly under linux subsystem of windows.

### ISSUE THREAD

**Issue by thinksource** [aws/aws-cli#3803]
I try use aws-cli inside my linux(ubuntu) subsystem of windows.

my aws-cli version is:

```
slu@BX-LTB77MLQ2-SS:~$ aws --version
aws-cli/1.16.75 Python/3.6.7 Linux/4.4.0-17134-Microsoft botocore/1.12.65
```

I use aws-mfa to login my aws account with mfa.
```
slu@BX-LTB77MLQ2-SS:~$ aws-mfa --profile my-identity
INFO - Validating credentials for profile: my-identity with assumed role: arn:aws:iam::053********:role/NSWPointDeveloperAccess
INFO - Obtaining credentials for a new role or profile.
Enter AWS MFA code for device [arn:aws:iam::5053********:mfa/slu] (renewing for 43200 seconds):608519
INFO - Fetching Credentials - Profile: cadnsw-identity, Duration: 43200
INFO - Success! Your credentials will expire in 43200 seconds at: 2018-12-17 11:26:36+00:00
```
and then I change aws profile like:

```
export AWS_PROFILE=admin_role
```
then I try to execute some command line of aws, and get access denied error.

```
slu@BX-LTB77MLQ2-SS:~$ aws s3 ls

An error occurred (AccessDenied) when calling the AssumeRole operation: Access denied
``` 

I think that is bug for linux subsystem of windows.

**Comment by justnance** [comment]
@thinksource - Thank you for reaching out and reporting an issue with using assumed roles.  The CLI is only echoing an error returned from the service and has no control over this behavior.   It is recommended to reach out to [AWS Support](https://console.aws.amazon.com/support/home#/) because they can analyze the account's IAM configuration with their internal tools.  Another option is to reach out to [AWS Forums for IAM](https://forums.aws.amazon.com/forum.jspa?forumID=76).
