### ISSUE TITLE
Add `cloudformation package` support for `AWS::AppSync::FunctionConfiguration`

### ISSUE THREAD

**Issue by Umkus** [aws/aws-cli#3816]
Even though `AWS::AppSync::FunctionConfiguration` type was added recently, it's still missing the related `aws cloudformation package` support, similarly to other `AWS::AppSync::` resources.

aws --version
```
aws-cli/1.16.81 Python/2.7.15 Darwin/17.7.0 botocore/1.12.71
```

**Comment by justnance** [comment]
@Umkus - Thank you for reporting this missing feature.  @sanathkr - What are your thoughts?

**Comment by mkrn** [comment]
I have the same problem, and created an issue at first in aws sam cli repo before realizing  it has to be implemented in aws-cli first.
Here for reference:
https://github.com/awslabs/aws-sam-cli/pull/898

https://github.com/aws/aws-cli/blob/develop/awscli/customizations/cloudformation/artifact_exporter.py this file needs to be updated, I expect it to be identical to AWS::AppSync::Resolver RequestMappingTemplateS3Location and 
ResponseMappingTemplateS3Location  implementations

**Comment by mkrn** [comment]
Submitted a PR, anyone can review please? Seems straight-forward as it's analogous to AppSync::Resolver mapping templates

**Comment by xentek** [comment]
:+1: also need this -- just converted most of my resolvers to `PIPELINE`s and now have hundreds of __*MappingTemplateS3Location__ values I would have to manage by hand in order to ensure that CloudFormation updates them properly when the referenced file changes. Inlining the templates isn't really a viable option either, since there is a lot of reuse of the same mapping templates across `FunctionConfiguration` blocks.

Any hope of this being merged in soon @justnance?

**Comment by jfuss** [comment]
@justnance Package supports the other `AWS::AppSync::*` resources. I don't see why we can't expand this further.

**Comment by TheSriram** [comment]
This PR: https://github.com/awslabs/aws-sam-cli/pull/898 is blocked on this as well.

**Comment by sharmmoh1983** [comment]
Is  FunctionConfiguration working now through aws-package?
