### ISSUE TITLE
s3 docs refer to nonexistent section

### ISSUE THREAD

**Issue by thanatos** [aws/aws-cli#3832]
The documentation for `s3 cp` (`aws s3 cp help`) read as follows:

> `--acl` (string) Sets the ACL for the object when the command is performed. If you use this parameter you must have the "`s3:PutObjectAcl`" permission included in the list of actions for your IAM policy. Only accepts values of `private`, `public-read`, `public-read-write`, `authenticated-read`, `aws-exec-read`, `bucket-owner-read`, `bucket-owner-full-control` and `log-delivery-write`. See <i>Canned ACL</i> for details

Note: I have italicized "Canned ACL"; in the original, it is underlined, as if it were a subsection on the man page. However, no such subsection exists, and there is no other occurrence of "Canned ACL" on the page. This "See also" seems to not be followable.

(`aws-cli/1.16.80 Python/3.7.2 Darwin/18.2.0 botocore/1.12.70`)

**Comment by kyleknap** [comment]
So the italicized `Canned ACL` is actual a link to another site. For the man pages from running the `help` command, this is the expected behavior. For the online [help references](https://docs.aws.amazon.com/cli/latest/reference/s3/cp.html), you should be able to click on the link to follow it.  Let us know if that helps.
