### ISSUE TITLE
aws cloudfront wait distribution-deployed doesn't wait long enough

### ISSUE THREAD

**Issue by richardgavel** [aws/aws-cli#3865]
I use this command within a Terraform file so the deployment isn't considered complete until I can hit the API Gateway that the distribution fronts. However, the number of retries it takes is never enough to cover the amount of time before the distribution itself is fully deployed.

**Comment by diehlaws** [comment]
Hi @richardgavel, thanks for reaching out to us about this. Per the waiter's [documentation page](https://docs.aws.amazon.com/cli/latest/reference/cloudfront/wait/distribution-deployed.html), this command will check the status of the distribution once per minute for 25 minutes, if the distribution is not in a Deployed status by then it will exit with a return code of 255. 
After some testing, I found that distributions using S3 Buckets as the origin typically take about 20 minutes to move to a Deployed status, which falls within the 25-minute time limit for the waiter. By contrast, distributions that use custom origins can take closer to 30-35 minutes to move to a Deployed state.

During my investigation I've found that this 25 minute time limit applies for this waiter across the majority of our SDKs, which does not fit well for distributions that are not backed by S3. I'll be reaching out to the appropriate teams internally to improve these waiters to fit a wider range of use cases.

In the meantime, having Terraform wait for 8-10 minutes before invoking the waiter would give the distribution enough time to start propagating that the waiter should consistently succeed without the distribution already being in a Deployed state by the time the waiter is started. Alternately, calling the waiter a second time if it returns `Waiter DistributionDeployed failed: Max attempts exceeded` with the return code of 255 should allow the distribution sufficient time to deploy, resulting in a successful response from the waiter the second time around.

**Comment by richardgavel** [comment]
I've actually had an issue were I needed to include a wait in TF: Because I assign API keys to API Gateway Usage Plans and the TF then completes and runs tests that invoke API Gateway. However, that assignment is eventually consistent. Problem is the terraform gets called from both Windows and Linux machines and I haven't figured out a way to do a universal delay or differentiate the OS. That would also impact being able to look at the exit code.

**Comment by diehlaws** [comment]
Thanks for the additional information @richardgavel. I've presented my findings on this topic to the CloudFront team and am actively working on getting the timeout raised for this waiter across all SDKs so it will wait for a total of 35 minutes instead of 25 before timing out. Once I have more information on this end I will update the issue accordingly.

Please keep in mind that CloudFront is an "origin pull" CDN, meaning the content served to viewers is not propagated to any edge location at the time the distribution is created. Instead, when CloudFront receives a request for an object that has not been requested at a given edge location it reaches out to the origin to fetch the object in question, then caches that object on the edge location that received the request for the amount of time specified either in the `expires` or `cache-control` headers, or in the Default TTL value for the cache behavior corresponding to the object's path if the value for either of these headers is missing or falls outside of the Minimum TTL and Maximum TTL values specified in the cache behavior in question. 
As a result, the amount of content sitting at the distribution's origin does not have any impact on the time it takes to create the distribution - the deployment time for a newly created distribution is a result of the distribution's configuration propagating to all edge locations.

**Comment by richardgavel** [comment]
Is there any update on this issue?

**Comment by th3noname** [comment]
I have the same problem with the `aws cloudfront wait invalidation-completed` command, which tries every 20 seconds 30 times (10 minutes). Within our production evironment this regulary times out.

Is there a chance to increase this timeout as well?

**Comment by exalted** [comment]
I know this is somewhat a "non-answer" however, as a workaround, you could retry `aws cloudfront wait distribution-deployed` again and again since it will exit with a non-zero status code when it timeouts:

```
while ! $(aws cloudfront wait distribution-deployed ... 2> /dev/null); do
  echo 'Waiting for distribution to be deployed...'
done
```

**Comment by kdaily** [comment]
Hi all,

It looks like this change was actually made live. The default wait is 60 seconds, and 35 retries are attempted.

https://github.com/boto/botocore/blob/48b861aa195e41c798cb90643ca100f81b1bd8cb/botocore/data/cloudfront/2020-05-31/waiters-2.json#L7

@th3noname, if you are still experiencing issues with this command (each waiter is configured separately), please open a separate issue. You can also use the Python SDK to configure the waiter timeout and retry:

https://github.com/boto/botocore/issues/981#issuecomment-234415991

Thanks!
