### ISSUE TITLE
aws elbv2 wait target-in-service RateExceeded

### ISSUE THREAD

**Issue by richardgavel** [aws/aws-cli#3898]
We use this call within our Terraform to wait until a target group is healthy before calling the deloyment complete. However, we get RateExceeded errors on and off. The cli should be handle this on its own with backoff/retry logic.

**Comment by justnance** [comment]
@richardgavel - Thanks for posting your request.  Maybe you can help provide a bit more information about it so I can clarify if the behavior is originating from the service or the CLI.   By design, it may [exit with a return code of 255 after 40 failed checks.](https://docs.aws.amazon.com/cli/latest/reference/elbv2/wait/target-in-service.html)

Are there any specific errors returning with the RateExceeded errors?  
What deployment method is in use?  AWS Cloudformation?

**Comment by richardgavel** [comment]
As mentioned, we make this aws cli call from within a Terraform configuration, but in essence, it's just shelling out to AWS CLI. We execute various calls that are based on "wait"s. I'm familar with instances where the check repeats and timeouts because the condition in question hasn't been met. But because this call is occurring within the context of a deployment, a RateExceeded, which I assume means we're being throttled, really can't happen. I was under the impression the aws cli had backoff/retry logic built into it.

**Comment by justnance** [comment]
@richardgavel - The CLI has back-off logic for retrying throttling errors. The debug logs can show us if the retries are failing or if they are not happening at all.  Any chance you can add `--debug` to the command and provide the sanitized version of the output?
