### ISSUE TITLE
s3 cp -recursive option fails if first parameter is a file (Not a directory)

### ISSUE THREAD

**Issue by rmadabhushanam** [aws/aws-cli#3909]
here is current behaviour

> aws s3 cp mydir s3://mybucket --recursive

performs copy of all files in current directory recursively. But, below command fails to perform any copy.

> aws s3 cp myfile s3://mybucket --recursive

Here expected goal is to perform copy of single file and not fail because it is not a directory. 

This feature will simply the logic when handling the copy of multiple files in an automated way, with out checking whether source is a file or object.

**Comment by jamesls** [comment]
I believe that was done for consistency with downloads.  I think what you're describing can make sense for uploads, but it's less clear what we should do for downloads, and we'd preferably want consistent behavior for both uploads and downloads.  For example, what if I had:

```
$ aws s3 cp myfile s3://bucket/recursive
$ aws s3 cp myfile s3://bucket/recursive/myfile
```

What should be the expected behavior of:

```
$ aws s3 cp s3://mybucket/recursive --recursive
```

If we can work out a consistent way to handle uploads and downloads I think it's something we can look at implementing.
