### ISSUE TITLE
aws pinpoint update-apns-channel: missing credentials

### ISSUE THREAD

**Issue by Jordan-McMillan101** [aws/aws-cli#3936]
`aws --version`
`aws-cli/1.16.76 Python/2.7.10 Darwin/16.7.0 botocore/1.12.66`

I'm trying to programmatically add an APNS_SANDBOX channel to a pinpoint app. I'm able to do this successfully via the pinpoint console, but not with aws cli or a lambda function which is the end goal. Changes to our Test/Prod environments can only be made via the CodePipeline, but for testing purposes I'm trying to achieve this with the aws cli.

I've tried both aws cli (using the root credentials) and a lambda function -- both result in the following error:

`An error occurred (BadRequestException) when calling the UpdateApnsSandboxChannel operation: Missing credentials`

I have tried setting the Certificate field in the UpdateApnsSandboxChannel json object as the path to the .p12 certificate file as well as using a string value retrieved from the openssl tool.

Today I worked with someone from aws support, and they were not able to figure out the issue after trying to debug for a couple of hours. They said they would send an email to the pinpoint team, but they did not have an ETA on when they might respond.

Please help and thank you for your time.

**Comment by Jordan-McMillan101** [comment]
I ended up getting this to work successfully -- This is why it was failing:

I was originally making the cli call with the following request object as this is what is including in the documentation:
```
{
    "APNSSandboxChannelRequest": {
        "BundleId": "com.bundleId.value", 
        "Certificate":"P12_FILE_PATH_OR_CERT_AS_STRING", 
        "DefaultAuthenticationMethod": "CERTIFICATE", 
        "Enabled": true, 
        "PrivateKey":"PRIVATEKEY_FILE_PATH_OR_AS_STRING",
        "TeamId": "",
        "TokenKey": "",
        "TokenKeyId": ""
    }, 
    "ApplicationId": "Pinpoint_PhysicalId"
}

```

After playing around with it some more I got it to work by removing BundleId, TeamId, TokenKey, and TokenKeyId. I believe these fields are needed when using a p8 certificate.

```

{
    "APNSSandboxChannelRequest": {
        "Certificate":"P12_FILE_PATH_OR_CERT_AS_STRING", 
        "DefaultAuthenticationMethod": "CERTIFICATE", 
        "Enabled": true, 
        "PrivateKey":"PRIVATEKEY_FILE_PATH_OR_AS_STRING"      
    }, 
    "ApplicationId": "Pinpoint_PhysicalId"
}

```

**Comment by justnance** [comment]
@Jordan-McMillan101 - Thank you for contact us about this issue and glad to hear the issue was resolved.  I discussed this issue with our Premium Support team and stepped through reproducing the issue with the information provided.  

With the information you provided, I found the use of the options specifically under the Pinpoint documentation may not be so clear because the use of options is listed in other places.  The global use of the options with all CLI commands is the same so it is not listed under each individual command.  As per our [CLI user guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-help.html): 

> If an option is shown in square brackets, it's either optional, has a default value, or has an alternative option that you can use instead. 

The synopsis section in the CLI reference also indicates "[options without square brackets indicate the option is required.](https://docs.aws.amazon.com/cli/latest/reference/)".   

As such with both of the following commands, there are only 2 required options: 

[aws pinpoint update-apns-channel](https://docs.aws.amazon.com/cli/latest/reference/pinpoint/update-apns-channel.html)
>  update-apns-channel
--apns-channel-request <value>
--application-id <value>
[--cli-input-json <value>]
[--generate-cli-skeleton <value>]

[aws pinpoint update-apns-sandbox-channel](https://docs.aws.amazon.com/cli/latest/reference/pinpoint/update-apns-sandbox-channel.html)
>   update-apns-sandbox-channel
--apns-sandbox-channel-request <value>
--application-id <value>
[--cli-input-json <value>]
[--generate-cli-skeleton <value>]

I am discussing this issue with our documentation writers as we continually look for ways to improve.  Please advise if there is any feedback on how we can improve our documentation.
