### ISSUE TITLE
Sagemaker VPC Endpoint not getting connected from Lambda

### ISSUE THREAD

**Issue by awsCloudPractitioner** [aws/aws-cli#3940]
Hello Team - We are facing an issue when trying to access sagemaker api from Lambda code. The code works fine when the lambda function does not have any VPC/security groups network settings. However, after adding VPC, subnets and security groups to Lambda , it is not able to connect to Sagemaker API. 

We have created VPC endpoint for Sagemaker.api and Sagemaker.runtime services and attached the same subnets and security groups. Looks like something more needs to be done to make this flow work. 

Appreciate your help to resolve this issue.

**Comment by justnance** [comment]
@awsCloudPractitioner - Thank you for reporting this issue and reaching out for guidance.  Do you have the CLI commands in use so I can try reproduce the issue and understand the behavior to determine if there is a bug in the CLI.  It would also help if you can post the sanitized output using the [`--debug option`](https://docs.aws.amazon.com/cli/latest/reference/index.html).  

Initially, it sounds like the issue may be isolated to a network issue and [Configuring a Lambda Function to Access Resources in an Amazon VPC](https://docs.aws.amazon.com/lambda/latest/dg/vpc.html):

> AWS Lambda runs your function code securely within a VPC by default. However, to enable your Lambda function to access resources inside your private VPC, you must provide additional VPC-specific configuration information that includes VPC subnet IDs and security group IDs. AWS Lambda uses this information to set up elastic network interfaces (ENIs) that enable your function to connect securely to other resources within your private VPC.

> AWS Lambda does not support connecting to resources within Dedicated Tenancy VPCs. 

> The Lambda function execution role must have permissions:
- to create, describe and delete ENIs.
- for the necessary EC2 actions

There are other requirements around configuring access to the internet.  As such, it is recommended to reach out the [AWS Premium Support](https://console.aws.amazon.com/support/home#/) for additional guidance.

**Comment by awsCloudPractitioner** [comment]
Hi - Thanks so much for responding. I have CLI installed and functional. Let me know which command you want me to run and give you logs for that. Right now I am using console to do all this work so I don't have the results for these commands handy. 

Code snippets from Lambda - 
sagemaker = boto3.client('sagemaker')
sagemaker.create_training_job(<passing the parameters here>)

As per the Cloud Watch logs for this Lambda, its trying to setup connection and eventually timed out -
Starting new HTTPS connection (1): sagemaker.us-east-1.amazonaws.com
Starting new HTTPS connection (2): sagemaker.us-east-1.amazonaws.com
Starting new HTTPS connection (3): sagemaker.us-east-1.amazonaws.com........................

**Comment by justnance** [comment]
@awsCloudPractitioner - Thank you for your feedback.  [CLI commands for SageMaker can be found in our CLI reference](https://docs.aws.amazon.com/cli/latest/reference/sagemaker/index.html)  The [`--debug` option](https://docs.aws.amazon.com/cli/latest/reference/) is a global command that can be used with any CLI command. 

Based on the details provided so far, the behavior initially looks like a network issue.  Our online documentation for [Authentication and Access Control for Amazon SageMaker
](https://docs.aws.amazon.com/sagemaker/latest/dg/authentication-and-access-control.html
) and [Connect to Amazon SageMaker Through a VPC Interface Endpoint
](https://docs.aws.amazon.com/sagemaker/latest/dg/interface-vpc-endpoint.html) might be a good starting point for trouble shooting this issue and getting started with CLI commands.  Just know CLI will echo any errors or issues returned from the service.  

It is recommended to reach out to [AWS Premium Support](https://console.aws.amazon.com/support/home#/).  Using the request ID, they can investigate some of the following SageMaker issues with their internal tools:

- ResponseSize
- SidecarUrl
- PreActivityLatency
- HttpStatusCode
- PayloadSize
- ModelLatency
- PostActivityOverheadLatency
- OverheadLatency

They can also investigate the following if you are able to share your CloudWatch logs:

- Invocation4XXErrors
- Invocation5XXErrors
- Invocations
- InvocationsPerInstance
- ModelLatency
- OverheadLatency

Since this issue is not a problem with the CLI it needs to be moved to the [SageMaker forums](https://forums.aws.amazon.com/forum.jspa?forumID=285) or a case submitted to [AWS Premium Support](https://console.aws.amazon.com/support/home#/).
