### ISSUE TITLE
lambda, region has to be specified, even when ARN is used

### ISSUE THREAD

**Issue by PSLLSP** [aws/aws-cli#3954]
This is not a bug but something like an idea for improvement.

I don't have default region configured and I have to specify it on command line.
When I try to describe lambda function, I can use ARN and ARN points to a region.
Even that region is part of ARN, I have to implicitly specify it on command line.

Examples:

```
$ aws lambda get-function --function-name arn:aws:lambda:us-east-1:123456789012:function:some-lambda

You must specify a region. You can also configure your region by running "aws configure".
```

This works:
```
$ aws lambda get-function --function-name arn:aws:lambda:us-east-1:123456789012:function:some-lambda --region us-east-1
```

And this doesn't work (and I think this is ok):
```
$ aws lambda get-function --function-name arn:aws:lambda:us-east-1:123456789012:function:some-lambda --region us-east-2

An error occurred (ResourceNotFoundException) when calling the GetFunction operation: Functions from 'us-east-1' are not reachable in this region ('us-east-2')
```

```
$ aws --version
aws-cli/1.15.83 Python/2.7.14 Linux/4.14.88-88.73.amzn2.x86_64 botocore/1.10.82
```

```
$ aws --version
aws-cli/1.16.101 Python/3.6.7 Linux/4.4.0-17134-Microsoft botocore/1.12.91
```

**Comment by justnance** [comment]
@PSLLSP - Thanks for posting your idea for a new feature.  

We require an ARN when you need to specify a resource unambiguously across all of AWS including API calls but some resources do not require a region so the region might be omitted from ARN.  As such, since not all ARN _point to a region_ this feature could cause a break change.  

Related documentation: https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html
