### ISSUE TITLE
Why doesn't "aws s3 sync" accept --expected-size?

### ISSUE THREAD

**Issue by neongreen** [aws/aws-cli#4008]
`aws s3 cp` takes `--expected-size`:

> Failure to include this argument under these conditions may result in a failed upload due to too many parts in upload.

However, `aws s3 sync` doesn't. Does it mean that if I use `aws s3 sync` to upload a directory with files that are bigger than 5GB, the upload might fail? If so, what can I do to work around it?

**Comment by neongreen** [comment]
Oh, or is `--expected-size` only needed when uploading a stream, not files?

**Comment by zeniri** [comment]
--expected-size (string) This argument specifies the expected size of a stream in terms of bytes. Note that  **this argument is needed only when a stream is being uploaded to s3** and the size is larger than 5GB. Failure to include this argument under these conditions may result in a failed upload due to too many parts in upload.
**Source: AWS Docs**

The aws s3 sync and aws s3 cp are the high level commands for the work around S3 with AWS CLI.
_The sync command synchronizes the contents of a bucket and a directory, or two buckets even in different regions._ Thus, what it does is just an sync only the updated portion between files/directories. Therefore one cannot use --expected-size option because the person if using sync command will be using it to synchronize and cannot know what will be the size of the data to be synced. However if using it to sync new files in an old folder between the s3 bucket/local and local/another-s3-bucket one should use copy if the sync command fails because that isn't the use-case of sync command.

So using --expected-size with sync command is not a wise choice and **file changes** larger than 5GB shouldn't fail.

I hope you received the answer to both of your queries.

**Comment by justnance** [comment]
@neongreen - Thanks for your post.  The feedback provided by @zeniri' is correct and spot-on.  Thanks for the solid explanation @zeniri.  

[**Source: AWS Docs**](https://docs.aws.amazon.com/cli/latest/reference/s3/cp.html)

**Comment by zeniri** [comment]
@justnance your welcome just here to help!
