### ISSUE TITLE
Unknown option when use aws s3 sync

### ISSUE THREAD

**Issue by liaogz82** [aws/aws-cli#4031]
I am running this command `ls | awk -v snumber=201412 '$1>snumber' | xargs -n1 aws s3 sync {$1} s3://BUCKET-NAME/s3fs-public/images/{$1} --acl public-read --dryrun` and it keeps giving me an error

```
Unknown options: 201501
xargs: aws: exited with status 255; aborting
```

Yes there is folder called 201501 that I want to sync, but I cant tell if it is a xargs error or aws error. Can help?

**Comment by swetashre** [comment]
@liaogz82 - Thank you for reporting the behavior. This error is due to the incorrect formulation of xargs command . CLI is working as expected.

Here is the command i executed to check the parameters that are being passed from xargs to AWS command.

```
$ ls | awk -v snumber=201412 '$1>snumber' | xargs -n1 echo aws s3 sync {$1} s3://BUCKET-NAME/s3fs-public/images/{$1} --acl public-read --dryrun

aws s3 sync {} s3://BUCKET-NAME/s3fs-public/images/{} --acl public-read --dryrun 201501
```
As you can see 201501 is not being passed as a input folder , instead it's being passed as an option . That's why AWS CLI is throwing error.

Here is the command to get the desired output.
```
$ ls | awk -v s=201412 '$1>s'| xargs -n1 -I %  aws s3 sync % s3://BUCKET-NAME/s3fs-public/images/% --acl public-read --dryrun

```

**Comment by liaogz82** [comment]
thank you. I have confirmed it works and you can close this issue.
