### ISSUE TITLE
Whitespaces not handled properly in cloudformation deploy parameter overrides

### ISSUE THREAD

**Issue by saiviswanath** [aws/aws-cli#4055]

**Comment by saiviswanath** [comment]
Currently when running aws cloudformation deploy \
        --template-file <> \
        --stack-name <> \
        --capabilities CAPABILITY_NAMED_IAM \
        --no-fail-on-empty-changeset \
        --parameter-overrides <> \
        --tags <>

whitespaces are not properly handled in --parameter-overrides.

Eg: --parameter-overrides Foo=A B C Foo1=Foo2 
 characters post whitespace are ignored. It takes it as Foo=A.

Tried 
--parameter-overrides Foo="A B C" Foo1=Foo2
--parameter-overrides "Foo=A B C" Foo1=Foo2
--parameter-overrides Foo="A\ B\ C" Foo1=Foo2

**Comment by swetashre** [comment]
@saiviswanath - Thank you for your post .It looks like that CLI is taking A,B and C as three different value because of the space .That's why its taking Foo=A and in this case it will give an error. 
It should work by quoting the entire Key=Value. It looks like this is a duplicate of #3274.
Let me know if it works for you.

**Comment by saiviswanath** [comment]
@swetashre- Quoting the entire key value like "Key=Value" even doesn;t work. As shown in my examples as well.

**Comment by Fectorez** [comment]
Try this :
--parameter-overrides "key=my\ value"

**Comment by kdaily** [comment]
@saiviswanath does this fix this for you?

**Comment by vfrank66** [comment]
I currently have this error on `--tags` but it functions the same for `--parameter-overrides` on this command. Even though this error is related to how the shell handles spaces/arrays/string it sends in the --parameters-overrides one long string in the cases above, but I feel like the cli should be handling this. For `cloudformation deploy` there is already a method `parse_key_value_arg()` that parses both the parameters and tags (my error is the tags). In this function there could be check for single parameter with multiple `=` and it could reparse this out since it has specific formatting for parameters and overrides. 

The aws cli code assumption is by the time you get to `parse_key_value_arg()` the parameters overrides (and tags) are an "Array of strings, where each string is of form Key=Value". But depending on how you load that string in shell and how python cli accepts sys.argv, plus we cant use a file, it is typically with jq and possibly sed, sometimes the shell will send in to the aws cli a "string "in the form Key=Value.

Method location:
https://github.com/aws/aws-cli/blob/develop/awscli/customizations/cloudformation/deploy.py#L397

An example of bash sending in the wrong sys.argv into python:
![image](https://user-images.githubusercontent.com/7524999/153530833-b060d1ea-5654-4213-9817-f54300df40fc.png)


My example, I have to handle spacing in these values + arrays so my jq is different but
```bash
# LOAD PARAMS: aws cli - correctly identifies this as a array of strings 
params=$(cat blah-parameters-${environment}.json \
    | jq '.[] | .ParameterKey + "=" + if .ParameterValue|type=="array" then .ParameterValue | join(",") else .ParameterValue end ' \
    | sed -e 's/"//g' \
    | sed -e $'s/\r//g' | tr '\n' ' ')

# LOAD TAGS TWO FILES: aws cli -incorrectly treats this as a single string
tags=$(cat tags-common.json | \
	jq '.[] | (.Key + "=" +.Value)' | \
	sed -n -e 'H;${x;s/\n/ /g;s/^ //;p;}' | \
	tr '\n' ' ')
tags=$tags$(cat tags-${environment}.json | \
    jq '.[] | (.Key + "=" +.Value)' | \
    sed -n -e 'H;${x;s/\n/ /g;s/^ //;p;}')

   ...
   
    aws cloudformation deploy \
    --template-file "stack-name-transform.yaml" \
    --stack-name "stack-name" \
    --parameter-overrides "${params}" \
    --tags "${tags}"
```
This is the output echo'ed out, as you can see no difference between the parameters and tags, mine is failing the the bash script on the `$tags`
```bash
   aws cloudformation deploy \
    --region us-east-1 \
    --no-fail-on-empty-changeset \
    --template-file ./cfn/stack-name-transform.yaml \
    --stack-name stack-name-sand \
    --capabilities CAPABILITY_NAMED_IAM \
    --parameter-overrides Environment=sand CertificateArn=arn:aws:acm:us-east-1:::: DomainName=test.api.io \
    --tags TAG1=stack-name TAG2=Yes CostCenter=78-900 TAG3='a string' Environment=Sandbox
```

If I take the echo output and then copy that to the clipboard and then paste that without any variable interpolation it will run successfully. 

If it is in the bash script it will fail because `$tags` is a single string to the cli.  To me this should be handled by the cli, since for the cicd automation of tag and parameters files with aws cli deploy it is a good amount of work to figure out how the python aws cli will accept inputs.

**Comment by PalituxD** [comment]
I resolved this scenario using options below: 

`
"scripts": {
    "invoke": "sam ... --parameter-overrides \"$(jq -j 'to_entries[] | \"\\(.key)='\\\\\\\"'\\(.value)'\\\\\\\"''\\ '\"' params.json)\""
  }
`

Or

`
sam ... --parameter-overrides "$(jq -j 'to_entries[] | "\(.key)='\\\"'\(.value)'\\\"''\ '"' params.json)"
`
