### ISSUE TITLE
Codestar: Unknown parameter in input: "toolchain" or "sourcecode"

### ISSUE THREAD

**Issue by hoang-innomizetech** [aws/aws-cli#4101]
When using AWS CLI version aws-cli/1.11.134 Python/2.7.10 Darwin/18.5.0 botocore/1.6.1

I followed [this](https://docs.aws.amazon.com/codestar/latest/userguide/cli-tutorial.html) instruction to create a custom project. When I run `aws codestar create-project --cli-input-json file://input.json` command, I got below error

```
Parameter validation failed:
Unknown parameter in input: "toolchain", must be one of: name, id, description, clientRequestToken
Unknown parameter in input: "sourceCode", must be one of: name, id, description, clientRequestToken

```

The input.json file I used is the same as the one mentioned on the above article

Does anyone know how to fix this error?

**Comment by swetashre** [comment]
@hoang-innomizetech - Thank you for your post. With the latest version of CLI (1.16.144) this command is working as expected. 
```
$ aws codestar create-project --cli-input-json file://input.json
{
    "arn": "arn:aws:codestar:us-west-2:413287592343:project/myproject"
}
```
As you are using the older version of CLI ```toolchain``` and```SourceCode``` is not set as required parameters in .json file and that's why you are getting parameter validation failed error.

I would recommend updating your CLI version. Here is the link https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html
