### ISSUE TITLE
S3 Progress --- wrong number of files remaining

### ISSUE THREAD

**Issue by VitBu** [aws/aws-cli#4113]
I am copying 105GB / 580,000 files from my PC to s3 Bucket. 

Using a  command similar to: 

`aws s3 cp C:/something s3://something --recursive `

The copy is actually taking place, and I got informed when files finishes to upload.
I am getting a progress similar to this:

> Completed 6.7 GiB/~6.9 GiB (3.3 MiB/s) with ~1005 file(s) remaining (calculating...)

No matter how much files left to upload it always returns 1005 or 1004 files remaining.
And the total size of the transfer (6.9 GiB in the example) is getting higer and higher.

**Comment by justnance** [comment]
@VitBu - Thank you for reporting this behavior.  There is a little history related to the s3 cp progress output.  How the the current s3 progress works is explained issue #488 which discusses the implementation of adding "approximate count" progress output.  Issue #488 goes into detail on how memory is consumed in the process and may contribute to the "approximate count" in the expected output.   Since then, issue #2269 was marked as a feature request tracking the improvement of a progress bar for s3 cp. 

Please review the details in the related issues and advise if you think the behavior you are seeing is a bug to which I can continue to investigate.  If not, please add a 👍 and/or comment to the feature request we are tracking under issue @2269.
