### ISSUE TITLE
aws-cli config in sagemaker notebook

### ISSUE THREAD

**Issue by amitgupta1984** [aws/aws-cli#4139]
Hi,
I was trying to push my docker image from sagemaker notebook and was successful in doing that . But i'm confused how was i able to get temporary login without setting up aws configure in the notebook. Ideally we need to do aws configure before we run any aws command for getting or making any aws service do anything. Interestingly when i ran the **ls  ~/.aws** , i got only .config file and not credential file. How is this thing even working?

https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/scikit_bring_your_own/scikit_bring_your_own.ipynb

Can someone please help me understand when and how aws configure happened and what access key id was used to push to ecr

Thanks!

**Comment by justnance** [comment]
@amitgupta1984 - Thanks for your post.  I'm glad to hear the process to push your docker image from your SageMaker Notebook was successful.  

Sagemaker is a [fully managed learning service](https://docs.aws.amazon.com/sagemaker/latest/dg/whatis.html), [requires credentials](https://docs.aws.amazon.com/sagemaker/latest/dg/authentication-and-access-control.html), and [uses temporary credentials](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_aws-services-that-work-with-iam.html#machine_learning).  From the link you shared it appears SageMaker was setup with permissions using an `IAM role`.  

[When you run CLI commands using a profile that specifies an IAM role, the AWS CLI uses the source profile's credentials to call AWS Security Token Service (AWS STS) and requests temporary credentials for the specified role. The user in the source profile must have permission to call sts:assume-role for the role in the specified profile. The role must have a trust relationship that allows the user in the source profile to assume the role. The process of retrieving and then using temporary credentials for a role is often referred to as assuming the role.](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html#cli-role-prepare).  The [profile for the role is defined in the ~/.aws/config file](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html).  An [example of this configuration](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html) is listed in our documentation.

You can use the following `iam` commands to learn more about the `iam roles` in your aws account:

[Get a list of IAM roles on your account:](https://docs.aws.amazon.com/cli/latest/reference/iam/list-roles.html)
```
aws iam list-roles
```

[To get the details of a specific role:](https://docs.aws.amazon.com/cli/latest/reference/iam/get-role.html)
aws iam get-role --role-name SageMakerRole

Since the CLI is working as expected, I recommend reaching out to the SageMaker Developer Forums or to AWS Premium Support for more usage guidance.

**Comment by amitgupta1984** [comment]
@justnance Thanks this helps a lot :) . Closing this out
