### ISSUE TITLE
aws cloudformation deploy does not refresh credentials

### ISSUE THREAD

**Issue by mseiwald** [aws/aws-cli#4200]
Hi,

we are using `aws cloudformation deploy` on an EC2 instance (with instance role credentials). When the update of a Cloudformation stack takes longer than 1 hour, the command fails with `Failed to create/update the stack.` even though the stack update is still in progress. I assume that awscli does not refresh the credentials in this case. In any case, the error message is very misleading.

Thanks

**Comment by justnance** [comment]
@mseiwald - Thanks for reporting this issue.  It is possible there is an [issue with the IAM instance role](https://docs.aws.amazon.com/IAM/latest/UserGuide/troubleshoot_iam-ec2.html) because the instance role [should get a refreshed set of credentials every hour, or at least 15 minutes before the current set expires.](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html#roles-usingrole-ec2instance-roles).  I would have to reproduce this issue exactly but it would helpful if you can provide a sanitized output of the `--debug` option so we can see what is happening.
