### ISSUE TITLE
aws cloudformation package causes internet connection to drop

### ISSUE THREAD

**Issue by kaitlynbrown** [aws/aws-cli#4236]
I run the following command to package my aws sam template:
`aws cloudformation package --template-file cloudformation.yml --s3-bucket mm-build-artifacts --output-template-file packaged-template.yml`

Over the last several days, this has consistently caused my internet connection to drop, within a minute of starting execution, approximately half of the times I have attempted (about 20 in total). This causes the command to hang until the connection is restored. 
This *only* happens when trying to package my cloudformation template using the aws-cli. Otherwise, I have had no connectivity issues whatsoever.
Turning my wifi off and back on again restores my internet connection, and causes the command to resume (as long as not too much time has passed).
When my connection drops, my co-workers report their connections as completely fine with no problems.

Also, I'm not sure if this is related or not, but it seems to upload the template to S3 multiple times each time I run the command. It goes from 0% to 100%, stays there for a minute, then starts over again 5 or 6 times before finally completing. The whole process takes more than 10 minutes for a template with only 38 lambdas.

**Comment by justnance** [comment]
@kaitlynbrown - Thanks for reporting this issue.  Referring to "This only happens when trying to package my cloudformation template using the aws-cli.", please confirm if this problem exists when using the AWS Management Console.  Also, please confirm if the problem exists when using an EC2 Instance and while using the latest version of the CLI.   I also recommend posting this issue on the [AWS Forums for the service](https://forums.aws.amazon.com/forum.jspa?forumID=92) to see if anyone else has encountered this issue and can provide further help.  

@sanathkr , what are your thoughts?

**Comment by sanathkr** [comment]
I can't imagine why the command would make your connection to drop. May be your router is getting overwhelmed due to the large upload volume?

**Comment by kaitlynbrown** [comment]
@justnance I have set up a CodeBuild project with a post-build phase that runs the following command:
`aws cloudformation package --template-file cloudformation.yml --s3-bucket mm-build-artifacts --output-template-file packaged-template.yml`
It hasn't failed or lost internet connection once. It only happens when running from the aws cli locally.

In the two weeks since posting this, the problem seemed to disappear, but the problem came back today with a vengeance. I'm a half hour into my day and it has literally already happened 4 times. It happened multiple times while typing this comment (and trying to package my project locally). My co-workers report no problems whatsoever with their internet connections. It only happens when running `aws cloudformation package`.

**Comment by justnance** [comment]
@kaitlynbrown - Thanks for your feedback.  Like @sanathkr mentioned, the CLI command would not cause this network problem.  Here's some trouble shooting that might help. 

- What are the results when the issue is reproduced on a different computer with the same internet connection or run the CLI command on an EC2 Instance?  
- How large is the total uploaded? 
- Is it uploading all of the code for the lambdas that is referenced in the template? 

 This problem seems to be related to an issue with the network driver on the local computer which is possibly triggered by the optimized way the CLI uploads file in parallel.  If the wifi is dropping when a uploading large files then it is recommended to test uploading it to S3 from the console from the same computer. 

I hope this helps.
