### ISSUE TITLE
cloudwatch logs filterLogEvents incorrect results 

### ISSUE THREAD

**Issue by byskr** [aws/aws-cli#4262]
When requesting the log entries for a certain timespan I experienced following behavior.
When the timestamp of a log event equals the `--end-time` parameter it is not returned, in opposite to what is documented.

e.g.
`aws logs filter-log-events --log-group-name=/some-log-group-name --start-time=1561183562759 --end-time=1561247999000`

### expected
```
{
    "searchedLogStreams": [
       ...
    ],
    "events": [
        {
            "ingestionTime": 1561183563588, 
            "timestamp": 1561183562759, 
            "message": "some message 1", 
            "eventId": "...", 
            "logStreamName": "..."
        },
        {
            "ingestionTime": 1561205163932, 
            "timestamp": 1561205163058, 
            "message": "some message 2", 
            "eventId": "...", 
            "logStreamName": "..."
        }, 
        {
            "ingestionTime": 1561248363591,
            "timestamp": 1561247999000, 
            "message": "some message 3", 
            "eventId": "...", 
            "logStreamName": "..."
        },
    ]
}
```
### got
```
{
    "searchedLogStreams": [
       ...
    ],
    "events": [
        {
            "ingestionTime": 1561183563588, 
            "timestamp": 1561183562759, 
            "message": "some message 1", 
            "eventId": "...", 
            "logStreamName": "..."
        },
        {
            "ingestionTime": 1561205163932, 
            "timestamp": 1561205163058, 
            "message": "some message 2", 
            "eventId": "...", 
            "logStreamName": "..."
        }
    ]
}
```

I experienced this behaviour with the cli, node and golang.

**Comment by kyleknap** [comment]
I can confirm that whenever a value for `--end-time` is specified that is the same value as the timestamp for one of the logs, it does not return the log message with that matching timestamp (i.e. `1561247999000` in your example). Looking over the debug logs, the CLI appears to be sending the correct request and the service is the one not returning the log. So there is nothing really more the CLI can do here.

I'd recommend reaching out to the service team via their [forums](https://forums.aws.amazon.com/forum.jspa?forumID=138) or through AWS support to see if this is intentional and if their documentation needs to be updated.
