### ISSUE TITLE
CloudFormation deploy Not Executing Change Set

### ISSUE THREAD

**Issue by TebanSierra** [aws/aws-cli#4277]
### Description

I'm working with Jenkins + SAM to deploy lambdas. How ever when I reach the deploy stage at my Jenkins Pipeline and execute the following:

`sam deploy --template-file ./package.yaml --stack-name nequi-data-${stackName} --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --region us-east-1`

The console output of Jenkins is: 

```sh
sam deploy --template-file ./package.yaml --stack-name nequi-data-ndt-lambda-test --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --region us-east-1

Waiting for changeset to be created..

'Status'
```

After check the CloudFormation console I get:

**Stack Status:** REVIEW_IN_PROGRESS
**Change Set Status:** CREATE_COMPLETE

The problem: Deploy method is not executing Change Set

Permissions are already checked so the Role doing the Job have permisson for ExecuteChangeSet

### Observed result

```sh
Exception: Command '['aws', 'cloudformation', 'deploy', '--capabilities', 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', '--region', 'us-east-1', '--stack-name', u'nequi-data-ndt-lambda-test', '--template-file', './package.yaml']' returned non-zero exit status 255
```

This SAM CLI debug print means that under `sam deploy` I'm executing: 

`aws cloudformation deploy --template-file ./package.yaml --stack-name nequi-data-ndt-lambda-test --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --region us-east-1`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: CentOS
2. `aws --version`: aws-cli/1.16.185 Python/2.7.5 Linux/3.10.0-514.16.1.el7.x86_64 botocore/1.12.175 
3. `sam --version`: SAM CLI, version 0.17.0

**Comment by justnance** [comment]
@TebanSierra - Thank you for posting this issue, providing the arguments entered to CLI, and the exception.  I am trying to reproduce this issue but need more information.  Please tell me about the IAM resources in use.  I think it is not related to a permissions because you stated:

>Permissions are already checked so the Role doing the Job have permisson for ExecuteChangeSet

I'm looking to replicate the IAM configuration and need to know more about the use of the `--capabilities` and [if custom names are in use or not](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/deploy/index.html).  Looks like you are trying to use:

```
--capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
```

If custom names are not in use then `CAPABILITY_NAMED_IAM` is not required.  Also, when working with `--capabilities (list)`, only [one of these capabilities](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html) are required. [The following IAM resources require you to specify **either** the CAPABILITY_IAM **or** CAPABILITY_NAMED_IAM capability.
](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html).

Let us know if this helps.

**Comment by TebanSierra** [comment]
After an extensive review I was able to find out that was a permissions issue. However, neither aws-cli nor aws-sam-cli was capturing them.

The permission error was shown in the CloudFormation console, under the "Events" tab of the created Stack.

**Comment by justnance** [comment]
@TebanSierra - Thank you for the feedback.  The AWS CLI does not have control over this behavior as it is only echoing what is being returned by the service.  It looks like this is an enhancement the CloudFormation Service team could address.  If you can reach out to them on their [forums](https://forums.aws.amazon.com/forum.jspa?forumID=92) and post the forum link here, I can escalate it internally.

**Comment by AltruCoder** [comment]
@TebanSierra - What was the missing permission?  I'm having the same issue, but nothing is showing in the "Events" tab.

**Comment by afireinside09** [comment]
Any info on the missing permission? Running into this exact problem

**Comment by cb-bobin** [comment]
@afireinside09 Did you manage to figure out what was missing in your case?
Ran into this same problem, with no failure or error messages. Got resolved after providing the (list, describe) permissions for changesets.

**Comment by gh-pyen** [comment]
I was getting the same behavior, and I figured out that the missing permission in my case was `cloudformation:DescribeChangeSet`.
