### ISSUE TITLE
SSL Certification issue using CLI

### ISSUE THREAD

**Issue by kishorekkota** [aws/aws-cli#4279]
Seeing below error when running aws cli commands.

SSL validation failed for https://sts.us-east-1a.amazonaws.com/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1051)

Env details

± |master U:5 ?:2 ✗| → aws --version
aws-cli/1.16.184 Python/3.7.1 Darwin/17.7.0 botocore/1.12.174

Behind Proxy and have PROXY set in the ENV

When I use --no-verify-ssl getting DNS error.

Your requested host "sts.us-east-1a.amazonaws.com" could not be resolved by DNS.

**Comment by justnance** [comment]
@kishorekkota - Thank you for reporting this issue.  The DNS error could be because "sts.us-east-1a.amazonaws.com" is not a valid endpoint.  The [STS regional endpoint](https://docs.aws.amazon.com/general/latest/gr/rande.html#sts_region) for us-east-1 is `sts.us-east-1.amazonaws.com`.   

If this does not resolve the issue, please reply with steps to reproduce the issue and the output of `--debug` option so I can investigate further.
