### ISSUE TITLE
create-change-set does not allow using StackPolicyBody in --cli-input-json

### ISSUE THREAD

**Issue by dthielking** [aws/aws-cli#4329]
Hello,

I am using `aws cli` to create and execute CloudFormation change sets. I saw that there is an option to enable us to control what is allowed while updating our CF Stacks. (Stack Policies)
If I create a cli skeleton for creating/updating a stack like `aws cloudformation create-stack  --generate-cli-skeleton > out.json` I see that there is a field called StackPolicyBody.
If I do the same but for a different create-change-set there is no field like that. 
Why is that missing?

Thank you for clarifying that to me.

**Comment by justnance** [comment]
Thank you for posting this issue. 

According to our [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-ug.pdf), the API parameter `StackPolicyBody` is being used in the following [API calls](https://docs.aws.amazon.com/search/doc-search.html?searchPath=documentation-guide&searchQuery=StackPolicyBody&x=0&y=0&this_doc_product=AWS%20CloudFormation&this_doc_guide=API%20Reference&doc_locale=en_us#facet_doc_product=AWS%20CloudFormation&facet_doc_guide=API%20Reference):

[SetStackPolicy](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_SetStackPolicy.html)
[GetStackPolicy](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_GetStackPolicy.html)
[CreateStack](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html)
[UpdateStack](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_UpdateStack.html) 

As you pointed out, `StackPolicyBody` is not listed with `aws cloudformation create-change-set` because the service is not explosing it to the CLI.  It is also not listed with the `CreateChangeSet` API parameters as shown [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateChangeSet.html). 

According to our docs, after you apply a stack policy, you can't remove it from the stack, but you can use the AWS CLI to modify it.  To set a stack policy when you create a stack, you can use the CLI command `aws cloudformation create-stack` with the `--stack-policy-body` option to type in the modified policy.  To modify the stack policy, you can use the CLI command `aws cloudformation set-stack-policy` with the `--stack-policy-body` option to type in a modified policy.   If you execute a change set on a stack that has a stack policy associated with it, AWS CloudFormation enforces the policy when it updates the stack. You also can't specify a temporary stack policy that overrides the existing policy when you execute a change set. To update a protected resource, you must update the stack policy or use the [direct modification method](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-direct.html).  There is an example of direct modification [posted in our docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-changesets-samples.html#using-cfn-updating-stacks-changesets-samples-directly-editing-a-template).

This behavior is controlled by the CloudFormation service and not the CLI.  To submit a feature request to the service team, I suggest reaching out to the [service team forums](https://forums.aws.amazon.com/forum.jspa?forumID=92) or [AWS Premium Support](https://console.aws.amazon.com/support/home#/). 

I hope this answers your question.

**Comment by hoxu** [comment]
Was a feature request filed upstream? The CloudFormation (CLI) API is missing a lot of parameters I would expect to be there for consistency, and `create-change-set --stack-policy-body` is one of them.
