### ISSUE TITLE
aws s3 presign url adds us-east-2 by default

### ISSUE THREAD

**Issue by beyondszine** [aws/aws-cli#4338]
Hi all,
I am experiencing a problem of bad URL generation with aws cli.
```sh
$ aws --version
aws-cli/1.16.81 Python/2.7.15+ Linux/4.15.0-43-generic botocore/1.12.71
```
Example: (morphed values)
```sh
○ → aws s3 presign 's3://ml-static-files/cfg.zip'
https://ml-static-files.s3.amazonaws.com/cfg.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=3600&X-Amz-Credential=xyxyxyxyxus-east-2%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Date=20190723T113238Z&X-Amz-Signature=xyxyxyxyxxyxyx
```
The URL being generated is forcing region 'us-east-2' for reasons not being understandable to me.
Irrespective of any bucket from any region I choose, the region that comes in presign URL is 'us-east-2' only.
On requesting the URL, the following response comes on page.
```xml
<Error>
<Code>AuthorizationQueryParametersError</Code>
<Message>
Error parsing the X-Amz-Credential parameter; the region 'us-east-2' is wrong; expecting 'ap-south-1'
</Message>
<Region>ap-south-1</Region>
<RequestId>XXXXXXXX</RequestId>
<HostId>
YXYXYXXYXY
</HostId>
</Error>
```
It seems like its an issue with the url generator.  Let me know If this is happening with others too or something has been corrupted on my end itself.

**Comment by beyondszine** [comment]
anybody ?

**Comment by justnance** [comment]
@beyondszine - Thank you for posting this issue.  This error indicates the region set in `aws configure` or in the environment variable is set to `us-east-2` and the bucket is in the `ap-south-1` region.   You can use the following commands to confirm this:

```
aws configure list
```

```
env | grep AWS
```

It appears the CLI is using the default region configured in the environment variable orthe local `aws configure`.  This is the [precedence](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#precedence) used for the CLI.  

It also looks like the `ap-south-1` region was [added around June 2016](https://github.com/boto/botocore/commit/cc0543a4e934753c4551696d0f3b2daa2325f339
) which is after January 30, 2014.  As such means the `ap-south-1` [only support Signature Version 4](https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html
).   As per the CLI reference, the `presign` command [requires the region to be configured explicitly for sigv4 requests. ](https://docs.aws.amazon.com/cli/latest/reference/s3/presign.html)

The recommendation to resolve this issue to is use the `--region` global option:

```
aws s3 presign s3://bucket-name/directory/file -- region ap-south-1
```

I suggest changing your command to:

```
aws s3 presign 's3://ml-static-files/cfg.zip'
```

Also, I also suggest to update the CLI to the latest version to avoid other bugs or new features that might have been added since the version you are using.  

Let use know if this helps.

**Comment by beyondszine** [comment]
Hi @justnance,
Thank you for your response.  I also apologise for being late to revert back on the issue.
1. The environment variable issue.

```sh
 2019-08-06 12:57:43 ⌚  beyond-GL552VW in /tmp
○ → aws configure list
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
access_key     ****************XXXX              env    
secret_key     ****************XXXX              env    
    region           ap-southeast-1              env    AWS_DEFAULT_REGION


 2019-08-06 12:57:45 ⌚  beyond-GL552VW in /tmp
○ → env | grep AWS
AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXX
AWS_DEFAULT_REGION=ap-southeast-1
AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXX
```
I don't think so that it has been because of my environment variables as you can also see from my environment variables values.

2. The latest release here is 'https://github.com/aws/aws-cli/releases/tag/1.16.211', right?
The `aws` binary's version is same as I check by downloading the release code.
```sh
 2019-08-06 13:41:29 ⌚  beyond-GL552VW in /tmp/aws-cli-1.16.211
○ → cd bin/
 2019-08-06 13:43:30 ⌚  beyond-GL552VW in /tmp/aws-cli-1.16.211/bin
○ → ls
aws  aws_bash_completer  aws.cmd  aws_completer  aws_zsh_completer.sh
 2019-08-06 13:43:30 ⌚  beyond-GL552VW in /tmp/aws-cli-1.16.211/bin
○ → ./aws --version
aws-cli/1.16.81 Python/2.7.15+ Linux/4.15.0-43-generic botocore/1.12.71

```

3. But as you also pointed out the presign command requires the region to be configured explicitly for sigv4 requests(which I couldn't understood that time completely)
By supplying the global params with aws cmdline, the region is being set correctly and I am able to use as I desired.

The problem I faced is resolved in newer releases but the root cause is not yet understood as:
1. if setting region is must, why the command was anyway generating an URL with wrong params.
2. It generates URL even if region is not given or wrong.
ex:
```sh
2019-08-06 13:48:39 ⌚  beyond-GL552VW in /tmp/aws-cli-1.16.211/bin
○ → ./aws s3 presign 's3://ml-static-files/cfg.zip' --region i-created-region
https://ml-static-files.s3.i-created-region.amazonaws.com/cfg.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=3600&X-Amz-Credential=XXXXXXXXXXXXXXXXX%2F20190806%2Fi-created-region%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Date=20190806T082640Z&X-Amz-Signature=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
For the time being, I am closing the issue & many thanks for your support.

**Comment by Nanyak** [comment]
i have the some problem, it keeps giving us-east-1 region as default, i have to add --region ap-southeast-1 to solve the problem.
