### ISSUE TITLE
Ambiguous error message for "logs put-subscription-filter"

### ISSUE THREAD

**Issue by AlexL-CC** [aws/aws-cli#4422]
Hello,
I try:
`aws logs put-subscription-filter --log-group-name $loggrpname --filter-name "everything" --filter-pattern "" --destination-arn $destarn`

The error is:
`An error occurred (AccessDeniedException) when calling the PutSubscriptionFilter operation: User with accountId: 1111111111 is not authorized to perform: logs:PutSubscriptionFilter on resource: arn:aws:logs:eu-west-1:2222222222:destination:testDestination`

It would be very helpful to explain what user in acc: 1111111111  does not have such permissions. 

p.s. the same error when the user and the destination in the same account, without user/identity/role name.

Thanks.

**Comment by kyleknap** [comment]
This error is coming directly from the service. The AWS CLI is just proxying the error back to stderr. In order to get this error message updated, it will need to be updated in the service. I'd recommend opening a case with AWS Support or reaching out to their [forums](https://forums.aws.amazon.com/forum.jspa?forumID=138) to get it updated.
