### ISSUE TITLE
Option to specify subnet name when using create-subnet

### ISSUE THREAD

**Issue by ryanbarlow1** [aws/aws-cli#4451]
When you create a subnet using the AWS UI you have the option to type in a name for that subnet. However, there is no such option when creating a subnet through create-subnet in the CLI. Is there a reason for this? If not, can that feature be added?

Thank you!

**Comment by joguSD** [comment]
In general the AWS CLI is a 1:1 mapping of the service API. There's no option for this when calling `create-subnet` because the API does not support the option. I suspect the web console is making multiple API calls to make this possible. If you would like this feature I would suggest raising your concerns via [AWS Support](https://console.aws.amazon.com/support/home#/) so it can be forwarded to the corresponding service team.

The name is actually just a clever use of tags.
To achieve this using the CLI you'll need to make the subnet then make a call to `create-tags`:
```
aws ec2 create-tags --resources vpc-someid --tags Key=Name,Value=<vpc_name_here>
```
