### ISSUE TITLE
`aws ssm start-session` not working from inside docker container 

### ISSUE THREAD

**Issue by shuynh** [aws/aws-cli#4465]
hi!
i have a docker container based off https://github.com/bopen/docker-ubuntu-pyenv/blob/master/Dockerfile
...where i'm installing the aws-cli and would like to use ssm to access a remote instance. 

i bring up the container with `docker-compose run my-container bash` where i have my AWS_PROFILE mounted and can access all other aws-cli commands (i tested with ec2 describe and even did an `aws ssm send-command` to the instance). 

BUT when i do `aws ssm start-session` from the container, i get nothing. running it with `--debug` gives me the exact same output from when i run it locally, minus the `Starting session with SessionId:` part obviously. 
(i'm able to run `aws ssm start-session` from my local shell to this instance so i know that ssm is configured properly)

is this a aws-cli issue, or is my container doing weird stuff with stdout?? apologies if it's the latter!

`aws-cli/1.16.200 Python/3.6.9 Linux/4.9.125-linuxkit botocore/1.12.190`

**Comment by sruthi-maddineni** [comment]
I'm able to start session from the container based off https://github.com/bopen/docker-ubuntu-pyenv/blob/master/Dockerfile.
Please post the error you are seeing to help debug this.

**Comment by jamesls** [comment]
To start session with SSM you also need to have the session manager plugin installed, which is a separate install from the AWS CLI (it's not a python package so it can't be installed with pip).

Looking over your docker file it doesn't look like your installing it.  I suspect it's installed on your host system which is why it works outside of docker.

More info here: https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html
