### ISSUE TITLE
Error parsing parameter '--description' when passing a url as the option value

### ISSUE THREAD

**Issue by ZhukovAlexander** [aws/aws-cli#4473]
When I try to use `aws elasticbeanstalk create-application-version` and try to pass a url as the `--description`, I get this weird validation error. Example:

Input:
`aws elasticbeanstalk create-application-version --application-name my-imaginary-app --version-label="123" --description="https://example.com/foobar"` 
Output:
`Error parsing parameter '--description': Unable to retrieve https://example.com/foobar: received non 200 status code of 404`

aws-cli version:
`aws-cli/1.16.165 Python/3.7.2 Linux/4.15.0-58-generic botocore/1.12.155`

**Comment by jamesls** [comment]
This is because the CLI has behavior where if a param starts with "http/https" we'll automatically fetch the contents of that file and use those contents as the value.  Your workarounds are:

1. Set the `cli_follow_urlparam` to false in your `~/.aws/config` file.
2. Change your description to not start with https.

FWIW this behavior is being removed entirely in AWS CLI v2.
