### ISSUE TITLE
Allow attach-role-policy to accept multiple policy ARNs

### ISSUE THREAD

**Issue by belugabehr** [aws/aws-cli#4481]
https://docs.aws.amazon.com/cli/latest/reference/iam/attach-role-policy.html

However, I would like to attach multiple policies to the role:

```
attach-role-policy --role-name MY_ROLE --policy-arn <value> --policy-arn <value> --policy-arn <value>
````

Saves me from having to call the command 3 times.

**Comment by belugabehr** [comment]
Same thing with `detach-role-policy`

**Comment by belugabehr** [comment]
Same thing with `delete-role` and its `--role-name` field

**Comment by belugabehr** [comment]
Same thing with `create-group` and `--group-name` field

**Comment by jamesls** [comment]
These commands map exactly to what's provided with the IAM API: https://docs.aws.amazon.com/IAM/latest/APIReference/API_AttachRolePolicy.html

I'd suggest asking for this feature on the IAM forums.  If it's supported in the IAM API we'll automatically pick that up in the CLI. Otherwise for now you'll have to invoke the command multiple times.
