### ISSUE TITLE
command 'aws' not found ubuntu

### ISSUE THREAD

**Issue by MatteoGioioso** [aws/aws-cli#4496]
Trying to install aws cli using pip following these instructions: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html#install-tool-pip

But when I try to run `aws --version` I have the following error `command 'aws' not found`.
Try to follow the troubleshoot part but it did not lead anywhere.

Ubuntu 18.04.3 LTS
Pip: 19.2.3
Python: 3.7.4

**Comment by jamesls** [comment]
It sounds like the CLI wasn't installed.  Please share the output of running your install commands and any troubleshooting steps you took and we will be able to help.

**Comment by MatteoGioioso** [comment]
@jamesls I have solved by using the bundled installer.
I think that installing the cli using pip has some problem. I have tried with three different systems following the instructions provided, but in all three of them it was resulting in the same output.

**Comment by vvisan** [comment]
Hi, I encountered the exact same problem, also wih Ubuntu 18. 

I used 
pip install awscli --upgrade --user
and got:
```

vm@vm:~$ aws --version

Command 'aws' not found, but can be installed with:

sudo snap install aws-cli  # version 1.16.266, or
sudo apt  install awscli 

See 'snap info aws-cli' for additional versions.
```
It seems to work, when I use "sudo apt  install awscli "

**Comment by MatteoGioioso** [comment]
As my understanding installing the cli with `pip` won't work, not sure why it is in the instructions. I have tried with multiple ubuntu on different machines and still the same error, that is why I have opted for the bundled installer.

**Comment by sorosliu** [comment]
I tried the following command and it seems to fix the issue:

pip3 install awscli --ignore-installed six

**Comment by AvulaRanjan** [comment]
**Step 1 : - Connect your ubuntu server and type aws  like below and you see the message** 

**root@ip:~# aws**
Command 'aws' not found, but can be installed with:

snap install aws-cli  # version 1.15.58, or
apt  install awscli

See 'snap info aws-cli' for additional versions.


**Step 2:- User this is command  to install aws cli-- **snap install aws-cli --classic****

root@ip-172-31-39-184:~# snap install aws-cli --classic
aws-cli 1.15.58 from Amazon Web Services (aws✓) installed
**Step 3 - type aws** 
root@ip-172-31-39-184:~# aws
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: the following arguments are required: command

Your error will fix

**All the best**

**Comment by devophiral** [comment]
> I tried the following command and it seems to fix the issue:
> 
> pip3 install awscli --ignore-installed six

It is working for me thanks

**Comment by bin8686** [comment]
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install

**Comment by Ramprasad4121** [comment]
> sudo apt install awscli

thank you buddy

**Comment by amroz121** [comment]
It is always a good practice to run the sudo apt-get update command, this will help a lot.

**Comment by shamnad-sherief** [comment]
If you installed the AWS CLI locally without sudo, the binary is safely placed inside ~/.local/bin/.
Ubuntu/Debian systems already have a built-in mechanism to add this folder to your $PATH via ~/.profile. However, it only triggers if the folder already existed when you logged in or booted your system. Since the AWS installer just created it, you simply need to reload your profile

source ~/.profile


#### Why the Command 'aws' not found error happens
If you look inside your default ~/.profile file, you will find this standard conditional check

```
#set PATH so it includes user's private bin
 if it existsif [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"fi
```

 
* The Problem: The very first time you use the AWS CLI install script, the ~/.local/bin folder does not exist yet. Because of that if [ -d ... ] safety check, your system skipped adding it to the $PATH when you booted up or opened your desktop session. 
* The Result: The script creates the directory and installs the binary, but your current terminal context is still unaware of it.
