### ISSUE TITLE
An error occurred (KMS.NotFoundException) when calling the PutObject operation: Invalid keyId aws/s3

### ISSUE THREAD

**Issue by luisamador** [aws/aws-cli#4507]
I'm trying to run this command from an EC2 instance that is assuming a cross account IAM role.

```
aws s3 cp config s3://my_bucket_blah/hi.txt --region eu-west-1 
upload failed: ./config to s3://my_bucket_blah/hi.txt An error occurred (KMS.NotFoundException) when calling the PutObject operation: Invalid keyId aws/s3
```

The cross account IAM role has "kms:*" permissions on the remote account.

obviously the aws/s3 key which is reporting as invalid exists on the remote account where the S3 bucket is hosted

I'm completely stuck with this.

**Comment by luisamador** [comment]
Had to add `--sse=aws:kms` to the command above to make it work.

```
aws s3 cp config s3://my_bucket_blah/hi.txt --sse=aws:kms
```

The error message is not very helpful.

**Comment by aiplescaamdaris** [comment]
I also got this error, both in cli and in the web browser. solved it by using "Server-side encryption with Amazon S3 managed keys (SSE-S3)" instead of "Server-side encryption with AWS Key Management Service keys (SSE-KMS)" for encrypting the bucket.

also in terraform by using:
apply_server_side_encryption_by_default {
    sse_algorithm     = "AES256"
 }

instead of 
apply_server_side_encryption_by_default {
    kms_master_key_id = "aws/s3" 
    sse_algorithm     = "aws:kms" 
}
