### ISSUE TITLE
service-quotas list-service-quotas does not list all available quotas

### ISSUE THREAD

**Issue by ghost** [aws/aws-cli#4569]
Using the Service Quotas UI, we can clearly see that ` Inbound or outbound rules per security group ` and ` Security groups per network interface ` exist and belong to the category `Amazon Virtual Private Cloud (Amazon VPC)`. In total I can see 22 Service quotas in this category.

I'd expect the aws-cli to return the same service quotas with the following command:
```
aws service-quotas list-service-quotas --service-code=vpc --region=eu-west-1
```

In reality it only returns:
```
"QuotaName": "Internet gateways per Region",
"QuotaName": "VPCs per Region",
```

These two are also listed in the UI, but the response is clearly lacking the 20 other Service Quotas.

**Comment by dineshrathee12** [comment]
The APIs you have used will only return those quotas for which applied quota values are available (2 of them - Internet gateways per Region and VPCs per Region).

➜ aws service-quotas list-service-quotas --service-code vpc --region eu-west-1 --query "Quotas[*].{ServiceName:ServiceName,QuotaName:QuotaName,QuotaCode:QuotaCode,Value:Value}" --output table
------------------------------------------------------------------------------------------------------
|                                          ListServiceQuotas                                         |
+------------+--------------------------------+---------------------------------------------+--------+
|  QuotaCode |           QuotaName            |                 ServiceName                 | Value  |
+------------+--------------------------------+---------------------------------------------+--------+
|  L-A4707A72|  Internet gateways per Region  |  Amazon Virtual Private Cloud (Amazon VPC)  |  10.0  |
|  L-F678F1CE|  VPCs per Region               |  Amazon Virtual Private Cloud (Amazon VPC)  |  10.0  |
+------------+--------------------------------+---------------------------------------------+--------+


>> You will have to use the "list-aws-default-service-quotas" API to get the details:
[+] https://docs.aws.amazon.com/cli/latest/reference/service-quotas/list-aws-default-service-quotas.html
[+] https://docs.aws.amazon.com/servicequotas/2019-06-24/apireference/API_ListAWSDefaultServiceQuotas.html


Example - Using : "list-aws-default-service-quotas":
======================================
➜  ~ aws service-quotas list-aws-default-service-quotas --service-code vpc  --region eu-west-1 --query "Quotas[*].{ServiceName:ServiceName,QuotaName:QuotaName,QuotaCode:QuotaCode,Value:Value}" --output table
-----------------------------------------------------------------------------------------------------------------------
|                                             ListAWSDefaultServiceQuotas                                             |
+------------+------------------------------------------------+---------------------------------------------+---------+
|  QuotaCode |                   QuotaName                    |                 ServiceName                 |  Value  |
+------------+------------------------------------------------+---------------------------------------------+---------+
|  L-7E9ECCDB|  Active VPC peering connections per VPC        |  Amazon Virtual Private Cloud (Amazon VPC)  |  50.0   |
|  L-45FE3B85|  Egress-only internet gateways per Region      |  Amazon Virtual Private Cloud (Amazon VPC)  |  5.0    |
|  L-1B52E74A|  Gateway VPC endpoints per Region              |  Amazon Virtual Private Cloud (Amazon VPC)  |  20.0   |
|  L-83CA0A9D|  IPv4 CIDR blocks per VPC                      |  Amazon Virtual Private Cloud (Amazon VPC)  |  5.0    |
|  L-085A6257|  IPv6 CIDR blocks per VPC                      |  Amazon Virtual Private Cloud (Amazon VPC)  |  1.0    |
|  L-0EA8095F|  Inbound or outbound rules per security group  |  Amazon Virtual Private Cloud (Amazon VPC)  |  60.0   |
|  L-29B6F2EB|  Interface VPC endpoints per VPC               |  Amazon Virtual Private Cloud (Amazon VPC)  |  50.0   |
|  L-A4707A72|  Internet gateways per Region                  |  Amazon Virtual Private Cloud (Amazon VPC)  |  5.0    |
|  L-FE5A380F|  NAT gateways per Availability Zone            |  Amazon Virtual Private Cloud (Amazon VPC)  |  5.0    |
|  L-B4A6D682|  Network ACLs per VPC                          |  Amazon Virtual Private Cloud (Amazon VPC)  |  200.0  |
|  L-DF5E4CA3|  Network interfaces per Region                 |  Amazon Virtual Private Cloud (Amazon VPC)  |  5000.0 |
|  L-DC9F7029|  Outstanding VPC peering connection requests   |  Amazon Virtual Private Cloud (Amazon VPC)  |  25.0   |
|  L-2C462E13|  Participant accounts per VPC                  |  Amazon Virtual Private Cloud (Amazon VPC)  |  100.0  |
|  L-589F43AA|  Route tables per VPC                          |  Amazon Virtual Private Cloud (Amazon VPC)  |  200.0  |
|  L-93826ACB|  Routes per route table                        |  Amazon Virtual Private Cloud (Amazon VPC)  |  50.0   |
|  L-2AEEBF1A|  Rules per network ACL                         |  Amazon Virtual Private Cloud (Amazon VPC)  |  20.0   |
|  L-2AFB9258|  Security groups per network interface         |  Amazon Virtual Private Cloud (Amazon VPC)  |  5.0    |
|  L-407747CB|  Subnets per VPC                               |  Amazon Virtual Private Cloud (Amazon VPC)  |  200.0  |
|  L-44499CD2|  Subnets that can be shared with an account    |  Amazon Virtual Private Cloud (Amazon VPC)  |  100.0  |
|  L-8312C5BB|  VPC peering connection request expiry hours   |  Amazon Virtual Private Cloud (Amazon VPC)  |  168.0  |
|  L-E79EC296|  VPC security groups per Region                |  Amazon Virtual Private Cloud (Amazon VPC)  |  2500.0 |
|  L-F678F1CE|  VPCs per Region                               |  Amazon Virtual Private Cloud (Amazon VPC)  |  5.0    |
+------------+------------------------------------------------+---------------------------------------------+---------+

**Comment by allir** [comment]
This seems to list 3 quotas now, the two mentioned above plus "Network interfaces per Region"
I'm pretty sure this is also affecting setting quotas via Terraform as if I try to set a quota outside those 3 I get an error, for example:
`Error: error getting Service Quotas Service Quota (vpc/L-FE5A380F): NoSuchResourceException:`

**Comment by dineshrathee12** [comment]
> This seems to list 3 quotas now, the two mentioned above plus "Network interfaces per Region"
> I'm pretty sure this is also affecting setting quotas via Terraform as if I try to set a quota outside those 3 I get an error, for example:
> `Error: error getting Service Quotas Service Quota (vpc/L-FE5A380F): NoSuchResourceException:`

**Error :  "NoSuchResourceException"**
`"An error occurred (NoSuchResourceException) when calling the ListAWSDefaultServiceQuotas operation: The request failed because the specified service does not exist."
`
**Cause:  This error could occur because of two reasons:**

Either customer is trying to access something which has not been integrated with Service Quotas
Sometimes it can be occurred when we have a typo ( case sensitive ) for example - writing "ec2" as "EC2"
**Solution :** Please note that "Service Codes" are case sensitive. Hence, please make sure you correct any typo made.


**Example : ( Checking Service codes for  ec2   &  AWSCloudMap)**

`# aws service-quotas list-services --region eu-west-1 --query "Services[*].{ServiceCode:ServiceCode}" --output table |grep -i ec2
|  ec2                      |
# aws service-quotas list-services --region eu-west-1 --query "Services[*].{ServiceCode:ServiceCode}" --output table |grep -i awscloudMap
|  AWSCloudMap              |
<< Typing different letters >>
# aws service-quotas list-aws-default-service-quotas --service-code EC2
An error occurred (NoSuchResourceException) when calling the ListAWSDefaultServiceQuotas operation: The request failed because the specified service does not exist.

# aws service-quotas list-aws-default-service-quotas --service-code awsCloudMap
An error occurred (NoSuchResourceException) when calling the ListAWSDefaultServiceQuotas operation: The request failed because the specified service does not exist.
`

Success : ( Below is an example when we use the correct Service code ) 

`# aws service-quotas list-aws-default-service-quotas --service-code AWSCloudMap --query "Quotas[*].{ServiceCode:ServiceCode,ServiceName:ServiceName,QuotaCode:QuotaCode}" --output table
------------------------------------------------
|          ListAWSDefaultServiceQuotas         |
+------------+---------------+-----------------+
|  QuotaCode |  ServiceCode  |   ServiceName   |
+------------+---------------+-----------------+
|  L-D95E8A57|  AWSCloudMap  |  AWS Cloud Map  |
|  L-2DA90E5C|  AWSCloudMap  |  AWS Cloud Map  |
|  L-0FE3F50E|  AWSCloudMap  |  AWS Cloud Map  |
+------------+---------------+-----------------+`
