### ISSUE TITLE
[V2] Issue Validating Terminal Code in website

### ISSUE THREAD

**Issue by churtado-edrans** [aws/aws-cli#4644]
Hi All!

I tried to following this (https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html) and when i arrived to web validate code appear in terminal the website show the next error.

`Unexpected Error 
TypeError: Failed to fetch`

Any ideas?

Version:
`aws-cli/2.0.0dev0 Python/3.7.4 Darwin/18.7.0 botocore/2.0.0dev0`

**Comment by pb-clckwrk** [comment]
Getting the same error on Mac/Linux/Windows with Chrome/Safari and Firefox browsers.

**Comment by e-moshaya** [comment]
You need to disable browser content security policy then it should work

**Comment by dspaxton** [comment]
> You need to disable browser content security policy then it should work

Where is this in Chrome/Firefox/Safari?

**Comment by danielsaibt** [comment]
https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden?hl=en

**Comment by holmesjr** [comment]
While that is the issue:

`VM14:1 Refused to connect to 'https://oidc.ap-southeast-2.amazonaws.com/device_verification?user_code=XLTQ-XQBG' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.`

`VM14:1 Refused to connect to 'https://oidc.ap-southeast-2.amazonaws.com/device_verification?user_code=XLTQ-XQBG' because it violates the document's Content Security Policy.`

disabling security features in a browser is not a solution.

**Comment by holmesjr** [comment]
Also, can someone attach the V2 label to this issue so it gets some visibility?

**Comment by joguSD** [comment]
@holmesjr You're correct. We do not recommend disabling CSP to work around this issue. 

This was a bug in the console page that I've been told has since been fixed. You may need to clear you browser cache. Let me know if you're still running into this issue.

**Comment by holmesjr** [comment]
This does appear to have been fixed.

**Comment by churtado-edrans** [comment]
> Also, can someone attach the V2 label to this issue so it gets some visibility?

I can't do it!

**Comment by churtado-edrans** [comment]
> is was a bug in the console page that I've been told has since been fixed. You may need to clear you browser cache. Let me know if you're still runnin

Today i will test again.

**Comment by churtado-edrans** [comment]
I update with the latest version and now works fine. Thank you
