### ISSUE TITLE
aws-cli exposes tokenCode

### ISSUE THREAD

**Issue by udf2457** [aws/aws-cli#4648]
aws-cli/1.16.263 Python/3.6.9 Linux/4.12.14-lp151.28.25-default botocore/1.12.253

As you can see, the input is not echo'd but the output prints it.

```
foo@bar:~> aws s3 presign s3://foobar/barfoo --expires-in 604800 --profile foobar
Enter MFA code for arn:aws:iam::123456789:mfa/foobar: 

An error occurred (ValidationError) when calling the AssumeRole operation: 2 validation errors detected: Value '138502\' at 'tokenCode' failed to satisfy constraint: Member must have length less than or equal to 6; Value '138502\' at 'tokenCode' failed to satisfy constraint: Member must satisfy regular expression pattern: [\d]*
```

**Comment by joguSD** [comment]
This particular error message is coming back from the service. Considering they're returning the token code as part of the error message it would appear they aren't too concerned about it being displayed. Also, due to the nature of the error the exposed code is (according to the service) invalid, so it's unlikely that the code displayed is actually relevant. I don't think we're particularly concerned about this.
