### ISSUE TITLE
Improved output formats for v2

### ISSUE THREAD

**Issue by chizou** [aws/aws-cli#4703]
Can a feature be created to allow for improved output formats? JMESPath just doesn't seem to have the power/flexibility of tools like jq. This leads to me frequently having to switch to jq, write some ugly bash to parse it, or switch to writing it in python. 

For example, trying to produce a csv of all accounts via `aws organizations list-accounts` seems non-trivial to do with aws-cli and the `--query` option. But with `jq`, it's just `| @csv`

**Comment by jamesls** [comment]
> Can a feature be created to allow for improved output formats?

Definitely.

One thing worth noting though is that it might be challenging to have csv as a generic output format.  It works when you have a list of scalar values but it's not clear how we should serialize something like this response as csv:

```
$ aws2 dynamodb describe-table --table-name TestTable4 --profile default
{
    "Table": {
        "AttributeDefinitions": [
            {
                "AttributeName": "Foo",
                "AttributeType": "S"
            }
        ],
        "TableName": "TestTable4",
        "KeySchema": [
            {
                "AttributeName": "Foo",
                "KeyType": "HASH"
            }
        ],
        "TableStatus": "ACTIVE",
        "CreationDateTime": "2019-11-30T19:38:39.575000-08:00",
        "ProvisionedThroughput": {
            "NumberOfDecreasesToday": 0,
            "ReadCapacityUnits": 0,
            "WriteCapacityUnits": 0
        },
        "TableSizeBytes": 0,
        "ItemCount": 0,
        "TableArn": "arn:aws:dynamodb:us-west-2:abcd:table/TestTable4",
        "TableId": "b1bac233-93d7-4890-baaf-0062be3a923c",
        "BillingModeSummary": {
            "BillingMode": "PAY_PER_REQUEST",
            "LastUpdateToPayPerRequestDateTime": "2019-11-30T19:38:39.575000-08:00"
        }
    }
}
```

Any thoughts?

**Comment by lousyd** [comment]
@jamesls , It seems like @chizou is not asking to be able to output csv, per se, but rather to have jq syntax available with the aws cli. In other words, use jq's syntax instead of jmespath. (Or in addition to jmespath somehow.)

**Comment by chizou** [comment]
Thanks @lousyd. That's exactly it. My gripe is that JMESPath isn't improving very quickly as a language yet jq continues to add new features and capabilities. Implementing CSV was just one example, but there are many things that require diving into python, bash, or some other language with `--query` that I can achieve with a few extra commands in `jq`.

**Comment by jthomerson** [comment]
I'm not sure if this should be here or somewhere else, but I also have problems with the output formats from some AWS CLI commands. In particular, DynamoDB does not give you a way to really process output in a stream. Since all the items returned from a scan/query end up in `.Items[]`, you have to process the _entire file_ in order to use it in any other tools. We really need a streamable output format, like line-delimited JSON, so that we can pipe the output through other tools.

Imagine something like this:

```
aws dynamodb scan --table-name some-table --projection-expression 'pk, sk' | jq '.Items[] | (.pk.S + "," + .sk.S)'
```

The problem there is that if the scan returns millions or billions of items, jq has to read the entire file, which takes a ton of memory. If the output from the AWS CLI were streamable (i.e. processable one line at a time), it would be much more powerful / natural on the CLI.

https://twitter.com/jthomerson/status/1282096480522768385
