### ISSUE TITLE
[V2] logs writting on itself on the same line

### ISSUE THREAD

**Issue by QuentinDela** [aws/aws-cli#4714]
Hello, 
I am running `aws2 logs tail /aws/lambda/$FUNCTION_NAME --follow` on iTerm2 with zsh and when I want to print a JSON 
```
    const str = {
      str: 'foo',
      num: 100,
      bool: false,
      null: null,
      array: ['foo', 'bar', 'baz'],
      obj: { a: 1, b: 2 },
    };
```
The output is strangely truncated on the same line 

![Screen Shot 2019-11-28 at 10 37 35 AM](https://user-images.githubusercontent.com/12401728/69794869-5af10680-11cb-11ea-9af8-660d21bfc0ce.png)

is there a way to fix that ?

**Comment by jamesls** [comment]
Not sure why it's doing that.  When I tried to repro this, I'm seeing the behavior I'd expect.  FWIW here's the lambda code I tried:

```python
import json

from chalice import Chalice

app = Chalice(app_name='test-json-log')


@app.lambda_function()
def printjson(event, context):
    json_doc = {
        'hello': 'world',
        'foo': {
            'bar': {
                'baz': True,
            }
        }
    }
    print(json.dumps(json_doc, indent=2))
```

And here's the output I was seeing:


![Screen Shot 2019-12-12 at 4 47 38 PM](https://user-images.githubusercontent.com/368057/70760630-2454d900-1cff-11ea-812d-63db3cbb99ab.png)

Perhaps your lambda function isn't properly printing the JSON?  Otherwise I'm not sure, but as far as I can tell, I'm not sure what we could change in the CLI here.
