### ISSUE TITLE
Retrieve Sagemaker instance metrics from cloudwatch via CLI

### ISSUE THREAD

**Issue by adiell** [aws/aws-cli#4757]
Not sure if this is the right place, but I'll try:

I've got a training job running on Sagemaker. I would like to retrieve instance metrics like MemoryUtilization etc by CLI or boto3 client.

Obviously I can see them in the console. However, I cannot see them in the CLI/API. For example, when running:
```
aws cloudwatch list-metrics --namespace "AWS/SageMaker"
```
I can see only metrics regarding endpoint invocation but not any training job related metrics.

Any idea?

Thanks!

**Comment by jamesls** [comment]
If you're not seeing them in the CLI or API that's likely not due to a CLI specific error.  We're just returning the data that cloudwatch is sending back.  In the console I would double check the namespace those metrics are being published in.  If there's just EC2 instances, perhaps they're in the AWS/EC2 namespace.
