### ISSUE TITLE
Allow aws cloudformation deploy to use --template-url

### ISSUE THREAD

**Issue by galartsi-cg** [aws/aws-cli#4773]
A ticket was created, but never finished:
https://github.com/aws/aws-cli/issues/2461

Still can not use `aws cloudformation deploy` with a template url on S3.

**Comment by joguSD** [comment]
The ticket #2461 was closed because https://github.com/aws/aws-cli/pull/2778 added support for providing a `--s3-bucket` parameter in addition to the `--template-file`. This means rather than explicitly providing a template url, the `aws cloudformation deploy` command will figure out if your template is larger than the threshold and requires being uploaded to S3. In which case it will upload the template to your bucket and provide a template url instead.

Let me know if that helps, or if you would still like to have the explicit `--template-url` parameter.

**Comment by chintanvyas360** [comment]
Can we reopen this issue?
It would be better to have an explicit `--template-url ` parameter. The reason being our CI/CD workflow automatically creates the bundles including the template file and stores it in an S3 bucket. The use case here is being able to use the template already available in an S3 bucket instead of AWS creating another copy and storing it again in the specified bucket. It just seems like an unnecessary step and adds a bit of complexity while automating thee CI/CD. A lot of people I know are using create/execute changeset because of this reason which puts the additional overhead of writing scripts to check which action to perform (create or update and wait).

**Comment by falnyr** [comment]
@sanathkr any updates on this?

**Comment by dza89** [comment]
@joguSD 
The --s3-bucket parameter uploads your template from local to S3.

The request is to able to deploy a cfn template from a remote template which is located at s3.
This seems to be not possible with the CLI, where this is actually possible in GUI.

**Comment by DelDennis** [comment]
Yes this has been very frustrating for me and i cannot understand for the life of me why this isn't possible. Seems like it should be a default option and makes the deploy process a mess if using nested stacks. I thought this would be 'fixed' by now, but no, here we are in 2020.

I cannot understate how much of a pain this has been for me. I want to deploy everything from s3 via CLI vs having to do this hybrid thing where nested stacks are in s3 but master.yaml can only be deployed from the local machine. 

Am i missing something?

**Comment by alekspickle** [comment]
Upd: here we are in 2021

**Comment by timharris777** [comment]
@joguSD , please reopen this issue. Ideally both would be supported.

**Comment by timharris777** [comment]
I just submitted a PR with working code that accepts either a local path or s3 url to the cloudformation template with the `--template-file` option.

https://github.com/aws/aws-cli/pull/6409

**Comment by nidnogg** [comment]
Just piling in on the request for reopening this. This should definitely be supported.
