### ISSUE TITLE
[v2] Output using more.com on Windows

### ISSUE THREAD

**Issue by wsmelton** [aws/aws-cli#4787]
On Windows 10 aws2 is sending output to more and will not output all the content at once.

Is there a way to have it not use more (e.g. `"some long output object with multiple lines" | more`) on Windows. When you are using the CLI in VS Code it is a pain to have some just run only to find out you have to change focus to a terminal window to get the command to finish so you can move on to the next one.

**Comment by joguSD** [comment]
You can set the `AWS_PAGER` env var or the `cli_pager` shared config to the empty string which will disable sending output to a pager entirely. Let me know if that solves your issue.

**Comment by wsmelton** [comment]
So that would mean it is either deal with the paging or get nothing?

I would prefer to see the output, just want it output all at once.

**Comment by joguSD** [comment]
If you disable the pager you'll still get pagination, those are two separate features.

Here's the doc page on pagination:
https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html

And we don't have a doc page for the pager settings yet but this PR has a good overview:
https://github.com/aws/aws-cli/pull/4702

**Comment by wsmelton** [comment]
I set the environment variable as `$env:AWS_PAGER = ' '` on my machine and I loose all output from `aws2 ssm send-command ...`.

I set the environment variable as $env:AWS_PAGER = ""` and it still hits the output to `more` on Windows.

So if I want the output and not for it be sent to the pager, what should this be set to?

**Comment by kyleknap** [comment]
It appears that for PowerShell setting the environment variable to an empty string deletes the environment variable. Instead, you can also set `cli_pager` in the shared config file. So in your `~/.aws/config` file, you can have it set as empty in your default profile:
```
[default]
cli_pager=
```
That should turn it off. However that being said, it may be worth supporting an alternative value to turn off paging. We were following the pattern that git uses when we chose this, but git also turns it off if the environment variable is set to `cat`. So it maybe worth supporting that as well. I also noticed that the `configure set` command does not support using an empty string to turn off automatic paging on Windows (but works for linux/mac):
```
C:\Users\Administrator\Documents\GitHub> aws2 configure set cli_pager ""
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws2.exe: error: the following arguments are required: value
```
Let us know if that helps.

**Comment by wsmelton** [comment]
Changing to a new machine and once I get that setup will let you know. Thanks.

**Comment by kellertk** [comment]
The `" "` (one space character) setting for AWS_PAGER looks like it doesn't work on macOS as well.

On macOS:
* `AWS_PAGER=" "` -> `list index is out of range`, no output
* `AWS_PAGER=""` -> no pager is used
* `AWS_PAGER="cat"` -> output appears to be piped to `cat`, which effectively disables paging
* `AWS_PAGER="more"` -> output is piped to `more`, which pages the output
* `AWS_PAGER="head"` -> output is piped to `head`, only the first lines are returned
* `AWS_PAGER="python"` -> output is piped to `python`, which of course returns a syntax error
* `AWS_PAGER` is not set -> output is piped to `less`, which pages the output

In Powershell on Windows:
* `$env:AWS_PAGER = ' '` (one space character) -> there is no output at all
* `$env:AWS_PAGER = ''` -> output is piped to `more.com` because the environment variable is not set
* `$env:AWS_PAGER = 'cat'` -> tries to output to `cat`, which doesn't exist, so returns an error
* `$env:AWS_PAGER = 'powershell -c $input'` -> output is piped to another powershell instance, which does not page the output
* `$env:AWS_PAGER = 'more.com'` -> behaves the same as the default
* `$env:AWS_PAGER = 'C:\Users\kellertk\AppData\Local\Programs\Python\Python38\python.exe'` -> output is piped to `python`, producing a syntax error
* `$env:AWS_PAGER` is not set -> output is piped to `more.com`

Setting `cli_pager=` in the config appears to work on both platforms for me.

**Comment by kdaily** [comment]
Bumping as still relevant.
