### ISSUE TITLE
Glacier initiate-job output case consistency

### ISSUE THREAD

**Issue by ivankisic** [aws/aws-cli#4799]
Not sure if it's worth mentioning (and also not sure if it's related just to the CLI), but glacier initiate-job and list-jobs gives out a different case for the "jobId" field.

`aws glacier list-jobs` the output is "JobId" and with `aws glacier initiate-job` it's "jobId", one using camel case and the other camel back.

`aws-cli/1.16.291 Python/2.7.16 Linux/5.0.0-37-generic botocore/1.13.27`

**Comment by kyleknap** [comment]
While it would be better if the casing was consistent, there is not really much we can do here. Specifically, changing the case would be a backwards incompatible change, and in order to change it we would likely have to expose a new command (e.g. `initiate-job-2` or `list-jobs-2`) that uses the correct casing, which does not seem worth the potential confusion that it may create.
