### ISSUE TITLE
[v2] Older version of AWS CLI V2 getting installed on Linux

### ISSUE THREAD

**Issue by joelbrandenburg** [aws/aws-cli#4802]
When I install AWS CLI v2 on an Amazon Linux 2 instance, I get this version:
aws-cli/2.0.0dev2 Python/3.7.3 Linux/4.14.152-127.182.amzn2.x86_64 botocore/2.0.0dev1

When I install AWS CLI v2 on Mac OS, I get this version:
aws-cli/2.0.0dev2 Python/3.7.4 Darwin/18.7.0 botocore/2.0.0dev1

Any particular reason why that would be?  There are some service features that won't work on 3.7.3 that do work on 3.7.4.

**Comment by joelbrandenburg** [comment]
I am unable to add the "v2" label to this issue for some reason, but this is a v2 issue.

**Comment by kyleknap** [comment]
So both installations are version `2.0.0dev2` of the AWS CLI, which means that both installation share the same feature set. However, it does look like they use different patch versions of Python. This is because the CLI built for Linux is built with Python 3.7.3, while the Mac version is built with Python 3.7.4. This something on our end that we will need to update to make sure the artifacts share the same Python version. Marking as enhancement.

**Comment by kdaily** [comment]
Commenting to keep this open, marking as installation-related.
