### ISSUE TITLE
dynamodb wait cmd support for backfilling global secondary index

### ISSUE THREAD

**Issue by erikpaasonen** [aws/aws-cli#4845]
When updating an existing DynamoDB secondary index, the DynamoDB service takes several minutes to backfill. During this time, requests to read from the index result in a message similar to:
>{
  "errorMessage": "ValidationException: Cannot read from backfilling global secondary index: my-index-name\n\tstatus code: 400, request id: 8T7RMYSAMPLEREQUESTID1111NSO5AEMVAAAAAAAAAAAAA",
  "errorType": "requestError"
}

Would like to be able to run a command similar to 
```
aws dynamodb wait secondary-index --index-name my-index-name
```
and have it exit only when querying the table is available once more.

Currently the only two subcommands of `aws dynamodb wait` are `table-exists` and `table-not-exists`.

**Comment by joguSD** [comment]
Putting this down as a feature request.

**Comment by tim-finnigan** [comment]
Hi @erikpaasonen thanks for your patience. I've just stumbled on this issue and trying to better understand the request. 

The DynamoDB waiter models can be found here in botocore: https://github.com/boto/botocore/blob/develop/botocore/data/dynamodb/2012-08-10/waiters-2.json

Those waiter definitions involve polling an API until a state is reached. For `table-exists` and `table-not-exists` that API is [DescribeTable](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_DescribeTable.html).

I'm not very familiar with secondary indexes and not sure if there is a way to define a waiter for this use case. Do you have any suggestions or opinions on what the waiter model might look like?

Another point to mention is that waiter model definitions are now owned by the respective service teams (because the waiter models are shared across AWS SDKs). So if we conclude that this is a valid feature request then we would forward this to the DynamoDB team.
