### ISSUE TITLE
aws-cli should set default region to EC2 instance region

### ISSUE THREAD

**Issue by mveitas** [aws/aws-cli#486]
Recently we provisioned an EC2 instance with the aws-cli installed that is using IAM roles. We forgot to set the AWS_DEFAULT_REGION environment variable and got an error stating that the default region was not specified.

I am proposing that aws-cli should be able to assume the given region of the EC2 instance. This would eliminate one step of adding the environment variable to the system. If the aws-cli needs to talk to a different region, it can always use a different profile or override the region.

I am sure there are implications to this that need to be thought about.

**Comment by aalbertson** [comment]
+1

**Comment by dmulter** [comment]
+1

**Comment by nonbeing** [comment]
+1

**Comment by npinchot** [comment]
+1
I think this would be great, even if I had to pass a param like `--use-instance-region`. Right now I have to parse the region from `ec2metadata` and a regex and then pass it as `--region`.

**Comment by georgealton** [comment]
+1

**Comment by vpal** [comment]
+1

**Comment by cosmok** [comment]
+1

**Comment by BradErz** [comment]
This still isn't a thing? Its super annoying.... 

I currently get around it by:
`region=$(curl http://169.254.169.254/latest/dynamic/instance-identity/document|grep region|awk -F\" '{print $4}')
`'echo "[default]\nregion = ' + region + '" > /root/.aws/config'`

It would be so useful to have it default to the region that the instance is spawned in...

**Comment by WhileLoop** [comment]
+1

**Comment by maslakov** [comment]
+1

**Comment by szotrj** [comment]
+1
I don't want to have to specify region in all my CLI commands when there is only 1 region in GovCloud (us-gov-west-1)

**Comment by Daxito** [comment]
+1

**Comment by qwrrty** [comment]
Why has this not yet been implemented?

+1

**Comment by ededdneddyfan** [comment]
+1, ran into the same issue myself trying to run something on Boto3

**Comment by jaymecd** [comment]
any progress here? plz

**Comment by spektom** [comment]
As a workaround we run the following before any `aws cli` command:
```bash
export AWS_DEFAULT_REGION=$(curl -m5 -sS http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/.$//')
```

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by georgeludwig** [comment]
All right then, +1 on the feature request, why in god's name has this not been implemented yet???

**Comment by kdubmartins** [comment]
Upvote for this feature request. 

I have a case when instances in China (cn-north-1) using IAM Roles fail to query a s3 bucket just because the region is not specified. Meanwhile instances in Ireland (eu-west-1) with the same IAM Role can run the same command without errors.

The error is:
```An error occurred (InvalidToken) when calling the PutObject operation: The provided token is malformed or otherwise invalid.```

The EC2 Instance, the IAM Role and their association to one another is performed by terraform, so there are no disparities in privileges.

When I run `aws configure list` on both instances, I get the same result:
```$ aws configure list
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
access_key     ****************AAAA         iam-role
secret_key     ****************AAAA         iam-role
    region                **<not set>**             None    None```

And to finish, if I run `aws configure` on the China instance and set the default region to cn-north-1, the s3 command starts working.

**Comment by reversefold** [comment]
This problem also shows up in another way when working in govcloud. In the default AWS regions some awscli commands work just fine, such as uploading an ssh key to IAM. In govcloud, though, I get an invalid token error. If I add an explicit region the command works.

**Comment by kyleknap** [comment]
This has been implemented in v2: https://github.com/aws/aws-cli/pull/3680 and it pulls region from the instance metadata service by default. We'd recommend upgrading and relying on it once v2 is GA. Closing issue.

**Comment by benjimin** [comment]
Did this ever happen? (Or did it only happen in `aws-cli` not other core SDK libraries?)

I'm still getting boto errors like:
`botocore.exceptions.NoRegionError: You must specify a region.`
on code that was deployed to an EC2.
