### ISSUE TITLE
Support kafka delete-configuration

### ISSUE THREAD

**Issue by dr460neye** [aws/aws-cli#4897]
To be able to support a complete cluster destruction in any way ( my case, terraform),

configurations should not be available forever. 

I did not found any way (cli or web interface) to delete the Kafka configuration, which means, after creating it once, it will stay there forever.

Do you see any way to achieve this? Or is this feature really missing?

**Comment by klaytaybai** [comment]
Hi @dr460neye.  Thanks for reporting this.  It does seem to be a missing feature in the service API.  I'm going to send feedback to the MSK team and close the issue here.

Also linking this issue: https://github.com/terraform-providers/terraform-provider-aws/issues/9082

**Comment by smithatlanta** [comment]
This shouldn't have been closed since there still is no way to still do this in the cli today.

https://docs.aws.amazon.com/cli/latest/reference/kafka/index.html

**Comment by dr460neye** [comment]
@klaytaybai , did you get any update from the aws team?

**Comment by robinbowes** [comment]
I found this issue when I hit the same problem - unable to delete custom msk configurations.

I have written terraform code to manage an msk cluster with a custom configuration. I can run a plan/apply which creates the cluster, then run a  destroy to delete it. However, the custom configuration is not deleted. This means that When I run plan/apply again I get a "duplicate name" error because terraform tries to create a custom configuration with the same name as the one that still exists.

**Comment by archyemi** [comment]
I am having the same issue. no way to delete the msk configuration.
