### ISSUE TITLE
CLI always asks for region when using named profile with a region set.

### ISSUE THREAD

**Issue by IanMoroney** [aws/aws-cli#4903]
aws --version
aws-cli/1.17.9 Python/3.7.6 Darwin/19.2.0 botocore/1.14.9

```
aws configure list
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
access_key     ****************HF6T      assume-role    
secret_key     ****************G8nE      assume-role    
    region                eu-west-1      config-file    ~/.aws/config
```
```
aws configure list --profile root
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                     root           manual    --profile
access_key     ****************WME4      assume-role    
secret_key     ****************rcEO      assume-role    
    region                <not set>             None    None
```

~/.aws/config

[default]
region=eu-west-1
output=text

[root]
region=eu-west-1
output=text

aws ec2 describe-instances --profile root
You must specify a region. You can also configure your region by running "aws configure".

Effectively,
When running awscli commands against a named profile that has a region configured, the cli ignores the region configured for that profile.

**Comment by bisdavid** [comment]
This problem is caused by the ~/.aws/config file being incorrectly formed.  The entry for the profile name must be:
`[profile root]` not just `[root]`

This applies only to the ~/.aws/config file (NOT ~/.aws/credentials), and NOT to `[default]`.  All named profiles in ~/.aws/config _**except**_ `[default]` must include the word profile in the name.  See this page https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html for more details.

I hope this helps!
Dave

**Comment by IanMoroney** [comment]
Ah! I never knew this 😄 
Thank you, will try now!

**Comment by IanMoroney** [comment]
Yep! all working now

Thanks @bisdavid !
