### ISSUE TITLE
DynamoDB update-table with ReplicaUpdates gives unclear ValidationException

### ISSUE THREAD

**Issue by haleksan** [aws/aws-cli#4906]
I was trying to convert an existing local single-region DynamoDB table to a Global Table using AWS CLI. 

I was following this page: https://aws.amazon.com/blogs/aws/new-convert-your-single-region-amazon-dynamodb-tables-to-global-tables/ 

I have executed the following commands:

- to create the table:
`aws dynamodb create-table  --region us-east-1 --table my-test-table  --key-schema AttributeName=id,KeyType=HASH  --attribute-definitions AttributeName=id,AttributeType=S 
--billing-mode PAY_PER_REQUEST`

- to update the table:
`aws dynamodb update-table --table-name my-test-table "{\"ReplicaUpdates\":[{\"Create\":{\"RegionName\":\"us-east-1\"}}]}"`

which resulted into the following error:
`An error occurred (ValidationException) when calling the UpdateTable operation: Cannot add, delete, or update the local region through ReplicaUpdates. Use CreateTable, DeleteTable, or UpdateTable as required.`

which is not exactly highlighting the issue, which is an attempt to add a region which already exists for the table. In GUI, the regions which are already used are not showing in the drop-down menu.

Could you please consider improving the error text?

**AWS CLI version:** 1.16.298
**Python version:** 3.7.0
**Botocore version:** 1.13.34
**Global table version:** 2019.11.21

**Comment by KaibaLopez** [comment]
Hi @haleksan, 
Thanks for pointing this out, let me look a bit into this, it might be a limitation on the error codes the service sends.

**Comment by AlexKryv** [comment]
Hi, any updates on this topic?

**Comment by tim-finnigan** [comment]
Hi @haleksan and @AlexKryv thanks for your patience - I've just stumbled upon this issue and trying to understand if it's still a problem. I wasn't able to reproduce the issue with the original commands provided. (I am using v2.8.2 of the AWS CLI and recommend upgrading to the latest version of v2 if you're able to.)

If this is still an issue please provide a reproducible snippets as well as debug logs (by adding `--debug` to the command) so that we can look further into this. Thanks!
