### ISSUE TITLE
Windows doesn't install aws2 executable

### ISSUE THREAD

**Issue by wscarano** [aws/aws-cli#4933]
Been using Mac with aws and aws2 and it's working well.
Installed Windows version and confused.

Both CLI 1 and 2 install with an "aws" executable. Expected cli 2 to install with "aws2". I manually renamed cli 2 preview to aws2. Seems to work.
But on a corporate machine it requires admin to rename it.

Why isn't it installed as aws2? Also, instructions indicate you should use aws. 
https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-windows.html

To confirm the installation, use the aws --version command at a command prompt (open the Start menu and search for cmd to start a command prompt).
C:\> aws --version
aws-cli/2.0.0dev4 Python/3.7.4 Windows/10 botocore/2.0.0dev3

Sorry if I missed this being covered elsewhere.

**Comment by KaibaLopez** [comment]
Hi @wscarano ,
To clarify, the issue is you expected cli's command to be "aws2" to represent the version 2 installation? Or did you not want version 2 to replace the older version?

**Comment by wscarano** [comment]
Yes, expected the Windows installer to install aws2 executable not aws. With aws you can't distinguish between both versions. On Mac it is installed as aws2.
The resolution was to simply rename the aws file to aws2.
No, I do not want to replace older version. I want to run both side by side.

**Comment by KaibaLopez** [comment]
Hi @wscarano , 
The thing is, V2 is meant to replace V1, so by default you'd only have one version installed and not the 2 side by side .
So if you want that then yea, you're going to have to do so manually (different install location/name/command), I don't think we would or should change that.
What is confusing though is that for mac you say that aws2 was installed as a default... I tried it on my mac and it didn't though, so maybe you got v2 when it was still in a beta stage, but at least now it works as expected so that is fixed.

**Comment by wscarano** [comment]
Yes..disconnect on my end. Didn't know aws2 went into GA and was renamed. All makes sense now. Thank you! I'll close.
