### ISSUE TITLE
Cannot upload file on ec2 instance to s3 through AWS Systems Manager

### ISSUE THREAD

**Issue by 09panesara** [aws/aws-cli#4938]
Hi,

I am trying to upload a file via SSM to an S3 bucket from an EC2 instance (have set up the permissions accordingly) and get this error: 

> An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
> failed to run commands: exit status 1.

If I run the same command directly from the ec2 instance, it works fine. So is there some additional permission I need to set up to be able to upload the file from the instance to s3 via SSM?

Downloading a file from s3 i.e. running `aws s3 cp s3://my bucket name/path_to_file /home/shared/filename.mp4` works

Any help would be much appreciated! 
Amrita

**Comment by kyleknap** [comment]
Given that you are able to log into the EC2 instance and run the command successfully. It seems the issue may be due to the policy for the role that is getting assumed. Specifically, I'm wondering if specific SSM privileges are not assigned to to its trust policy. I'd recommend reaching out to AWS Support to figure this out. We try to reserve issues in this repository for [CLI specific issues](https://github.com/aws/aws-cli/blob/develop/README.rst#getting-help) and support should be able to better troubleshoot the issue you are running into.

**Comment by 09panesara** [comment]
Hi yeah I think it is something with the policies, thank you for the recommendation I will get in touch with AWS Support!
