### ISSUE TITLE
Why did timestamp length increase by 8 chars in aws-cli V2?

### ISSUE THREAD

**Issue by mbailey** [aws/aws-cli#5045]
Untested fix: https://github.com/aws/aws-cli/pull/5046

I'm reviewing the aws-cli V2 [breaking changes](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-timestamp) to update [Bash-my-AWS](https://github.com/bash-my-aws/bash-my-aws/issues/293) and noticed timestamps just got 8 chars longer. The reason I care is that Bash-my-AWS provides wraps AWSCLI commands to provide line oriented output when listing AWS Resources. This change makes lines adds up to 16 chars of output (where there is create_time, update_time) without providing more information (IMO).

Is there any value in consuming an extra 8 CLI columns for each timestamp?:
- Replacing `Z` with `+00:00`
- Appending `000` in switch from milliseconds to microseconds.

## Output from running the same command using V1 and V2

**aws-cli v1**
```
$ ~/.local/bin/aws --version
aws-cli/1.16.314 Python/3.7.6 Linux/5.4.20-200.fc31.x86_64 botocore/1.13.50
$ ~/.local/bin/aws cloudformation list-stacks --query 'StackSummaries[1].CreationTime' --output text
2019-12-31T14:04:11.575Z
```

**aws-cli v2**
```
$ aws --version
aws-cli/2.0.2 Python/3.7.3 Linux/5.4.20-200.fc31.x86_64 botocore/2.0.0dev6
$ aws cloudformation list-stacks --query 'StackSummaries[1].CreationTime' --output text
2019-12-31T14:04:11.575000+00:00
```

**Comment by nateprewitt** [comment]
Hey @mbailey, thanks for reaching out! The main driver for this change was to support consistent time stamping across all AWS services. In v1, we return whatever timestamp the service gave us back which is problematic because formats aren't necessarily consistent across services.

The reason for going with milliseconds is it's the most granular format a service may return. This saves the user from having to go read docs about whether the precision of a timestamp the service returns.

The second advantage was to make timestamps constant length going forward so parsing becomes less difficult. This also meant removing the special casing for `Z` representing `+00:00` in order to avoid an edge case.

That said we may be able to look into providing a configurable date format option. Do you have any thoughts on that or alternative approaches?

**Comment by mbailey** [comment]
Hi @nateprewitt , the change actually added microseconds, not milliseconds and this seems like overkill, especially as they seem to always be zeros.

**Comment by nateprewitt** [comment]
Apologies for the typo, @mbailey. I've edited the above comment to make my initial response clearer.

While those last three digits may be zeroes with common services today, that's subject to change as existing services evolve and new ones are launched. The goal with v2 is to provide consistent unambiguous timestamps for that potential future.

We can definitely take a look at options for supporting configurable timestamp formatting, if you think that would be helpful.

**Comment by mbailey** [comment]
Consistent timestamping is an improvement on the previous behaviour. :-)

Allowing users to specify shorter output would be great.

This could be as simple as an environment variable that specifies and alternative `timespec` argument to `isoformat()`. The current one is:

[`.isoformat(timespec='milliseconds')`](https://github.com/aws/aws-cli/blob/f23703e419c4f80276883942e4db805275ae3b1d/awscli/utils.py#L137)
