### ISSUE TITLE
Feature: Different sections or subsections for EC2 Compute and Network commands

### ISSUE THREAD

**Issue by nofunatall** [aws/aws-cli#5054]
Issue: Within `aws ec2` there are some 398 options which is a pain to deal with from a readability sense and from a tab completion sense. In particular many of these commands that are underneath EC2 are purely networking related and are not really uniquely tied to EC2 compute service.

Suggestion: Move networking commands to a different subsection of aws e.g one called network `aws network create-vpc <commands>`
Or alternatively create a subsection within `aws ec2` called 'network' or 'networking' and move commands related to networking to this subsection e.g `aws ec2 network create-vpc`

Additionally since some services also use networking features like VPC's e.g containers it doesn't make sense from the CLI to have these networking commands underneath EC2.

**Comment by klaytaybai** [comment]
Thanks for the feedback.  You make a good point.

Our SDKs and the CLI generate the majority of their service-specific code based on models that we get from the service teams.  What this means for this issue is that there is currently no hierarchy of commands within a given service.  Your feedback gives us more customer evidence for the need to make this hierarchy happen.
