### ISSUE TITLE
Connection was closed before we received a valid response from endpoint URL

### ISSUE THREAD

**Issue by bdrgn** [aws/aws-cli#5090]
I am receiving the above error when trying to upload my code to Lambda using the cli:

`aws lambda update-function-code --function-name AvitoFlats --zip-file fileb://function.zip`

One day ago it worked fine like many times before.

Tried:
- Different networks
- Restarting my machine
- Updating AWS CLI to the latest version

Connection was closed before we received a valid response from endpoint URL: "https://lambda.us-east-2.amazonaws.com/2015-03-31/functions/name/code".

**Comment by KaibaLopez** [comment]
Hi @bdrgn ,
could you add --debug to the command and show me what you get? (Remember to sanitize personal info).

**Comment by bdrgn** [comment]
![image](https://user-images.githubusercontent.com/34234843/77817858-3e180180-70df-11ea-95dd-20b9418fbb25.png)
First this and then some huge nonsensical mess which freezes my machine. 
I will try to make sense of this next if current out

**Comment by bdrgn** [comment]
Looks like this.
![image](https://user-images.githubusercontent.com/34234843/77829168-587acb00-7131-11ea-9ca2-c1a80e2b5518.png)

**Comment by KaibaLopez** [comment]
Hmmm,
yea not really much I can see from the logs, it does sound like it's a connection problem, is the zip file very heavy or is your connection unstable? Could you be trying to connect through a different region? 
sorry that I can't be of much help, kind of shooting at the dark here since I don't have much information to go by... I can't reproduce either.

**Comment by dvillevald** [comment]
I am having the same problem trying upload zip folder to lambda

**Comment by PranavMonotype** [comment]
Its can be a network error.
If you are connected to a VPN , try after disconnecting it
try with better internet connection
my case, closing the VPN worked

**Comment by nestradarand** [comment]
damn, I'm having this same exact problem as well

**Comment by miesismore** [comment]
Same problem here, uploading a 12GB .7z compressed file, is there any problem with this size? is better to upload uncompressed or at lower sizes? (i read CLI was recommended for >160Gb so i guess is no problem with this)

**Comment by itsdarrylnorris** [comment]
I am getting the same error sometimes. Any workarounds?

**Comment by szanata** [comment]
I was having the same issue. One day it worked, the very next day, not.
In my case I was uploading a lambda layer with a ~20M zip file. My script was using AWS 2.0 inside a docker container.
What I did to solve the issue was to restart the Docker client and reconnect the WIFI. So I guess this is indeed related to a network error.

**Comment by itsdarrylnorris** [comment]
If you are on a VPN or slow connection this will happen all the time. My recommendation is to switch to a faster internet connection and get off any VPN if possible.
