### ISSUE TITLE
Should be able to filter EFS by tags

### ISSUE THREAD

**Issue by ay0o** [aws/aws-cli#5126]
**Is your feature request related to a problem? Please describe.**
`aws efs describe-file-systems` does not support filters. This makes it inconsistent with the usage of many other resources such as EC2, VPC, etc.

**Describe the solution you'd like**
It should support the `--filters` argument, the same way many other resources already do.

For example, `aws efs describe-file-systems --filters 'Name=tag:Name,Values=foo'`

**Additional context**
I understand it has the `--creation-token` argument, but to keep consistency with other products, it should also support `--filters`.

**Comment by kdaily** [comment]
Hi @ay0o,

Since the `--filter` parameter is used server-side, this will be a feature request to the service team. In the meantime, you can use the `--query` parameter and a JMESPath filter to achieve this result too, while this may not be desirable since it happens client-side:

https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-output.html#cli-usage-output-filter
