### ISSUE TITLE
while im trying to login from iam user giving my access id and secret access key im getting below error

### ISSUE THREAD

**Issue by naveenhc** [aws/aws-cli#5166]
while im trying to login from iam user giving my access id and secret access key im getting below error

An error occurred (SignatureDoesNotMatch) when calling the GetUser operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

**Comment by KaibaLopez** [comment]
Hi @naveenhc ,
It could be that you made a mistake when saving it, or that the credentials expired, in any case since there is no way for me to safely check for you or recreate the problem all I can really suggest is creating a new access key and secret key for the iam user.
 Try:
`aws iam create-access-key --user-name your_user_name`
And put those in your ./aws/credentials file.
