### ISSUE TITLE
[v2] sts assume role does not save credentials to /.aws/cli/cache

### ISSUE THREAD

**Issue by hybmg57** [aws/aws-cli#5171]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Run sts assume role and it gets printed to console but not saved in cache

**SDK version number**
2.0,.5

**Platform/OS/Hardware/Device**
Mac OS Catalina

**To Reproduce (observed behavior)**
run `aws sts assume-role --role-arn arn:aws:iam:12233122:role/testRole --role-session-name test`

**Expected behavior**
I expect it to save automatically so I can assume role and run cli command without having to do extra work

**Logs/output**

**Additional context**

**Comment by KaibaLopez** [comment]
Hi @hybmg57 , 

Sorry but could you clarify a bit for me? 
when you run the sts assume role, it succeeds right?
What happens for calls done after that? is it using the correct role?
Also, did you verify that the expiration of the assume role was not reached?

**Comment by hybmg57** [comment]
Hi @KaibaLopez ,

Yes sts assume role succeds but it returns JSON at the response.
I'm currently saving the response using `jq` to a file and sourcing it to export the `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` , `AWS_SESSION_TOKEN`
but it is not ideal and I want a way to automatically wrap those within my cli commands and refresh every time I call assume role AWS CLI command

**Comment by KaibaLopez** [comment]
@hybmg57 , 
I did some digging because I wasn't completely clear on the service and what you were saying made sense, but as it turns out sts assume role is not going to do that, according to the [API documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sts/assume-role.html): 

> assume-role
> Returns a set of temporary security credentials that you can use to access AWS resources that you might not normally have access to. These temporary credentials consist of an access key ID, a secret access key, and a security token. 

Confusing as the naming may be, assume role only fetches the credential, doesn't _use_ them...
That being said, have you taken a look at [this guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html)? It goes over how to use IAM roles using the CLI only it does it through config file setup rather than cli calls? 

Chaeck it out, let me know what you think or if I am missing something here.

**Comment by cyrillay** [comment]
Same issue here.

The documentation [states](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html) that

```
When you use a role, the AWS CLI caches the temporary credentials locally until they expire.
```

and then, the doc gives this command to clear the cache :

`rm -r ~/.aws/cli/cache`

So I was also assuming that the credentials would be stored in this file.
