### ISSUE TITLE
aws ec2 run-instances doesn't support --availability-zone

### ISSUE THREAD

**Issue by julieso** [aws/aws-cli#555]
I was looking for an equivalent to the --availability-zone option for ec2-run-instances. Can I launch an instance into a particular AZ in EC2-Classic using the AWS CLI?

**Comment by l15k4** [comment]
What if you want to create 3 instances and each in a different AZ ?

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by julieso** [comment]
I'm fine closing this out, as new accounts haven't had access to EC2-Classic since around the time I opened this.
