### ISSUE TITLE
Global --quiet --only-show-errors flags

### ISSUE THREAD

**Issue by dreh23** [aws/aws-cli#5573]
The aws s3 command has this feature, the aws s3api command not. This seems very in concise and breaks developer expectations.

Proposition:
Global flags for all subcommands

**Comment by kdaily** [comment]
Hi @dreh23, 

Thanks for the feature request. It's possible that a global flag could be used, but it would have to be scoped to the CLI so that it wouldn't cause any incompatibility with different services. It could be something like `--cli-quiet-mode`.

The current thinking is the output that is shown is limited to that of high importance. You can get rid of anything further unwanted with standard command line tools, like redirecting to `/dev/null`.

I'm going to leave it as a feature request for more discussion, but it's not something that we'd look to change immediately.

**Comment by dreh23** [comment]
Hi @kdaily,

we are using the cli tool programmatically and it would be useful if we do not need to pipe output to null. This just complicates things if you have several jq/awk/sed pipelines.

I believe developer experience could be massively improved if commands and subcommands, global flags are streamlined.
