### ISSUE TITLE
amazon/aws-cli Docker image from DockerHub doesn't work

### ISSUE THREAD

**Issue by yarax** [aws/aws-cli#5593]
I'm using GitLab Pipeline with the AWS CLI Docker image and getting immediately error before execution of any actual commands of the pipeline inside the container:

```
Checking out ...
Skipping Git submodules setup
Executing "step_script" stage of the job script
00:01
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
```

It looks like container executes a command without or with wrong arguments on start up.
So the pipeline fails without running any further commands

**Comment by kdaily** [comment]
Hi @yarax,

I agree that it looks like the container is executing a command improperly. However I would need to see how you (or the pipeline) is invoking this container. Important to note the [entrypoint for this container](https://github.com/aws/aws-cli/blob/v2/docker/Dockerfile#L21) has the `aws` command filled for you (See the [docs here](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-docker.html#cliv2-docker-install)). Running it then looks like:

```
$ docker run --rm -it amazon/aws-cli command
```

Note that you do not provide another call to `aws`. Could your call, or the pipeline, be doing that?

**Comment by yarax** [comment]
Ok, now I see why it happens, thank you @kdaily for the tip. 
I think it would be useful for any kind of CI/CD tools (GitHub Actions e.g support the similar way of running things) not to have entrypoint (if I need, I could pass it directly as `docker run --rm -it amazon/aws-cli aws s3 ls`). 
Because how these CI/CD tools work, they run container and execute certain pipeline commands inside of it. So I as a user of the pipeline don't expect any default commands, just needed software (aws cli in this case) or OS.

**Comment by kdaily** [comment]
Thanks for the use case @yarax.

I looked at how GitHub Actions documents setting up an action based on a Docker container image. They do show the use of an entrypoint, which means a user only needs to know what parameters to supply:

https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-docker-container-action#creating-a-dockerfile

I do, however, agree with you that the AWS CLI feels a bit different than that, given that it provides full access to the entire command (and sub-command) set. I'm going to mark this as a feature request and something for more discussion.

**Comment by kdaily** [comment]
I looked into this some more, and the decision was made to make it easy to run commands for local use and maintain 'look and feel' of running a command line command. Indeed, we document how easy it is to add an alias to run the Docker container image from the CLI so that it's just like if it was locally installed:

https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-docker.html#cliv2-docker-aliases

It is also to reinforce that the AWS CLI executable is the only thing supported in this container. If you want to override the entry point to use other commands, the option is available to you. I think that CI/CD programs will still run as intended by just leaving out the `aws` prefix from the command name. If you do want to remove that behavior, using this container image as a parent is straightforward in your own `Dockerfile`:

```
FROM amazon/aws-cli:2.0.54
ENTRYPOINT []
```
