### ISSUE TITLE
aws s3 cp not retrying on failure -- large file

### ISSUE THREAD

**Issue by nunoperalta** [aws/aws-cli#5596]
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [x] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.

**Platform/OS/Hardware/Device**
Windows 10

**Describe the question**
I'm trying to upload a 200GB file to my S3 bucket.

I've already tried a few attempts, but after a random number of hours, one of the requests fail, and the whole thing crashes.

Command:
`aws s3 cp D:\BIG_FILE s3://my-bucket/ --storage-class DEEP_ARCHIVE --profile s3bucket --output text`

I was able to upload one 200GB file on the second attempt, yesterday,
but today it's been already 3 attempts and ended up crashing.

I'm afraid I could try this several times, while my monthly bill increases on every attempt.

Isn't the command supposed to retry that specific request when it fails, so that I don't have to **start from beginning** every time there's a failure?

**Logs/output**

> D:\>aws --version
> aws-cli/1.18.149 Python/3.6.0 Windows/10 botocore/1.18.8
> 
> D:\>aws s3 cp D:\BIG_FILE s3://my-bucket/ --storage-class DEEP_ARCHIVE --profile s3bucket --output text
> upload failed: .\BIG_FILE to s3://my-bucket/BIG_FILE Connection was closed before we received a valid response from endpoint URL: "https://my-bucket.s3.us-west-2.amazonaws.com/BIG_FILE?uploadId=cB...............TEMdD&partNumber=211".
> 
> D:\>aws s3 cp D:\BIG_FILE s3://my-bucket/ --storage-class DEEP_ARCHIVE --profile s3bucket --output text
> upload failed: .\BIG_FILE to s3://my-bucket/BIG_FILE Connection was closed before we received a valid response from endpoint URL: "https://my-bucket.s3.us-west-2.amazonaws.com/BIG_FILE?uploadId=P0...............Dh8ak&partNumber=707".
> 
> D:\>aws s3 cp D:\BIG_FILE s3://my-bucket/ --storage-class DEEP_ARCHIVE --profile s3bucket --output text
> upload failed: .\BIG_FILE to s3://my-bucket/BIG_FILE Connection was closed before we received a valid response from endpoint URL: "https://my-bucket.s3.us-west-2.amazonaws.com/BIG_FILE?uploadId=dM...............U1GrO&partNumber=417".
> fatal error:
> 
> D:\>

**Comment by kdaily** [comment]
Hi @nunoperalta,

Sorry to hear you're having trouble uploading this big file. Since this is so large, the AWS CLI is using a multi-part upload strategy. Retries are indeed attempted on each part. In order to get a better idea of what is going on, I'd need to see the output of this command with the `--debug` flag added.

In general, this error points to a network problem or instability. In your logs, you'll see successful parts uploaded with lines like:

```
2020-10-01 09:48:45,381 - ThreadPoolExecutor-0_6 - botocore.hooks - DEBUG - Event needs-retry.s3.UploadPart: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.ut
2020-10-01 09:48:47,345 - ThreadPoolExecutor-0_1 - botocore.hooks - DEBUG - Event needs-retry.s3.UploadPart: calling handler <botocore.retryhandler.RetryHandler object at 0x107994a60>
2020-10-01 09:48:47,345 - ThreadPoolExecutor-0_1 - botocore.retryhandler - DEBUG - No retry needed.
```

Unsucessful uploads that need retries look like what you are experiencing. I could force this to happen by simulating network problems by suspending the command, waiting for a couple minutes, and then restarting it:

```
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://mybucket.s3.us-west-2.amazonaws.com/test.bin?uploadId
=HK0poARrTZOwa8q7qnSshWreKU2_LKN_soCl7kaHm4WGm86z7j95C1aglW6.cdy5I0aSdjgTaxwU9bDrLz6umf7T7T2EvU6MGMAIC2aCglC8aArU33z1v.abULMBVTDc&partNumber=95".
2020-10-01 09:54:19,820 - ThreadPoolExecutor-0_1 - botocore.retryhandler - DEBUG - Retry needed, action of: 0.40170638577266715
2020-10-01 09:54:19,820 - ThreadPoolExecutor-0_7 - botocore.hooks - DEBUG - Event before-parameter-build.s3.UploadPart: calling handler <function convert_body_to_file_like_object at 0x105b15d30>
```

One thing that can help remediate connection timeouts due to network instability is to adjust the configuration parameter `--cli-connect-timeout` to a larger value. In the most extreme case you can set it to `0` and it will block the command from exiting until a connection is established (not recommended).

You can also check out these resources on transferring to S3:

- https://aws.amazon.com/premiumsupport/knowledge-center/s3-upload-large-files/
- https://docs.aws.amazon.com/AmazonS3/latest/dev/optimizing-performance.html

**Comment by nunoperalta** [comment]
Thank you very much. I'm glad there's an option such as "--cli-connect-timeout". I will be setting it to '0' next time I run this. As this is a job that will be run manually and monitored while it runs, I think it will be fine :)

Yeah, I'm actually running it again with "--debug" (since I saw it suggested in other threads), but it hasn't failed since.
If it does fail, I'll paste here the output. If it succeeds, I'll close the thread.

Thank you!

**Comment by nunoperalta** [comment]
Closing this as my last attempt was successful!
Have a great day.
