### ISSUE TITLE
Document the AWS_EC2_METADATA_DISABLED environment variable

### ISSUE THREAD

**Issue by kdaily** [aws/aws-cli#5623]
**Is your feature request related to a problem? Please describe.**

If no region is set, the AWS CLI tries to use the IMDS service to determine it. In some cases, like when running the AWS CLI on an Azure instance, another service can be running at the same non-routable IP address used by IMDS. One way to get around this is to explicitly set a region. However, there is an undocumented environment variable that can prevent the request to IMDS:

```
AWS_EC2_METADATA_DISABLED=true
```

Related issues:

- https://github.com/aws/aws-cli/issues/5262
- https://github.com/aws/aws-cli/issues/5234

**Describe the solution you'd like**

Document the environment variable in the user guide:

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html

**Describe alternatives you've considered**

Setting the region can prevent this behavior, but using the environment variable is more explicit in controlling it.

**Additional context**

None

**Comment by esamattis** [comment]
Today our CI deploys in Github Actions started fail on AWS CLI commands. They print lines like

```
<botocore.awsrequest.AWSRequest object at 0x7f83d900af70>
```

and exit with 255 code. No other error messages.

Setting `AWS_EC2_METADATA_DISABLED=true` fixed the issue for us. Probably a networking issue with github vs. aws.

Posting this here since googling this brought me here and it might help others too.

**Comment by kdaily** [comment]
Hi all, this is now in the documentation of environment variables for the CLI:

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
