### ISSUE TITLE
default profile does not use expected credentials from environment variables

### ISSUE THREAD

**Issue by jrobison-sb** [aws/aws-cli#5767]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
My goal is to be able to use `--profile default` with my credentials exported as environment variables.

As part of trying to do that, I see that `credential_source = Environment` doesn't work as expected for the default profile.

**SDK version number**
`aws-cli/1.18.185 Python/3.9.0 Linux/5.4.0-1029-aws botocore/1.19.25`

**Platform/OS/Hardware/Device**
Debian, on EC2.

**To Reproduce (observed behavior)**
Use an EC2 server with an IAM role so that credentials can be pulled from the metadata service.

And also export `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`, which belong to a separate IAM user.

Instruct the AWS CLI to use credentials from those environment variables:
```
$ head ~/.aws/config
[default]
region = us-east-1
credential_source = Environment
```

You can see that when the CLI is used without `--profile`, the credentials from the exported environment variables are used, which is the expected behavior:
```
$ aws configure list
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
access_key     ****************foo               env    
secret_key     ****************foo               env    
    region                us-east-1              env    AWS_DEFAULT_REGION
```

But when the CLI is used with `--profile default`, credentials from an IAM role are used instead of credentials from environment variables, which is not the expected behavior:
```
$ aws configure list --profile default
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                  default           manual    --profile
access_key     ****************bar          iam-role    
secret_key     ****************bar          iam-role    
    region                us-east-1              env    AWS_DEFAULT_REGION
```

**Expected behavior**
I would expect that `aws configure list --profile default` should use the same credentials as `aws configure list`.

**Comment by kdaily** [comment]
Hi @jrobison-sb, 

This looks like it might be related to #4958.

**Comment by kdaily** [comment]
One thing that could help me is to provide `--debug` when you run the `aws configure` commands. Thanks!

**Comment by kdaily** [comment]
Hi @jrobison-sb, sorry for the delay. Per the documentation, `credential_source` is only available for use when assuming a role:

https://docs.aws.amazon.com/credref/latest/refdocs/setting-global-credential_source.html

So, this behavior is not possible, and that's by design. Having credentials come from different sources if profiles are set or not would make it difficult to debug. This is the expected behavior, however - the credential provider chain is described here: 

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-precedence

In the first case, you're not explicitly setting `--profile`, so your environment variables are used. In the second, you are setting `--profile` (even though it is `default`, it's still a named profile), there are no credentials configured, so it goes all the way through to using IMDS with the IAM role attached to your EC2 instance.

Hope this makes sense!
