### ISSUE TITLE
Update metadata information for a subfolder in a bucket

### ISSUE THREAD

**Issue by galaxy79** [aws/aws-cli#5847]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
x
Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [ x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
Ubuntu
**Describe the question**
Hi, is there a way using aws cli to update metadata info of all the objects available on a subfolder ?

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by kdaily** [comment]
Hi @galaxy79,

Thanks for the question. Unfortunately there isn't a specific command available with the S3 public API, so it's also not available with the AWS CLI.

This has been requested a few times here (see https://github.com/aws/aws-cli/issues/2895, which suggests using tags instead of metadata, and https://github.com/boto/boto3/issues/389 which has some examples in Python).

The best answer I've found on how to do this is from the AWS Go SDK - a similar method is found in #389, but this has more details. It would probably be easier to manage this with an AWS SDK (like `boto3`) rather than trying to do this on the command line, as you'll need some data structures to facilitate.

https://github.com/aws/aws-sdk-go/issues/2833

**Comment by galaxy79** [comment]
thanks @kdaily
