### ISSUE TITLE
CLI v1.18.218 uses version(s) of PyYAML that has a known vulnerability

### ISSUE THREAD

**Issue by smimani-godaddy** [aws/aws-cli#5893]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
AWS cli requires  PyYAML<5.4,>=3.10 but these versions have a known vulnerability. https://snyk.io/vuln/pip:pyyaml 
**SDK version number**
latest
**Platform/OS/Hardware/Device**
What are you running the cli on?
macOS

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

**Expected behavior**
Use a version of PyYAML that is vulnerability free
**Logs/output**
 awscli 1.18.218 has requirement PyYAML<5.4,>=3.10; python_version != "3.4", but you'll have pyyaml 5.4 which is incompatible.
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by nateprewitt** [comment]
Hi @smimani-godaddy, I believe there's already a PR (#5887) open around this. The CLI only uses `safe_load`, so it's not impacted by the current CVEs in PyYAML. We're working to validate we can raise the allowed pin, allowing other software to use an updated version.

Users who upgrade to the CLI v2 will avoid these routine CVEs with PyYAML since the dependency has been dropped entirely.
