### ISSUE TITLE
aws s3 sync doesn't sync all folders inside a bucket

### ISSUE THREAD

**Issue by vivekjhauipath** [aws/aws-cli#5908]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
I am using aws s3 sync to take backup of a bucket to local disk. My bucket contains 3 folders (at a logical level) - PipelineRun, logs, Packages. Inside each of these folders I have subfolders for each run and then files generated during those runs in different formats. e.g. logs files are text files, PipelineRun contains json files, images etc.
When I run `aws s3 sync ` on bucket the destination folder only contains PipelineRun & Packages folders with all the blobs inside it.
It is missing logs folder
When I run `aws s3 sync ` on bucket/logs folder the destination folder contains all the files and folders from the logs folder

**SDK version number**
Version 2

**Platform/OS/Hardware/Device**
What are you running the cli on?
I am running on ubuntu 18.04. The only difference from your normal use cases would be that I am running it against ceph storage which exposes s3 apis.

**To Reproduce (observed behavior)**
Steps to reproduce the behavior
- Create ceph storage
- Create bucket in ceph
- Create folders in that bucket
- Get credentials to connect aws cli to it
- run aws s3 sync on bucket
Data sharing might be difficult for me as those are customer files.

**Expected behavior**
sync should generate all files and folders

**Logs/output**
I will try to attach log file somehow. It is 30MB.

**Additional context**

**Comment by vivekjhauipath** [comment]
Log files

[xad.txt](https://github.com/aws/aws-cli/files/5908874/xad.txt)
[xac.txt](https://github.com/aws/aws-cli/files/5908875/xac.txt)
[xab.txt](https://github.com/aws/aws-cli/files/5908876/xab.txt)
[xaa.txt](https://github.com/aws/aws-cli/files/5908877/xaa.txt)

**Comment by vivekjhauipath** [comment]
[syncad.txt](https://github.com/aws/aws-cli/files/5909004/syncad.txt)
[Uploading syncac.txt…]()

**Comment by vivekjhauipath** [comment]
[syncac.txt](https://github.com/aws/aws-cli/files/5909010/syncac.txt)
[syncab.txt](https://github.com/aws/aws-cli/files/5909011/syncab.txt)
[syncaa.txt](https://github.com/aws/aws-cli/files/5909012/syncaa.txt)
[syncad.txt](https://github.com/aws/aws-cli/files/5909013/syncad.txt)

**Comment by stobrien89** [comment]
Hi @vivekjhauipath  ,

Thanks for writing in and taking the time to provide us with your log files. When reviewing the logs,  I noticed the response returned from ceph is that of the (older) [ListObjects response syntax](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html#API_ListObjects_ResponseSyntax).  One indicator of this is the presence of a “Marker” element in the response: 

```
2021-02-02 04:49:58,666 - MainThread - botocore.parsers - DEBUG - Response body:
<?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>[operation]-5c44556b-535e-4db9-9fa2-46f383e219cc</Name><Prefix></Prefix><Marker></Marker>
```

Because the CLI is sending a [ListObjectsV2](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html) request, the Ceph response syntax is incorrect.  Additionally, the empty “Marker” element indicates there is no proper pagination, which is limiting the sync to 1000 files— It appears there may be an issue with the Ceph implementation. I’d suggest reaching out to Ceph for support with this issue, as we have seen [similar issues](https://github.com/aws/aws-cli/issues/4268) with their endpoints in the past. We can only guarantee that S3 sync works with AWS endpoints.  Hope this helps!

**Comment by vivekjhauipath** [comment]
Thanks @stobrien89 for these details, I will reach out to ceph. I agree that they have a few such issues.
Meanwhile do you have any recommendations on how I can get around it if ceph is unable to deliver the fix soon.

**Comment by stobrien89** [comment]
Hi @vivekjhauipath ,

Of course! That's what we're here for.  I'm unfortunately not familiar enough with ceph to provide any workarounds, as the response is coming directly from their endpoint.  The only thing I could suggest/support would be S3 buckets, but I know that's likely not an option if you're currently relying on ceph. Wish I could be of more help!

**Comment by vivekjhauipath** [comment]
Thanks for the help
