### ISSUE TITLE
AWS s3 Fails without a helpful error

### ISSUE THREAD

**Issue by ClappTrap** [aws/aws-cli#6028]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug** 

trying to copy a golang binary from github actions to aws s3 and it fails on a call to url `/latest/api/token` (I think this is an auth call? clarification would be cool so i can understand more how the calls work). 

**SDK version number**
2.1.30
**Platform/OS/Hardware/Device**
Github Actions

**To Reproduce (observed behavior)**
I have not been able to reproduce with my admin user creds. A helpful error response would provide more context as to why this call fails. 

**Expected behavior**
I would expect the file to upload. 

**Logs/output**
<img width="1078" alt="Screen Shot 2021-03-17 at 9 15 56 AM" src="https://user-images.githubusercontent.com/36860492/111500623-6db18680-8701-11eb-9c9d-0df0650c7bf1.png">

**Additional context**

This may just be a failing call for no reason. this all worked yesterday. 

---------
It appears this is isolated to github actions. I was able to push on my local machine vs github actions.

**Comment by DylanBohlender** [comment]
I am currently having what appears to be a somewhat related issue - also involving GitHub Actions. 

Specifically, I'm getting a 255 error code from `aws sts get-caller-identity` when running the AWS CLI on GitHub Actions (for reference, I'm getting this code by `echo`ing the `$?` register after running the command). I've triple-checked that the IAM credentials provided to the remote GitHub Actions runner are correct, and I've even been able to successfully call the aforementioned STS function on my local machine, using the exact same numerical version of the CLI and the exact same IAM credentials.

There must be _something_ different between GitHub Actions's build/implementation of the 2.1.29 AWS CLI and my local machine's build/implementation of the 2.1.29 AWS CLI. Proverbial question of course being whether the problem lies in the build itself, or the implementation.

Here is the version info for the AWS CLI executable on **my machine** (which works fine): `aws-cli/2.1.29 Python/3.8.8 Darwin/19.6.0 exe/x86_64 prompt/off`

Here is the version info for the AWS CLI executable that **GitHub Actions** appears to have installed: `aws-cli/2.1.29 Python/3.8.8 Linux/5.4.0-1040-azure exe/x86_64.ubuntu.20 prompt/off`

I only noticed this becoming a problem a day ago, so my suspicion is that the problem lies on GitHub Actions's end (a fault in their VMs maybe?). I haven't been tracking the version of the AWS CLI that GitHub Actions has been using before this point in any fashion though - because usually the CLI "just works" (big kudos to the team here for that).

However, since I can't personally debug the ubuntu.20 version that GitHub Actions is using, I can't say with certainty that the problem isn't the AWS CLI binary itself. Hopefully someone can add further clarity!

**Comment by DylanBohlender** [comment]
@ClappTrap I found an issue on GitHub Actions's side that might be helpful to you. They have been gradually upgrading their VMs to Ubuntu 20.04, and those upgraded VMs default to v2 of the AWS CLI instead of v1 like their old Ubuntu 18 VMs.

The big difference between the two is that you need to **explicitly** specify the `region` for the AWS CLI, even if you're using something like S3 that is typically referred to in regionless fashion. Explicitly specifying the region with `aws configure set region region-name-here` prior to running CLI commands fixed my STS problem entirely, and hopefully it will help fix yours too!

**Comment by ClappTrap** [comment]
@DylanBohlender I will try this in a little while! Thanks for looking into it. Nice catch!

**Comment by ClappTrap** [comment]
@DylanBohlender  you are my hero. <3 thanks
