### ISSUE TITLE
aws-cli push deploy error with yaml file

### ISSUE THREAD

**Issue by rgb4268** [aws/aws-cli#6062]
So I was following the instructions on https://docs.aws.amazon.com/codedeploy/latest/userguide/tutorials-wordpress-upload-application.html to create my app to upload to AWS using CodeDeploy. My dev machine is Windows, so the issue is that the chmod command which is 
chmod +x /tmp/WordPress/scripts/*

I created a zip file as indicated  in https://docs.aws.amazon.com/codedeploy/latest/userguide/tutorials-wordpress-upload-application.html, including an appspec.yml file in the WordPress directory as specified. Then I did 
aws deploy push --application-name WordPress_App --s3-location s3://<bucket-name>/WordPressApp.zip --ignore-hidden-files

But I got this error - 
appspec.yml was not found

So how to fix this?

**Comment by stobrien89** [comment]
Hi @rgb4268,

Thanks for writing in!  It's difficult to say what the issue is without a bit more information— Would you be able to provide your CLI version number, as well as debug logs by appending `--debug` to your command? Please redact any sensitive information, such as account numbers.  Thanks!
