### ISSUE TITLE
pip install aws-cli versión 1.19.51 fail

### ISSUE THREAD

**Issue by geekofer** [aws/aws-cli#6096]
![image](https://user-images.githubusercontent.com/12529651/114789157-4376d700-9d48-11eb-9a59-d40f41c15103.png)

**Comment by shadowfool** [comment]
Seeing this same issue with node alpine current.

**Comment by adamist521** [comment]
Same here with alpine.

**Comment by adamist521** [comment]
Seems to be problem on alpine...
I was able to build successfully on 1.19.51 yesterday but changing awscli version to 1.19.51 didn't fix the problem.

**Comment by geekofer** [comment]
> Seems to be problem on alpine...
> I was able to build successfully on 1.19.51 yesterday but changing awscli version to 1.19.51 didn't fix the problem.

temporarily solvent by adding the following line before installing aws-cli
    - pip install pyyaml==5.3.1


![image](https://user-images.githubusercontent.com/12529651/114801747-f273dc80-9d61-11eb-804a-d262a5f455cd.png)

**Comment by geekofer** [comment]
> Seeing this same issue with node alpine current.

temporarily solvent by adding the following line before installing aws-cli
- pip install pyyaml==5.3.1

![image](https://user-images.githubusercontent.com/12529651/114801879-3bc42c00-9d62-11eb-86f9-4a8911e10025.png)

**Comment by adamist521** [comment]
@geekofer 
I'll try that!

**Comment by adamist521** [comment]
@geekofer 
It's working now. Thanks for the workaround.

( I had release today and suddenly it failed to deploy... You saved my life!!  Thank you in advance! )

**Comment by shadowfool** [comment]
Here's an alternate solution that doesn't require pinning
`- apk add gcc alpine-sdk python3-dev python3 py3-pip && pip3 install awscli`

**Comment by nateprewitt** [comment]
To add some more details, the issue appears to be specific to Alpine with the [new release](https://pypi.org/project/Cython/0.29.23/#history) of `Cython` today. This is a build-time dependency of one of our dependencies (PyYAML) that is usually not installed since users download pre-built wheels.

It looks like the latest release of `Cython` is missing a wheel compatible with Alpine, forcing the package to be built from source. Installing `gcc` and `python3-dev` provides the header file (`Python.h`) that the build is failing on which is what resolves the issue.

We don't have much we can do from the CLIs side since we don't control any of the packages in this installation path. The best option would be to reach out to `Cython` and see if they can upload a compatible wheel for Alpine. It looks like they supplied a wheel (`Cython-0.29.22-py2.py3-none-any.whl`) in the last release that's platform agnostic. It doesn't appear to be present in the latest release. There may also be other wheels missing, I didn't perform a full diff between the two versions.

One quick test for anyone interested would be to see whether a wheel or .tar.gz file is used when installing `cython==0.29.22` on Alpine.
