### ISSUE TITLE
How to continue to use pip 18.1 that installs python 2.7.18 to continue to work with aws cli v1

### ISSUE THREAD

**Issue by ujjwal2190** [aws/aws-cli#6099]
I use docker:18.09.6-dind container to run builds where the script is as below :-
apk add curl
apk add py-pip
pip install --user awscli
Everytime i see that pip installed on this container OS is always 18.1 but when it tries to install awscli it pulls latest in the 1.19 series.
So latest is 1.19.52 now. We had issues for most of yesterday when it was trying to install 1.19.51 as it failing on cython which i have no idea where that came from.. Now starting today its pulling 1.19.52 and that works fine.
My question is will pip 18.1 which  i believe will always remain the case with the fixed OS  docker:18.09.6-dind, continue to always pull latest in 1.19 series for awscli or will it at some point in future also pull from 1.20.* .Also will awscli in 1.19 will ever be released which won't work with python 2.7.18? If so it will be a nightmare for us to switch to a different dind container or else change the installation across several places.

**Comment by nateprewitt** [comment]
Hi @ujjwal2190,

It looks like the issue you hit yesterday yesterday is the same as #6096. The issue was constrained to Alpine images due to a incomplete release by the [`Cython`](github.com/cython/cython) team that's since been fixed. The issues shouldn't be related to the version of `pip` you're using.

`pip` (versions 9.0.0 and later) will automatically install the latest *compatible* version of a package unless given a specifier constraining the version range (e.g. `awscli<1.20`). We don't intend to release anything breaking for Python 2.7 in the awscli 1.19.* release series. Please note however, Python 2.7 support will end on July 15th, 2021 with the release of awscli 1.20.0. You can find full info in our [blog post](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-python-2-7-in-aws-sdk-for-python-and-aws-cli-v1/). At that point in time, your containers will stop receiving updates for the CLI unless upgraded to Python 3.6+.

**Comment by ujjwal2190** [comment]
Thanks Nate for the swift response. So on a given fixed alpine version lets say in my case docker:18.09.6-dind container OS, the OS should continue to always install pip 18.1 (since it would pull whatever is compatible i believe) and this pip should always install aws-cli 1.19.* versions and since pip 18.1 has python 2.7.18 (last release of python 2.7 series), so it should continue to work with any aws cli released in the future. Also does awscli 1.20 require python 3.* series ? if so will this pip 18.1 (python 2.7.18) will ever try to install awscli 1.20.*

**Comment by nateprewitt** [comment]
Correct, `pip` 18.1 should be recent enough to avoid installation issues. AWS CLI 1.20.0 and later will only provide compatibility/support for Python 3.6+. `pip` should recognize this and instead choose the last compatible version for your Python 2.7 runtime which would be the last CLI release in the 1.19.* series.

Please note though, you will no longer be receiveing feature or security updates at that point, so it's encouraged to upgrade to Python 3.6+ at your earliest convenience.
