### ISSUE TITLE
Bug in filtering in  aws greengrassv2 list-core-devices with multiple thing group memberships

### ISSUE THREAD

**Issue by FredrikMeyer** [aws/aws-cli#6121]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

I have two IoT things that are in a different groups `A`, `B`, and I created a new one `C `and added both things to that group.

When I try
```
aws greengrassv2 list-core-devices --thing-group-arn arn:aws:iot:eu-west-1:123:thinggroup/C
```

I get an empty list, even though the group `C` contains two members.

**SDK version number**

**Platform/OS/Hardware/Device**

```
aws-cli/2.1.32 Python/3.8.8 Darwin/20.3.0 exe/x86_64 prompt/off
```

**Comment by kdaily** [comment]
Hi @FredrikMeyer, the Greengrass team is aware of this issue. I'll let you know when there's an update.

**Comment by moshe-shaham-intel** [comment]
I am also experiencing this bug, even when there is only one group membership for a device.

**Comment by tim-finnigan** [comment]
Checking in as there hasn't been in activity on this issue in a while. Is this bug still occurring? The original report mentioned using AWS CLI v2.1.32 and the current version is 2.8.8 per the [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1) so this may have been fixed since then. If not then please let me know and I'll escalate this to the Greengrass team. (Also for future reference we recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) for service API issues like this to help with directing the issue to the appropriate team.)

**Comment by tim-finnigan** [comment]
Since we haven't heard back I'm going to close this. If you're still experiencing this issue please let us know here or create a new issue. Thanks!
