### ISSUE TITLE
get-login-password fails with bad request.

### ISSUE THREAD

**Issue by rafaelf82** [aws/aws-cli#6128]
Confirm by changing [ ] to [x] below:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [X] Other/Not sure.

**Platform/OS/Hardware/Device**
Docker image.

**Describe the question**
Running this command:
docker run --rm -it amazon/aws-cli aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin id.dkr.ecr.us-east-2.amazonaws.com

Fails with Bad request 400.

The following also fails:

docker run --rm -it amazon/aws-cli aws ecr get-login-password \
    --region us-east-2 \
| docker login \
    --username AWS \
    --password-stdin id.dkr.ecr.us-east-2.amazonaws.com

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.
Adding this results in:
unknown flag: --debug

**Comment by stobrien89** [comment]
Hi @rafaelf82,

Sorry to hear you've been having issues.  I think this may be a duplicate of #4962.  Please let us know if you can't find anything there that helps resolve the issue!

**Comment by rafaelf82** [comment]
Hi stobrien89, nothing on that post fixed my issue (I did see it before), I'm thinking I'm either missing some step that I couldn't find on the documentation or the issue might be related to using it from inside Putty...

![image](https://user-images.githubusercontent.com/14276684/117303565-36cf3580-ae53-11eb-9f03-4dc8d1922bce.png)

**Comment by stobrien89** [comment]
Hi @rafaelf82,

Thanks for checking! I was going to mention this earlier, but assumed you may have found something to resolve the issue: does removing the `aws` after `aws-cli` make a difference? the `aws` is baked into the command if you're using the docker image, so the format should look like the following:

`docker run --rm -it amazon/aws-cli <service> <operation>`.

**Comment by rafaelf82** [comment]
Hi, same thing, bad request.

Is there something that needs to be done? I'm confused about how simply running the above command would give me access to a private repository... Shouldn't I need to put username and password somewhere?

**Comment by stobrien89** [comment]
Hi @rafaelf82,

Almost forgot about this— since you're using the CLI docker image, because it is run in a container,  you'll need to mount the host system’s `~/.aws` directory to the container in order to share your credentials, environment variables and files.  You can find instructions on how to do so [here](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-docker.html#cliv2-docker-share-files).  Is there a particular reason you're using the CLI docker image instead of the CLI?

In terms of the username and password, `AWS` is the default username for authenticating to the ECR registry, and the password/authentication token is passed directly from the output of the `get-login-password` operation.  The `get-login-password` operation is authenticated using your AWS credentials, which you put into the [credentials file, or set using environment variables](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html).  Hope this helps!

**Comment by rafaelf82** [comment]
Hi I managed to make it work, as expected the error was lack of credentials, I'll leave here a suggestion to put this info on the documentation: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-docker.html#cliv2-docker-share-files

I did it creating and sharing the credentials using the -e parameter.

**Comment by stobrien89** [comment]
Hi @rafaelf82,

Glad you were able to find the source of the problem!  I'll bring this up to our doc writers— We don't have much control over this behavior, as it's a Docker error message, but I think it could definitely be documented.
