### ISSUE TITLE
AWS CLI landing page (and its Description for v1 and v2)

### ISSUE THREAD

**Issue by jenellea** [aws/aws-cli#6150]
1. Default landing page when opening AWS CLI Command Reference (v 1 or v 2) from other places is a command page, such as **shield** command,  or **aws** command, which differs from Home page in the AWS CLI Command Reference.  (https://awscli.amazonaws.com/v2/documentation/api/latest/index.html). Here are 2 examples:

Clicking CLI Reference from https://docs.aws.amazon.com/cli/?id=docs_gateway opens to https://docs.aws.amazon.com/cli/latest/reference/, which typically defaults to v1 even though the link is "latest." Also this url may resolve to a command, including **shield**  and **aws**
Clicking  CLI  from  https://docs.aws.amazon.com/index.html  (there are 3 links that go to either https://aws.amazon.com/cli/ or https://docs.aws.amazon.com/cli/?id=docs_gateway 
 

2. Description for **shield** command (in AWS CLI Reference) has spaces before closing period on both sentences. Not an issue elsewhere.

**Comment by stobrien89** [comment]
Hi @jenellea,

Thanks for pointing this out! I'll review the linking (to the `aws` command) issue with our doc writers to see we're able to switch them over to [this page](https://docs.aws.amazon.com/cli/latest/index.html).  The linking to the v1 reference guide by default, however, is intentional— this is something we'll likely look at changing in the future, but we do include a note at the top of each v1 reference guide page that informs the user and provides a link to the v2 documentation.  

In reference to the spaces at the end of the Description for shield, I noticed this is also present in the boto3 documentation— the CLI and boto3 share the same docs build, so I'll see what we're able to do to get that corrected.

I checked all of our links from the pages you provided and I could only find instances of a link to the `aws` command.  Do you have any examples where they are resolving to another service, such as `shield`?
