### ISSUE TITLE
inconsistency aws secretsmanager put-secret-value / get-secret-value and documentation  aws-cli/1.19.71

### ISSUE THREAD

**Issue by chleiva** [aws/aws-cli#6169]
Dear AWS cli team,

when using aws secretsmanager put-secret-value with --secret-binary (adding the secret as part of the command line) we observe different output when trying to retrieve the same secret using aws secretsmanager get-secret-value (this is encoded in Bae64) and the behaviour changed between AWS CLI V1 and AWS CLI V2, However: The documentation of both CLI V1 and CLI V2 are the same, but CLI V2 is expecting the parameter in BASE64 whilst CLI V1 is expecting the parameter in raw format, this cause confusion as there is nothing in the document indicating the expected input encoding format:
https://docs.aws.amazon.com/cli/latest/reference/secretsmanager/put-secret-value.html
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/secretsmanager/put-secret-value.html

**Comment by kdaily** [comment]
Hi @chleiva,

This change of behavior is documented here in the migrating to CLI V2 notes:

https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-binaryparam

If you need the CLI V1 behavior for consistency, you can add this to your profile in the `config` file:

```
cli_binary_format=raw-in-base64-out
```

Since this effects all cases like this, the documentation was not changed every place that has a binary parameter. Let me know if that solves your issue!
