### ISSUE TITLE
aws s3api report task progress

### ISSUE THREAD

**Issue by TheRealDwright** [aws/aws-cli#6214]
**Is your feature request related to a problem? Please describe.**
The `aws s3api put-object` does not provide any feedback for long running tasks unlike other API's e.g. `aws s3 cp`

**Describe the solution you'd like**
A progress report for larger files indicating how far the upload has progressed, e.g.

`Completed 2.8 MiB/1.7 GiB (495.8 KiB/s) with 1 file(s) remaining`

**Describe alternatives you've considered**
We have used the s3 cp for our purpose, but I feel this functionality would be good for the s3api command also. We also tried --debug which wasn't overly useful.

**Additional context**
We have users uploading large files via a bash script using the s3api, it would be nice for them to see progress of the upload rather than a blank screen.

**Comment by stobrien89** [comment]
Hi @TheRealDwright,

Thanks for the feature request!

**Comment by kdaily** [comment]
Hi @TheRealDwright,

The `s3api` commands provide direct access to the S3 API. The `aws s3` customization was build specifically to provide user-friendly features in a Linux-like fashion, including progress reporting. We won't be adding it directly to the API commands.

Can you provide more details as to why users are choosing `aws s3api` instead of the `aws s3` commands?

**Comment by TheRealDwright** [comment]
Thanks for the reply @kdaily, given the response happy for this one to be closed.
