### ISSUE TITLE
parameter containing uri string is interpreted as uri parameter

### ISSUE THREAD

**Issue by DominikTo** [aws/aws-cli#630]
When passing an uri as a string, awscli fetches the content of the uri instead of just using the string value.

**Example:**

```
aws ec2 run-instances \
[...] \
--user-data 'https://foo/bar' \
[...] \
```

**Expected result:**
- User data should contain the string 'https://foo/bar'.

**Actual result:**
- User data contains the contents served at that uri (which **should only happen** if an **uri is passed without quotes**).

**Comment by armitagemderivitec** [comment]
Has anything been done to remedy this? It still remains an issue I believe. If anyone has a workaround other than creating a txt file with the value I would appreciate it

**Comment by AlJohri** [comment]
this is way way way too magical. please have an option to disable this.

**Comment by AlJohri** [comment]
switching to https://www.npmjs.com/package/kms-cli for now

**Comment by jasonmcaffee** [comment]
fyi, for ssm put-parameter param, i found a workaround using the --cli-input-json, that i'm guessing will work for the ec2 command as well:
```
aws --profile myprofile ssm put-parameter --cli-input-json '{
  "Name": "/some/url/param",
  "Value": "http://google.com",
  "Type": "String",
  "Description": "url"
}'
```

**Comment by toby5box** [comment]
This just blind-sided me again, even though I supposedly knew about it, having commented on a related issue before.

Please fix it, the current behaviour is just too surprising and potentially dangerous.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by AlJohri** [comment]
Adding direct link: https://aws.uservoice.com/forums/598381-aws-command-line-interface

**Comment by armitagemderivitec** [comment]
@ASayre could you please provide a direct link to this feature request in UserVoice so that people finding this issue in an internet search can easily navigate there and up-vote. Thanks

**Comment by toby5box** [comment]
Well that's odd, did some of my recent comments get deleted from this thread?

**Comment by AlJohri** [comment]
@armitagemderivitec 
![screen shot 2018-02-07 at 10 29 04 am](https://user-images.githubusercontent.com/2790092/35924696-bd07098c-0bf1-11e8-9a1a-326278f5c3ad.png)

**Comment by armitagemderivitec** [comment]
https://aws.uservoice.com/forums/598381-aws-command-line-interface/suggestions/33168802-parameter-containing-uri-string-is-interpreted-as

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by jonathan-willis** [comment]
This is one of those "features" that's such a horrible idea, it's surprising it's not fixed. The feature should have had some kind of prefix like fetch-url:http://example.com. For now there should be a way of turning it off at least by some kind of environment variable. Ideally it would be off by default and could be turned on for those who actually use it.

**Comment by jmehnle** [comment]
Per https://github.com/aws/aws-cli/issues/1475#issuecomment-136532062 the workaround is to put your URL value in a file and pass it via `fileb://$FILENAME`. E.g., using Bash's process substitution:

```aws ec2 run-instances [...] --user-data fileb://<(echo -n 'https://foo/bar')```

**Comment by rosswilson** [comment]
This has now been fixed. A new configuration option called `cli_follow_urlparam` can be set to disable this auto-fetch URL behaviour across the entire AWS CLI.

In your `~/.aws/config` file, add the following line:

```
cli_follow_urlparam = false
```

See the [documentation](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#general-options) for more details.

**Comment by DominikTo** [comment]
Great to hear!
Would be even better with `false` as the default. Unexpected behaviour.

**Comment by joguSD** [comment]
In addition to the configuration mentioned by @rosswilson, this functionality has been entirely removed in the AWS CLI v2.
