### ISSUE TITLE
CLI versions 1.20.9 and 2.2.24 shipped a breaking change in a dot release

### ISSUE THREAD

**Issue by dylanlingelbach** [aws/aws-cli#6308]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Versions 1.20.9 and 2.2.24 shipped a breaking change to EKS support by changing the supported k8s API value from `v1alpha1` to `v1beta1`. This breaks any existing kubeconfigs that have `v1alpha1` specified in their kubeconfig.

The [PR that changed this behavior](https://github.com/aws/aws-cli/pull/6289) clearly specified this is a breaking change, however the changed shipped in a point release, with no clear communication about it being a breaking change.

The error message you see when attempting to use a kubeconfig with an incorrect version is:
```
unable to use kubectl with the EKS cluster (check 'kubectl version'): Unable to connect to the server: getting credentials: exec plugin is configured to use API version client.authentication.k8s.io/v1alpha1, plugin returned version client.authentication.k8s.io/v1beta1
```

**SDK version number**
1.20.9
2.2.24

**Platform/OS/Hardware/Device**
What are you running the cli on?

Linux/Mac OS X

**To Reproduce (observed behavior)**
1. Have a kubeconfig that uses `eks get-token` for authentication
2. Upgrade CLI to 1.20.9 or 2.2.24
3. Run a `kubectl` command

**Expected behavior**
Point releases of CLIs to not include breaking changes

**Logs/output**
```
unable to use kubectl with the EKS cluster (check 'kubectl version'): Unable to connect to the server: getting credentials: exec plugin is configured to use API version client.authentication.k8s.io/v1alpha1, plugin returned version client.authentication.k8s.io/v1beta1
```

**Additional context**
Related to https://github.com/aws-samples/eks-workshop/issues/1232

**Comment by kdaily** [comment]
Hi @dylanlingelbach,

Thanks for opening this issue. This change breaks `kubectl` when upgrading the AWS CLI but not running `aws eks update-kubeconfig`, and this was unintentional.

We recommend downgrading the AWS CLI to 1.20.8 or 2.2.23. We are going to roll back this change (pull request https://github.com/aws/aws-cli/pull/6309). 

We would not recommend mitigating by updating the `kubeconfig` or re-running the `aws eks update-kubeconfig` with the affected versions of the AWS CLI until we release the versions 1.20.12 and 2.2.25.

**Comment by gabegorelick** [comment]
> We would not recommend mitigating by updating the kubeconfig or re-running the aws eks update-kubeconfig with the affected versions of the AWS CLI until we release the versions 1.20.12 and 2.2.25.

What do you recommend for people that have already worked around this issue by updating their kubeconfigs to v1beta1?  Will there be a way to force `aws eks get-token` to return v1beta1?

**Comment by kyleknap** [comment]
@gabegorelick
> What do you recommend for people that have already worked around this issue by updating their kubeconfigs to v1beta1?

I’d say pin to the current version of the AWS CLI you are on if you do not want to update your kubeconfig again. Otherwise, when 1.20.12 and 2.2.25 are released, make sure to rerun the `update-kubeconfig` command after you upgrade the AWS CLI.

> Will there be a way to force `aws eks get-token` to return v1beta1?

Not in the 1.20.12 and 2.2.25 releases. These releases are stopgaps to prevent essentially every user who has preexisting kubeconfig file that upgrades the AWS CLI from having to troubleshoot this issue and figure out that they need to either rerun their `update-kubeconfig` command or manually update their kubeconfig file. We are sorry that this does cause churn for people who have already handle this update, but we suspect that a majority of users have not ran into this issue yet since this is a recent change.

As a fast follow up to these releases, we are considering adding options to opt into a particular API version (e.g. by introducing `--api-version` flags to both the `update-kubeconfig` and `get-token` commands) so users can 1) Lock to an API version without having to worry about it changing from under them. 2) Unblock users who want to use the v1beta1 API version.

**Comment by kyleknap** [comment]
Version 2.2.25 is now available, which fixes this issue by reverting the upgrade to the v1beta1 API version.

**Comment by joshsleeper** [comment]
hey @kyleknap I always feel guilty bumping stuff, but is there any progress or tracking issue on those `--api-version` opts you said would be considered?
we were in the apparently-too-quick-to-update camp across nearly 100 repos and we've been pinned to `2.2.24` since 😆

**Comment by bigspawn** [comment]
Hey, don't forget to rollback `aws-iam-authenticator` because it also has an impact on it. I use [v0.5.3](https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/tag/v0.5.3)

**Comment by stevehipwell** [comment]
I've opened https://github.com/aws/aws-cli/issues/6916 to request adding the `--api-version` flag to `aws eks get-token`.
