### ISSUE TITLE
Major version level Docker image tag

### ISSUE THREAD

**Issue by houstonj1** [aws/aws-cli#6337]
**Is your feature request related to a problem? Please describe.**

Currently on Docker Hub, there are only docker tags for each patch version of the v2 CLI. For example, amazon/aws-cli:v2.2.30

**Describe the solution you'd like**

It would be nice if there was a single tag for v2 of the CLI, knowing that there is still a v1, and assuming there may be a v3...vX in the future. 

This is extremely helpful for automation that uses these images, so we can always get the latest v2 image, without having to change scripts, pipelines, etc. for each minor and patch version that gets published

Ideally things like this would work:
```bash
# In case I need v1 for some reason
docker pull amazon/aws-cli:v1

# To get the latest v2 image ( including security patches, bug fixes )
docker pull amazon/aws-cli:v2
```

**Describe alternatives you've considered**
Currently to get this auto-update behavior, I've configured any automation to use amazon/aws-cli:latest, which seems like a Docker anti-pattern. Although unlikely, it is possible to get breaking changes pushed to the latest tag. 

**Additional context**
N/A

**Comment by stobrien89** [comment]
Hi @houstonj1,

Thanks for the feature request!

**Comment by stobrien89** [comment]
Hi again @houstonj1,

Wanted to clarify that the aws-cli image is only supported for v2 currently, but this is something we will keep in mind moving forward.  Since the `latest` tag represents the latest version for the only version we support, we'll be closing this at this time.  Happy to revisit if we introduce support for v1 or vnext, whenever that may be!
