### ISSUE TITLE
Support of Amazon Managed Service for Grafana (AMG)

### ISSUE THREAD

**Issue by fhopeman** [aws/aws-cli#6367]
**Is your feature request related to a problem? Please describe.**
It's currently not possible to manage "Amazon Managed Service for Grafana" via AWS CLI.

**Describe the solution you'd like**
Managing AMG via AWS CLI commands.

Best regards
Fabian

**Comment by tim-finnigan** [comment]
Hi @fhopeman, thanks for reaching out! 

Since this feature request would extend to all SDKs, I created an issue to track this in our shared SDK repository: https://github.com/aws/aws-sdk/issues/118

[Amazon Managed Grafana](https://aws.amazon.com/grafana/) is still relatively new, but we will post updates for this feature request to that issue going forward.

**Comment by fhopeman** [comment]
Hi @tim-finnigan,

CLI support ist now available (https://github.com/aws/aws-sdk/issues/118). Is it possible to re-open this issue?

Best regards

**Comment by fhopeman** [comment]
Hi @tim-finnigan,

SDK support ist now available (aws/aws-sdk#118). Is it possible to re-open this issue?

Best regards

**Comment by tim-finnigan** [comment]
Hi @fhopeman, SDK support is available for Amazon Grafana as mentioned [here](https://github.com/aws/aws-sdk/issues/118#issuecomment-963679036):

> Here is API documentation: https://docs.aws.amazon.com/grafana/latest/APIReference/Welcome.html.
> Here is CLI documentation: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/grafana/index.html

Are there specific SDKs or API calls you need that aren't currently supported?
