### ISSUE TITLE
-..-

### ISSUE THREAD

**Issue by Wangchingold** [aws/aws-cli#6369]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

**SDK version number**

**Platform/OS/Hardware/Device**
What are you running the cli on?

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

**Expected behavior**

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by stobrien89** [comment]
Hi @Wangchingold,

We're unable to tell what this issue is for.  If you are having an issue with the AWS CLI and intended to open an issue with us, please open a new issue, select the issue type that best fits the problem you're experiencing and provide the information requested in the template.  Thanks!

**Comment by Wangchingold** [comment]
I want a Cash Saving Account for gold  Web Application which customer can Sign up and Deposit Cash via Promp-Pay, Paypal, Credit Card
