### ISSUE TITLE
aws cli not reporting error

### ISSUE THREAD

**Issue by jostendorf** [aws/aws-cli#6419]
I have v2 of the aws cli installed on my MacBook and when I type "aws --version" at the command prompt, it just returns to the command prompt with no output.  Same result with any other cli command.

**Comment by kdaily** [comment]
Hi @jostendorf,

Sorry to hear you're having a problem. I'll need you to provide some more details for me to help you.

Just to clarify:

>  Same result with any other cli command.

Does this refer to commands besides the AWS CLI, or still limited to the AWS CLI sub-commands (e.g., `aws s3 ls`)?

Can you tell me:

1. How you installed the AWS CLI v2? Did you use the installation guide [here](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-mac.html)?
2. Since you can't run `aws --version` to check the version, does it happen with a fresh installation? That way I would know the version is what is available today. Note that a new version was released an hour ago (2.2.41), so if you got this error with an installation earlier today, you may have been using `2.2.40`.

I just installed today's release (2.2.41), and I get the following:

```
❯ aws2 --version
aws-cli/2.2.41 Python/3.8.8 Darwin/19.6.0 exe/x86_64 prompt/off
```

Thanks!

**Comment by jostendorf** [comment]
Yes, I followed the guide to install it.  I installed version 2.2.40.  Yes, I'm guessing it is just failing silently?  Any cli command I use results in just going back to the prompt.  Also, FYI.   I am unable to post any screen shots here.  I will try to delete everything and start over today with the newest version. Not really sure how to even debug this.

**Comment by kdaily** [comment]
Thanks for the update!

If you can, you might try to use it in a different terminal program, like iTerm. 

Did you install using the `pkg` file, or using the command line?

**Comment by jostendorf** [comment]
I uninstalled everything again and was able to get it working.  Was a Rouge
simlink I think...

Thanks for taking the time to respond.

**Comment by kdaily** [comment]
Thanks for letting us know! Glad it's working. Closing this out.
