### ISSUE TITLE
Support debug logging to a file

### ISSUE THREAD

**Issue by jamesls** [aws/aws-cli#642]
Right now, the best way to capture a debug log to a file is to redirect stderr to a file:

```
aws service operation --debug 2>/tmp/debug.log
```

However, error messages are also printed to stderr.  It would be helpful if there was a way to leave stdout/stderr untouched (that is, things that print directly to `sys.stdout` and `sys.stderr` are left alone) and all debug logs go to a file.

Some proposed ideas:
- Add a new flag, `aws service op --debug-file /tmp/debug.log`
- Allow `--debug` to take an optional argument.  `aws service op --debug` -> logs go to stderr.  `aws service op --debug /tmp/foo.debug` -> logs go to /tmp/foo.debug.
- Maybe allow the user to point to a complete logging configuration file either in INI format, or IMO easier to work with, a JSON file that matches the dictConfig format.  This would give them control over everything (which loggers/levels/files to log), but is likely overkill for anyone who isn't a CLI dev (http://docs.python.org/2/library/logging.config.html#module-logging.config).

**Comment by ericcox** [comment]
I don't think this needs to be built into the program itself... just use 'tee'.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by kdaily** [comment]
After further discussion, there are times where this would be useful, but given the lack of interest and priority, we're going to close this. Using existing command line tools gets you pretty far into the ability (except for #3, which is the hard part of this request anyways!).

**Comment by john-aws** [comment]
> I don't think this needs to be built into the program itself... just use 'tee'.

There's a supported client OS called Windows. It doesn't natively include `tee`. The awscli is supposed to function standalone (which is why it includes python and implements `--query`, for example).
