### ISSUE TITLE
Specifying Projected Attributes for @key directive

### ISSUE THREAD

**Issue by julien-tamade** [aws/aws-cli#6442]
**Is your feature request related to a problem? Please describe.**
General List queries with filtering tends to be really slow and the unpredictable pagination annoying. I'm looking into using @key to set up some common queries on my tables so that I can quickly list the items I need. In these instances though, If i'm setting up a bunch of indexes, I'd like to be able to specify the projected attributes to optimize speed and cost. For instance I might only need a list of User IDs and then I don't need to get their user data until I select the user. I know that this might not work great with graphQL given the nature of specifying what you want returned when writing the query itself, but think it might be helpful.

**Describe the solution you'd like**
Ideally I'd be able to specify the projected Attributes when defining the @key directive. 

**Describe alternatives you've considered**
I've been considering moving off Amplify toward a SQL approach but this idea is slowing that move down.

**Additional context**

**Comment by kdaily** [comment]
Hi @julien-tamade,

I'm not sure what you're referring to here. I see you mention moving off of Amplify - are you using the AWS Amplify CLI? To get help with that, you'll need to head over here:

 https://github.com/aws-amplify/amplify-cli/issues

Otherwise if you could provide more detail, that would be great. Thanks!

**Comment by kdaily** [comment]
Per #6443 this is for AWS Amplify CLI. Closing!
