### ISSUE TITLE
Add parameter `Name` to `CreateVpcEndpoint` 

### ISSUE THREAD

**Issue by tailaiw** [aws/aws-cli#6455]
**Is your feature request related to a problem? Please describe.**
A VPC endpoint can have a custom name set in AWS Console, but no way to do so via CLI.

**Describe the solution you'd like**
Having an optional parameter `Name` in for `CreateVpcEndpoint` and `ModifyVpcEndpoint`.

**Comment by tim-finnigan** [comment]
Thanks @tailaiw for sharing that. I agree this should be clarified. I found a similar pattern is used for naming EC2 instances, but they make it clearer in the Console by adding the “click to add a Name tag” button here:
﻿﻿﻿
<img width="845" alt="image" src="https://user-images.githubusercontent.com/87778557/136439798-64281f60-d15e-4eeb-b636-a220d017b53f.png">

I reached out to the VPC team about adding more clarity to this process. I will post an update here when I hear back from them. Thanks for bringing this to our attention!

**Comment by tim-finnigan** [comment]
Hi @tailaiw, I received an update from the VPC team. They are planning an update in the near future that will make it more straightforward to set Name tags in the console. Otherwise it is recommended to use `--tag-specifications` with the [create-vpc-endpoint](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/create-vpc-endpoint.html) command as mentioned earlier to specify a Name tag using the CLI. 

---

Another alternative is to use the [resourcegroupstaggingapi](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/resourcegroupstaggingapi/index.html) service. For example you could see all of your VPC endpoint tag information using this command:

`aws resourcegroupstaggingapi get-resources —resource-type-filters ec2:vpc-endpoint`

And you could tag VPC endpoints using this command:

`aws resourcegroupstaggingapi tag-resources —resource-arn-list <your_vpc_endpoint_arn> --tags Name=VPC_Endpoint_Name`

For more information on tagging resources please see this documentation: https://docs.aws.amazon.com/general/latest/gr/aws_tagging.html

Does that help? Please let me know if you had any follow up questions. Otherwise I'll go ahead and close this issue for now.
