### ISSUE TITLE
Powershell JSON whitespace issues updating data in DynamoDB using the AWS CLI

### ISSUE THREAD

**Issue by tdekoning93** [aws/aws-cli#6591]
**Describe the question**
I've been fiddling for a while with updating records in DynamoDB using the AWS CLI from Powershell. I can't seem to update a value that contains a whitespace. See below command where `2021-11-17 14:48:41` contains the whitespace. I've tried a lot of different quote and escape combinations, but haven't been successful. Any help would be appreciated.

This is from a Windows 2016 server running AWS CLI 1.18.216. In bash or Powershell Core on MacOS I don't experience this issue.

**Logs/output**
Command
`aws dynamodb update-item --table-name $TableName --key $KeyStackJson --update-expression 'SET #H = :h,#D = :d,#E = :e' --expression-attribute-names $AttributeNameJson --expression-attribute-values '{\":h\":{\"S\":\"0.0.189-alpha\"},\":d\":{\"S\":\"test\"},\":e\":{\"S\":\"2021-11-17 14:48:41\"}}'`

Output
`Unknown options: 14:48:41"}}`

**Comment by tdekoning93** [comment]
Will solve it in a different way so I don't have whitespaces. Writing the ISO 8601 format to DynamoDB and after pulling the data, changing it for display.

**Comment by stobrien89** [comment]
Hi @tdekoning93,

I was just about to respond to this— You may be able to get this to work if you wrap the `expression-attribute-values` in backticks instead of single quotes.  Powershell has some interesting quoting rules when it comes to nested structures.  We elaborate a bit more on that [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-parameters-quoting-strings.html#cli-usage-parameters-quoting-strings-containing)

**Comment by tdekoning93** [comment]
Thanks for your reply @stobrien89. That also doesn't seem to work. Powershell is indeed super funky with this stuff. I'll just solve it in a different way.
