### ISSUE TITLE
Retain original modified date time

### ISSUE THREAD

**Issue by bmacbmac2** [aws/aws-cli#6601]
Confirm by changing [ ] to [x] below:
- [ x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [x] Service API : I want to do X using Y service, what should I do?
- [ x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
Windows 10

**Describe the question**
Retaining the original date/time on our files is very crucial to our operation.  When uploading to S3 and then downloading back to our system the modified date/time is always today.

While searching github I have seen some information about --exact-timestamps but that hasn't solved the problem.  

aws s3 sync --exact-timestamps c:\KTB\ s3://mybucket/KTB/

I just installed aws cli version2, but don't see any new documentation about this.

Thanks!

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by stobrien89** [comment]
Hi @bmacbmac2,

Thanks for reaching out!  The `--exact-timestamps` option is primarily intended to override the default behavior of _not_ downloading S3 objects that have a more recent `LastModified` time (in the case of same-sized items)— we default to that behavior because when a file is uploaded to S3, the `LastModified` time will always be changed to the time of upload.  This a limitation (but mainly a feature) of using an object store as opposed to a file system.  S3 will likely not change this behavior due to the security/compliance implications of doing so.

One way you could keep track of a given file's actual last modified time is by adding custom metadata to an upload.  Here's an example of copying a local file to S3 and adding a custom metadata property:

```
aws s3 cp metadata.txt s3://<bucket> --metadata original-modified-time=2021-12-09T18:44:32+00:00

aws s3api head-object --bucket <bucket> --key metadata.txt 


{
    "AcceptRanges": "bytes",
    "LastModified": "2021-12-09T18:47:37+00:00",
    "ContentLength": 0,
    "ETag": "\"etag\"",
    "VersionId": "versionid",
    "ContentType": "text/plain",
    "Metadata": {
        "original-modified-time": "2021-12-09T18:44:32+00:00"
    },
    "ObjectLockMode": "COMPLIANCE",
    "ObjectLockRetainUntilDate": "2021-12-10T18:47:36.135000+00:00"
}
```

Hope this helps!

**Comment by victorelec14** [comment]
reopen Issue :)

I also think that the modification date is something important, especially for synchronization systems or in case of downloading the files.

Saving the modification date of files would cause multiple people to leave Samba/CIFS/NFS to migrate to S3.

Thanks

**Comment by Mitchell-kw-Lee** [comment]
Vote +1.
Are you AWS even working on?

**Comment by kryten4b** [comment]
I have the same issue. Does anyone have a workaround?

**Comment by paulfwhite** [comment]
The Last Modified attribute changes when moving an object to a different S3 storage tier.
I recently moved 14TB = a years worth of SQL backups into Glacier Instant retrieval. All object dates changed to the date of the move. Therefore, the expiry action for 12 month old backups will need to wait another year.

I guess I will create a CLI script to delete them myself.
