### ISSUE TITLE
S3 Sync Memory Leak - Large Buckets

### ISSUE THREAD

**Issue by jackspayed** [aws/aws-cli#661]
Bucket contains millions of files in a structure of 

s3://bucket/sub/sub/sub/sub/sub/sub/file(x)

s3 sync process consumes memory until exhausted at a rate of approx .5GB / Min

**Comment by jaredbroad** [comment]
+1 for this bug. I have 99M files in similar directory structure (4 deep) S3 -> Local. It eats up roughly 2MB every 5-10 seconds then ubuntu "Killed" it and it stops syncing. I installed your script to replace AWS command and attempted to re-run and it didn't output any files.

99.9% of the files are already on the disk, I'm just syncing to get updates so running: 
aws s3 sync --size-only s3://bucket /local/path

**Comment by jamesls** [comment]
I'll take a look and see what I can find.  To clarify, something like this should demonstrate the issue:

1. Create around 99 million files in s3.
2. Sync from s3 to local (initial sync)
3. Sync from s3 to local with `--size-only` (and record memory usage)

And in step 3, I'd see memory usage increase until the OOM kills the process right?

What's the average size/range of the files?  Just want to try to repro as closely as possible.

**Comment by jaredbroad** [comment]
1,2,3 -- Correct. Average size is 33 million 20kb, 66 million between 100kb - 1MB.
Unfortunately creating that number of files in S3 will cost you approximately $500.

The OOM killing process seems dependent on other processes running on the machine -- the machine hovers at 90% usage when running the script is going, and if another process uses more than remaining 10% then it gets killed. Still -- its 3.3GB ram out of 3.7 on the machine -- is this expected?

![2015-01-07 22_47_36-root ip-10-178-162-202_ _quantconnect lean engine](https://cloud.githubusercontent.com/assets/2243225/5656662/3d03d59e-96bf-11e4-8116-69da627d7e70.png)

**Comment by jrochkind** [comment]
We are likely running into this problem too, just adding a note since this issue is what I found googling, and it hasn't been touched in a few years. It's possible the problem still exists. We're gonna give the third party s3cmd a try and see if it works better for us for syncing a bucket with millions of objects.

**Comment by nikojarvinen** [comment]
We're having some variation of this problem. The problem server is running on Linode 4G and other processes use approx 1gb of memory.  
We're currently backing up a directory which has about 300k files to S3. Currently the process eats all the available memory and then starts eating SWAP just a bit.  I deleted about 100k files because originally we had about 400k files and that started causing serious performance issues. The files are about 30% php/css/js files and rest are cellphone photos. 

So I think the main issue is that s3cmd just takes way too much memory to hold the file tree in memory.. We need to start looking for alternative way right now because I don't want to upgrade our server(s) just because s3cmd needs crazy amount of memory few times a day...

**Comment by jrochkind** [comment]
We are definitely still having this problem routinely, exactly as described above. Any chance of re-opening the ticket? 

I don't believe there is actually any additional reporter-response being waited for?

It is making it so we can't reliably use the aws-cli to sync a large bucket; we're having to look into third party tools or writing our own. 

@jamesls if you're still around? I may try opening another ticket if no response.

**Comment by rkz** [comment]
We're running into the same issue, though at a more manegeable pace.

On a t3.medium instance and typical file size of 100KB in the bucket, it leaks in a seemingly linear shape at ~10 MB/min.

For very large buckets a workaround (not tested) could be to shard the sync based on prefixes:

```
aws s3 sync s3://origin/a* s3://destination
aws s3 sync s3://origin/b* s3://destination
aws s3 sync s3://origin/c* s3://destination
...
```

**Comment by Zempheroth** [comment]
Hi there! And it;s a late 2023..but problem still be actual
I'm trying to simply `MOVE` a folder with a ~1kk of images (~25kb each) to bucket using
```
aws s3 mv /local/folder/path s3:://destination/path --recursive --no-guess-mime-type --no-progress --quiet 
```
And there is a memory / per time usage chart on k8s pod
![image](https://github.com/aws/aws-cli/assets/5180270/f92d562b-31ae-41c5-80eb-daf1fed8d9b5)
