### ISSUE TITLE
AWS CLI is showing SSL validation 

### ISSUE THREAD

**Issue by mudasirnazir** [aws/aws-cli#6639]
I am getting SSL validation failed while trying to run AWS CLI. After updating the CLI to the latest version also, I'm facing the same issue. Plz help.

Thanks,
Mudasir
+91-9910400782
![Uploading MicrosoftTeams-image (4).png…]()

**Comment by tim-finnigan** [comment]
Hi @mudasirnazir, thanks for reaching out. In order to help we would need more information. Please provide this info from our [Bug report template](https://github.com/aws/aws-cli/issues/new?assignees=&labels=needs-triage&template=---bug-report.md&title=):

> **Platform/OS/Hardware/Device**
> What are you running the cli on?
>
>**To Reproduce (observed behavior)**
>Steps to reproduce the behavior
>
>**Logs/output**
>Get full traceback and error logs by adding --debug to the command.

I’d also encourage you to look through [similar issues](https://github.com/aws/aws-cli/issues?q=is%3Aissue+is%3Aclosed+%22ssl+validation+failed%22+) regarding this topic and see if a solution for your issue was already found.

If you're getting a SSL: CERTIFICATE_ VERIFY_FAILED error message then please refer to this section in our troubleshooting guide: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-troubleshooting.html#tshoot-certificate-verify-failed
