### ISSUE TITLE
Don't peg the library to a specific patch version of botocore

### ISSUE THREAD

**Issue by zags** [aws/aws-cli#6647]
**Is your feature request related to a problem? Please describe.**
The library currently requires a specific minor version of botocore.  From `setup.py`:
```
install_requires = [
    'botocore==1.23.31',
    # ...
]
```

By specifying a sub-dependency this specifically, the library is far more likely to cause dependency version conflicts when installed with other libraries.  In particular, this library is currently incompatible with [AWS's own eb-cli](https://github.com/aws/aws-elastic-beanstalk-cli), which currently requires `'botocore>=1.21.0,<1.22.0'`.

**Describe the solution you'd like**
Please broaden the range of versions of botocore that this library can use.

At a minimum, the library should be compatible with the entire minor version of botocore.

Additionally, this library should be mutually installable with the elastic beanstalk CLI

**Comment by nateprewitt** [comment]
Hi @zags,

Botocore is the core library for the AWS CLI. They are inherently a 1:1 match because Botocore provides the majority of the functionality in each CLI release. Trying to swap in a different version is *highly* likely to break a significant portion of the CLIs functionality (such as missing services, arguments, customizations, etc.).

The `eb-cli` choosing to use Botocore and introducing a cap effectively makes it incompatible with a range of releases. Their current decision to add that means it isn't usable with any CLI version besides 1.21.x. You should be able to downgrade your CLI installation to meet that requirement if the `eb-cli` is required in your environment. Our recommendation though would be for them to track their cap more closely if they're going to utilize Botocore. Looking at their [commits](https://github.com/aws/aws-elastic-beanstalk-cli/commit/119cbca31c11b3662da6de7324d9f4391f5106e3), their constraints appear to be arbitrary.

**Comment by nateprewitt** [comment]
It looks like you've already created a ticket with the eb-cli team (aws/aws-elastic-beanstalk-cli#101). We can track that for the fix on their end. I've added a +1 and will reach out to their engineers.

For anyone wanting to avoid these kinds of conflicts, the [AWS CLI v2 ](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) will install itself in an isolated environment avoiding the limitations of Python's packaging environments.

**Comment by nateprewitt** [comment]
I've spoken with the `eb-cli` team and they're working on a fix. They'll track a better long term fix for keeping their pins updated in sync with the AWS CLI.

**Comment by nateprewitt** [comment]
Hi @zags, I haven't been able to get a response from the `eb-cli` team. I'm not sure there's anything more to be done from the CLI side though. I'm going to resolve this ticket and we'll track the issue further in aws/aws-elastic-beanstalk-cli#101. Thanks again for bringing this to our attention!
