### ISSUE TITLE
S3 Bucket Policy Delete / Put race condition

### ISSUE THREAD

**Issue by Stretch96** [aws/aws-cli#6672]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

When deleting and creating an S3 Bucket Policy, if the Put request is ran too quickly after the Delete request, the policy appears to have been applied, but does not have any affect (The S3 Bucket Policy will appear in the AWS console, and via the aws api)

**To Reproduce (observed behavior)**

Create an EC2 instance in a VPC with an S3 Gateway Endpoint configured
Create a private S3 Bucket (encryption and versioning disabled), with the following Policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::<S3_BUCKET_NAME>/*",
            "Condition": {
                "StringEquals": {
                    "aws:sourceVpc": "<VPC_ID>"
                }
            }
        }
    ]
}
```

Create a test file within the bucket

Ensure you can make a GET request to the test file:

```
$ curl https://<S3_BUCKET_NAME>.s3.<REGION>.amazonaws.com/test-file.txt
test file contents
```

Now run the following to quickly delete and recreate the S3 Bucket Policy:

```
aws s3api delete-bucket-policy --bucket <S3_BUCKET_NAME> & \
aws s3api put-bucket-policy --bucket <S3_BUCKET_NAME> --policy file://<POLICY_FILE>.json
```

Check that the policy appears to have been applied:

```
aws s3api get-bucket-policy --bucket <S3_BUCKET_NAME>
```

The curl request will now fail fith 403 Access Denied:

```
$ curl https://<S3_BUCKET_NAME>.s3.<REGION>.amazonaws.com/test-file.txt
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>xxx</RequestId><HostId>xxx</HostId></Error>
```

(The delete/create commands may need to be ran more than once for this to work, it's an intermittent issue)

It will only sometimes return the correct error of:

```
An error occurred (OperationAborted) when calling the PutBucketPolicy operation: A conflicting conditional operation is currently in progress against this resource. Please try again.
```

**Comment by kdaily** [comment]
Hi @Stretch96,

This looks to me like an issue with S3 and not the AWS CLI. I will investigate further, but I would suggest that you open up a post at the AWS discussion forum at [repost.aws](https://repost.aws/) for a faster resolution.

**Comment by Stretch96** [comment]
Thanks @kdaily 

We have opened an AWS support request for the API race condition

However - we wonder if aws-cli may be able to guard against this issue, until it is resolved?

**Comment by kdaily** [comment]
The AWS CLI `s3api` commands are a thin wrapper around the Python SDK, which in turn wraps the API models we get from S3. We only know about the failure and error message when we get a response back from the server. We would not be able to modify how the `put-bucket-policy` operation behaves client side. 

Could you use [`get-bucket-policy`](https://awscli.amazonaws.com/v2/documentation/api/2.0.34/reference/s3api/get-bucket-policy.html) to interrogate if the policy still is there? The [example](https://awscli.amazonaws.com/v2/documentation/api/2.0.34/reference/s3api/get-bucket-policy.html#get-and-put-a-bucket-policy) provided for that operation indicates that the pattern here would be to essentially replace the bucket policy without explicitly deleting it.

The only other change I can think of is to add a waiter for policy operations, like we have for buckets and objects. However, those are also implemented by the S3 service team, because they are available to other AWS SDKs besides Python and the AWS CLI.

**Comment by Stretch96** [comment]
Hi @kdaily

Yep we've not figured out a solution, apart from possibly adding a pause before the PUT request, but it doesn't feel right (and could allow the issue to still surface if the DELETE request is delayed for whatever reason)

Thankfully our support request with this issue has been confirmed and forwarded to the AWS S3 Service Team 👍 

Shall we keep this issue open so that I can update with any further updates?

**Comment by kdaily** [comment]
Hi @Stretch96,

Thanks again for your patience and the details you provided. I'm going to close this out for now because it's not specific to the AWS CLI - you would have the same issue if you did this with the Python SDK. I'll be in the loop should the S3 service team need input from the AWS CLI team!
