### ISSUE TITLE
SignatureDoesNotMatch error report

### ISSUE THREAD

**Issue by rbavery** [aws/aws-cli#6676]
I get this when opening a terminal now all of a sudden. This happened when I turned on my computer, and wasn't occurring earlier in the day. I happen to use dual boot with Windows and Linux, not sure if that is relevant. The error is on my Ubuntu partition. Here is the error report:

```
An error occurred (SignatureDoesNotMatch) when calling the GetCallerIdentity operation: Signature expired: 20220127T001427Z is now earlier than 20220127T014428Z (20220127T015928Z - 15 min.)

```

**Comment by kamyker** [comment]
I'm unable to zip update lambda function getting the same error in both cli and browser. Was fine 4 days ago.

**Comment by kdaily** [comment]
Hi @rbavery and @kamyker,

This error is generally due to incorrect system time. Here's a similar report for the AWS JS SDK too:

https://github.com/aws/aws-sdk-js/issues/1174

This external StackOverflow post has a good summary of common issues and solutions:

https://stackoverflow.com/questions/44017410/signature-expired-is-now-earlier-than-error-invalidsignatureexception

This page describes more about how signature issues can arise:

https://docs.aws.amazon.com/general/latest/gr/signature-v4-troubleshooting.html

I hope this helps. Let us know if you still have questions.
