### ISSUE TITLE
cognito-idp update-user-pool overwrites lambda triggers

### ISSUE THREAD

**Issue by drvora** [aws/aws-cli#6698]
Hi, we want to enable multiple triggers from Cognito to Lambda aliases. While doing so aws CLI overwrites triggers. We were using aws-cli 2.0.31 but tried with latest version (2.4.16) as well with no luck.

Steps to reproduce -
1) Adding PostConfirmation trigger via the following command. 
aws cognito-idp update-user-pool --user-pool-id poolid --lambda-config PostConfirmation=arn:aws:lambda:region:accountno:function:CognitoPostConfirmationFunction-dev:live

2) Verified on AWS Console that pool has Post Confirmation trigger.
![image](https://user-images.githubusercontent.com/12400942/152619818-6aa26c23-81af-455b-94f9-386723d196ac.png)

3) Adding PreSignup trigger via the following command.
aws cognito-idp update-user-pool --user-pool-id poolid --lambda-config PreSignUp=arn:aws:lambda:region:accountno:function:CognitoPreSignupApproveFunction-dev:live

4) Verified that Post Confirmation is removed and Presignup trigger is shown.
![image](https://user-images.githubusercontent.com/12400942/152619922-0f12afa9-9ff7-47bd-8a17-e5073be0683e.png)

5) Setup triggers via AWS Console and verified both triggers are active.
![image](https://user-images.githubusercontent.com/12400942/152621355-a9e894f5-6c21-4f06-a1fb-b9b955a30545.png)

We would like to use AWS CLI instead of Console as Console doesn;t allow us to setup trigger to Lambda alias.

**Comment by tim-finnigan** [comment]
Hi @drvora thanks for reaching out. Have you tried adding both triggers using commas? This approach worked for me:

`aws cognito-idp update-user-pool --user-pool-id poolid --lambda-config PostConfirmation=arn:aws:lambda:region:accountno:function:CognitoPostConfirmationFunction-dev:live,PreSignUp=arn:aws:lambda:region:accountno:function:CognitoPreSignupApproveFunction-dev:live`

**Comment by kurtislamb** [comment]
Hello, looking to reopen this as its still an issue 

Running aws-cli/2.5.1 

We deploy a everything using Terraform which deploys everything as intended. (See Triggers Below)
![image](https://user-images.githubusercontent.com/24253647/161242302-f4a82bd0-adb6-46a9-a67f-914c8335edd5.png)

Due to a lack of support for Cognito in Terraform we follow that up with a call to the AWS CLI as such

```
JSON=$(jq --null-input \
  --arg admin_create_only "$ALLOW_ADMIN_CREATE_USER_ONLY" \
  --arg sms_message "$SMS_MESSAGE_STRING" \
  --arg email_message "$EMAIL_MESSAGE_STRING" \
  --arg email_subject "$EMAIL_SUBJECT" \
  '{
        "AllowAdminCreateUserOnly": ($admin_create_only=="true"),
        "InviteMessageTemplate":{
            "SMSMessage": ($sms_message|@text),
            "EmailMessage": ($email_message|@text),
        "EmailSubject": ($email_subject|@text)
        }
    }')

echo $JSON

aws cognito-idp update-user-pool --user-pool-id $USER_POOL_ID --admin-create-user-config "$JSON"
```
this call takes parameters passed in and ONLY updates the AllowAdminCreateUserOnly options, we do not touch Lambda Trigger at all (because this is done in Terraform).

Once applied you can see it wipes them out
![image](https://user-images.githubusercontent.com/24253647/161242960-148617cb-a26e-4f58-a285-1057885a80cd.png)


I am loathed to include them in here because it would mean moving them out of where they are already specified and I suspect the AWS CLI shouldn't be over writing them when they are not specified
