### ISSUE TITLE
Transparent decompression of S3 files based on content encoding

### ISSUE THREAD

**Issue by michaeleisel** [aws/aws-cli#6765]
When I upload a file to S3 with, e.g., `Content-Type: application/json;charset=utf-8` and `Content-Encoding: gzip`, and then later download it with `aws s3 cp`, I want the version I download to be automatically decompressed based on the `Content-Encoding` field. This would match what happens from the AWS web interface. Since this would change existing behavior, it could be gated with a flag. Otherwise, not only do I have to decompress myself based on the content encoding (which I may have to do extra work to determine), but I also have the confusing situation of a file with extension `.json` that really should be `.json.gz` (but if I name it `.json.gz`, then I'm tying the file name to the encoding, which isn't what I want for transparent decompression). As for having the decompression utility available, `gzip` is installed on Mac and I'd imagine it is on Linux by default as well. Perhaps it could decompress gzipped files as long as that utility is available, or else fail entirely.

**Comment by tim-finnigan** [comment]
Hi @michaeleisel thanks for reaching out. This request overlaps with https://github.com/aws/aws-cli/issues/1131 and https://github.com/boto/boto3/issues/1257.  This is also being tracked here in the botocore repository: https://github.com/boto/botocore/issues/1255. We are tracking the request in botocore because it would apply to both the CLI and boto3. You can 👍 that issue to show your support or add a comment if you wanted to share any more information on your use case or proposed implementation.
