### ISSUE TITLE
Where is the source of the documentation of the help command ?

### ISSUE THREAD

**Issue by jean-pasqualini** [aws/aws-cli#6802]
Confirm by changing [ ] to [x] below:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [X] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
Linux

**Describe the question**
I want to contribute on it.

**Comment by kdaily** [comment]
Hi @jean-pasqualini,

Thanks for writing! Most of the documentation comes from a model of the API written by AWS docs writers for the services. You can see all of the documentation in the models at the `botocore` package, which the AWS CLI uses. For example, see the `documentation` keys at various levels of the Autoscaling API model:

https://github.com/boto/botocore/blob/develop/botocore/data/autoscaling/2011-01-01/service-2.json#L5304

This documentation is not open for direct contribution, but if you do find errors, typos, or misformatting, please do let us know with a GitHub issue here or on any of the AWS SDKs.

However, the examples are more readily available for contribution. AWS CLI examples live here in this repository:

https://github.com/aws/aws-cli/tree/develop/awscli/examples

Feel free to open pull requests for issues that you identify. If you have an idea for a new example, I would suggest that you open an issue for discussion so that we can also involve a doc writer. There is a style guide that is not currently public, but we can provide feedback on any PR that you open.

Hope this helps, and glad to have you!
