### ISSUE TITLE
error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

### ISSUE THREAD

**Issue by jedrekdomanski** [aws/aws-cli#7030]
### Describe the bug

I've just installed the latest `aws-cli` using this documentation for Linux
https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
```aws --version
aws-cli/2.7.7 Python/3.9.11 Linux/5.13.0-48-generic exe/x86_64.ubuntu.21 prompt/off
```
I then ran `kubectl version` and got an error:
```
error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
```

I removed `kubectl` completely, installed it again using PPA for Ubuntu 21.10, ran `kubectl version` again and got the same error.

### Expected Behavior

No error is raised

### Current Behavior

error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

### Reproduction Steps

Installed the latest `aws-cli` using this documentation for Linux
https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html

Install `kubectl`
Run `kubectl version`

### CLI version used

2.7.7

### Environment details (OS name and version, etc.)

Linux Home 5.13.0-48-generic #54-Ubuntu SMP Wed Jun 1 20:38:48 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tim-finnigan** [comment]
Hi @jedrekdomanski thanks for reaching out. This was also reported here in a recent issue: https://github.com/aws/aws-cli/issues/6920. You can refer to [this comment](https://github.com/aws/aws-cli/issues/6920#issuecomment-1119141939) for more background on the issue and [this one](https://github.com/aws/aws-cli/issues/6920#issuecomment-1119926885) for the resolution. Since you’re using a recent version of the CLI, you may just need to run the `update-kubeconfig` command.

**Comment by tim-finnigan** [comment]
Since we haven't heard back in a week I am going to close this. If you're still encountering this issue please let us know.
