### ISSUE TITLE
AWS Linux 2 AMI does not contain awscli2 and deprecation warning does not explain how

### ISSUE THREAD

**Issue by ecki** [aws/aws-cli#7036]
### Describe the feature

After getting a deprecation warning of awscli 1.x on a freshly started EC2 AMI with Amazon Linux 2 I was looking for a way to upgrade to awscli2, and the manual only describes a manual way with curl. Why is awscli not in the default ami and not even installable via yum?

### Use Case

keep my linux current.

### Proposed Solution

Either install awscli in version 2 in AMI, install it in parallel to aws 1.x as aws2 or at least provide a yum repo/option to get the aws 2.x major version and describe it on a help page linked by the deprecation message for 1.x

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CLI version used

1.18.x

### Environment details (OS name and version, etc.)

Amazon Linux 2 on EC2 us-east-1 from Web console quickstart.

**Comment by tim-finnigan** [comment]
Hi @ecki thanks for reaching out. We recommend reaching out to the [amazonlinux team](https://github.com/amazonlinux) regarding this. There was a recent update in [this issue](https://github.com/amazonlinux/amazon-linux-2022/issues/71#issuecomment-1153003090) regarding the plan to make CLI v2 the default for AL2022 going forward. You could ask there about default v2 support for Amazon Linux 2 and yum installation as well. Hope that helps, please let us know if you had any other questions. Otherwise I will set this issue to close automatically soon.

**Comment by ecki** [comment]
Thanks for the help.
