### ISSUE TITLE
Update TRN ( Tax settings ) per account in Organization

### ISSUE THREAD

**Issue by pawelfraczyk** [aws/aws-cli#7060]
### Describe the feature

Possibility to update TRN (maybe in JSON format?) of member account in Organization where are multiple AWS Sellers and we don't want to all accounts to inherit root's account TRN

### Use Case

We have pipelines to create new AWS Accounts accross the globe in 1 Organization. After account is created - we need to update TRN manually from Web Console

### Proposed Solution

AWS Cli command to update member account's TRN Tax Settings from Root account level by providing Account ID + TRN + Billing info

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

Any

### Environment details (OS name and version, etc.)

Any

**Comment by tim-finnigan** [comment]
Hi @pawelfraczyk thanks for the feature request. This type of feature request for new API functionality would have to be implemented upstream by a service team, because the APIs are used across the CLI and SDKs. In a recent related issue (https://github.com/aws/aws-sdk/issues/283) I wrote:

> The team that I reached out to said that Public APIs for tax settings are currently under development. The APIs may be available later this year but we can't guarantee any timelines. Please feel free to check in for updates on this in the future

I can pass along your specific request to this team, but I think the same response as above would apply here as well. I'll set this issue to close soon but please let me know if you have any feedback or questions.
