### ISSUE TITLE
`TagSpecifications` not honored on `ec2 authorize-security-group-egress`

### ISSUE THREAD

**Issue by danfuzz** [aws/aws-cli#7067]
### Describe the bug

When calling `ec2 authorize-security-group-egress` with a JSON argument, `TagSpecifications` listed in the argument do not seem to be honored, and end up causing partial failure of the command. Specifically, an egress rule gets added without a tag, and the command returns a `false` status.

### Expected Behavior

The command should add a rule with a tag, and it should return a `true` status.

Here's expected behavior from the script in the "repro steps section:"

```
$ ./egress-bug 
Group ID: sg-xxxxxxxx
{
    "Return": true
}
[
  "sgr-xxxxxxxx",
  [{ "Key": "Name", "Value": "hello-there" }]
]
```

### Current Behavior

An egress rule gets added but without any tags, and the command returns a `false` status.

Here's current behavior from the script in the "repro steps section:"

```
$ ./egress-bug 
Group ID: sg-xxxxxxxx
{
    "Return": false
}
[
  "sgr-xxxxxxxx",
  []
]
```

### Reproduction Steps

Here's a script. See above for the expected and actual results.

```bash
#!/bin/bash

# Replace with a valid VPC ID.
vpcId='vpc-xxxxxxxx'

groupId="$(
aws ec2 create-security-group --output json --region us-west-2 \
    --description test --group-name test --vpc-id "${vpcId}" \
| jq --raw-output '.GroupId'
)"

echo "Group ID: ${groupId}"

jsonArg="$(jq -n --arg groupId "${groupId}" '
{
  GroupId: $groupId,
  IpPermissions: [
    {
      FromPort: -1,
      ToPort: -1,
      IpProtocol: "-1"
    }
  ],
  TagSpecifications: [
    {
      ResourceType: "security-group-rule",
      Tags: [
        {
          Key: "Name",
          Value: "hello-there"
        }
      ]
    }
  ]
}
')"

aws ec2 authorize-security-group-egress --output json --region us-west-2 \
    --cli-input-json "${jsonArg}"

aws ec2 describe-security-group-rules --output json --region us-west-2 \
    --filters Name=group-id,Values="${groupId}" \
| jq '.SecurityGroupRules[] | [.SecurityGroupRuleId, .Tags]'
```

### Possible Solution

No idea what's going wrong; sorry.

### Additional Information/Context

If I remove the `TagSpecifications` section from the JSON argument, the command succeeds, including returning a `true` status. E.g., if change the construction of the JSON argument in the script to just be this:

```bash
jsonArg="$(jq -n --arg groupId "${groupId}" '
{
  GroupId: $groupId,
  IpPermissions: [
    {
      FromPort: -1,
      ToPort: -1,
      IpProtocol: "-1"
    }
  ]
}
')"
```

… then the command succeeds.

### CLI version used

aws-cli/2.6.1 Python/3.9.12 Darwin/21.5.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

macOS 12.4

**Comment by tim-finnigan** [comment]
Hi @danfuzz thanks for reaching out. I saw you created a couple other issues related to `authorize-security-group-egress`: https://github.com/aws/aws-cli/issues/7068  and https://github.com/aws/aws-cli/issues/7069.

If there are issues with the API then we would have to communicate those to the service team (in this case EC2). This is because the underlying API [AuthorizeSecurityGroupEgress](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AuthorizeSecurityGroupEgress.html) is shared across SDKs, so these issues likely wouldn’t be specific to the CLI.

In any case, it would help to have more information before going to that team. If you use the `--tag-specifications` argument directly rather than `--cli-input-json` does that work? If you could provide your debug logs (with any sensitive info redacted) by adding `--debug` to the command that could help give us more insight into what’s going on.

**Comment by danfuzz** [comment]
Here's a debug log corresponding to this command:

```
aws ec2 authorize-security-group-egress --debug \
    --output json --region us-west-2 \
    --group-id "${groupId}" \
    --ip-permissions 'FromPort=-1,ToPort=-1,IpProtocol=-1' \
    --tag-specifications \
    'ResourceType=security-group-rule,Tags=[{Key=Name,Value=hello-there}]'
```

The output from this command was:

```
{
    "Return": false
}
```

though (per original report) the egress rule _was_ actually added (sans tag).

The only redaction I did was around request auth/signing.

[debug-log.txt](https://github.com/aws/aws-cli/files/9012636/debug-log.txt)

**Comment by danfuzz** [comment]
I believe I tracked this down to the same underlying cause as issue #7068.
