### ISSUE TITLE
AWS_PROFILE priority over credentials in environment variables

### ISSUE THREAD

**Issue by juanibiapina** [aws/aws-cli#7174]
### Describe the bug

Given I have these three environment variables set:

```
export AWS_ACCESS_KEY_ID="..."
export AWS_SECRET_ACCESS_KEY="..."
export AWS_PROFILE=default
```

When I run `aws --profile default sts get-caller-identity` It uses the `default` profile. But instead when I run `aws sts get-caller-identity` it uses the credentials to authenticate directly and the value of `AWS_PROFILE` is effectively ignored.

### Expected Behavior

I would expect that running `aws sts get-caller-identity` with `AWS_PROFILE` set would still pick up the profile and instead ignore the credentials (or use them later to authenticate a source-profile).

### Current Behavior

In the current behavior, specifying credentials in environment variables ignores `AWS_PROFILE`, while it still respects `--profile` in the command line.

### Reproduction Steps

It's in the description.

### Possible Solution

My suggestion is to make the `AWS_PROFILE` variable have priority over credentials.

### Additional Information/Context

As I write this I see this is probably not a bug, and probably hard to change because it causes backwards incompatibilities, but hey, I just wanted to bring it up.

### CLI version used

2.7.14

### Environment details (OS name and version, etc.)

aws-cli/2.7.14 Python/3.10.5 Linux/5.15.58 source/x86_64.nixos.22 prompt/off

**Comment by tim-finnigan** [comment]
Hi @juanibiapina thanks for reaching out. For more info on credential precedence you can refer to this documentation: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-precedence

If I run `aws sts get-caller-identity` with `AWS_PROFILE` set, then it will use the value assigned to that environment variable. And if I run `aws sts get-caller-identity --profile default` then it uses the default profile as expected. 

As you mentioned, any behavior related to this is unlikely to change due to the need to maintain backwards compatibility. Are there any points you wanted to clarify or expand on regarding this?

**Comment by juanibiapina** [comment]
Right, but if you run `aws sts get-caller-identity` with `AWS_PROFILE`, `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`, it won't use the profile.

**Comment by tim-finnigan** [comment]
@juanibiapina If I run `aws sts get-caller-identity` with those environment variables set then it does use the values assigned to the variables. If that's not the case for you can you share the steps you took for reproducing that?

**Comment by juanibiapina** [comment]
In my case `AWS_PROFILE` is ignored. I don't think I can provide any more steps than:
1. Set `AWS_PROFILE`, `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` (make sure the key is referring to a user different from the user referred to by the chosen profile
2. run `aws sts get-caller-identity` and check that the user comes from the key, not from the profile.
