### ISSUE TITLE
Documented settings precedence not followed 

### ISSUE THREAD

**Issue by Kaniee** [aws/aws-cli#7183]
### Describe the bug

Since there are multiple places where config and credentials can be defined, the precedence is documented here: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html

The CLI does not follow the documented precedence since it uses for the same profile a SSO config defined in `~/.aws/config` over the credentials defined in `~/.aws/credentials`.

This is essentially problematic since the GO SDK follows the documentation so there in inconsistent behavior between the AWS CLI and the GO SDK.

### Expected Behavior

If there are credentials given for the current profile in `~/.aws/credentials` these are used independent of the SSO config in `~/aws/config`.

### Current Behavior

The credentials in `~/.aws/credentials` are ignored if there exists a SSO config in `~/.aws/config`.

### Reproduction Steps

`~/.aws/config`:
```
[default]
sso_start_url = https://my-url.awsapps.com/start
sso_region = us-east-1
sso_account_id = 999999999999
sso_role_name = my_role_name
```

`~/.aws/credentials`:
```
[default]
aws_access_key_id=PURPOSELYWRONG
aws_secret_access_key=Something
aws_session_token=NotAValidReallyLongToken
```
`aws sts get-caller-identity`

### Additional Information/Context

For my use case its actually good that the config is used over the credentials, but only if this would be the case for all implementations (e.g. GO SDK) and if it documentation would align with it.

### CLI version used

aws-cli/2.7.21 Python/3.9.11 Linux/5.15.0-43-generic exe/x86_64.ubuntu.22 prompt/off

### Environment details (OS name and version, etc.)

Ubuntu 22.04.1 LTS

**Comment by aBurmeseDev** [comment]
Hi @Kaniee, thanks for reaching out.

After bringing it up to the team internally, we think it's expected behavior since credential provider chain used by each SDK varies as mentioned in the documentation [here](https://docs.aws.amazon.com/sdkref/latest/guide/standardized-credentials.html#credentialProviderChain). 

Also note that there seems to be changes between Go version _V1_ vs _V2_ where config file is ignored in _V1_ and not in _V2_. Here are documentations on that for [V1](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-credentials) and [V2](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/#specifying-credentials).

However, we would like to hear your use case and if you have anything additional to add as far as how this is affecting your workflows.
