### ISSUE TITLE
Allow passing S3 bucket arn to s3api operations

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cli#7187]
### Describe the feature

For example, `aws s3api delete-bucket --bucket arn:aws:s3:::bucket-name` should work.

### Use Case

Sometimes we have the bucket ARN instead of just the name. For example, when the bucket was discovered via `aws resource-groups search-resources`. We shouldn't have to chop off the ARN prefix in this situation.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

1.25.8

### Environment details (OS name and version, etc.)

Alpine 3.16

**Comment by tim-finnigan** [comment]
Hi @rittneje thanks for reaching out. We had a related feature request opened recently in another one of our repositories: https://github.com/boto/botocore/issues/2728. Since this request relates to S3 service APIs I created a new issue for it in our cross-SDK repository: https://github.com/aws/aws-sdk/issues/314. Please refer to that issue for tracking the request going forward. Feel free to leave any feedback there and I can pass it along to the S3 team.
