### ISSUE TITLE
Create method in aws cli for converting IAM secret access key to SES SMTP password

### ISSUE THREAD

**Issue by isleshocky77** [aws/aws-cli#725]
It would be nice to be able to use AWS CLI to convert a IAM Secret Access Key to a SMTP Password.

http://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-credentials.html
This page shows the algorithm for converting an IAM Secret Access Key to a SES SMTP Password in Java.

http://www.snip2code.com/Snippet/21344/an-attempt-to-convert-AWS-IAM-credential
This page _may_ show how to do this in python.

Possible command would be 

`aws ses generate-ses-smtp-password --iam-secret-access-key="ThisIsTheSecretAccessKey"`

**Comment by brian-villanueva** [comment]
And this shows how to do it in bash: [](https://github.com/crylium/aws-scripts/blob/master/ses-smtp-conv.sh)

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by volphy** [comment]
Will the new method to convert from IAM secret access key to SMTP password be implemented?

**Comment by tim-finnigan** [comment]
Checking in as this issue was created a long time ago and hasn't recent much recent activity. The [documentation page](https://docs.aws.amazon.com/ses/latest/dg/smtp-credentials.html) originally linked now shows a Python example for doing this rather than Java. But regardless - it sounds like this would have to be redirected to the SES team as a high-level API feature request. For new API feature requests we recommend reaching out directly to [AWS Support](https://aws.amazon.com/contact-us/) for further escalation. 

We can also forward requests internally to service teams but opening a support case can help with more direct correspondence and tracking on the customer's end. Please let us know if there's anything else we should know about this request or how to proceed, otherwise I will set this issue to auto-close if there are no further comments in the next few days.

**Comment by ad-zsolt-imre** [comment]
As we already rely on AWS CLI to set up parts of our infrastructure it would have been great if it provided that simple feature of converting IAM secret access key to SES SMTP password. That way we did not have to "hack" things with Python (yet another dependency and added complexity we have to manage).
