### ISSUE TITLE
Kinesis: describe-stream timestamp is iso format, not epoch time

### ISSUE THREAD

**Issue by anjafr** [aws/aws-cli#7292]
### Describe the issue

The CLI reference for `kinesis describe-stream` lists the data type of `StreamCreationTimestamp` as `timestamp` and the examples show an epoch time value. The actual behaviour however is, that this is a datetime string in isoformat:
```
{
    "StreamDescription": {
        "Shards": [ ...
        ],
        "StreamARN": "arn:aws:kinesis:eu-central-1:123:stream/AwsWhy",
        "StreamName": "AwsWhy",
        "StreamStatus": "ACTIVE",
        "RetentionPeriodHours": 24,
        "EnhancedMonitoring": [
            {
                "ShardLevelMetrics": []
            }
        ],
        "EncryptionType": "NONE",
        "KeyId": null,
        "StreamCreationTimestamp": "2022-09-23T11:54:00+02:00"
    }
}
```

This does not affect the boto3 documentation, where this is listed correctly.

### Links

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/kinesis/describe-stream.html#output

**Comment by tim-finnigan** [comment]
Hi @anjafr thanks for reaching out. This appears to relate to https://github.com/aws/aws-cli/issues/6224. As I commented in that issue the CLI converts timestamps into a ISO 8601 format by default in v2 (see https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration-changes.html#cliv2-migration-timestamp). 

I still think the v2 documentation examples should be updated to reflect that or at least have an explanatory note. Since the team is still using https://github.com/aws/aws-cli/issues/6224 to track the underlying issue, I think we should close this one. Please let us know if there are any distinctions you want to call out between the issues or any additional feedback. Thanks again for bringing this to our attention.
