### ISSUE TITLE
--no-verify-ssl is ignored

### ISSUE THREAD

**Issue by h3adache** [aws/aws-cli#7366]
### Describe the bug

aws cli 2.8.5 is warning about invalid certs even when using `--no-verify-ssl`

### Expected Behavior

aws cli should not warn about invalid certs when using `--no-verify-ssl` flag

### Current Behavior

```
aws --no-verify-ssl --endpoint-url=https://aws.internal.io s3 ls
/opt/homebrew/Cellar/awscli/2.8.5/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'aws.internal.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
```

### Reproduction Steps

Run any aws cli commands on an self signed endpoint.

### CLI version used

aws-cli/2.8.5 Python/3.10.8 Darwin/22.1.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

MacOS Ventura 13.0 (22A380)

**Comment by hrvolapeter** [comment]
I have the same issue seems to be problem of combination no verify ssl and endpint arguments

**Comment by tim-finnigan** [comment]
That warning is coming from [urllib3](https://urllib3.readthedocs.io/en/stable/) and I think it is accurate — it doesn't mention anything about invalid certs but notes that it is an `InsecureRequestWarning` due to an `Unverified HTTPS request`. I don't think there's anything the AWS CLI can or should do about this, but you should be able ignore that warning in your environment if you'd like, for example: https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings
