### ISSUE TITLE
Implement --only-show-errors option within aws cloudwatch get-metrics-statistics

### ISSUE THREAD

**Issue by Sims24** [aws/aws-cli#7375]
### Describe the feature

Add an option to mask error messages not related to the AWS Cloudwatch request.

The `--only-show-errors` flag is allowing this in other awscli namespaces like s3 but it's not available for `cloudwatch get-metric-statistics.`

Doing such command would not throw `Unknown options: --only-show-errors` anymore.

`aws cloudwatch get-metric-statistics --region eu-west-1 --namespace AWS/S3 --metric-name 'BucketSizeBytes' --start-time 2022-10-26T09:23:45 --end-time 2022-10-28T09:23:45 --period 86400 --statistics Average --output json --dimensions 'Name=StorageType,Value=StandardStorage' 'Name=BucketName,Value=my-rds-backup' --endpoint-url='https://w.x.y.z:1234' --no-verify-ssl --only-show-errors`

### Use Case

In some cases, AWS resources are hosted by a third party and that might require a specific endpoint and skip SSL verification. 

When you programmatically parse the JSON output, most parsers will throw an error because of the raw error message displayed: 

```
{
    "Label": "BucketSizeBytes",
    "Datapoints": [
        {
            "Timestamp": "2022-10-26T09:42:00Z",
            "Average": 14021958169.0,
            "Unit": "Bytes"
        }
    ]
}
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'https://w.x.y.z:1234'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
```
  

### Proposed Solution

I'm not sure if the --only-show-errors support is the solution but [solutions](https://github.com/MarketSquare/robotframework-requests/issues/135) to hide this are mentioned in other projects but it sounds rather inelegant. 

### Other Information

The error is displayed because of the condition below from the `usr/lib/python3/dist-packages/urllib3/connectionpool.py` library.

```
        if not conn.is_verified:
            warnings.warn(
                (
                    "Unverified HTTPS request is being made to host '%s'. "
                    "Adding certificate verification is strongly advised. See: "
                    "https://urllib3.readthedocs.io/en/latest/advanced-usage.html"
                    "#ssl-warnings" % conn.host
                ),
                InsecureRequestWarning,
            )
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.5.8

### Environment details (OS name and version, etc.)

CentOS 7, should be the same everywhere.

**Comment by tim-finnigan** [comment]
Hi @Sims24 thanks for the feature request. There is an `--only-show-errors` parameter for commands such as [s3 sync](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html) but that's because the default output can be a bit noisy. For the [get-metrics-statistics](https://docs.aws.amazon.com/cli/latest/reference/cloudwatch/get-metric-statistics.html) command can you expand a bit more on how a `--only-show-errors` would help with your use case? 

I'm not too familiar with that API but my expectation is that an error would prevent the command from running at all, rather than something like `s3 sync` where an error might occur on a specific file after dozens of others were logged as successfully synced. 

I saw you mentioned that `InsecureRequestWarning` but that is a logged warning rather than service API error. If you're just trying to suppress warnings then you could add an environment variable such as `PYTHONWARNINGS="ignore:Unverified HTTPS request"` as suggested in https://github.com/boto/boto3/issues/699

**Comment by Sims24** [comment]
Hi @tim-finnigan , 

Thanks for your answer. Indeed, it was more something like --quiet maybe but doesn't make sense anyway. 

I wasn't able to find the solution you mentioned with the environment variable by myself so many thanks. It will does the trick.

Best.
