### ISSUE TITLE
Allow Customization of the Assume Role cache directory path (`~/.aws/cli/cache`)

### ISSUE THREAD

**Issue by jh-kainos** [aws/aws-cli#7376]
### Describe the feature

I couldn't find any mention of this in the CLI docs and from looking at the code [here](https://github.com/aws/aws-cli/blob/d1498cb06baf6cd7701db05ed6933f2390b09066/awscli/customizations/assumerole.py#L8) it doesn't appear that it can be customised. Would it be possible to add an environment variable or command line option that we can use to set this path, please?

### Use Case

We use [amazon-eks-pod-identity-webhook](https://github.com/aws/amazon-eks-pod-identity-webhook) to assign IAM roles to pods in our Kubernetes cluster. We use Pod Security Policies to set the root filesystems of most of our containers to read-only. If a pod uses the AWS CLI and `pod-identity-webhook` together, it will fail to write to the CLI cache directory as it's read-only.

### Proposed Solution

Add an environment variable and/or CLI arg for specifying a custom CLI cache directory path.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

1.26.3

### Environment details (OS name and version, etc.)

Alpine Linux 3.15

**Comment by tim-finnigan** [comment]
Hi @jh-kainos thanks for reaching out. I think this is a duplicate of https://github.com/aws/aws-cli/issues/1804. That issue was opened a long time ago but was labeled as `automation-exempt` because the team didn't want it to get auto-closed. Could you 👍 that issue and share your use case there? That would help the team with tracking and prioritization going forward.

I also saw that you checked the box that you may be able to implement this feature request. If you are interested in contributing please refer to the [Contribution Guide](https://github.com/kdaily/aws-cli/blob/contrib-guide-proposal/proposals/contribution-guide.md) that was updated earlier this year.

**Comment by jh-kainos** [comment]
Hi @tim-finnigan

Good spot, it is a duplicate. I'll go add my use case there, thanks.

I might be able to spend some time on implementing it, but I can't promise anything at the moment.
