### ISSUE TITLE
A suggestion for vpc endpoint creation

### ISSUE THREAD

**Issue by Bishop0948** [aws/aws-cli#7424]
### Describe the feature

This maybe no so serious or important, im hoping that when i create an interface vpc endpoint, there have a commandline option to appoint a network interface.

### Use Case

Here is the thing, i have this project that required endpoint and EC2 instance. More precisely is create endpoint first and then EC2 instance, and the instance should have a fixed private ip in VPC CIDR range.
The good part is the EC2 instance can assgin a network interface with fixed private ip, the sad part is there always have conflict: the instance's fixed ip address already been used by the VPC endpoint. It's so frustrated :(

### Proposed Solution

So is there any chance that can allow the endpoint to attach a network interface or a small cidr range for endpoint only to create-vpc-endpoint commandline ? Or add a new command for create a endpoint network interface. 
i hope this is for the best.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CLI version used

2.7.21

### Environment details (OS name and version, etc.)

Amazon Linux 2

**Comment by tim-finnigan** [comment]
Hi @Bishop0948 thanks for reaching out. Can you explain a bit more about what you've tried and where you're stuck? I saw this documentation on creating an interface VPC endpoint: https://docs.aws.amazon.com/vpc/latest/privatelink/create-interface-endpoint.html. Does following those steps accomplish what you're trying to do?

**Comment by Bishop0948** [comment]
> Hi @Bishop0948 thanks for reaching out. Can you explain a bit more about what you've tried and where you're stuck? I saw this documentation on creating an interface VPC endpoint: https://docs.aws.amazon.com/vpc/latest/privatelink/create-interface-endpoint.html. Does following those steps accomplish what you're trying to do?

Thanks for replying ! What bothers me is the network interface is automatic created when create an interface endpoint, which constantly conflict with the EC2 instance's fixed private IP. 
We tried using terraform coordinated with cli to work around this, but didn't go well.
There have two separate part, the VPC and EC2, and the endpoint is in VPC part, so...
Right now we can re-create the endpoint manualy or change the EC2 fixed IP when caught up a conflict, but this hardly a 
good solution, so i think the key is make the network interface can be a option in this commandline to manualy attach it to an insterface endpoint by ID or something else.

**Comment by tim-finnigan** [comment]
Hi @Bishop0948 thanks for following up. Just to clarify - it sounds like you're using the [create-vpc-endpoint](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/create-vpc-endpoint.html) EC2 command. The corresponding API for that is [CreateVpcEndpoint](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVpcEndpoint.html) which is used across SDKs.

Since service teams own the design of the APIs, feature requests like this would need to get rerouted to those teams. I can to forward this to the EC2 team (Or if you have a support plan with AWS then you can also reach out through [AWS Support](https://aws.amazon.com/contact-us/) for direct assistance with feature requests such as this).

Just to get a little more context on your use case, could you expand on what the command you're requesting might be called and how it would be different than `create-vpc-endpoint`? Or could what you're trying to do be possible by adding a new parameter to that existing command?
