### ISSUE TITLE
Receiving `/c: /c: Is a directory` when running CLI commands on Windows

### ISSUE THREAD

**Issue by RyianRockers** [aws/aws-cli#7440]
### Describe the bug

When executing certain CLI commands, I receive a message that says "/c: /c: Is a directory", instead of the output of the command. This particular example, I was using this command: "aws transfer describe-access --server-id <serverID> --external-id <externalSID>"

### Expected Behavior

The expected output is the description of the access to the aws transfer family server.

### Current Behavior

![image](https://user-images.githubusercontent.com/17551097/201949283-6c57a185-baee-43c1-bede-1bbdc046f908.png)

### Reproduction Steps

aws transfer describe-access --server-id <serverID> --external-id <externalSID>

### Possible Solution

could be an issue with my botocore version? When I use the --debug flag I get this output:

![image](https://user-images.githubusercontent.com/17551097/201950624-1126a3dc-2679-40f1-a68e-3c9ad96a500d.png)

### CLI version used

2.7.14

### Environment details (OS name and version, etc.)

AWS Workspace/Windows Server 2016/

**Comment by RyianRockers** [comment]
botocore versions:

![image](https://user-images.githubusercontent.com/17551097/201951659-eb37a0ee-dedc-4157-8d67-f04de07f557c.png)

**Comment by tim-finnigan** [comment]
Hi @RyianRockers thanks for reaching out. Botocore is packaged with the AWS CLI so installing the latest version of the CLI should update botocore as well. You could try updating to the latest version of the CLI.

I'm not sure that this issue is specific to the AWS CLI - it could have something to do with your shell configuration. Are you able to run other commands? And if you're using Powershell, does running commands in Command Prompt work? 

I saw you're using an older workspace (Windows Server 2016), so if you're able to use a newer workspace then that might resolve the issue.
