### ISSUE TITLE
created a RDS cluster snapshot, using cli made the snapshot public but still visible as private in the AWS console.

### ISSUE THREAD

**Issue by Nisirinkuptycs** [aws/aws-cli#7462]
### Describe the bug

Steps:

1. created a RDS Cluster with storage_encrypted = "false".
2. created a snapshot from the RDS Cluster.
3. modified the RDS snapshot to make it public
`aws rds modify-db-cluster-snapshot-attribute --db-cluster-snapshot-identifier  xxxxxxx --attribute-name restore --values-to-add all --p xxxxxx  `

### Expected Behavior

from AWS console 

1. select the RDS Cluster Snapshot
2. select Actions -> Share Snapshot
3. 
![image](https://user-images.githubusercontent.com/90234967/203260857-a8c12f80-e231-4fc1-a63d-3a9654144981.png)
the expected behavior should be public but incorrectly showing as private 

### Current Behavior

incorrectly showing as private
![image](https://user-images.githubusercontent.com/90234967/203261593-2aafb467-1a2b-4c03-a112-c7e59dfaf735.png)

![image](https://user-images.githubusercontent.com/90234967/203261467-b8e4eba8-54e7-41e4-9b8e-75381e5c98a5.png)

### Reproduction Steps

`aws rds modify-db-cluster-snapshot-attribute --db-cluster-snapshot-identifier  xxxxxxx --attribute-name restore --values-to-add all --p xxxxxx  `

### CLI version used

aws-cli/1.20.13 Python/3.9.1 Linux/5.10.102.1-microsoft-standard-WSL2 botocore/1.21.13

### Environment details (OS name and version, etc.)

Windows 10

**Comment by aBurmeseDev** [comment]
Hi @Nisirinkuptycs - thanks for reaching out.

It seems like you're using older version of AWS CLI. I attempted to replicate it with recent version and wasn't able to. I would suggest updating your CLI and you should see expected behavior. 

Here's docs guide on updating CLI for reference:https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html#getting-started-install-instructions

Please let me know if this issue persists. 

Best,
John
