### ISSUE TITLE
Missing 

### ISSUE THREAD

**Issue by eaoliver** [aws/aws-cli#7479]
### Describe the bug

I am running awscli packaged through homebrew. 

version 2.9.1 is missing docutils dependency. 

### Expected Behavior

aws commands should run as normal without error.

### Current Behavior

eaoliver@Voracious ~ % aws
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/Cellar/awscli/2.9.1/libexec/lib/python3.11/site-packages/awscli/clidriver.py", line 43, in <module>
    from awscli.help import ProviderHelpCommand
  File "/usr/local/Cellar/awscli/2.9.1/libexec/lib/python3.11/site-packages/awscli/help.py", line 20, in <module>
    from docutils.core import publish_string
ModuleNotFoundError: No module named 'docutils'

### Reproduction Steps

Simply execute 'aws'

### Possible Solution

docutils missing from installation.

### CLI version used

2.9.1

### Environment details (OS name and version, etc.)

Mac OS 10.15.7 (19H2026)

**Comment by 3mini** [comment]
I'm having the same problem.

```
$ aws
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/Cellar/awscli/2.9.1/libexec/lib/python3.11/site-packages/awscli/clidriver.py", line 43, in <module>
    from awscli.help import ProviderHelpCommand
  File "/usr/local/Cellar/awscli/2.9.1/libexec/lib/python3.11/site-packages/awscli/help.py", line 20, in <module>
    from docutils.core import publish_string
ModuleNotFoundError: No module named 'docutils'
```

### awscli version
2.9.1

### Environment
macOS 13.0.1 (Ventura)

**Comment by mitsuhisaT** [comment]
I'm fixed.

```shell
$ brew reinstall docutils
```

**Comment by aBurmeseDev** [comment]
Hi @eaoliver - thanks for reaching out. 

Unfortunately, the Homebrew Formulae for the AWS CLI is not managed and/or supported by AWS, but by the Homebrew maintainers. Here's the [official documentation guide](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) for AWS CLI.

Also it seems like the previous comment made by @mitsuhisaT fixes the issue here. If you're still having issue, I'd suggest reaching out on [Homebrew](https://github.com/Homebrew/homebrew-core/issues) repository. 

I'm going to close this issue now. Please let us know if there's anything we can help with [AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html).

**Comment by tluck** [comment]
Thank for the fix!!! 
brew reinstall docutils 
helped me.

**Comment by asanka-x** [comment]
> 

Saved my day!! thanks @mitsuhisaT
