### ISSUE TITLE
AWS CLI Prompt Breaks ECR login

### ISSUE THREAD

**Issue by seanfariacustomink** [aws/aws-cli#7503]
### Describe the bug

AWS CLI prompt breaks ECR login

AWS_CLI_AUTO_PROMPT=on
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html#envvars-list-aws_cli_auto_prompt

Due to the prompt stopping every command it fails to do the docker login part.

For example
aws ecr get-login-password --region region | docker login --username AWS --password-stdin aws_account_id.dkr.ecr.region.amazonaws.com

### Expected Behavior

hit enter again and login is successful

### Current Behavior

aws ecr get-login-password --region region | docker login --username AWS --password-stdin aws_account_id.dkr.ecr.region.amazonaws.com

The command hangs and no way to continue if you hit enter it causes an 
"Error response from the daemon: login attempt to https://<accountnumber>.dkr.ecr.us-east-1.amazonaws.com/v2/ failed with status: 400 Bad Request"

### Reproduction Steps

create env variable
AWS_CLI_AUTO_PROMPT=on

then run:
aws ecr get-login-password --region region | docker login --username AWS --password-stdin aws_account_id.dkr.ecr.region.amazonaws.com

### Possible Solution

When the command has a " | " do not allow prompt

### CLI version used

aws-cli/2.9.4

### Environment details (OS name and version, etc.)

MAC

**Comment by aBurmeseDev** [comment]
Hi @seanfariacustomink - thanks for reaching out and sorry to hear you're having issues.

From looking at the bad request error you get, it sounded like credentials aren't being shared with the container. 

Since AWS CLI v2 is run in a container, by default the CLI can't access the host file system, which includes configuration and credentials. To share the host file system, credentials, and configuration to the container, you'll need to mount the host system’s `~/.aws` directory to the container at `/root/.aws` with the `-v` flag to the docker run command. This allows the AWS CLI version 2 running in the container to locate host file information.

Here's [docs](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-docker.html#cliv2-docker-share-files) on how to share credentials to the container.

Please let me know if that helps or you have any other questions!
Best,
John

**Comment by seanfariacustomink** [comment]
Hi @aBurmeseDev,

This is not the case since if you turn off the prompt feature the issue is resolved. 
When the AWS CLI prompt feature is turned on the issue returns.
Please test it and you will see this is a bug where the prompt stops the command from finishing causing bad requests and additional characters.

**Comment by seanfariacustomink** [comment]
Hi @aBurmeseDev,
I have also confirmed this happens on windows as well.

**Comment by aBurmeseDev** [comment]
Hi @seanfariacustomink - apologies for the delay. I attmpted to reproduce this again with both AWS CLI prompt enabled and disabled but didn't see the behavior mentioned. Would you be able to share your debug logs by appending `--debug` to your command? That would give us more insights into finding the cause of the behavior. 
Thanks,
John
