### ISSUE TITLE
SSO cache files are written to home directory instead of respecting XDG

### ISSUE THREAD

**Issue by jasonkarns** [aws/aws-cli#7513]
### Describe the bug

AWS cli does not respect the XDG specification for writing cache files; nor does it have its own environment variable for custom configuration as a workaround for XDG basedir spec violation.

### Expected Behavior

I expected these files to be written to `${XDG_CACHE_HOME:-~/.cache}/aws`

### Current Behavior

After logging in with aws sso, some files were written to `~/.aws`

```
$ tree .aws/
.aws/
└── sso
    └── cache
        ├── *.json
```

### Reproduction Steps

`aws configure sso && aws sso login`

### Possible Solution

aws cli should respect XDG specification: https://github.com/aws/aws-sdk/issues/30

### CLI version used

aws-cli/2.9.5 Python/3.11.0 Darwin/22.1.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

macOS 13.0.1

**Comment by tim-finnigan** [comment]
Hi @jasonkarns thanks for creating this issue. In the related issue you linked I think [this comment](https://github.com/aws/aws-sdk/issues/30#issuecomment-742712191) still applies:

>While I do not disagree with this convention, this would be a big breaking change to many users who rely on the current configuration settings. In order to make this work, this convention would need to be adhered to by all AWS SDKs and tools. Because of this, I'm going to move this issue to the AWS SDK issue tracking repository at https://github.com/aws/aws-sdk.

Requests involving environment configuration are tracked in that repository since the convention would need to be adhered to by other AWS SDKs as mentioned above. Since both of these issues relate to the XDG specification I think we can continue tracking the requests in that existing cross-SDK issue. If you have any questions please let me know, and you can always reach out through [AWS Support](https://aws.amazon.com/contact-us/) for direct assistance and escalations.
