### ISSUE TITLE
ec2 copy-image does not copy image tags

### ISSUE THREAD

**Issue by volphy** [aws/aws-cli#7524]
### Describe the bug

AWS CLI version:
```
$ aws --version
aws-cli/2.9.6 Python/3.9.11 Linux/4.14.301-224.520.amzn2.x86_64 exe/x86_64.amzn.2 prompt/off
```

EC2 tags are not copied while copying AMI images.

### Expected Behavior

There should be the same EC2 tags in the source AWS account and target AWS account.

### Current Behavior

The following AWS CLI command:
```
SOURCE_AMI_NAME=....
SOURCE_IMAGE_ID=...
AWS_REGION=eu-west-1
$ aws ec2 copy-image --name ${SOURCE_AMI_NAME} --source-image-id ${SOURCE_IMAGE_ID} --source-region ${AWS_REGION} --copy-image-tags
```

does not copy image tags from the source AWS account to the target AWS account.

The AMI image is shared and copied correctly (though without tags).
As a workaround tags are created in the target AWS account:
```
TARGET_IMAGE_ID=...
SOURCE_AMI_NAME=...
$ aws ec2 create-tags --resources ${TARGET_IMAGE_ID} --tags Key=Name,Value=${SOURCE_AMI_NAME}
```

Is it expected behaviour or should EC2 tags be successfully copied in my scenario?

### Reproduction Steps

See Current Behavior section

### CLI version used

2.9.6

### Environment details (OS name and version, etc.)

Linux x86_64 (EC2 instance)

**Comment by aBurmeseDev** [comment]
Hi @volphy - thanks for reaching out.

As mentioned in the [API docs](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CopyImage.html#API_CopyImage_RequestParameters), there are some conditions on which image tags will be copied over and might seem like the ones you have won't copy over under those conditions. But looks like you're on the right path by using `create-tags` instead. 

Since it's expected behavior, I'm going to add `closing-soon` label and if you have any other questions, please feel free to reach out again.

>CopyImageTags
> The following tags will not be copied:
> - System tags (prefixed with aws:)
> - For public and shared AMIs, user-defined tags that are attached by other AWS accounts
Default: Your user-defined AMI tags are not copied.

Best,
John
