### ISSUE TITLE
awscli does not respect Identity Center sso session duration length

### ISSUE THREAD

**Issue by jeremymturner** [aws/aws-cli#7538]
### Describe the bug

When a user runs `aws sso login`, the returned SSO session token expiresAt returns a +8 hour value, regardless of what the administrator set under IAM Identity Center -> Settings -> Authentication -> Maximum session duration.

Note that this is not looking at a session duration of any permission sets, just at IAM Identity Center itself.

### Expected Behavior

awscli should respect the value set under IAM Identity Center -> Settings -> Authentication -> Maximum session duration when it returns the expiresAt value.

### Current Behavior

awscli returns the current time +8 hours

### Reproduction Steps

```
rm ~/.aws/sso/cache/*; rm ~/.aws/cli/cache/*;
aws sso login
cd ~/.aws/sso/cache
echo expiresAt
cat $(ls -t . | head -n1) | jq -r ".expiresAt"
echo currentTime
TZ=Z date +%Y-%m-%dT%H:%M:%SZ
```

### Possible Solution

Short-term fix:
1. Modify awscli to respect the Maximum session duration value in IAM Identity Center -> Settings -> Authentication -> Maximum session duration.

Long-term fix:
1. Provide a maximum session duration setting for console and a separate one for command-line
2. Modify awscli to respect the (new) command-line maximum session duration value

### Additional Information/Context

Resolution of this would also complete the request asked for in https://github.com/aws/aws-cli/issues/6547.

### CLI version used

aws-cli/2.9.8 Python/3.11.0 Darwin/21.6.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

macOS Monterey 12.6.1

**Comment by tim-finnigan** [comment]
Hi @jeremymturner thanks for reaching out. [This comment](https://github.com/aws/aws-cli/issues/6547#issuecomment-970508351) from the issue you linked mentioned how the https://docs.aws.amazon.com/singlesignon/latest/userguide/authconcept.html documentation page said:
>Each time a user signs in to AWS SSO, a sign in session is created with an 8-hour lifetime.

That documentation has since been updated to note:

>Each time a user signs in to IAM Identity Center, a sign in session is created for the duration configured in Identity Center, which can be up to 7 days. For more information, see [Manage IAM Identity Center integrated application sessions](https://docs.aws.amazon.com/singlesignon/latest/userguide/manage-app-session.html).

This is what I see when configuring session settings in the IAM Identity Center:

<img width="645" alt="image" src="https://user-images.githubusercontent.com/87778557/208732379-618e1473-cb4c-4ff7-9335-6d897453852f.png">

You said you're using v2.9.8 which is currently the latest CLI version per the [CHANGELOG](https://raw.githubusercontent.com/aws/aws-cli/v2/CHANGELOG.rst). But you're saying that if you configure the session duration beyond 8 hours then it does not refresh the token?

If you have a support plan I recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) for direct assistance with issues like this.

**Comment by jeremymturner** [comment]
> "You said you're using v2.9.8 which is currently the latest CLI version per the [CHANGELOG](https://raw.githubusercontent.com/aws/aws-cli/v2/CHANGELOG.rst). But you're saying that if you configure the session duration beyond 8 hours then it does not refresh the token?"

Correct. If I configure the session duration to 24 hours, the `~/.aws/sso/cache/*.json` expiresAt value remains at 8 hours. I tried logging out and back in to my IdP, and removing all cached tokens in `~/.aws` with the same behavior.

Additionally, I looked at the boto3 module docs under the `sso` and `sso-admin` sections, and it's not clear to me that there is an API that would return this information. https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sso-admin.html

The actual token refresh (from SSO token to permission set/role token) seems to be working normally. It's just that the SSO token duration doesn't match what the UI has.

**Comment by ronmegini** [comment]
The same thing happens here.
The session duration configured in the IAM Identity Center is 12 hours but the token generated by the AWS SSO login command expires in 8 hours.
Current time: 13:08:07, Expiration time (in ./aws/sso/xxx.json): `"expiresAt": "2023-11-29T21:08:07Z".`

For example with granted assume cli the session duration is indeed 12h: `[✔] [development](us-east-1) session credentials will expire in 12 hours `

Leave me a comment for further details.

**Comment by jishi** [comment]
Why was this closed? 

I'm seeing the same thing, the iam identity center is completely schizofrenic. I have several AWS accounts that I can log into via identity center. Some of them will give me 8h tokens regardless of the session expiration setting in identity center, but now I notice that one of the accounts always give me a 1h token (!), probably due to sso configuring it at a later time (so something has changed?)

This is even more frustrating than having an 8h token.

**Comment by SampaioLeal** [comment]
@jishi i'm freaking out having to configure sso every hour 
the real feeling is like every day the expiration time is reduced :smiling_face_with_tear:

**Comment by panda7zip** [comment]
regardless of what you are configuring in AWS Identity Center - you will get 8 hour access, why this is closed?

**Comment by hostmit** [comment]
+1, SSO configuration has no effect, it's always 8 hours

**Comment by venky999** [comment]
Our team had similar issues. 

There is a setting in AWS Identity Centre Settings -> Authenticaition Tab which where we could set the session duration.

Minium of the permission set sestion duration and AWS Identity Centre Settings session duration  is considred I think. 

This is tested for Entra ID as exteranl IDP. 

Please check  https://docs.aws.amazon.com/singlesignon/latest/userguide/user-interactive-sessions.html and https://aws.amazon.com/blogs/security/define-a-custom-session-duration-and-terminate-active-sessions-in-iam-identity-center/
