### ISSUE TITLE
MAC - upload failed: ./file.txt to s3://bucket Unable to locate credentials

### ISSUE THREAD

**Issue by GanesanRengasamy** [aws/aws-cli#7545]
### Describe the bug

I am trying to upload the single file in the AWS by using the below AWS command in MAC(.sh file)
`aws s3 cp "$filename" s3://bucketname`

But I am facing the below error
upload failed: ./file.txt to s3://bucket Unable to locate credentials

So, I have configured my credentials by using the below command.

`aws configure import --csv "file://./awscredentials.csv"`

I got the below output for the above command
`Successfully imported 1 profile(s)`

But still I am facing the same issue while upload. So, I have tried the below command to check whether the credentials configure or not.

`aws configure list`

But I got the below. As per the below table I suspect the credential is not configured properly

![image](https://user-images.githubusercontent.com/16695209/209459368-ec5a59be-ee0a-4b95-be88-c492b81ce906.png)

Could you please check this issue and provide the solution to upload the single file in AWS?

### Expected Behavior

The credential should configured and upload the file

### Current Behavior

The credential not configured and upload not working

### Reproduction Steps

Create the .csv file with the details of User Name, Access key ID, Secret Access Key headers and run the below two commands,

`aws configure import --csv "file://./awscredentials.csv"`
`aws s3 cp "$filename" s3://Bucket`

### CLI version used

ws-cli/2.9.7 Python/3.9.11 Darwin/21.6.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

macOS-12

**Comment by aBurmeseDev** [comment]
Hi @GanesanRengasamy - thanks for reaching out.

From looking at the output from `aws configure list`, it shows that credentials aren't set for the profile. Try running `aws configure --profile <yourProfile>`. That will ask you to enter your Access Key ID and Secret Key. After that, try  `aws configure list` again and you should see the updated credentials. That should resolve the issue. 

If that didn't work out, please try re-configuring with awscli command `aws configure` instead of importing a key pair with .CSV file. Here's docs guide for your reference: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-config

Hope it helps,
John~

**Comment by Dreamypops33** [comment]
Confirmation
