### ISSUE TITLE
Add support for PAGER/AWS_PAGER

### ISSUE THREAD

**Issue by jamesls** [aws/aws-cli#757]
We've had feature requests to support a PAGER/AWS_PAGER environment variable.  It would work similar to other CLIs that support a pager env var in that any output would be sent to the pager if the var is set (provided it would take up more than one page).

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by SydneyUniLibrary-Jim** [comment]
All these many years later, this is now a thing. #4702 

And I hate it because they've changed the default behaviour! All my scripts containing aws commands are halting at each aws command as less waits for me to hit q.

**Comment by seren** [comment]
Yeah, very much a breaking change to all automation scripts using `--output`.

**Comment by joguSD** [comment]
@SydneyUniLibrary-Jim @seren It's possible to disable piping to a pager by setting `AWS_PAGER=""`.

**Comment by seren** [comment]
@joguSD Thanks. Yes, I've had to add `AWS_PAGER=""` to the top of all scripts that use aws-cli and remind teammates to do the same for any new scripts.

**Comment by kdaily** [comment]
Thanks all for your feedback. Given that this is implemented, I'm going to close this. There is an open issue around what the behavior should be at #5102. If you have comments on the behavior please make them there!

There is a CLI parameter `--no-cli-pager` to opt-out as well.
