### ISSUE TITLE
aws sync and aws cp hangs with "recursive" option (old bug)

### ISSUE THREAD

**Issue by felipelalli** [aws/aws-cli#7583]
### Describe the bug

The same as described in closed - aws sync hangs #2477 - issue.

For me, after running the command:
`aws s3 sync <bucket> . --no-guess-mime-type --exclude "*" --include "xpto*"`

I get:
`Completed 25.0 MiB/~25.0 MiB (10.2 MiB/s) with ~0 file(s) remaining (calculating...)`

But the command never ends.

### Expected Behavior

The command `aws cp` and `aws sync` should end after end and not hang.

### Current Behavior

The command hangs.

### Reproduction Steps

100% of the time:

`aws s3 sync <bucket> . --no-guess-mime-type --exclude "*" --include "xpto*"`

### Possible Solution

I have no idea.

### CLI version used

aws-cli/2.9.14

### Environment details (OS name and version, etc.)

Python/3.9.11 Linux/5.15.0-1028-aws exe/aarch64.ubuntu.22 prompt/off

**Comment by aBurmeseDev** [comment]
Hi @felipelalli - thanks for reaching out and sorry to hear about the issue.

From looking at the issue mentioned, some users found out that it was memory issues like [here](https://github.com/aws/aws-cli/issues/2477#issuecomment-375306914) and others mentioned they had to remove logs files from the bucket like [here](https://github.com/aws/aws-cli/issues/2477#issuecomment-375709590). Could any of those two be a concern in your case?

If not, I would be happy to help to further troubleshoot for you. Please share your debug logs by appending `--debug` to your command so that would give us more insights on figuring out the issue, along with the command you're using. 

Best,
John

**Comment by felipelalli** [comment]
Thank you John. Unfortunately I had already terminated the machine where I
had worked on that.

Thanks.

Felipe.

**Comment by aBurmeseDev** [comment]
Understood, please feel free to reach out to us again if you have any other questions. I'm going to close this issue now. 

Have great day!
John
