### ISSUE TITLE
describe-user-pool returns inaccurate EstimatedNumberOfUsers

### ISSUE THREAD

**Issue by tallulah-carlisle** [aws/aws-cli#7604]
### Describe the bug

600 Users are in AWS Cognito User Pool and the Estimated Number of Users reports that there are 700

### Expected Behavior

 I expect to see an accurate count of the users in the user pool

### Current Behavior

There is an inaccurate count of users displayed

### Reproduction Steps

Create 600 users to the Cognito User Pool and check how many the Estimated number of users displays

### CLI version used

aws-cli/2.8.7

### Environment details (OS name and version, etc.)

macOS version 12.5.1

**Comment by tim-finnigan** [comment]
Hi @tallulah-carlisle thanks for reaching out. For us to investigate further, could you please share your debug logs (with any sensitive info redacted) by adding `--debug` to your command?

The results variable is an "Estimated" number so this may just be the expected behavior. The debug logs will help give more insight into the issue.
