### ISSUE TITLE
TypeError: deprecated() got an unexpected keyword argument 'name'(short issue description)

### ISSUE THREAD

**Issue by stoccalino** [aws/aws-cli#7607]
### Describe the bug

Hello,  I installed some dependencies on my project with poetry, and after the installation was over, any pip3 command throws the next error :

`TypeError: deprecated() got an unexpected keyword argument 'name'
`

I see that there are other issues reported 
(https://github.com/aws/aws-cli/issues/7325)
(https://github.com/pyca/pyopenssl/issues/1151)
 suggesting that uninstalling pyOpenSSL resolves the issue, but I can't even uninstall, since any pip3 command throws this error.

Any help would be appreciated.
Thanks! 

### Expected Behavior

pip3 working as normal 

### Current Behavior

any pip3 command throws error "TypeError: deprecated() got an unexpected keyword argument 'name'" 

### Reproduction Steps

pip3 check : TypeError: deprecated() got an unexpected keyword argument 'name'

### CLI version used

-

### Environment details (OS name and version, etc.)

Macos Ventura13.1

**Comment by tim-finnigan** [comment]
Hi @stoccalino thanks for reaching out. How are you installing the AWS CLI and which version are you installing? Here is the documentation on installing the AWS CLI: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html#getting-started-install-instructions. 

I don't think this issue is directly related to the AWS CLI but please let us know if there is any more context you can share as far as steps to reproduce the issue.

**Comment by stoccalino** [comment]
I'm sorry, no. I don't think this is concerned with AWS CLI. I'm using poetry which manages all the dependencies from a project. After I ran `poetry install` , I got the 'TypeError: deprecated() got an unexpected keyword argument 'name'' error and can no longer use any pip3 command

**Comment by tim-finnigan** [comment]
Thanks @stoccalino for following up. In that case I think this issue would be better suited for the poetry repository: https://github.com/python-poetry/poetry/issues. I recommend creating an issue there, and if any issue directly related to the AWS CLI is found then we can revisit this here.
