### ISSUE TITLE
Installating AWS CLI on Windows 7

### ISSUE THREAD

**Issue by ribery77** [aws/aws-cli#7659]
### Describe the bug

Hi All. I try to install AWS CLI on Windows 7. I stumble upon this error below.
![Aws_CLI](https://user-images.githubusercontent.com/8490134/218320780-abe9a402-987d-4b20-9ab1-840efa5fc2c2.PNG)

 I try to install  Visual C++ Redistributable for Visual Studio 2015 but it does not help me. Please see reference here https://stackoverflow.com/questions/54214600/pyinstaller-error-loading-python-dll-formatmessagew-failed

Any suggestions are welcome.

### Expected Behavior

I cannot isntall AWS CLI/

### Current Behavior

It does not work.

### Reproduction Steps

NA

### CLI version used

2

### Environment details (OS name and version, etc.)

Windows 7 sp1

**Comment by tim-finnigan** [comment]
Hi @ribery77 thanks for reaching out. This appears to be expected behavior. You're using Python 3.9 and that version is not supported by Windows 7 as noted here: https://www.python.org/downloads/release/python-390/
>The installer now also actively disallows installation on Windows 7. Python 3.9 is incompatible with this unsupported version of Windows.

Also in the [AWS CLI v2 installation instructions](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) it notes the requirement of 64-bit Windows. For more information on supported Python versions you can refer to this blog post: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/

**Comment by tim-finnigan** [comment]
First you'd need to downgrade your version of Python as 3.9 is not supported on Windows 7.

For the AWS CLI v2 you'd need a 64-bit version of Windows as mentioned here: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html#getting-started-install-instructions

Otherwise you can try installing v1 as documented here: https://docs.aws.amazon.com/cli/v1/userguide/install-windows.html.

**Comment by tlhogi84** [comment]
You need to first verify the version of Python that can be supported by your machine.
On windows 7, the most recent version that can be downloaded is Python 3.8.8

You then need to check which version of AWS CLI v2 is supported by your version of Python.
This can be verified on the [change logs](https://raw.githubusercontent.com/aws/aws-cli/v2/CHANGELOG.rst)

You can see in the logs that version 2.5.0 and above require Python 3.9 and higher.
Thus, if you have Python 3.8.8, you will need to install AWS CLI v2 2.4.29 and lower.

You can install a version via the following link:
https://awscli.amazonaws.com/AWSCLIV2-2.4.29.msi

Replace the version as appropriate

**Comment by bencfreeman** [comment]
> You need to first verify the version of Python that can be supported by your machine. On windows 7, the most recent version that can be downloaded is Python 3.8.8
> 
> You then need to check which version of AWS CLI v2 is supported by your version of Python. This can be verified on the [change logs](https://raw.githubusercontent.com/aws/aws-cli/v2/CHANGELOG.rst)
> 
> You can see in the logs that version 2.5.0 and above require Python 3.9 and higher. Thus, if you have Python 3.8.8, you will need to install AWS CLI v2 2.4.29 and lower.
> 
> You can install a version via the following link: https://awscli.amazonaws.com/AWSCLIV2-2.4.29.msi
> 
> Replace the version as appropriate

I've been trying to solve this problem for the last day and a half in my spare time, and I went down a bunch of irrelevant Python rabbit holes. I've never knowingly and purposefully installed python on anything, ever, so it seemed odd that I would need to install an older version just to be able to run what I thought was a standalone exe. I've used the AWS CLI V2 for years on Win7 and Win10 systems. I recently needed to install and use the CLI on a Windows 7 PC, and I wish I had looked into earlier builds of the AWS CLI first.

This answer is perfect. I downloaded and installed the MSI from the link and now I can get back to work.
