### ISSUE TITLE
EBS - how to know when RequestEnvironmentInfo has finished?

### ISSUE THREAD

**Issue by alexconlin** [aws/aws-cli#766]
Is there any way to receive some kind of notification for when the command request-environment-info has finished requesting the information? I have written a shell script which uses this command and it seems to take a second or two so I don't know how long to wait until I can then call retrieve-environment-info.

Thanks,

**Comment by jamesls** [comment]
The AWS CLI recently added support for a `wait` command which will block until a particular state on a resource is reached.  We can add some elasticbeanstalk waiters for this case.  Marking as a feature request.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
