### ISSUE TITLE
token expiration despite re-login

### ISSUE THREAD

**Issue by adcanis** [aws/aws-cli#7689]
### Describe the bug

setup IAM SSO, using Amplify. Initial setup is fine and can push no problem. Issue comes in if token is expired. I re-login via `aws sso login --profile <profile name>` and re-authenticate no problem. BUT when perform `amplify push -y ` or any other command, I get error: 

> ✖ There was an error pulling the backend environment dev.
🛑 The provided token has expired.

### Expected Behavior

Login should allow for commands 

### Current Behavior

no ability to perform commands

### Reproduction Steps

1. aws sso login --profile <profile name>
2. amplify push -y

### CLI version used

2.4.25

### Environment details (OS name and version, etc.)

mac v13.2

**Comment by aBurmeseDev** [comment]
Hi @adcanis - thanks for reaching out. I think you're using [aws-amplify/amplify-cli](https://github.com/aws-amplify/amplify-cli) rather than AWS CLI in this case and the error you're seeing seems related to amplify-cli.

I came across this [issue](https://github.com/aws-amplify/amplify-cli/issues/4488) from that repo and you might find something helpful to the issue you're having. And looks like you've already reached out to their repo [here](https://github.com/aws-amplify/amplify-cli/issues/12056). 

Hope that helps,
John
