### ISSUE TITLE
Please update cryptography ceiling version 

### ISSUE THREAD

**Issue by jgournet** [aws/aws-cli#7699]
### Describe the feature

https://github.com/aws/aws-cli/blob/v2/pyproject.toml contains:
```    
"cryptography>=3.3.2,<38.0.5",
```

### Use Case

This version is flagged as a CVE:
https://avd.aquasec.com/nvd/2023/cve-2023-0286/

### Proposed Solution

Could you please upgrade to the fixed version:
```
"FixedVersion": "39.0.1",
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

v2

### Environment details (OS name and version, etc.)

linux

**Comment by tim-finnigan** [comment]
Hi @jgournet thanks for reporting this issue. The team is aware of this, and there is an open dependabot PR to update the version range for cryptography: https://github.com/aws/aws-cli/pull/7646. This should hopefully get merged soon, pending the resolution of some work upstream of this.

I also brought the CVE up for discussion with the team and the consensus was that the CLI is **not affected** because it does not use any of the cryptography APIs that exercise the OpenSSL interface that is impacted by the CVE.

For more control over your dependencies you can now build and install the AWS CLI from source: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-source-install.html. (You _could_ manually update this cryptography version range in source if this is a major blocker for you, although that is not recommended).

**Comment by anirbanmu** [comment]
With the linked [PR](https://github.com/aws/aws-cli/pull/7717) being merged & looking @ the [CHANGELOG](https://raw.githubusercontent.com/aws/aws-cli/v2/CHANGELOG.rst) having `* enhancement:dependency: Update cryptography requirement from <38.0.5,>=3.3.2 to >=3.3.2,<39.0.3` in v2.11.1...

Would the expectation be that `aws-cli/v2/2.11.1` would have `cryptography` version `39.0.1`? I'm asking because that's not what I'm seeing
- `aws-cli/v2/2.11.1/dist/cryptography-3.3.2.dist-info` is present and the `METADATA` file says `Version: 3.3.2`

**Comment by hwinkler** [comment]
That PR doesn't address the problem. The earliest version of `cryptography` that fixes the problem is `0:3.3.2 / 39.0.1`. The fix is to change the *floor* to `39.0.1` i.e. ` >=39.0.1,<39.0.3`.

**Comment by hwinkler** [comment]
Context: for some reason the built zipfile that AWS distributes ships `cryptography-3.3.2` which sets off alarms for everybody. I'm presuming the above version limits would fix that build.

**Comment by tim-finnigan** [comment]
Checking in again - https://github.com/aws/aws-cli/pull/7717 was merged to address the original issue, and there is a new dependabot PR (https://github.com/aws/aws-cli/pull/8030) for raising the ceiling again.

To address the recent comments above: the floors for dependency versions are rarely changed. They don't affect users who want to upgrade, and could potentially force breakages for customers who aren't impacted by a CVE or have other dependency requirements. A floor would generally only gets moved up in the scenario where a required feature from the dependency is pulled in that isn't available in very old versions.
