### ISSUE TITLE
SSM get-document doesn't return documents shared by another account in the same organization

### ISSUE THREAD

**Issue by Szasza** [aws/aws-cli#7712]
### Describe the bug

SSM get-document doesn't return documents shared by another account in the same organization.

### Expected Behavior

The document details are returned.

### Current Behavior

The following error is returned:
```
An error occurred (InvalidDocument) when calling the GetDocument operation: Document with name some-document-here does not exist.
```

### Reproduction Steps

* I have an AWS Organization with two accounts
* I create an SSM document in Account 1 and share it with Account 2 named `some-document-here`
* I execute `aws ssm get-document --profile account-2-profile --name some-document-here`

### Possible Solution

Unsure where the issue lies. If it is the CLI, it needs to be fixed. If this is a shortcoming of the AWS API, it needs to be addressed there.

### CLI version used

aws-cli/1.24.8 Python/3.10.7 Linux/5.19.0-31-generic botocore/1.26.0

### Environment details (OS name and version, etc.)

Ubuntu 22.10

**Comment by Szasza** [comment]
Hi @tim-finnigan ,

Thank you for your response.

I was able to share documents between accounts using the method outlined in the AWS documentation before creating this issue, and yes, they were shared in the same region.

The documents were visible in the AWS Console, in the 'receiver' account when selecting 'Shared with me', but unfortunately the GetDocument call doesn't return them.

**Comment by tim-finnigan** [comment]
Thanks @Szasza for following up. I did notice you're using an older version of the CLI (1.24.8). The latest version of v1 is [1.27.91](https://raw.githubusercontent.com/aws/aws-cli/develop/CHANGELOG.rst). We also recommend [installing v2](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) if you are able to migrate to that. Upgrading your version of the CLI may not solve the issue but it's usually good to just rule that out. I would also double-check that you're using the correct profile in the CLI.

If you have a support plan then reaching out through [AWS Support](https://aws.amazon.com/contact-us/) is the most direct way to get assistance with this kind of issue. Otherwise we can forward API-related issues to service teams like SSM. Is there any more information you can provide for context on this issue? Adding `--debug` to your command to get the full debug logs may give more insight into the underlying issue.
