### ISSUE TITLE
`aws ectr get-login` gives `docker login` command with invalid flag

### ISSUE THREAD

**Issue by stefano-ottolenghi** [aws/aws-cli#7783]
### Describe the bug

When I run `aws ecr get-login`, the `docker login` command that comes as output has an unknown `-e` flag.

### Expected Behavior

That I get the right `docker login` command, that I can copy paste without errors.

### Current Behavior

```
stefano@stefano-XPS:~$ aws ecr get-login
docker login -u AWS -p XXX -e none https://xxx.dkr.ecr.eu-west-1.amazonaws.com
unknown shorthand flag: 'e' in -e
See 'docker login --help'.
```

### Reproduction Steps

```
stefano@stefano-XPS:~$ aws ecr get-login
docker login -u AWS -p XXX -e none https://xxx.dkr.ecr.eu-west-1.amazonaws.com
unknown shorthand flag: 'e' in -e
See 'docker login --help'.
```

```
stefano@stefano-XPS:~$ docker -v
Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.2
```

### Possible Solution

Take away the `-e None` flag from output.

### CLI version used

aws-cli/1.22.34 Python/3.10.6 Linux/5.15.0-67-generic botocore/1.23.34

### Environment details (OS name and version, etc.)

Mint 22, Docker 20.10.21

**Comment by aBurmeseDev** [comment]
Hi @stefano-ottolenghi - thanks for reaching out. 

The '-e' option has been deprecated and is removed in docker version 17.06 and newer. You must specify `--no-include-email` for docker version you're using. The default behavior is to include the '-e' flag in the 'docker login' output as mentioned here in [the docs](https://docs.aws.amazon.com/cli/latest/reference/ecr/get-login.html).

Also we recommend updating to AWS CLI version 2 since v2 offers new features/changes and there are also breaking changes between v1 vs v2. For example, this command is one of the breaking changes where `ecr get-login` was replaced with `ecr get-login-password` mentioned [here](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration-changes.html#cliv2-migration-ecr-get-login).

If you'd like to learn more about new changes in v2, please check out [this docs](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration-changes.html) and for updating to CLI v2, check out [this docs](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html).

Hope that helps,
John
