### ISSUE TITLE
Token expiration after re-login

### ISSUE THREAD

**Issue by adcanis** [aws/aws-cli#7789]
### Describe the bug

When re-logging in to an account via cli and trying to perform say `amplify push -y` error 

> The provided token has expired

is thrown. This is after running `aws sso logout`, clearing cookies and cache as mentioned in[ #7361 ](https://github.com/aws/aws-cli/issues/7361) and re-logging in. This issue was also mentioned in [#12174](https://github.com/aws-amplify/amplify-cli/issues/12174). 
It appears to only happen if the session exceeds the 8hr mark.
---
Steps taken so far:
- clear cookies at start page
- clear `.aws/sso/cache`
- clearing `.aws/config` and `.aws/credentials`
- running `aws configure sso` to re-configure sso
- run `aws sso login --profile <profile name>`
- performing any command such as `amplify push -y --profile <profile name>`

This is currently affecting 9 accounts 

### Expected Behavior

Session should be refreshed and commands should work

### Current Behavior

Token expired error and no commands work.

### Reproduction Steps

- create user in IAM identity centre
- login via start url and follow instructions under "Command line or programmatic access" using option 2
- run `aws sso login --profile <profile name>
- after confirming login success in terminal, try and perform task like `amplify push -y`

### CLI version used

aws-cli/2.11.2

### Environment details (OS name and version, etc.)

mac 13.2.1

**Comment by aBurmeseDev** [comment]
Hi @adcanis - I believe this was meant to be open in [aws-amplify/amplify-cli](https://github.com/aws-amplify/amplify-cli/issues) and I see your last activity from [existing issue](https://github.com/aws-amplify/amplify-cli/issues/12174) there. Since this's separate repo, we can't transfer this issue for you. I'm going to close this now and if you have any question regarding AWS CLI, feel free to reach out!
