### ISSUE TITLE
download is taking too long when downloading from S3 to fsx 

### ISSUE THREAD

**Issue by Iprakhar** [aws/aws-cli#7817]
### Describe the bug

I am using AWSSDK 1.11.1034.

Downloading a 600MB file  and a 2.5GB file, I am facing issue were it is taking 1.5mins  and above 10mins respectively.

TransferManager tm = new TransferManagerBuilder.standard().withS3Client(s3Client)

.withMultipartCopyPartSize(5L * 1024L * 1024L)
		        .withMultipartCopyThreshold(1L * 1024L * 1024L * 1024L)
				.withExecutorFactory(new ExecutorFactory() {
					@Override
					public ExecutorService newExecutor() {
						return Executors.newFixedThreadPool(mt);
					}
				}).build();

Download download = tm.download("BucketName","Key", file);
download.waitForCompletion();	

but using s3 cp command  in same locations the same file is gets downloaded within mins.

### Expected Behavior

It should take less than a minute.

### Current Behavior

when executing from K8 cluster and downloading from S3 to a fsx SSD Location the time taken to download 2.5GB file is 22mins.
and 600MB file is 1.5mins.

### Reproduction Steps

Execute from  a pod from K8 cluster 

### CLI version used

AWSSDK 1.11.1034

### Environment details (OS name and version, etc.)

Java 8

**Comment by tim-finnigan** [comment]
Hi @Iprakhar - I think this issue was intended for the AWS Java SDK: https://github.com/aws/aws-sdk-java/. (Also v2 of the Java SDK is recommended for new projects: https://github.com/aws/aws-sdk-java-v2).

This repository is for the AWS CLI. For any CLI-related issues please provide steps to reproduce and debug logs (with any sensitive info redacted) by adding `--debug` to your command. Thanks!
