### ISSUE TITLE
Error has occurred during file upload. The bucket does not allow ACLs

### ISSUE THREAD

**Issue by schaefergregor** [aws/aws-cli#7861]
### Describe the bug

Publishing a frontend to a Amazon CloudFront and S3 hosting is not possible with the latest amplify cli version.
The following error occurs

```
Publish started for S3AndCloudFront
× Error has occurred during file upload.
🛑 The bucket does not allow ACLs
``` 

### Expected Behavior

No manual edit of the Access control list (ACL) of my hosting bucket and turn off "Block all public access".

Frontend should be pushed with the publish command.

### Current Behavior

Error occurs
```
Publish started for S3AndCloudFront
× Error has occurred during file upload.
🛑 The bucket does not allow ACLs
``` 

### Reproduction Steps

Start some vue frontend (follow your instructions https://docs.amplify.aws/start/getting-started/setup/q/integration/vue/#set-up-frontend)

```
amplify init
amplify add hosting
```
=> Select Amazon CloudFront and S3 as hosting

```
amplify push
amplify publish
```

### Possible Solution
Edit S3 Hosting bucket 

Manual setting of:

1. Block all public access => Off
2. Edit Object Ownership => ACLs enabled
3. Edit access control list (ACL) => Everyone (public access) => READ

I'm not sure if this workaround is safe but it works

### CLI version used

11.1.0

### Environment details (OS name and version, etc.)

Windows 11 22H2

**Comment by aBurmeseDev** [comment]
Hi @schaefergregor - thanks for reaching out.

I believe this issue is meant for [AWS Amplify](https://github.com/aws-amplify/amplify-cli) rather than AWS CLI. 
Upon investigation, I found this [similar issue](https://github.com/aws-amplify/amplify-cli/issues/12503) on their repo and the fix was to enable ACL permissions on your hosting bucket via AWS Console. Please refer to that issue for more details.

Hope that helps,
John

**Comment by schaefergregor** [comment]
Hi @aBurmeseDev , oh damn sry. Yes it is the the AWS Amplify CLI, sry for that.
