### ISSUE TITLE
--query JMESPATH filtering is working backwards

### ISSUE THREAD

**Issue by ADUDevEx** [aws/aws-cli#7873]
### Describe the bug

Trying to filter EC2 Instances with only a specific InstanceLifecycle type I stumbled upon what seems to be a BUG, the filtering is working backwards.

### Expected Behavior

I expect the JMESPATH filtering to be working as expected.
The query with =='spot' should return the instances that actually are on Lifecycle 'spot' and vice versa.

### Current Behavior

```bash
# Trying to output instances that are spot (=='spot')
# Outputs instances that have no Lifecycle
user@: ~ $ aws ec2 describe-instances --query 'Reservations[].Instances[?InstanceLifecycle=='spot'].[InstanceLifecycle]' --output text
None
None
user@: ~ $ aws ec2 describe-instances --query 'Reservations[].Instances[?InstanceLifecycle!='spot'].[InstanceLifecycle]' --output text
# Trying to output instances that are not spot (!='spot)
# Outputs instances that are on spot Lifecycle
spot
spot
```
```bash
user@: ~ $ aws --version
aws-cli/2.11.17 Python/3.11.3 Darwin/21.6.0 source/arm64 prompt/off
```

### Reproduction Steps

Have an AWS Account with at least 2 EC2 instances, one being on a 'spot' lifecycle, the other one on 'none' lifecycle.

```bash
brew install aws
# Following should output 'spot'
aws ec2 describe-instances --query 'Reservations[].Instances[?InstanceLifecycle=='spot'].[InstanceLifecycle]' --output text
# Following should output 'none'
aws ec2 describe-instances --query 'Reservations[].Instances[?InstanceLifecycle!='spot'].[InstanceLifecycle]' --output text

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CLI version used

aws-cli/2.11.17 Python/3.11.3 Darwin/21.6.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

macOS Monterey v12.5 -- GNU bash, version 3.2.57

**Comment by tim-finnigan** [comment]
Hi @ADUDevEx thanks for reaching out. I think the issue here is with the quotes in your command. You have single quotes around both the query as well as `spot`. If you use double quotes on the outside of the expression like this then it should solve the issue:
```
aws ec2 describe-instances --query "Reservations[].Instances[?InstanceLifecycle=='spot'].[InstanceLifecycle]" --output text
```
Can you confirm on your end? Also in the [describe-instances](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/describe-instances.html) documentation it appears that `InstanceLifecycleType` can either be `spot` or `scheduled`, otherwise it is not returned in the response.

**Comment by ADUDevEx** [comment]
Hello @tim-finnigan, thank you for the quick response. I can confirm the issue was with the quotes in my command.

Thanks again.
