### ISSUE TITLE
Error while downloading public data from ncbi 

### ISSUE THREAD

**Issue by hemantgujar** [aws/aws-cli#7890]
### Describe the issue

According to the website bucket s3://sra-pub-run-odp/ is publicly accessible. 

However, I am having some issues downloading data. 
$ aws s3 cp s3://sra-pub-run-odp/sra/SRRxxxxx s3://xxx/fastq/ --no-sign-request --recursive
copy failed: s3://sra-pub-run-odp/sra/SRRxxxx/SRRxxxx to s3://xxxxdata/fastq/SRRxxxx An error occurred (AccessDenied) when calling the CreateMultipartUpload operation: Anonymous users cannot initiate multipart uploads.  Please authenticate.

### Links

https://www.ncbi.nlm.nih.gov/sra/docs/sra-aws-download/

**Comment by tim-finnigan** [comment]
Hi @hemantgujar thanks for reaching out. It looks like the issue here isn't with downloading the files but with trying to upload them to the S3 bucket `s3://xxx/fastq/`. First I would confirm that you have correctly [configured](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html) your CLI profile. Then I'd make sure that you have the necessary S3 permissions and bucket policies. Here is a troubleshooting guide with more information: https://repost.aws/knowledge-center/s3-troubleshoot-403. Please let us know if you have any follow up questions.

**Comment by hemantgujar** [comment]
Hi @tim-finnigan

Thank you for your response. I am able to download or upload objects from EC2 to S3 or local storage to S3. But the problem comes when uploading sra files from s3 ncbi bucket to my s3 bucket. 
I had made appropriate change in my s3 bucket policy 

"Resource": [
"arn:aws:s3:::mybucket", 
"arn:aws:s3:::sra-pub-run-odp/sra/*"
]

When i try to save this I get notification 

Unknown Error
An unexpected error occurred.
API response
Policy has invalid resource

**Comment by tim-finnigan** [comment]
Hi @hemantgujar thanks for following up, I think the issue here is that you are trying to set a policy on a bucket resource that is not in your account ("arn:aws:s3:::sra-pub-run-odp/sra/*"). Also [this page](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-quickstart.html) on getting started with the AWS CLI has more info that could help with your original authentication issue. And [this documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_policy-validator.html) on validating IAM policies may also be a helpful reference. If you add `--debug` to the AWS CLI command you're running then it should provide more insight into what the issue is  Please let us know if you had any other questions.
