### ISSUE TITLE
UpdateCertificateOptions command is not permitted for imported certificates

### ISSUE THREAD

**Issue by kerens-orca** [aws/aws-cli#7895]
### Describe the issue

Following https://docs.aws.amazon.com/cli/latest/reference/acm/update-certificate-options.html 
When trying to enable transparency logging on an **imported** certificate via the AWS CLI returns the following error: "The UpdateCertificateOptions command is not permitted for imported certificates".

Can you please advise? can you please update this in your documentation? 
How it's possible to enable transparency logging for IMPORTED certificates?

### Links

https://docs.aws.amazon.com/cli/latest/reference/acm/update-certificate-options.html

**Comment by aBurmeseDev** [comment]
Hi @kerens-orca - thanks for reaching out. I understand that you're trying to enable transparency logging for imported certificates and running into the error mentioned. Can you share the CLI command that you ran with the parameters used for me to reproduce the error? I'm also reaching out to the service team ACM regarding this to see if that's intended and if so, what's the other method you can use to enable the logging.

If you could share the logs without any sensitive info by adding `--debug` to the command, that would also be very insightful to find out the root cause.

Best,
John
