### ISSUE TITLE
add support for waiting for instance refresh to complete

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cli#7929]
### Describe the feature

We can start an instance refresh via [`aws autoscaling start-instance-refresh`](https://docs.aws.amazon.com/cli/latest/reference/autoscaling/start-instance-refresh.html). However, there is no `wait` command, so the only way to wait for the refresh to finish is to manually poll via [`aws autoscaling describe-instance-refreshes`](https://docs.aws.amazon.com/cli/latest/reference/autoscaling/describe-instance-refreshes.html). Please add a new command `aws autoscaling wait instance-refresh-completed` or similar.

### Use Case

We want to start an instance refresh and wait for it to finish.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

1.27.142

### Environment details (OS name and version, etc.)

Alpine 3.17

**Comment by tim-finnigan** [comment]
Hi @rittneje thanks for the feature request. Waiters must be implemented by service teams, as they are used across AWS SDKs in addition to the AWS CLI. I reached out to the AutoScaling team a few months ago with the request to add waiters: https://github.com/aws/aws-sdk/issues/419.

The AutoScaling team created a backlog item for tracking this request. I just now went ahead and added your use case for a InstanceRefreshComplete waiter. 

At this point it is up to that service team to prioritize adding the waiters. If more customers reach out with use cases then it may help with increasing the priority. We recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) for direct correspondence if you have a support plan. Feel free to check back in the future for updates, but I'm going to go ahead and close this issue since it has already been escalated to the appropriate team. Please let us know if you had any follow up questions.
