### ISSUE TITLE
Failed to build on latest Python version (bump PyInstaller)

### ISSUE THREAD

**Issue by peterdeme** [aws/aws-cli#7958]
### Describe the bug

The aws-cli fails to build on the latest Python versions (3.11.4 and 3.12 beta) due to [a bug](https://github.com/pyinstaller/pyinstaller/issues/7692):

```
  > [4/5] RUN unzip /aws/dist/awscli-exe.zip &&     ./aws/install --bin-dir /aws-cli-bin:
#7 4.141 [1] Module object for pyimod02_importers is NULL!
#7 4.141 Traceback (most recent call last):
#7 4.141   File "PyInstaller/loader/pyimod02_importers.py", line 22, in <module>
#7 4.141   File "pathlib.py", line 14, in <module>
#7 4.141   File "urllib/parse.py", line 40, in <module>
#7 4.141 ModuleNotFoundError: No module named 'ipaddress'
#7 4.142 Traceback (most recent call last):
#7 4.142   File "PyInstaller/loader/pyiboot01_bootstrap.py", line 17, in <module>
#7 4.142 ModuleNotFoundError: No module named 'pyimod02_importers'
```
([link](https://github.com/spacelift-io/aws-cli-alpine/actions/runs/5207578963/jobs/9395274112))

More info here: https://github.com/pyinstaller/pyinstaller/issues/7692

Please bump PyInstaller to 5.12.0 to fix this issue. 🙏 

### Expected Behavior

It should build fine.

### Current Behavior

Fails to build.

### Reproduction Steps

Attempt to build with Py 3.11.4:

```dockerfile
FROM python:3.11-alpine3.18

RUN apk add --no-cache git \
        unzip \
        groff \
        build-base \
        libffi-dev \
        cmake

RUN mkdir /aws && \
    git clone --single-branch --depth 1 -b 2.11.26 https://github.com/aws/aws-cli.git /aws && \
    cd /aws && \
    python -m venv venv && \
    . venv/bin/activate && \
    ./scripts/installers/make-exe

RUN unzip /aws/dist/awscli-exe.zip && \
    ./aws/install --bin-dir /aws-cli-bin && \
    /aws-cli-bin/aws --version

CMD ["/bin/sh"]
```

Then `docker build -t reproduceissue`

### Possible Solution

Bump PyInstaller to 5.12.0

### CLI version used

2.11.26

### Environment details (OS name and version, etc.)

alpine:3.18

**Comment by speller** [comment]
I'm facing the same issue.

**Comment by speller** [comment]
As a workaround, I've added the following commands right after cloning:

```bash
sed -i'' 's/PyInstaller.*/PyInstaller==5.12.0/g' requirements-build.txt
sed -i'' 's/PyInstaller.*/PyInstaller==5.12.0/g' requirements/portable-exe-extras.txt
```

**Comment by peterdeme** [comment]
The fix got merged, let's see if it helped 👀 I'm closing this issue as soon as the new version is released and I can confirm it.

**Comment by kyleknap** [comment]
Yeah that PR should fix it; the most recent GitHub actions runs were running on Python 3.11.4 which were failing before this PR was merged and those runs are now passing.

One thing that I would like to note is that if you are trying to build CLI v2 from source, I'd recommend using the source distribution instead of the `make-exe` script: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-source-install.html. The `configure`, `make`, `make install` flow is also usable directly from the GitHub repository as well. The main reason I'm suggesting it is that the `make-exe` script is not a public interface that the team supports and it is likely to be removed in a future version of the CLI. However, the source distribution is publicly supported and does effectively the same logic as the `make-exe` script. So it should be straightforward to swap in.

**Comment by peterdeme** [comment]
@kyleknap thanks for the tip!

**Comment by peterdeme** [comment]
Looks good!

**Comment by iyadal** [comment]
@peterdeme In case you haven't seen it yet, There is even an alpine example in the AWS doc mentioned by @kyleknap 
https://docs.aws.amazon.com/cli/latest/userguide/getting-started-source-install.html#source-getting-started-install-workflows-alpine
