### ISSUE TITLE
SerDe target for AppSpec

### ISSUE THREAD

**Issue by quinn** [aws/aws-cli#7975]
### Describe the feature

The API only specifies a type for the string value of the appspec:

https://docs.aws.amazon.com/codedeploy/latest/APIReference/API_AppSpecContent.html

### Use Case

I want to manipulate a field value of the appspec I have. I will have to create my own struct rather than a struct provided by the API to unmarshal into. 

### Proposed Solution

Create a data type in the API spec

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

N/A

### Environment details (OS name and version, etc.)

N/A

**Comment by tim-finnigan** [comment]
Hi @quinn thanks for the feature request. We can forward this to the CodeDeploy team for consideration, as they own the [AppSpecContent](https://docs.aws.amazon.com/codedeploy/latest/APIReference/API_AppSpecContent.html) API. (We recommend reaching out directly through [AWS Support](https://aws.amazon.com/contact-us/) if you have a support plan, otherwise we are happy to route your request.)

Could you provide any more details on your use case and why the current behavior is not sufficient?
