### ISSUE TITLE
aws ecr get-login-password does not work on Centos Stream Release 9

### ISSUE THREAD

**Issue by focalsolution** [aws/aws-cli#8027]
### Describe the bug

Problem: Cannot run `aws ecr get-login-password` command

When I run the command `aws ecr get-login-password` on Centos Stream Release 9. It fails at this step after 3 retries.

```
2023-07-09 20:12:03,081 - MainThread - botocore.httpsession - DEBUG - Certificate path: /usr/local/aws-cli/v2/2.11.27/dist/awscli/botocore/cacert.pem
2023-07-09 20:12:03,082 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): api.ecr.ap-southeast-1.amazonaws.com:443
2023-07-09 20:13:03,259 - MainThread - botocore.hooks - DEBUG - Event needs-retry.ecr.GetAuthorizationToken: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x7ff8091d04d0>>
2023-07-09 20:13:03,259 - MainThread - botocore.retries.standard - DEBUG - Max attempts of 3 reached.
2023-07-09 20:13:03,259 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2023-07-09 20:13:03,259 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
```

### Expected Behavior

`aws ecr get-login-password` can run correctly run return with password

### Current Behavior

It stop after retrying for 3 times.

### Reproduction Steps

1. Install aws cli via 
```
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install

```

2. Run `aws ecr get-login-password` on Centos Stream Release 9

### Possible Solution

I suspect that aws ecr api server might not response to TLS 1.3

### Additional Information/Context

I tried to run `curl` and found that the server does not respond to TLS negotiation.

```
curl -vvv https://api.ecr.ap-southeast-1.amazonaws.com
*   Trying 13.251.117.186:443...
* Connected to api.ecr.ap-southeast-1.amazonaws.com (13.251.117.186) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):

<Stop at this point>
```

### CLI version used

aws-cli/2.11.27 Python/3.11.3 Linux/5.14.0-316.el9.x86_64 exe/x86_64.centos.9 prompt/of

### Environment details (OS name and version, etc.)

Centos Stream Release 9

**Comment by amberkushwaha** [comment]
forwarded the given creation and coded anti-logs to the respective team.

**Comment by aBurmeseDev** [comment]
Hi @focalsolution - thanks for reaching out. 

I attempted to reproduce this behavior with the steps provided but was unable to. Upon investigation with the partial debug output provided, the culprit might be due to the incorrect credentials. How are the credentials configured? I would recommend running `aws configure` to reconfigure your credentials such as Access Key ID, Secret Access Key and Region. Here's [documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html) on how to set and configure credentials, for your reference.

- Are you able to run any other AWS CLI command at all?
- If you could provided full debug logs, that would give us more insight into finding the cause of the issue. You could get the logs by adding `--debug` to CLI command.

Hope that helps!

**Comment by focalsolution** [comment]
I still face this problem but now I dig further down by capturing the network level and suspect that it is because TLS version 1.0 is used when using the `aws ecr get-login-password` command.

Do you have way specify TLS version on the command?
