### ISSUE TITLE
No strict way to get bucket region via aws-cli, head-bucket output is empty

### ISSUE THREAD

**Issue by ei-grad** [aws/aws-cli#8068]
### Describe the bug

There is no strict way to get bucket region via aws-cli, `aws s3api head-bucket` output is empty. It is a critical UX issue because, in a proved fact, it leads to misconfigurations causing security implications, for example, confused developers of terraform-provider-aws made it to require excessive permissions from all terraform-provider-aws users using s3 bucket data-source - https://github.com/hashicorp/terraform-provider-aws/issues/15148. This is because it is not clear that bucket existence and location could be checked/retrieved via HeadBucket call, for which the `aws s3api head-bucket` can be considered as the main official frontend, which misleadingly outputs nothing and looks like a useless command. Even the `aws-cli` developers are confused and suggest to use an improper solutions (use the GetBucketLocation call (which is doing the wrong thing and is left for compatibility) for this trivial task.

### Expected Behavior

There should be an easy, clear and documented way to get the bucket region from aws s3api head-bucket call.

### Current Behavior

Currently, the only way to get s3 bucket region is to look for the response headers using the --debug flag.

### Reproduction Steps

1. See that this command provides empty output:
```
aws s3api head-bucket --bucket commoncrawl
```

2. Try to find how to get s3 bucket region.

### Possible Solution

* Implement similar hack as in #244 making s3api head-bucket command return the response headers
* Implement new s3 command for this #8063
* Add new feature to make the `--query` flag to be able to access response headers (or add a similar flag like --query-headers), and add example in docs how to use it to get bucket region.

### CLI version used

aws-cli/2.13.1

### Environment details (OS name and version, etc.)

Python/3.11.3 Linux/6.4.5-arch1-1

**Comment by tim-finnigan** [comment]
Thanks @ei-grad for reaching out again. By design the CLI does not return response metadata, but you could use an SDK like Boto3:
```python3
import boto3
client = boto3.client('s3')
response = client.head_bucket(Bucket='test-bucket')
print(response['ResponseMetadata']['HTTPHeaders']['x-amz-bucket-region'])
```
Alternatively you could also parse the response from the debug logs using:
`aws s3api head-bucket --bucket test-bucket-98103 --debug 2>&1 | grep 'x-amz-bucket-region'`

As mentioned in https://github.com/aws/aws-cli/issues/8063, the `aws s3api head-bucket` command maps to the S3 [HeadBucketAPI](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadBucket.html). The S3 [HeadObject API](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html#API_HeadObject_ResponseElements) returns response elements (in addition to ResponseMetadata) which are returned via the CLI. We can reach out to the S3 team to request that they make these API responses consistent, although API responses generally aren't changed due to the need to maintain backwards compatibility. Alternatively we could request that they release an official GetBucketRegion API.

I think what you suggested here is interesting:
>Add new feature to make the `--query` flag to be able to access response headers (or add a similar flag like --query-headers), and add example in docs how to use it to get bucket region.

Maybe this feature request could be updated to be something like 'Add a `--query-headers` flag' for use cases like this, which might also apply to other services/commands. What do you think?

**Comment by tim-finnigan** [comment]
Thanks @ei-grad for reaching out again. By design the CLI does not return response metadata, but you could use an SDK like Boto3:
```python3
import boto3
client = boto3.client('s3')
response = client.head_bucket(Bucket='test-bucket')
print(response['ResponseMetadata']['HTTPHeaders']['x-amz-bucket-region'])
```
Alternatively you could also parse the response from the debug logs using:
`aws s3api head-bucket --bucket test-bucket --debug 2>&1 | grep 'x-amz-bucket-region'`

As mentioned in https://github.com/aws/aws-cli/issues/8063, the `aws s3api head-bucket` command maps to the S3 [HeadBucketAPI](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadBucket.html). The S3 [HeadObject API](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html#API_HeadObject_ResponseElements) returns response elements (in addition to ResponseMetadata) which are returned via the CLI. We can reach out to the S3 team to request that they make these API responses consistent, although API responses generally aren't changed due to the need to maintain backwards compatibility. Alternatively we could request that they release an official GetBucketRegion API.

I think what you suggested here is interesting:
>Add new feature to make the `--query` flag to be able to access response headers (or add a similar flag like --query-headers), and add example in docs how to use it to get bucket region.

Maybe this feature request could be updated to be something like 'Add a `--query-headers` flag' for use cases like this, which might also apply to other services/commands. What do you think?
