### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by umutacar** [aws/aws-cli#8108]
### Describe the issue

We are having difficulties in determining a set of consistent dependencies between these packages
1) awsebcli
2) awscli
3) boto3
4) botocore

on a regular basis, we spend many hours hunting down a set of consistent versions that would install (using pip).  this has been a persistent problem for us.  we (and we expect the developer community as a whole) would appreciate if AWS could simplify the management of these packages.

### Additional Information/Context

this occurs in the context of a web app being deployed with beanstalk

### CLI version used

awscli==1.27.158

### Environment details (OS name and version, etc.)

Mac + windows

**Comment by tim-finnigan** [comment]
Hi @umutacar thanks for reaching out. This issue is probably better suited for the [aws-elastic-beanstalk-cli](https://github.com/aws/aws-elastic-beanstalk-cli/issues) repository. It looks like there have been [several issues](https://github.com/aws/aws-elastic-beanstalk-cli/issues?q=is%3Aissue+is%3Aclosed+botocore+version+) in the past related to the Botocore versions used, and that is something the ElasticBeanstalk team would need to address. We have reached out internally to that team to bring this issue to their attention. 

In the meantime you could create separate virtual environments for development if the dependency issues are blocking you. Also we recommend using v2 of the AWS CLI if possible (installation instructions [documented here](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html).)

**Comment by umutacar** [comment]
Thank you for this feedback.  We well move on to  version 2 of the CLI and contact EB CLI.
