### ISSUE TITLE
lambda invoke --payload documentation is not up to date.

### ISSUE THREAD

**Issue by thenger** [aws/aws-cli#8132]
### Describe the issue

Hello
Documentation for v1 and v2 are the same but behavior is different.

## versions
```bash
aws --version
#aws-cli/2.13.12 Python/3.11.4 Linux/5.15.90.1-microsoft-standard-WSL2 exe/x86_64.debian.12 prompt/off
```

so the v2 doc says:

> --payload (blob)

>> The JSON that you want to provide to your Lambda function as input.
>> You can enter the JSON directly. For example, --payload '{ "key": "value" }' . You can also specify a file path. For example, --payload file://payload.json .

It appears that we need to give a base64'd json:
```
# aws lambda invoke --function-name "test-lambda" --payload "$(echo '{"test":"yes"}' |base64)" file_out --log-type Tail --query 'LogResult' --output text --profile=mfa-coo --region=eu-west-1 |base64 -d
START RequestId: 071764e6-0b4d-435e-aa93-dd8f0fa22682 Version: $LATEST
END RequestId: 071764e6-0b4d-435e-aa93-dd8f0fa22682
REPORT RequestId: 071764e6-0b4d-435e-aa93-dd8f0fa22682  Duration: 283.95 ms     Billed Duration: 284 ms Memory Size: 128 MB     Max Memory Used: 90 MB
```

when I give the json directly:
```
# aws lambda invoke --function-name "test-lambda" --payload '{"test":"yes"}' file_out --log-type Tail --query 'LogResult' --output text --profile=mfa-coo --region=eu-west-1

Invalid base64: "{"test":"yes"}"
```

This output changed not a long ago. because when i was giving the json string I got :
```
An error occurred (InvalidRequestContentException) when calling the Invoke operation: Could not parse request body into json: Could not parse payload into json: Unexpected character ('~' (code 126)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
at [Source: (byte[])"~��y�{����"; line: 1, column: 2]
```

still submitting this issue for awareness

hth

### Links

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/invoke.html

**Comment by tim-finnigan** [comment]
Hi @thenger thanks for reaching out. In v2 of the AWS CLI, binary parameters are passed as base64-encoded strings by default. (This is noted in the [migration changes](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration-changes.html) documentation.) 

You can use the `--cli-binary-format` parameter to preserve compatibility with the v1 behavior. Here is the [example](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/invoke.html) documented for the `aws lambda invoke` command:
```
aws lambda invoke \
    --cli-binary-format raw-in-base64-out \
    --function-name my-function \
    --cli-binary-format raw-in-base64-out \
    --payload '{ "name": "Bob" }' \
    response.json
```

The `--cli-binary-format` is documented across v2 commands. The documentation otherwise generally maps to the [service API documentation](https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html). The AWS CLI team cannot make changes to that wording but you can send feedback directly via the [Provide feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=Lambda&topic_url=http://docs.aws.amazon.com/en_us/lambda/latest/dg/API_Invoke.html) links at the bottom of the API documentation pages.

**Comment by MaerF0x0** [comment]
ChatGPT says

```bash
# Encode the payload to base64
payload_base64=$(echo -n '{"id":"123", "topic":"PizzaCats"}' | base64)

# Invoke the Lambda function with the base64-encoded payload
aws lambda invoke \
  --function-name YourFunctionName \
  --payload "$payload_base64" \
  output.txt
```

**Comment by thenger** [comment]
@tim-finnigan Thank you for the pointers
sorry for the time loss

**Comment by tim-finnigan** [comment]
No worries at all, thanks for following up. I hope that helps resolve the issue you were seeing. If you're still running into an issue please share your debug logs (with sensitive info redacted) by adding `--debug` to the command for us to investigate further. Otherwise I'll go ahead and close this issue as resolved.
