### ISSUE TITLE
SSL validation failed when creating Lambda layer

### ISSUE THREAD

**Issue by jacksonisrael9** [aws/aws-cli#8138]
### Describe the bug

Verified account is logged in through AWS CLI; however, my attempt to upload a layer zip file fails. The zip file is 83mb, which doesn't exceed the 250mb size limit.

### Expected Behavior

JSON response confirming creation of the Lambda layer

### Current Behavior

```SSL validation failed for https://lambda.us-east-2.amazonaws.com/2018-10-31/layers/layer-headless_chrome-v0.2-beta.0/versions EOF occurred in violation of protocol (_ssl.c:2423)```

### Reproduction Steps

```aws lambda publish-layer-version --layer-name layer-headless_chrome-v0.2-beta.0 --zip-file fileb://layer-headless_chrome-v0.2-beta.0.zip --compatible-runtimes "python3.8"```

### CLI version used

2.13.13

### Environment details (OS name and version, etc.)

macOS Monterey 12.4

**Comment by tim-finnigan** [comment]
Hi @jacksonisrael9 thanks for reaching out. The `SSL validation failed...` is a commonly reported error and is often caused by certificate issues. [Here is a section](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-troubleshooting.html#tshoot-certificate-verify-failed) in the AWS CLI troubleshooting guide with more information. You could refer to related issues like https://github.com/aws/aws-cli/issues/6509 for guidance as well.

I should also point out in the Lambda [troubleshooting guide](https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-deployment.html) it notes:
>When you upload a deployment package or layer archive directly to Lambda, the size of the ZIP file is limited to 50 MB. To upload a larger file, store it in Amazon S3 and use the S3Bucket and S3Key parameters.

**Comment by mpansuja95** [comment]
Hi @jacksonisrael9 

I'm also facing the same issue. Were you able to resolve it?

**Comment by arthireddyannad** [comment]
@mpansuja95  @jacksonisrael9  I have the same error. I tried all possible ways to trouble shoot which include python version, zip folder content is 56.72mb, importing ssl in python 3.11, upgrading aws cli versions, region, however I am unable to publish a layer through CLI. Can some one help me resolve this error?
