### ISSUE TITLE
put-bucket-notification error message is non-descriptive

### ISSUE THREAD

**Issue by nhenjes** [aws/aws-cli#8162]
### Describe the bug

When running `aws s3api put-bucket-notification` in CLI or adding a notification in the UI and running into an error, all that is presented to the user is `Unable to validate the following destination configurations`. This indicates an error, but not what the error is.

### Expected Behavior

Using the `--debug` flag in CLI, I was able to determine the real cause of the issue was `Permissions on the destination queue do not allow S3 to publish notifications from this bucket`. 

### Current Behavior

The only context given for the error is `Unable to validate the following destination configurations`

### Reproduction Steps

When running `aws s3api put-bucket-notification` in CLI or adding a notification in the UI and running into an error, all that is presented to the user is `Unable to validate the following destination configurations`. This indicates an error, but not what the error is.

Add a notification to a bucket for an sqs queue without permissions for the bucket to write to the queue

### Possible Solution

It would be more helpful to display the actual error to help users understand why the request is wrong without having to use debug. This would also greatly help UI experience since UI doesn't have a debug option and someone would have no real way of knowing what exactly the problem is

### Additional Information/Context

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>
    InvalidArgument
  </Code>
  <Message>
    Unable to validate the following destination configurations
  </Message>
  <ArgumentName1>
    arn:aws:sqs:<region>:<account-number>:<sqs-queue-name>
  </ArgumentName1>
  <ArgumentValue1>
    Permissions on the destination queue do not allow S3 to publish notifications from this bucket
  </ArgumentValue1>
  <RequestId>
    <removed>
  </RequestId>
  <HostId>
    <removed>
  </HostId>
</Error>
```

### CLI version used

2.13.1

### Environment details (OS name and version, etc.)

MacOS 13

**Comment by tim-finnigan** [comment]
Hi @nhenjes thanks for reaching out. It looks like the command you're referring to is [put-bucket-notification-configuration](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/put-bucket-notification-configuration.html). The documentation does note:
>By default, only the bucket owner can configure notifications on a bucket. However, bucket owners can use a bucket policy to grant permission to other users to set this configuration with the required `s3:PutBucketNotification` permission.

However I also think that the error message could more clearly highlight that this is a permissions issue. 

The `put-bucket-notification-configuration` command corresponds to the [PutBucketNotificationConfiguration API](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketNotificationConfiguration.html), which is maintained by the S3 team. Therefore any requests to update the API behavior (including the error message) would need to get forwarded to them. We recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) for service API requests like this if you have a support plan. Otherwise we could forward the request on your behalf. Please let us know.
