### ISSUE TITLE
Cannot recognize credential profile name with leading empty space like [ default]

### ISSUE THREAD

**Issue by forkercat** [aws/aws-cli#8170]
### Describe the bug

Related to this issue in aws-sdk-cpp: https://github.com/aws/aws-sdk-cpp/issues/2650

aws-sdk-cpp 1.11.136 might persist profile names with leading empty space like `[ default]` and [ my-dev]`.

Then when I used the AWS CLI tool to call some AWS services it shows that the profile cannot be read.

> Unable to locate credentials. You can configure credentials by running "aws configure".

### Expected Behavior

The AWS CLI should recognize the empty space before the name and ignore the spaces.

### Current Behavior

The AWS CLI is not functioning when there are leading empty spaces.

### Reproduction Steps

You can manually test it by opening `~/.aws/credentials` and adding empty spaces before the default profile name. Then try to use the tool to interact with some AWS services like S3.

FYI, I tried it with `aws gamelift`.

```shell
aws gamelift create-game-session --location custom-location-unreal-us-west-2 --fleet-id fleet-b0032ace-04ff-4923-8502-c1a4f393e0a7 --name GameSession_1 --maximum-player-session-count 3
```

### CLI version used

2.11.18

### Environment details (OS name and version, etc.)

Python/3.11.3 Windows/10 exe/AMD64 prompt/off

**Comment by RyanFitzSimmonsAK** [comment]
Hi @forkercat, thanks for reaching out.  I'm not sure this is really a bug.  Profiles with a leading space *are* being read correctly by the CLI.  I tested this with a profile named ' testUser', and used `aws s3 ls --profile " testUser"`, which worked fine.  The issue would be specifically with the default profile, since the CLI looks for that profile name if none are specified.  As a workaround, you can still specify the profile you want to use (`--profile " default"`).  I'm not sure that changing the behavior here makes sense, since, in theory, leading empty space profile names should only be created intentionally.

**Comment by forkercat** [comment]
OK. It looks like it only happens to default profile. I think we can close it.
