### ISSUE TITLE
If AWS_PROFILE is set as an environment variable, it can't be overridden

### ISSUE THREAD

**Issue by ffMathy** [aws/aws-cli#8177]
### Describe the bug

If I set the `AWS_PROFILE` environment variable, it is always taken, even if I try to override it locally.

For instance, let's say I set `AWS_PROFILE` to be `sandbox` on my machine.

If I then write `AWS_PROFILE=production aws s3 ls` instead, I expect it to take the `production` profile. Instead, it still takes `sandbox`.

### Expected Behavior

See above.

### Current Behavior

See above.

### Reproduction Steps

See above.

### CLI version used

aws-cli/2.13.18 Python/3.11.5 Linux/5.15.49-linuxkit-pr exe/aarch64.debian.12 prompt/off

### Environment details (OS name and version, etc.)

node:18 docker container

**Comment by tim-finnigan** [comment]
Hi @ffMathy thanks for reaching out. Since you're using Docker you may just need to add the `-e` flag as [documented here](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-docker.html#cliv2-docker-share-files):

![image](https://github.com/aws/aws-cli/assets/87778557/2e80c175-87f2-4566-8fb4-be87306fd633)

Based on the AWS CLI documentation on [credential precedence](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-authentication.html#cli-chap-authentication-precedence), the `AWS_PROFILE` environment variable should take precedence outside after command line options.

**Comment by ffMathy** [comment]
But it's a dev-container where the environment variable is set in the devcontainer.json file.

**Comment by tim-finnigan** [comment]
Hi @ffMathy thanks for following up. That sounds like an issue with how variables take precedence in your environment rather than something that the AWS CLI can control. Can you use the `--profile` command line option as an alternative?

**Comment by ffMathy** [comment]
This happens with Pulumi commands. Do you think the issue comes from there instead?

**Comment by tim-finnigan** [comment]
Possibly, I'd recommend creating an issue in the Pulumi repository for more guidance: https://github.com/pulumi/pulumi/issues. This seems like a third-party or local environment issue, but to investigate a potential CLI issue we'd ask for the full reproduction steps and debug logs (with sensitive info redacted) by adding `--debug` to the command.
