### ISSUE TITLE
/.aws/config [DEFAULT] settings not being used for default configuration?

### ISSUE THREAD

**Issue by noahehall** [aws/aws-cli#8205]
### Describe the bug

lets say I have the following `~/.aws/config` 

```sh
[default]
region=us-east-1
output=yaml

[profile ABCD]
output=json

```

if I then set the profile to ABCD, my assumption is that the default region `us-east-1` would be applied.

however, if I execute: `aws configure get region` it returns an empty string instead of  `us-east-1`

### Expected Behavior

I expected settings under [DEFAULT] to applied 

### Current Behavior

config settings under [DEFAULT] are not applied to other named profiles

### Reproduction Steps

- create a [DEFAULT] profile and another profile
- set the default region to some value
- set `AWS_PROFILE=the_other_profile_name`
- execute `aws configure get region` and it returns nada

### CLI version used

aws-cli/2.13.22 Python/3.11.5 Linux/6.2.0-33-generic exe/x86_64.ubuntu.22 prompt/off

### Environment details (OS name and version, etc.)

ubuntu

**Comment by nateprewitt** [comment]
Hi @noahehall, profiles in the AWS Config file aren't additive with the default profile. As noted in the [documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html),

> The first [default] is used when you run a AWS CLI command with no profile specified.

Once you provide a profile, it uses only settings defined in that profile and ignores others. This is to allow users to unset things that may be defined in the default profile and ensure they know exactly what will be used with your command. Otherwise, unintended settings may be used with a call and have undesired outcomes.

There are some forms of profile composition noted in the documentation above, but I don't know they'll allow you to set a default region like you're trying to do. You might consider setting `AWS_REGION` or `--region` in conjunction with your profile if you need the two settings defined independently.

**Comment by noahehall** [comment]
@nateprewitt thanks for clearing that up
