### ISSUE TITLE
aws resourcegroupstaggingapi get-resources --include-compliance-details does not operate as documented

### ISSUE THREAD

**Issue by dboeke** [aws/aws-cli#8246]
### Describe the bug

resourcegroupstaggingapi get-resources does not return non-compliant resources when executed.

### Expected Behavior

I would expect from the documentation that for either of these invocations i would see resource types that have tags, that don't meet the pattern.

### Current Behavior

Running the command

```sh
aws resourcegroupstaggingapi get-resources \
  --tags-per-page 100 \
  --include-compliance-details \
  --max-items 10 \
  --tag-filters Key=foo,Values=bar
```
only shows resources that have a tag {"foo":"bar"}, it shows no non-compliant resources, even though there are tagged resources in the region that do not have {"foo":"bar"} and some resources that have {"foo":"baz"}

and 

```sh
aws resourcegroupstaggingapi get-resources \
  --tags-per-page 100 \
  --include-compliance-details \
  --exclude-compliant-resources \
  --max-items 10 \
  --tag-filters Key=foo,Values=bar
```

returns an empty result set (e.g. no resources)

### Reproduction Steps

1. Tag one resource foo=bar
2. Tag second resource foo=baz
3. run command 

```sh
aws resourcegroupstaggingapi get-resources \
  --tags-per-page 100 \
  --include-compliance-details \
  --exclude-compliant-resources \
  --max-items 10 \
  --tag-filters Key=foo,Values=bar
```

### CLI version used

aws-cli/2.13.25 Python/3.11.5 Darwin/23.0.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

MacOS Sonoma 14.0 (23A344)

**Comment by tim-finnigan** [comment]
Hi @dboeke thanks for reaching out. The [get-resources command](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/resourcegroupstaggingapi/get-resources.html) corresponds to the [GetResources API](https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/API_GetResources.html). Therefore if the results returned are not as expected, we may need to escalate the issue to the Resource Groups & Tagging team. (If you have a support plan we recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) for more direct assistance with service API issues, otherwise we can forward the issue internally on your behalf.)

Before escalating the the issue though, we probably need some more information. Could you share your debug logs (with any sensitive info redacted) by adding `--debug` to the command?

I also noticed that you're passing the `--max-items` parameter. If you exclude that, then do you see all of the expected results?
