### ISSUE TITLE
After executing awscli, the input is not displayed, and the carriage return does not wrap

### ISSUE THREAD

**Issue by amaoo** [aws/aws-cli#8247]
### Describe the bug

After executing the command that needs to turn pages, use ctrl+c to exit the command, which will result in the input not being displayed and the carriage return not being wrapped.

### Expected Behavior

Normal input

### Current Behavior

the input is not displayed, and the carriage return does not wrap

### Reproduction Steps

For example, if you execute this command, the following results will appear.
There is an (END) at the end.
use ctrl+c to exit the command, which will result in the input not being displayed and the carriage return not being wrapped.
```shell
[cloudshell-user@ip-10-4-50-169 ~]$ aws rds describe-certificates
{
    "Certificates": [
...      
    {
            "CertificateIdentifier": "rds-ca-2019",
            "CertificateType": "CA",
            "Thumbprint": "d40ddb29e3750dffa671c3140bbf5f478d1c8096",
            "ValidFrom": "2019-08-22T17:08:50+00:00",
            "ValidTill": "2024-08-22T17:08:50+00:00",
            "CertificateArn": "arn:aws:rds:ap-northeast-1::cert:rds-ca-2019",
            "CustomerOverride": false
        }
    ],
    "DefaultCertificateForNewLaunches": "rds-ca-rsa2048-g1"
}
(END)
[cloudshell-user@ip-10-4-50-169 ~]$ ^C
[cloudshell-user@ip-10-4-50-169 ~]$ [cloudshell-user@ip-10-4-50-169 ~]$ [cloudshell-user@ip-10-4-50-169 ~]$ [cloudshell-user@ip-10-4-50-169 ~]$ /home/cloudshell-user
[cloudshell-user@ip-10-4-50-169 ~]$ /home/cloudshell-user
``` 

### Possible Solution

`stty sane`
It will be normal after executing this command.

### CLI version used

aws-cli/2.13.26

### Environment details (OS name and version, etc.)

AWS CloudShell，MAC，WINDOWS，Linux

**Comment by aBurmeseDev** [comment]
Hi @amaoo - thanks for reaching out.

I'm not sure if I understand the statement "use ctrl+c to exit the command, which will result in the input not being displayed and the carriage return not being wrapped."

Can you please elaborate more on that? When I ran the command, it listed out all the certificates where you can extend the output by pressing arrow down, then I exited with ctrl+c and results are still displayed above. 

Hope to hear back.

**Comment by amaoo** [comment]
When (END) appears, typing ctrl +C exits the aws command. However, when you type Enter, there is no line feed. It is not displayed when you type any command.
The same problem occurs not only with the aws rds command, but also with other commands that output too long a line.
Only when stty sane is typed does it return to normal.
<img width="1975" alt="image" src="https://github.com/aws/aws-cli/assets/48399388/f511fe09-aeb8-4d2d-a84a-f5055366cc1a">

**Comment by aBurmeseDev** [comment]
@amaoo thanks for providing additional details. 

This's actually expected behavior when using the [default pager](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html#cli-usage-pagination-serverside) `less` in CLI v2 in AWS CloudShell. It only happens when the output is long enough to require scrolling where CLI pipes the output to a pager program like `less`. This allows you to scroll through the output and examine it before returning to the command prompt. 

The (END) indicates you've reached the end of the paged output. To exit the pager and return to the prompt, you can press `q` rather than `Ctrl + c` command. 

There are a few ways you can disable this pager, see [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html#cli-usage-pagination-clientside).

Hope that helps,
John

**Comment by amaoo** [comment]
@aBurmeseDev Thank you very much for your reply.
