### ISSUE TITLE
The aws cli command delete-stack does not delete stacks that are in DELETE_FAILED state

### ISSUE THREAD

**Issue by tanimaroy2012** [aws/aws-cli#8314]
### Describe the bug

i tried using the following commands to try and delete stacks that are in DELETE_FAILED state and then run without any error but i can still see the stack - 

aws cloudformation delete-stack --stack-name "$stackName" --retain-resources false
aws cloudformation delete-stack --stack-name "$stackName" --retain-resources true
aws cloudformation delete-stack --stack-name "$stackName"

Not sure if im missing something...

### Expected Behavior

AWS cli command delete-stack should delete stack that are in DELETE_FAILED state

### Current Behavior

AWS cli command delete-stack is running without any error but not  deleting stack that are in DELETE_FAILED state

### Reproduction Steps

use aws cloudformation delete-stack --stack-name "$stackName" cli command to delete a stack in DELETE_FAILED state

### CLI version used

aws-cli/2.13.31

### Environment details (OS name and version, etc.)

MAC and AWS CloudShell

**Comment by tim-finnigan** [comment]
Hi @tanimaroy2012 thanks for reaching out. The [delete-stack](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/delete-stack.html) documentation notes:
> `--retain-resources` (list)
>
>  For stacks in the `DELETE_FAILED` state, a list of resource logical IDs that are associated with the resources you want to retain. During deletion, CloudFormation deletes the stack but doesn’t delete the retained resources.
>
>    Retaining resources is useful when you can’t delete a resource, such as a non-empty S3 bucket, but you want to delete the stack.

Here is a article on this topic that provides more context: https://repost.aws/knowledge-center/cloudformation-stack-delete-failed. Specifically this example should help:
```
aws cloudformation delete-stack --stack-name my-stack --retain-resources myresource1 myresource2
```

>Replace **myresource1** and **myresource2** with the logical IDs of the resources that failed to delete.
>
>The CloudFormation stack tries to delete the stack again, but doesn't delete any of the resources that you selected to retain. The status of your stack changes to `DELETE_COMPLETE`.

**Comment by tanimaroy2012** [comment]
thanks for your reply @tim-finnigan , is there any way i can delete the stack without retaining the resources because i want to delete the resources as well

**Comment by tim-finnigan** [comment]
Hi @tanimaroy2012 - you will have to either manually delete the resources, or address the issues that make them unable to be deleted.

For example - if you created an S3 bucket in your stack and added objects to it, then running `delete-stack` will result in `DELETE_FAILED` because the bucket is not empty. If you empty the bucket then it should delete successfully. 

I'm not sure which resources you created or why they failed to delete, but you can run the `describe-stack-events` command (or view the Events tab in the AWS console via CloudFormation > Stacks) for more details. Please let us know if you have any follow up questions.
