### ISSUE TITLE
Filters do not work with snowball devices

### ISSUE THREAD

**Issue by dmc5179** [aws/aws-cli#8361]
### Describe the bug

When using the command:
```
aws --profile snowballEdge --region snow --endpoint https://192.168.1.30:8243 --ca-bundle /etc/pki/ca-trust/source/anchors/snow_cert.pem ec2 describe-instances --filters "Name=tag-value,Values=foo"
```

The CLI reports an error likely due to the reduced set of fields that are returned from any API query to a snowball device. The API returns valid JSON but the "filters" function inside the CLI is likely looking for fields that are assumed to be there for all AWS regions but are not there when using the "snow" region with a snowball device.

### Expected Behavior

The ec2 describe-instances task returns instances based on the filters provided with the command.

### Current Behavior

This is the error message I receive with the command listed above:
```
An error occurred (MalformedInput) when calling the DescribeInstances operation: Top level element may not be treated as a list
```

### Reproduction Steps

- Run the aws ec2 describe-instances command with the filters option against a snowball device
- Get error above

### Possible Solution

I suspect that the filters module inside the AWS CLI is performing jmespath queries against the JSON returned by the AWS snowball API without taking into account that snowball devices have a reduced API set and therefore have a reduced response set. The filter modules jmespath queries are probably looking for fields that are not there and produce an error

### CLI version used

aws-cli/2.13.38 Python/3.11.6 Linux/5.14.0-362.8.1.el9_3.x86_64 exe/x86_64.rhel.9 prompt/off

### Environment details (OS name and version, etc.)

RHEL-9.2

**Comment by tim-finnigan** [comment]
Hi @dmc5179 thanks for reaching out. The `--filters` parameter for [describe-instances](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html) is for server-side filtering. (Here is the filtering documentation for reference: https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-filter.html.)

I think we need more information in order to understand this specific issue better. Could you share your debug logs (with any sensitive info redacted) by adding `--debug` to the command?
