### ISSUE TITLE
When auto-prompt is on, aws codecommit credential-helper fails.

### ISSUE THREAD

**Issue by t-morissey** [aws/aws-cli#8370]
### Describe the bug

`aws codecommit credential-helper` command fails when auto-prompt is `on`. 

### Expected Behavior

If auto-prompt is on, the command will successfully complete.

### Current Behavior

The command fails with a warning `Warning: Input is not a terminal (fd=0).` and an error `Unknown options: protocol=https`. 

### Reproduction Steps

1. [Enable auto-prompt](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-parameters-prompting.html#cli-usage-auto-prompt-configure)
2. git config --global credential.helper '!aws codecommit credential-helper $@'
3. git config --global credential.UseHttpPath true
4. git clone https://git-codecommit.<region>.amazonaws.com/v1/repos/<repo_name>

My output:
```
$ export AWS_CLI_AUTO_PROMPT=on
$ git config --global credential.helper '!aws codecommit credential-helper $@'
$ git config --global credential.UseHttpPath true
$ git clone https://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/xxxxxxx
Cloning into 'xxxxxxx'...
Warning: Input is not a terminal (fd=0).
warning: invalid credential line: > aws codecommit credential-helper get

Unknown options: protocol=https
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Username for 'https://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/xxxxxxx':
```

### Possible Solution

I guess this error is caused by the temporary use of STDOUT to show prompt when using auto-prompt, which does not happen when `on-partial`, it might be enough to just mention that in the documentation.

### CLI version used

aws-cli/2.13.27

### Environment details (OS name and version, etc.)

Python/3.11.6 Darwin/22.6.0 exe/x86_64 prompt/off

**Comment by tim-finnigan** [comment]
Hi @t-morissey thanks for reaching out. We received another issue related to auto-prompt recently: https://github.com/aws/aws-cli/issues/8330. I think it's worth having further discussion there around how the current behavior or documentation could be improved. 

The CLI [documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html#envvars-list-aws_cli_auto_prompt) does note the following for `on-partial` mode:
>**`on-partial`** uses partial auto-prompt mode. If a command is incomplete or cannot be run due to client-side validation errors, auto-prompt is used. This mode is particular useful if you have pre-existing scripts, runbooks, or you only want to be auto-prompted for commands you are unfamiliar with rather than prompted on every command.

If you have any specific feedback on the wording there or in any part of the CLI User Guide, we recommend using the [Provide feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=AWS%20Command%20Line%20Interface&topic_url=http://docs.aws.amazon.com/en_us/cli/latest/userguide/cli-configure-envvars.html) link at the bottom of the page to send feedback.

I think the codecommit [credential-helper](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/codecommit/credential-helper/index.html) command is unique in that it is "not designed to be called directly from the AWS CLI." So maybe just that [examples](https://github.com/aws/aws-cli/blob/develop/awscli/examples/codecommit/credential-helper.rst) file could be updated to highlight the scenario you mentioned. (A PR to update the wording may be considered by I can't guarantee that.)

But since other commands may be affected, it may be better to add a section for this to the AWS CLI [Troubleshooting Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-troubleshooting.html).
