### ISSUE TITLE
Unable to generate long-living pre-signed URL

### ISSUE THREAD

**Issue by fade2black** [aws/aws-cli#8551]
### Describe the bug

I have a pdf file object in my private s3 bucket. Then I go to `Object Actions` and then`Share with a presigned URL`.
Then I choose `Hours` and enter 7 (meaning 7 hours) and it automatically copies the URL into my clipboard.
 

### Expected Behavior

To be available at least for one hour.

### Current Behavior

When I try to access the object (from browser) using the presigned URL it says that the token is expired.

### Reproduction Steps

NA

### CLI version used

aws-cli/2.13.3 Python/3.11.4

### Environment details (OS name and version, etc.)

MacOS

**Comment by RyanFitzSimmonsAK** [comment]
Hi @fade2black, thanks for reaching out.  Could you be more specific about how you're trying to access the object once you've created the URL, and how you're using AWS CLI in this process?  Thanks!

**Comment by fade2black** [comment]
@RyanFitzSimmonsAK Thank you for a quick reply. 😀
How slow you are. Your error/bugs are stupid, feedbacks takes months and years, and fixing them takes years and decades.  You'd better work on this first of all.🙄

**Comment by fade2black** [comment]
Lately I've left two comment regarding `sam build` (python + docker bug), so annoying!!! makes one sick when you work with sam. You promised to fix it, still there!!! No fixes.

**Comment by kellertk** [comment]
@fade2black, your comments in this thread are not acceptable behavior in this community. You must follow the guidelines outlined in our [Code of Conduct](https://github.com/aws/aws-cli/blob/develop/CODE_OF_CONDUCT.md) in order to participate in this repository. Please consider this your final warning on this.

You've filed this issue against the AWS CLI, but you are describing actions taken in the AWS Console (website). In order for the folks that work on the CLI to help you, you'll need to tell us how you're using the CLI. That's what we meant when we asked for reproduction steps in our issue template. If you can't reproduce this with CLI commands, we will be unable to help you here.

I tried following your reproduction steps: in a private S3 bucket, create a presigned URL for 7 hours. The URL is copied to my clipboard, and I am able to access the object using that URL. Please help us understand what's breaking for you.

**Comment by fade2black** [comment]
@kellertk 
As for the "acceptable behavior". Maybe you should start with your behavior? From how you treat users and devs in this community?  I asked a question describing details on Feb 27, and you on May 8 like "could you be more specific about how you're trying to access" as if I asked the question a couple of hours/days ago. Usually your bugs either takes years to fix or you don't fix it at all. Is it acceptable behavior?

**Comment by kellertk** [comment]
You're not wrong in that it would be better if we can respond to issues more quickly. Unfortunately, I'm not able to go back in time and answer your question on Feb 27. Your feedback on issue responsiveness has been noted, but the best we can do is try and help you right now.

Please help me help you. You've described in your report that you are unable to click through the AWS console and create a working presigned URL for an object in S3. I just tried this a few moments ago and was able to download my object without problems, even from a bucket with public access disabled. I can't seem to reproduce the behavior you're seeing, which is why we need more detail from you.

* Are you using the AWS CLI? If not, are you able to reproduce this with just [AWS CLI commands](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/presign.html)? Once you do, would you please attach the debug logs from your AWS CLI commands showing creating the URL?
* Are you signed in to AWS with a principal that has permissions on the bucket you're working with?
* What ACLs, IAM policies, or bucket policies are present on the bucket?
* Do you see the same behavior on a new, freshly-created bucket? 
* Are you seeing problems in one region or in multiple regions?
