### ISSUE TITLE
Why is colorama pinned to 0.4.5?

### ISSUE THREAD

**Issue by Lawouach** [aws/aws-cli#8571]
### Describe the issue

Currently, the colorama dependency is pinned to `colorama>=0.2.5,<0.4.5`. Is there a particular reason as this means we cannot upgrade some other packages that expect 0.4.6

### CLI version used

latest

### Environment details (OS name and version, etc.)

linux

**Comment by RyanFitzSimmonsAK** [comment]
Hi @Lawouach, thanks for your patience.  I assume you're referring specifically to the AWS CLI v1 pin, since v2 has a higher pin already.  If you're able to upgrade to CLI v2, that should allow you to use the higher colorama version.  Dependencies for v1 and v2 are tracked separately, we do have an [open PR](https://github.com/aws/aws-cli/pull/8122) for this dependency.  I've asked the team to take a look at the colorama pin the next time they review dependencies.  In the meantime, as we have a [general tracking issue](https://github.com/aws/aws-cli/issues/5943) for dependency pins, I'm going to close this as a duplicate.
