### ISSUE TITLE
aws logs tail --follow never exits

### ISSUE THREAD

**Issue by BeyondEvil** [aws/aws-cli#8576]
### Describe the bug

`aws logs tail <log_group> --log-stream-names <stream name> --follow`

Never exits even tho no more logs are coming in due to the service (Fargate Task in this case) has exited.

This means I have to quit the command using Ctrl-C and hence can't use it programatically.

### Expected Behavior

aws logs tail should time out when no more logs are coming in.

### Current Behavior

`aws logs tail <log_group> --log-stream-names <stream name> --follow`

Never exits even tho no more logs are coming in due to the service (Fargate Task in this case) has exited.

### Reproduction Steps

- Start a Fargate task
- Run the command
- Observe command not finish when task is finished

This is reproducibel on both Mac and Linux systems.

### CLI version used

aws-cli/2.13.33 Python/3.11.6 Darwin/23.2.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

macOS (M2) Sonoma 14.2.1

**Comment by julienfdev** [comment]
i'm sorry but why is it a bug ? the log group still exists, thus, the logs tail --follow does not exits.
an ECS task finishing has absolutely nothing to do with the state of your log group / stream.

If you need to do something programmatically, either trigger an SNS event when the task is finished or monitor its status inside your app

**Comment by tim-finnigan** [comment]
Thanks for reaching out and your patience here. The [tail](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/logs/tail.html) command documentation notes the following for the `--follow` parameter:
>`--follow` (boolean) Whether to continuously poll for new logs. By default, the command will exit once there are no more logs to display. To exit from this mode, use Control-C.

So if there are no more logs then I would expect the command to exit. Is this issue consistently reproducible? And outside of Fargate as well? Have you tried testing on more recent versions of the CLI? (The latest version per the [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1) is 2.15.51.)

There may be a delay in the ingestion of logs from the Fargate task to the CloudWatch Logs service. It's also possible that the log stream associated with the Fargate task is not being properly terminated or marked as complete, causing the `aws logs tail` command to continue waiting for more logs indefinitely.

If you can provide debug logs (with sensitive info redacted) by adding `--debug` to the command then that might help provide more insight into the issue. Otherwise using the [get-log-events](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/logs/get-log-events.html) command could serve as a workaround.

**Comment by BeyondEvil** [comment]
Sorry for the late response.

I'll make sure I'm on the latest version(s) and repro with the `--debug` flag.

Stay tuned.
