### ISSUE TITLE
Add dotenv output format for `aws ssm get-parameters-by-path`

### ISSUE THREAD

**Issue by stuft2** [aws/aws-cli#8599]
### Describe the feature

Add a `--dotenv` flag (or maybe an `--output dotenv` format option) to format the output of the `get-parameters-by-path` command in [dotenv format](https://www.dotenv.org/docs/security/env.html).

### Use Case

Environment variables are often stored in the SSM Parameter Store. Fetching them out of the store and formatting them in dotenv format is common but not trivial and requires either many steps or a very complicated chain of terminal commands. The dotenv format is widely adopted by tools and mainstream IDEs for configuring environment variables for developers.

### Other Information

Use [awsparams](https://pypi.org/project/awsparams/) with the `--dotenv` flag
```sh
awsparams ls /$APP/$ENV --with-decryption --dotenv
```

OR with linux native tools and the aws cli
```sh
export APP=<my-app-name>
export ENV=<my-environment-name>

aws ssm get-parameters-by-path --no-cli-pager --with-decryption --output text --query 'Parameters[].[Name,Value]' --path /$APP/$ENV | sed -e "s/\/$(echo $APP)\/$(echo $ENV)\/\(\w*\)/\U\1/g" -e "s/\t/=/g" > .env
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/2.12.6 Python/3.11.4 Darwin/23.1.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

macOS 14.1.2

**Comment by tim-finnigan** [comment]
Thanks for the feature request regarding the [get-parameters-by-path](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ssm/get-parameters-by-path.html) command. 

Here is related documentation on [AWS CLI command line options](https://docs.aws.amazon.com/cli/v1/userguide/cli-configure-options.html#cli-configure-options-list). The request to add a `--output dotenv` would likely not be considered because `--output` is a global parameter used for general formatting of outputs (json, table, text) and I don't think this use case is common or general enough to warrant a new output format.

The SSM service team owns the underlying [GetParametersByPath API](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParametersByPath.html) that is used here, so we could forward a feature request to them to provide the ability to return parameters in dotenv format.

I'll also share a utility script that I think accomplishes what you're trying to do:
```bash
#!/bin/bash

# Set the parameter path prefix
PARAMETER_PATH="/"

# Fetch parameters from the Parameter Store
PARAMETERS=$(aws ssm get-parameters-by-path --path "$PARAMETER_PATH" --recursive --with-decryption --query 'Parameters[*].[Name,Value]' --output text)

DOTENV_LINES=$(echo "$PARAMETERS" | awk -F $'\t' '{ printf "%s=%s\n", $1, $2 }')

# Write the dotenv lines to a file
echo "$DOTENV_LINES" > .env

echo "Environment variables exported to .env"
```

Also in a Boto3 script:
```python3
import boto3

# Set up AWS credentials/configurations
session = boto3.Session()
ssm_client = session.client('ssm')

# Define the parameter path prefix
parameter_path = '/'

# Fetch parameters from the Parameter Store
response = ssm_client.get_parameters_by_path(Path=parameter_path, Recursive=True, WithDecryption=True)

# Format parameters in dotenv format
dotenv_lines = []
for parameter in response['Parameters']:
    key = parameter['Name'].split('/')[-1]
    value = parameter['Value']
    dotenv_lines.append(f"{key}={value}")

# Write dotenv lines to a file
dotenv_file = '.env'
with open(dotenv_file, 'w') as f:
    f.write('\n'.join(dotenv_lines))

print(f"Environment variables exported to {dotenv_file}")
```

Hope that helps — please let us know if you'd also like us to reach out to the SSM team regarding this feature request.

**Comment by fsasieta** [comment]
@tim-finnigan in case this is the still the correct spot, I would like to support the request to forward this request to the SSM team

**Comment by tim-finnigan** [comment]
Hi @fsasieta - sure I went ahead and created a internal tracking item for the SSM team to review. I can't provide any guarantees on if or when this might be considered, but please track updates in the [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1) and [SSM blog](https://aws.amazon.com/blogs/mt/tag/aws-systems-manager/).
