### ISSUE TITLE
AWS Chatbot commands not working yet? Could not connect to the endpoint URL

### ISSUE THREAD

**Issue by jusdino** [aws/aws-cli#8658]
### Describe the bug

I'm looking at the [latest docs for the `aws chatbot` commands](https://docs.aws.amazon.com/cli/latest/reference/chatbot/) and they seem to be supported now, but even with a freshly updated cli v2 install, I can't get any of the commands to work.

### Expected Behavior

Commands like `aws chatbot describe-slack-channel-configurations`  should not error.

### Current Behavior

I tried this in a couple of regions, but they reliably error like this:
```Could not connect to the endpoint URL: "https://chatbot.us-east-1.amazonaws.com/describe-slack-channel-configurations"```

### Reproduction Steps

```
$ aws sts get-caller-identity
{
    "UserId": "AROXXXXXXXXXXXXXXXXXX:justin",
    "Account": "111122223333",
    "Arn": "arn:aws:sts::111122223333:assumed-role/AWSReservedSSO_AWSAdministratorAccess_9e203f6e4baf90df/justin"
}
$ aws chatbot describe-slack-channel-configurations

Could not connect to the endpoint URL: "https://chatbot.us-east-1.amazonaws.com/describe-slack-channel-configurations"
$ aws --version
aws-cli/2.15.42 Python/3.11.8 Darwin/23.2.0 exe/x86_64 prompt/off
```

### CLI version used

aws-cli/2.15.42 Python/3.11.8 Darwin/23.2.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

MacOS

**Comment by jusdino** [comment]
I just found a region that works:
```
$ export AWS_DEFAULT_REGION=us-east-2
$ aws chatbot describe-slack-channel-configurations
{
    "SlackChannelConfigurations": []
}
```

Is this some sort of mismatch because chatbot is a 'global' service, but you can't call other regional endpoints?

**Comment by tim-finnigan** [comment]
Thanks for reporting this issue, the service team is aware and currently in the process of updating their documentation. 

This page has since been added which highlights the supported regions: https://docs.aws.amazon.com/chatbot/latest/APIReference/Welcome.html

As noted there:
> AWS Chatbot APIs are currently available in the following Regions:
>
> - US East (Ohio)
> - US West (N. California)
> - US West (Oregon)
> - Asia Pacific (Singapore)

So in terms of region codes currently supported that is: us-east-2, us-west-1, us-west-2, ap-southeast-1.

There are still a handful of incomplete/inconsistent areas in the Chatbot documentation which they are aware of, and should be addressing in the near future. To send feedback on the documentation please use the [Provide feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=wheatley-docs&topic_url=https://docs.aws.amazon.com/en_us/chatbot/latest/APIReference/Welcome.html) at the bottom of the API documentation pages.

**Comment by jusdino** [comment]
That's interesting, since us-east-1 and us-west-1 were the two regions I was trying when I opened the ticket in the first place. For what it's worth, those region hosts had no A records when I did a DNS lookup when I opened it, but now they work for me. It's almost like there was an unreported chatbot outage or something.

**Comment by tim-finnigan** [comment]
Thanks for letting us know — the [AWS Health Dashboard](https://health.aws.amazon.com/health/status) should highlight any ongoing issues affecting service health. As mentioned the Chatbot team has updated their documentation to note the supported regions, and still has a few other places in their documentation to update. I think we can close this as their are no action items on our end, but for any other issues related to this you can let us know and we can escalate those to the Chatbot team.
