### ISSUE TITLE
aws ecr describe-image-scan-findings with no recommendations

### ISSUE THREAD

**Issue by oallauddin** [aws/aws-cli#8677]
### Describe the bug

`aws ecr describe-image-scan-findings` is not returning the recommendations that are in AWS Inspector.  

### Expected Behavior

Recommendations would match what is in AWS Inspector.  
![aws_inspector_info](https://github.com/aws/aws-cli/assets/13156842/64de0716-de24-4cf9-97a7-14d225462c77)

### Current Behavior

Recommendations always come back as None Provided for all findings.  
![aws_cli_response](https://github.com/aws/aws-cli/assets/13156842/a4f11632-5de2-4f8d-9102-9d5eac1ba2bb)

### Reproduction Steps

ECR repository in us-gov-west-1 with enhanced scanning and continuous scanning enabled.  
```
aws ecr describe-image-scan-findings --repository-name namespace/repo-name --image-id imageTag=1.0.0 | jq -rc '.imageScanFindings.enhancedFindings | .[].remediation'

{"recommendation":{"text":"None Provided"}}
{"recommendation":{"text":"None Provided"}}
{"recommendation":{"text":"None Provided"}}
{"recommendation":{"text":"None Provided"}}
```

### CLI version used

aws-cli/2.14.5 Python/3.9.16 Linux/5.15.146.1-microsoft-standard-WSL2 source/x86_64.amzn.2023 prompt/off

### Environment details (OS name and version, etc.)

Amazon Linux 2023 WSL2

**Comment by tim-finnigan** [comment]
Hi @oallauddin thanks for reaching out. The AWS CLI [describe-image-scan-findings](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecr/describe-image-scan-findings.html) involves a call to the underlying [DescribeImageScanFindings API](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_DescribeImageScanFindings.html). Therefore this issue relates to the API results rather than the CLI directly. 

In the [Response Syntax](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_DescribeImageScanFindings.html#API_DescribeImageScanFindings_ResponseSyntax) for the API it shows results for `findings` in addition to `enhancedFindings`. Do the results you're expecting show up there?

Or if there is an inconsistency between the console and API results, can you also confirm that you're using the same account for both?

**Comment by tim-finnigan** [comment]
Thanks for confirming. I think we will need to reach out to the ECR team regarding this issue, as they own the underlying APIs. Before forwarding this to them, could you just provide your debug logs (with sensitive info redacted) by adding`--debug` to the command? That could help with further investigation and understanding of the issue.

**Comment by oallauddin** [comment]
I reached out to AWS admins and they have started AWS support issue.

**Comment by oallauddin** [comment]
I am going to close this issue since it not AWS CLI related and is an issue with the API.  
For the moment it appears we will have to use inspector2 list-findings.  
AWS support is stilling looking into why the Remediation recommendation is always "None Provided". 
AWS support is reaching out to the ECR and Inspector teams.  
`aws inspector2 list-findings --filter-criteria '{"ecrImageRepositoryName":[{"comparison":"EQUALS","value":"image-namespace/image-name"}],"ecrImageTags":[{"comparison":"EQUALS","value":"1.0.0"}]}'`

The Inspector API version of the VulnerablePackage object seems to be the only way to get remediation information for a vulnerability at the moment.
Inspector API
https://docs.aws.amazon.com/inspector/v2/APIReference/API_VulnerablePackage.html
ECR API
https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_VulnerablePackage.html

Remediation object in both Inspector API and ECR API appears to always have recommendation value of "None Provided".  
Inspector API
https://docs.aws.amazon.com/inspector/v2/APIReference/API_Remediation.html
ECR API
https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_Remediation.html
