### ISSUE TITLE
Installing in relative path installs broken symlinks

### ISSUE THREAD

**Issue by timhughes** [aws/aws-cli#8799]
### Describe the bug

When installing in relative paths , the links created point to the wrong spot

### Expected Behavior

Symlinks should point to the correct location 

```
❯ ll .local/bin/aws*
lrwxrwxrwx 1 ttimhu users 52 2024-07-12 15:09 .local/bin/aws -> /home/ttimhu/.local/share/aws-cli/v2/current/bin/aws
lrwxrwxrwx 1 ttimhu users 62 2024-07-12 15:09 .local/bin/aws_completer -> /home/ttimhu/.local/share/aws-cli/v2/current/bin/aws_completer
```

### Current Behavior

```
❯ ll .local/bin/aws*
total 31456
lrwxrwxrwx 1 ttimhu users       39 2024-07-12 15:04 aws -> .local/share/aws-cli/v2/current/bin/aws
lrwxrwxrwx 1 ttimhu users       49 2024-07-12 15:04 aws_completer -> .local/share/aws-cli/v2/current/bin/aws_completer
```

### Reproduction Steps

```
cd $HOME
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
./aws/install --install-dir .local/share/aws-cli --bin-dir .local/bin
```

### Possible Solution

Adding a tilde at the front of all paths fixes it but shouldn't be required

```
./aws/install --install-dir ~/.local/share/aws-cli --bin-dir ~/.local/bin --update
```

### CLI version used

aws-cli/2.17.12

### Environment details (OS name and version, etc.)

Linux

**Comment by tim-finnigan** [comment]
Thanks for reaching out. This issue is currently being tracked in https://github.com/aws/aws-cli/issues/6852. I changed that issue title to this one as it more clearly highlights the problem. As mentioned in [this comment](https://github.com/aws/aws-cli/issues/6852#issuecomment-1092100465), the fix would be to "automatically [expand the paths](https://github.com/aws/aws-cli/blob/develop/scripts/install#L242) at runtime for the install script so they're properly stored in the aws bin file.". I will close this in order to continue tracking there, please refer to that issue for updates going forward.
