### ISSUE TITLE
Memory leak during recursive deletion of files from S3 bucket

### ISSUE THREAD

**Issue by cynepco3hahue** [aws/aws-cli#8815]
### Describe the bug

We have some buckets with big amount of files that we need to delete pro-actively(add retention policy currently out of options because of internal reasons). To do so we are running command 
```
/usr/local/bin/aws s3 rm --recursive s3://<some_bucket>/<some_folder> --only-show-errors
```
During run of command I can see that memory consumption is slowly growing until it reach the pod limit and killed by OOM mechanism.
<img width="1282" alt="Screenshot 2024-07-23 at 10 20 10" src="https://github.com/user-attachments/assets/cdac3dd5-a22b-4c67-88ab-c405ccf7a959">
Like you can from screenshot it slowly grow up to 4GiB of memory and killed by OOM and our retry mechanism trying to run command again.

### Expected Behavior

I am expecting that it will use always some limited amount of memory, the same way as sync mechanism is working.

### Current Behavior

We have a memory leak during run of command
```
/usr/local/bin/aws s3 rm --recursive s3://<some_bucket>/<some_folder> --only-show-errors
```

### Reproduction Steps

- you need some bucket with a lot of nested files ~100k will do the work, the consumption should be less, but still you should see the leak
- run command `/usr/local/bin/aws s3 rm --recursive s3://<some_bucket>/<some_folder> --only-show-errors` on the above bucket

### Possible Solution

I think we should use the same listing mechanism as under the sync command(maybe I am wrong and the problem not in list but somewhere else)

### CLI version used

1.29.85

### Environment details (OS name and version, etc.)

amazonlinux2

**Comment by tim-finnigan** [comment]
Thanks for reaching out. I saw that you're using 1.29.85 which is quite an old version. Have you tried testing on newer versions? The latest version of v1 is [1.33.31](https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst?plain=1). We also highly recommend [migrating to use v2](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html) of the CLI if possible.

Have you tried breaking down the deletion into smaller batches? For example running multiple aws [s3 rm](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/rm.html) commands targeting a smaller subset of the files rather than using `--recursive`?

Instead of using the `aws s3 rm` command, you could also try using the lower-level [aws s3api delete-objects](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/delete-objects.html) command which maps directly to the [S3 API](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html). Please let us know if that's something you've tried as well. Otherwise if you're able to share your debug logs (with any sensitive info redacted) by adding `--debug` to the command then that might help give more insight into any issues.
