### ISSUE TITLE
aws s3 prefix metadata not maintained during copy & sync

### ISSUE THREAD

**Issue by ashwallace** [aws/aws-cli#8817]
### Describe the bug

When performing aws s3 cp or aws s3 sync, metadata of objects is preserved. However i found metadata on s3 prefixes was not preserved. I imagine this is rare, but it happens (for example, AWS's own storage gateway puts metadata on prefixes)

### Expected Behavior

preserve metadata for prefixes when running `aws s3 cp` or `aws s3 sync`

### Current Behavior

metadata is not preserved on s3 prefixes when running `aws s3 cp` or `aws s3 sync`

### Reproduction Steps

```
aws s3api put-object --bucket sourcebucket --key test-prefix/ --metadata testkey=testvalue
aws s3api head-object --bucket sourcebucket --key test-prefix/ 
}
    REDACTED
    "Metadata": {
        "testkey": "testvalue"
    }
}
aws s3 cp s3://sourcebucket s3://targetbucket --recursive
aws s3api head-object --bucket targetbucket --key test-prefix/ 
:(
```

### Additional Information/Context

I am using AWS datasync as an alternative which has been tested to maintain prefix metadata, but my use cases preferences the CLI, and it would be nice for metadata expectations to be consistent.

### CLI version used

aws-cli/2.17.14 Python/3.11.9 Linux/6.1.96-102.177.amzn2023.x86_64

### Environment details (OS name and version, etc.)

Amazon Linux 2023 (AWS cloudshell)

**Comment by tim-finnigan** [comment]
Thanks for reaching out. I think we need to find out more info from S3 on this. The [PutObject API](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html) is allowing metadata to be added to a folder (prefix) but doesn't allow that to be viewed in the console (as far as I can tell), so I'm wondering if this is something that is technically possible but not recommended. I don't think this is the intended use of S3 [metadata](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html) and [prefixes](https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-prefixes.html), and so that would be why the S3 customization commands like `cp` and `sync`. We can try to get more info from S3, and in the meantime maybe you can provide more context on your use case.
