### ISSUE TITLE
Need productID, Product-code or other identifier indexed for use with ALL AMI's

### ISSUE THREAD

**Issue by thephantom922** [aws/aws-cli#8829]
### Describe the feature

Need productID, Product-code or other identifier indexed for use with ALL AMI's. 

### Use Case

To be able to use these identifiers to select the latest ami for the product code; e.g. we want to use the last image of ubuntu pro 22.04 lts with a product code of "Product Code: 6y8u38ej21s537z5n3ae8tycq" and a product ID of productId=756a488e-8d47-45c0-b2c9-3c4001e3b32a

however, these are not attributes of the output for only some marketplace images, this should be for ALL images since it will streamline the IAC required to use these.

when running aws ec2 describe-images --image-id {_insert_image_ID_} 

e.g. aws ec2 describe-images --image-id ami-0df0d8e5c758ac044

**Running this returns the ProductCodes attibute:**
{
    "Images": [
        {
            "Architecture": "arm64",
            "CreationDate": "2024-04-11T23:19:16.000Z",
            "ImageId": "ami-0df0d8e5c758ac044",
            "ImageLocation": "aws-marketplace/ubuntu-minimal/images/hvm-ssd/ubuntu-jammy-22.04-arm64-minimal-20240410-ad51111f-e245-404d-8492-515abfd1e565",
            "ImageType": "machine",
            "Public": true,
            "OwnerId": "679593333241",
            "PlatformDetails": "Linux/UNIX",
            "UsageOperation": "RunInstances",
            **"ProductCodes": [
                {
                    "ProductCodeId": "a9dyb1zo859c2vncy7wo8jasl",
                    "ProductCodeType": "marketplace"**
                }

**Whereas running aws ec2 describe-images --image-id ami-01ed44191042f130f, for example returns no ProductCode
![amazonOwnednoProductCodes](https://github.com/user-attachments/assets/ff08c106-4da4-48af-aa0e-83e7188b50b0)
![marketplaceProductCodes](https://github.com/user-attachments/assets/9d200c4d-f923-4fa8-ae8d-ecc5c9a77308)
![noProductCodes](https://github.com/user-attachments/assets/a24fcf3b-ced7-4a32-9f45-497ba1c90f76)
![ProductCodes](https://github.com/user-attachments/assets/16d192a5-258a-4260-a92d-533546332ab2)
s:**
{
    "Images": [
        {
            "Architecture": "x86_64",
            "CreationDate": "2024-06-06T02:45:44.000Z",
            "ImageId": "ami-01ed44191042f130f",
            "ImageLocation": "amazon/ubuntu-pro-server/images/hvm-ssd/ubuntu-jammy-22.04-amd64-pro-server-20240606",
            "ImageType": "machine",
            "Public": true,
            "OwnerId": "099720109477",
            "PlatformDetails": "Ubuntu Pro Linux",
            "UsageOperation": "RunInstances:0g00",
            "State": "available",
            "BlockDeviceMappings": [
                {
                    "DeviceName": "/dev/sda1",
                    "Ebs": {
                        "DeleteOnTermination": true,
                        "SnapshotId": "snap-0f4215c628e85fda9",
                        "VolumeSize": 8,
                        "VolumeType": "gp2",
                        "Encrypted": false

### Proposed Solution

make these attributes part of the output for all AMI's:
ProductID
Product-Code
ProductCodeId

### Other Information

owner is Amazon (returns NULL for product codes):
aws ec2 describe-images --owners 099720109477 --filters "Name=name,Values=*22.04*" | jq -r '.Images[] | "\(.OwnerId)\t\(.ImageId)\t\(.ProductCodes)"'

owner is AWS-marketplace (returns product codes):
aws ec2 describe-images --owners aws-marketplace --filters "Name=name,Values=*22.04*" | jq -r '.Images[] | "\(.OwnerId)\t\(.ImageId)\t\(.ProductCodes)"'

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

lastest/cloudshell

### Environment details (OS name and version, etc.)

cloudshell

**Comment by tim-finnigan** [comment]
Thanks for reaching out. The [describe-images](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/describe-images.html) command makes a request to the [DescribeImages API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImages.html). The response you're getting is returned directly from the API, so this issue relates to the API rather than CLI.

We can reach out to service teams regarding API issues, but in this case I think the behavior is expected. There is a documented example for the [describe-image-attribute](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/describe-image-attribute.html) command showing no product codes returned:

![image](https://github.com/user-attachments/assets/f685208a-1e95-4603-af78-38fd6c526766)

I found this documentation on AMI product codes: https://docs.aws.amazon.com/marketplace/latest/userguide/ami-getting-started.html

Maybe it could be clearer in stating that not all have AMIs will have product codes. I'd recommend using the [Provide feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=Marketplace&topic_url=https://docs.aws.amazon.com/en_us/marketplace/latest/userguide/ami-getting-started.html) at the bottom of that page (or the API page) if you'd like to ask for clarification in the service documentation.
