### ISSUE TITLE
Cannot use credential_process on the default configuration

### ISSUE THREAD

**Issue by luizbob** [aws/aws-cli#8860]
### Describe the bug

When I try to use the AWS default profile using credential_process the cli gets stuck on the process. My setup looks like this one available on the aws documentation on how to use the cli from a VM on GCP https://aws.amazon.com/blogs/security/access-aws-using-a-google-cloud-platform-native-workload-identity/
Config file:
```
[default]
credential_process = /opt/bin/credentials.sh
```

### Expected Behavior

Generated the credential and use the default configuration with credential_process

### Current Behavior

The command frozes and nothing happens, if not stopped, the VM frozes.
[debug_awscli.txt](https://github.com/user-attachments/files/16571537/debug_awscli.txt)
Debug logs on the file above, command executed was `aws sts get-caller-identity --debug`

### Reproduction Steps

Follow the steps on this link: https://aws.amazon.com/blogs/security/access-aws-using-a-google-cloud-platform-native-workload-identity/ and change the config for instead of using a profile to be the default config.

### Additional Information/Context

VM on Google cloud with a specific service account, if I try to use the setup as demonstrated on the documentation https://aws.amazon.com/blogs/security/access-aws-using-a-google-cloud-platform-native-workload-identity/ the config works as intended, but dont work when set as the default config

If the variable AWS_PROFILE is set as the profile that its configured with the credential_process, eg:
```
[profile aws]
credential_process = /opt/bin/credentials.sh
```

The same problem happens

### CLI version used

aws-cli/2.17.26 Python/3.11.9

### Environment details (OS name and version, etc.)

Ubuntu 24.04 LTS X64

**Comment by tim-finnigan** [comment]
Thanks for reaching out. Could you expand on this a bit more:
> if I try to use the setup as demonstrated on the documentation https://aws.amazon.com/blogs/security/access-aws-using-a-google-cloud-platform-native-workload-identity/ the config works as intended, but dont work when set as the default config

I'm trying to understand specifically what are the conditions in which this is and is not working. Also for reference here is documentation on using `credential_process` in the AWS CLI:

* User Guide: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html
* Reference Guide: https://awscli.amazonaws.com/v2/documentation/api/latest/topic/config-vars.html#sourcing-credentials-from-external-processes

(Also [this documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html#configure-precedence) on credentials shows where custom processes are in the order of precedence.)

**Comment by tim-finnigan** [comment]
Thanks for following up. I saw `Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.`. Could you try increasing the retries (see: https://docs.aws.amazon.com/cli/v1/userguide/cli-configure-retries.html) to ensure this wasn't caused by a transient network issue? Can you also confirm that you have the necessary IAM permissions to authenticate, and no proxy configurations that would be preventing the connection?

**Comment by alex-ren** [comment]
I got the same issue. The root cause is that in the /opt/bin/credentials.sh, there is the following statement
`aws sts assume-role-with-web-identity`. The will trigger the credential_process for the default profile again, which leads to the loop.

The way out I did is to create a dummy profile like the following
`[default]
credential_process = /opt/vmware/bin/credentials.sh

[profile zero]`

Then in the /opt/bin/credentials.sh, use `aws sts assume-role-with-web-identity --profile zero`.
