### ISSUE TITLE
logs tail fails to due to charmap problem

### ISSUE THREAD

**Issue by DaniWe** [aws/aws-cli#8928]
### Describe the bug

Executing the following command in PS:
> aws logs tail /aws/elasticbeanstalk/app-test-env/var/log/web.stdout.log --since 1h >D:\app-test.log

resulted in the following error and only part of the log was downloaded:
'charmap' codec can't encode character '\u2720' in position 1059: character maps to <undefined>

### Expected Behavior

aws logs tail must deal with undefined characters and unknown character encoding and continue download of the complete log file, with:

1. The unknown character removed, or
2. the line containing the unknown character removed, or
3. replace the unknown character with a default character, such as '?' or ' ', or
4. the text bytes copied verbatim without any string interaction or parsing/de/encoding by the python language.

Number 4 is obviously the most preferred, followed by number 3 or 1.

### Current Behavior

As written in the description; logs tail stops with the following error:

'charmap' codec can't encode character '\u2720' in position 1059: character maps to <undefined>

### Reproduction Steps

I am not certain what character has been inserted into the log to cause this behavior. Could be an upper latin-1 character output in the stream by printing of a "foreign" name perhaps. I suppose inserting '\u2720' into a log file and trying to download it should trigger the bug.

### Additional Information/Context

Our applications producing the logs are written in java21 with spring boot 3.2.0 and lombok.extern.slf4j.Slf4j logger.

### CLI version used

aws-cli/2.13.34 Python/3.11.6 Windows/10 exe/AMD64 prompt/off

### Environment details (OS name and version, etc.)

Windows 11, PowerShell.

**Comment by tim-finnigan** [comment]
Thanks for reaching out. Can you [update](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) your version of the AWS CLI? Version 2.13.34 is extremely old — the latest version is 2.17.55 per the [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1).

The `...codec can't encode character...` error has been reported [several times](https://github.com/aws/aws-cli/issues?q=is%3Aissue+%22codec+can%27t+encode+character%22+is%3Aclosed+) here in the past. This issue is generally caused by your system's locale configurations. Some solutions mentioned in those issues include:
* Updating to a more recent version of the AWS CLI.
* Setting your system locale to use UTF-8.
* Assigning this environment variable:`PYTHONUTF8=1`

**Comment by DaniWe** [comment]
Still seeing this occasionally with version:
aws-cli/2.23.6 Python/3.12.6 Windows/11 exe/AMD64

'charmap' codec can't encode character '\u2028' in position 1059: character maps to &lt;undefined&gt;

You need to put a try/catch around this and make sure you ignore it! As it is now, it won't download a single line if it encounters an "unexpected" character. This is AWS for christ sake! Not some random hobby project. Fix it! Don't tell me to put work-arounds in my system (which I may not have access rights to) with variables and crap to work around your poor choice of language.

**Comment by DaniWe** [comment]
\u2028 is Line Separator Unicode Character, so supposedly a fairly common character.
Downloading raw (text.csv) log from CloudWatch indicates it is included in stack traces.
