### ISSUE TITLE
Support aws s3 cp from Query String Authentication URLs

### ISSUE THREAD

**Issue by lrowe** [aws/aws-cli#905]
We control access to our files stored on S3 externally from our web application by sending a 302 redirect to a [signed url](http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#RESTAuthenticationQueryStringAuth), generated using [boto.s3.connection.S3Connection.generate_url](http://boto.readthedocs.org/en/latest/ref/s3.html#boto.s3.connection.S3Connection.generate_url).

Many of our files are large (multi-GB genome sequence data) and we'd like to allow users to download these using `aws s3 cp` as we've found it to be significantly faster than alternative parallel download utilities such as `pcurl.sh` and `lftp`.

Ideally this would support following a 302 redirect to the signed URL, so that our users could simply run:

```
$ aws s3 cp "https://user:pass@example.com/redirect-to-signed-s3-url" .
```

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
