### ISSUE TITLE
AWS CLI modify-db-cluster fails with unsupported DbClusterInstanceClass

### ISSUE THREAD

**Issue by marrataj** [aws/aws-cli#9077]
### Describe the bug

When trying to modify restored cluster using AWS CLI I'm getting error:
An error occurred (InvalidParameterCombination) when calling the ModifyDBCluster operation: DbClusterInstanceClass isn't supported for DB engine aurora-postgresql even though db.serverless is on the list when I do `aws cli describe-db-instance-options` for aurora-postgresql engine in eu-west-1 region. 

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

I should be able to modify db cluster instance class to db.serverless

### Current Behavior

An error occurred (InvalidParameterCombination) when calling the ModifyDBCluster operation: DbClusterInstanceClass isn't supported for DB engine aurora-postgresql.

### Reproduction Steps

1. Create rds cluster with aurora postgresql engine and serverless V2 capacity settings and db instance
2. Make backup using AWS backup
3. Restore from backup using AWS Console
4. Restored cluster is missing option to set Serverless V2 capacity settings
5. Try to modify restored cluster using AWS CLI `aws cli modify-db-cluster aurora-postgres-cluster-restored --db-cluster-instance-class db.serverless`
6. An error should occur

### CLI version used

1.36.3, 2.21.2, 1.22

### Environment details (OS name and version, etc.)

Linux 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux Ubuntu 22.04

**Comment by tim-finnigan** [comment]
Thanks for reaching out. The [modify-db-cluster](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/rds/modify-db-cluster.html) command calls the underlying [ModifyDBCluster API](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBCluster.html), so this issue involves the RDS service rather than the AWS CLI directly. 

I could reproduce this behavior — running:
```
aws rds modify-db-cluster --db-cluster-identifier database-1 --db-cluster-instance-class db.serverless
```
Results in:
```
An error occurred (InvalidParameterCombination) when calling the ModifyDBCluster operation: DbClusterInstanceClass isn't supported for DB engine aurora-mysql.
```

The documentation for that command/API notes the following regarding `DbClusterInstanceClass`: 
>Not all DB instance classes are available in all AWS Regions, or for all database engines.
>
>For the full list of DB instance classes and availability for your engine, see [DB Instance Class](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html) in the Amazon RDS User Guide.

For PostgreSQL specifically there is guidance here: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/PostgreSQL.Concepts.General.DBVersions.html

Based on the the documentation this appears to be expected behavior. If you would like us to reach out to the RDS team internally with any questions or feedback related to this, please let us know.
