### ISSUE TITLE
pcluster configure with sso broken after https://github.com/aws/aws-cli/issues/9092

### ISSUE THREAD

**Issue by ggscorzato** [aws/aws-cli#9107]
### Describe the bug

following https://docs.aws.amazon.com/parallelcluster/latest/ug/install-v3-configuring.html (but with sso)
the command 
`pcluster configure --config config-file.yaml`
should guide through the build of a config-file.yaml for a cluster

However, it replies 
Failed with error: Unable to locate credentials

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

the command 
`pcluster configure --config config-file.yaml`
should guide through the build of a config-file.yaml for a cluster

### Current Behavior

the command 
`pcluster configure --config config-file.yaml`
Failed with error: Unable to locate credentials

### Reproduction Steps
```
$aws --version
aws-cli/2.22.4 Python/3.12.6 Linux/4.18.0-553.27.1.el8_10.x86_64 exe/x86_64.rocky.8

$pcluster version
{
  "version": "3.11.1"
}

$aws configure sso --use-device-code
$aws sso login --profile AWSAdministratorAccess-XXX --use-device-code
$cat .aws/config
[profile AWSAdministratorAccess-XXX]
sso_session = my-sso
sso_account_id = XXX
sso_role_name = AWSAdministratorAccess
region = eu-north-1
output = json
[sso-session my-sso]
sso_start_url = https://ZZZ.awsapps.com/start/#
sso_region = eu-west-1
sso_registration_scopes = sso:account:access


$pcluster configure --config config-file.yaml  --region eu-north-1
Failed with error: Unable to locate credentials
$export AWS_PROFILE=AWSAdministratorAccess-XXX
$pcluster configure --config config-file.yaml  --region eu-north-1
Failed with error: The config profile (AWSAdministratorAccess-XXX) could not be found
```

### Possible Solution

check whether https://github.com/aws/aws-cli/issues/9092 might have broken some compatibility with pcluster

### CLI version used

aws-cli/2.22.4

### Environment details (OS name and version, etc.)

Python/3.12.6 Linux/4.18.0-553.27.1.el8_10.x86_64 exe/x86_64.rocky.8

**Comment by tim-finnigan** [comment]
Thanks for reaching out. Since this issue involves the `pcluster` CLI, can you also report the issue here in this repository: https://github.com/aws/aws-parallelcluster/issues? You can get the [logs](https://docs.aws.amazon.com/parallelcluster/latest/ug/troubleshooting-v3-pc-cli-logs.html) for further investigation.

For the AWS CLI `aws sso login` command, can you share the output and debug logs (with any sensitive info redacted)? You can get those logs by adding `--debug` to your command.

The conclusion from https://github.com/aws/aws-cli/issues/9092 was that things are working as expected, so I'm not sure that there's a compatibility issue here.

**Comment by ggscorzato** [comment]
restarting from a clean environment and using the latest awscli 2.22.6, the issue is not reproduced. Closing.
