### ISSUE TITLE
providing functionality equivalent to EC2 CLI's import-instance?

### ISSUE THREAD

**Issue by rhbecker** [aws/aws-cli#911]
I can't figure out any way that the aws-cli provides the ability to import / upload a VM image for use as an EC2 instance, ultimately for the purpose of creating a custom AMI.

Given that [various sources](http://aws.amazon.com/ec2/vm-import/) of [EC2 documentation](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/UsingVirtualMachinesinAmazonEC2.html) communicate only the EC2 CLI mechanism - i.e. [ec2-import-instance](http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/ApiReference-cmd-ImportInstance.html) - I'm left to conclude that aws-cli does not provide equivalent functionality. If that's true, **(1) why not?** and **(2) will it ever?**

While not _explicitly_ stating this, the [AWS Command Line Tools listing](http://docs.aws.amazon.com/general/latest/gr/GetTheTools.html) implies that this aws-cli tool provides the necessary functionality formerly provided via the tools listed under the "Previous" (i.e. deprecated?) header. I may be reading too much into that language, but fwiw, that's how I'm reading it.

(Apologies if I've duplicated an existing issue. I just searched for 'import' and none of the results appeared to be related.)

**Comment by quater** [comment]
I have been searching high and low for quite some time before I found this feature request. I understand that this feature is not yet implemented, which is a pity since I was hopping that I can run all automation by using the `aws-cli` tool only.

Anyway, for the time being it would be great if you could include a note in the `aws-cli` documentation, maybe by using its intended command name `import-image-instance` and say that it is not yet implemented and the workaround is to use the legacy `ec2-api-tools`.

This will save many people time.

**Comment by adminempire** [comment]
I agree with @quater would be very helpful to easily be able to find this out without wasting lots of time looking for this functionality in aws-cli.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
