### ISSUE TITLE
Add --source-version-id parameter to s3api copy-object

### ISSUE THREAD

**Issue by renat-sabitov** [aws/aws-cli#988]
To restore a version of object we need to copy it to itself with a source version ID specified. For this reason it'll be great to have --source-version-id parameter to specify a version of object we want to restore.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by tim-finnigan** [comment]
Is using the approach referenced above sufficient? If the original request is still needed then this should be redirected to the S3 team who owns their APIs. We generally recommend reaching out directly through [AWS Support](https://aws.amazon.com/contact-us/) for API-related requests but we can also forward the request internally. Please let us know if there is any feedback on this as there hasn't been any activity on this issue in a long time. I'll set the issue to auto-close if there is no further feedback here.
